### ISSUE TITLE
Dialog Activator Within Speed Dial Causes Cascading Close

### ISSUE THREAD

**Issue by jteppinette** [vuetifyjs/vuetify#1001]
### Reproduction Steps:
If a speed dial has a child `v-btn` that is a dialog activator, when the dialog opens, a click on the dialog causes the dialog and speed dial to close. You can check out the [CodePen](https://codepen.io/jteppinette/pen/qjwOQV)
 for more information and a full reproduction of this issue.

### Versions:
```
OS: "macOS Sierra"
Browser: ["Version 10.1.1 (12603.2.4), "Version 59.0.3071.104 (Official Build) (64-bit)"]
```

### Expected Behavior:
I believe the proper functionality would be for the speed dial to be the only component to be closed when the dialog is clicked on.

### Actual Behavior:
There is an issue where a nested dialog inside of a speed dial cannot be clicked on without the dialog being closed. The use case for this is the speed dial selecting between different actions, some of which open dialogs.

### Reproduction Link:
[CodePen](https://codepen.io/jteppinette/pen/qjwOQV)

**Comment by johnleider** [comment]
This will have to be solved by how you address your UI solution. It's how these components are designed to work, when you click-outside, it closes the component. Unfortunately, due to this, when you click, the speed-dial goes to close, but it also forces a re-render of it's children, which causes the overlay to be destroyed.

Here is a working example that solves your issue: https://codepen.io/johnjleider/pen/gRyaVE?editors=1111
