### ISSUE TITLE
[Documentation] Min and max range slider automatically changes the value in the first input

### ISSUE THREAD

**Issue by ygspasov** [vuetifyjs/vuetify#10034]
### Environment

**Browsers:** Firefox 71.0
**OS:** Windows 10

### Steps to reproduce
I just noticed that when you change the value of the first input for the Min and max range slider at https://vuetifyjs.com/en/components/sliders#custom-range-slider, and then the value of the second, the value of the first input also changes. Why is this so and can I prevent it?

### Expected Behavior
The value of the second input shouldn't change the value in the first.

### Actual Behavior
The value of the second input changes the value in the first.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/sliders#custom-range-slider" target="_blank">https://vuetifyjs.com/en/components/sliders#custom-range-slider</a>

**Comment by KaelWD** [comment]
I don't see anything like that, dot points with exact steps and what is expected at each stage are much more helpful than vague descriptions.

**Comment by ygspasov** [comment]
@KaelWD , the exact steps for reproducing the problem have already been provided but I'll do it once again below:

1. Go to https://vuetifyjs.com/en/components/sliders#custom-range-slider.
2. Find the "Min and max range slider" with default values in the left and right inputs of -20 and 70.
3. Mark -20 with your mouse and change it to 5. Then mark 70 and change it to 10. Do not use the arrows.
4. -20 automatically becomes 1 and 10 becomes 50. 

I've tested this first on my app and then on the documentation. It gives exactly the same result.

**Comment by KaelWD** [comment]
Right, you linked to the custom range slider so I was confused. This also only happens with specific values so having exact reproduction steps are always helpful to avoid wasting time. 

If you type the second number slowly you'll see what's happening, the slider always keeps its value as `[min, max]` so when you type `1` they swap and you add a 0 to the end of the 5. The solution is to use `@change` instead of `v-model`, equivalent to `v-model.lazy` on a native `<input>`: https://codepen.io/kaelwd/pen/yLybEoq?editors=1010

**Comment by ygspasov** [comment]
@KaelWD , you are right. I've also made it work on my app. However, I somehow believe that these changes should be in the documentation rather than on Codepen so that people don't pull out their hair accidentally.

**Comment by akashcoc** [comment]
will try it
