### ISSUE TITLE
[Bug Report] V-carousel not working in google chrome on Android 

### ISSUE THREAD

**Issue by shivanshtalwar0** [vuetifyjs/vuetify#10041]
### Environment
**Vuetify Version:** 2.1.15
**Last working version:** 1.5.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.93
**OS:** Android 9, Android

### Steps to reproduce
On nuxtjs , after successfully fetching images from server in asyncData method , and using the boilerplate code of v-carousel, it is just not working on Google Chrome android , i am wondering if its something related to chrome or some internal workings of v-carousel

### Expected Behavior
It should work on all supported platforms

### Actual Behavior
Just doesn't work on Google chrome  android app

### Reproduction Link
<a href="https://jsfiddle.com" target="_blank">https://jsfiddle.com</a>

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by shivanshtalwar0** [comment]
Can you be kind enough to tell me how do i reproduce this issue?

**Comment by shivanshtalwar0** [comment]
ok here's the thing v-carousel is not working mysteriously with v-img but it works just fine with img, this weird  behaviour is prominent only in nuxtjs project, so i am gonna close it since it is unclear from where this issue is originating.   

 <v-carousel hide-delimiters vertical    hide-delimiter-background  height="auto" >

        <v-carousel-item
          eager
          v-for="(item,i) in items"
          :key="i"
          :href="item.href"
        >
          <img
            style="width:100%;height:auto !important;"
            :src="item.image.downloadurl"  alt=""/>

        </v-carousel-item>
      </v-carousel>

solved my problem.
