### ISSUE TITLE
[Bug Report] v-list-group keeping active state when another v-list-item outside list-group is selected

### ISSUE THREAD

**Issue by MarceloLuis1997** [vuetifyjs/vuetify#10074]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
1- Click Admin > Management (it will active Admin and Management)
2- Click Account (it will active Account item, but Admin group will keep it's active state)

### Expected Behavior
Account item should be active and both Admin and Management should remove their active state and Admin group should close.

### Actual Behavior
List-group are keeping it's active state when their was previously opened and list-items outside list-group are active by router-link

### Reproduction Link
<a href="https://codepen.io/fabiosantos97/pen/abzLzML?editors=1010" target="_blank">https://codepen.io/fabiosantos97/pen/abzLzML?editors=1010</a>

### Other comments
I am trying to build a navigation drawer like this one: https://demos.creative-tim.com/vue-material-dashboard-pro/#/dashboard

However every time i try to use v-list-group i have that problem with active items state.

**Comment by hosseinmirhosseini76** [comment]
> ### Environment
> **Vuetify Version:** 2.1.15
> **Vue Version:** 2.6.11
> **Browsers:** Chrome 79.0.3945.88
> **OS:** Windows 10
> 
> ### Steps to reproduce
> 1- Click Admin > Management (it will active Admin and Management)
> 2- Click Account (it will active Account item, but Admin group will keep it's active state)
> 
> ### Expected Behavior
> Account item should be active and both Admin and Management should remove their active state and Admin group should close.
> 
> ### Actual Behavior
> List-group are keeping it's active state when their was previously opened and list-items outside list-group are active by router-link
> 
> ### Reproduction Link
> https://codepen.io/fabiosantos97/pen/abzLzML?editors=1010
> 
> ### Other comments
> I am trying to build a navigation drawer like this one: https://demos.creative-tim.com/vue-material-dashboard-pro/#/dashboard
> 
> However every time i try to use v-list-group i have that problem with active items state.

what should we do really???

**Comment by Tronix117** [comment]
Why has it been closed ?

There is multiple solutions, but none seems to be provided nor implementable in the current state:
* adding a grouping feature (other than using route namespace)
* adding an `active` prop to override default behavior
* adding `active` class if there is a children selected

**Comment by kungfu71186** [comment]
I was able to re-produce this but it only does it if the route is a sub-route

https://codepen.io/kungfu71186/pen/MWypeLZ?editors=1010

If you click on More - Bad > Export - it will highlight both Import and Export since Import goes to /more and Export goes to /more/export. Same if you click print since it's a sub route.

Besides that, it seems to work ok. so not sure what kind of bug this would be.

**Comment by James-Lam** [comment]
If current route path matches the `group` prop of `v-list-group`, then that `v-list-group` is active
![image](https://user-images.githubusercontent.com/15834794/109625770-ab97a200-7b7a-11eb-8751-b34e254bc649.png)

If current route path matches the `group` props of two `v-list-group`, then the first matched `v-list-group` will be active
![image](https://user-images.githubusercontent.com/15834794/109626597-b6066b80-7b7b-11eb-8f1c-a918ccf1e19e.png)

When I click `手动订单管理`, since its path matches two group (`库存管理` and `订单管理`), the first matched group will be active (`订单管理`)

Solution: using a group name (or a word) that will not be included in any paths, except for its children.
![image](https://user-images.githubusercontent.com/15834794/109627696-d8e54f80-7b7c-11eb-9486-454cfae1fd0c.png)
