### ISSUE TITLE
[Bug Report] Error in v-on handler: "TypeError: oldDesc.slice is not a function"

### ISSUE THREAD

**Issue by swirlingsand** [vuetifyjs/vuetify#10147]
### Environment
**Vuetify Version:** 2.1.15
**Last working version:** 1.5.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
Vuetify data table

### Expected Behavior
Not throw an error

### Actual Behavior
Throws error:

Create a data table using options.sync

```
vue.esm.js?a026:628 [Vue warn]: Error in v-on handler: "TypeError: oldDesc.slice is not a function"

found in

---> <VDataTableHeaderDesktop>
       <VSimpleTable>
         <VData>
           <VDataTable>
             <VCard>

vue.esm.js?a026:1897 TypeError: oldDesc.slice is not a function
    at VueComponent.toggle (vuetify.js?ce5b:8033)
    at VueComponent.sort (vuetify.js?ce5b:8081)
    at invokeWithErrorHandling (vue.esm.js?a026:1863)
    at VueComponent.invoker (vue.esm.js?a026:2188)
    at invokeWithErrorHandling (vue.esm.js?a026:1863)
    at VueComponent.Vue.$emit (vue.esm.js?a026:3897)
    at VueComponent.Vue.<computed> [as $emit] (backend.js:1793)
    at listeners.click (vuetify.js?ce5b:9886)
    at invokeWithErrorHandling (vue.esm.js?a026:1863)
    at HTMLTableCellElement.invoker (vue.esm.js?a026:2188)
```

### Reproduction Link
Please see error message.
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. Please open a new issue with the missing information.

Thank you for your contribution and interest in improving Vuetify. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by swirlingsand** [comment]
It's a literal error message in your system. I'm not going to spend a bunch of time debugging it for you and figuring out which part is causing it to break...
