### ISSUE TITLE
[Feature Request] VSelect is taller than VTextField

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#10300]
### Problem to solve
There is a 2 pixel difference in their height which makes them slightly unaligned. 

CodePen made some change with libraries so Vuetify examples are all broken. I didn't feel like making an example from scratch to show you something that just requires having eyes.

### Proposed solution
Make them the same height.

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/72960959-2de35d80-3de2-11ea-86de-7933d2cb3622.png)
![image](https://user-images.githubusercontent.com/15625235/72960968-350a6b80-3de2-11ea-9616-e19c7bd86e35.png)

You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. Please open a new issue with the missing information.

Thank you for your contribution and interest in improving Vuetify. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
