### ISSUE TITLE
[Documentation] 'Usage' widgets don't have code view (<> button)

### ISSUE THREAD

**Issue by thepurpleblob** [vuetifyjs/vuetify#10317]
### Environment

**Browsers:** Chrome 79.0.3945.88
**OS:** Mac OS 10.14.6

### Steps to reproduce
The code view of most of the Usage widgets is missing. Example, https://vuetifyjs.com/en/components/cards

You can configure the options to create the appearance you require, but the only way to see the HTML is to use the browser's Inspect function.

### Expected Behavior
I would expect to be able to get an HTML view

### Actual Behavior
No 'show HTML' option

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/cards" target="_blank">https://vuetifyjs.com/en/components/cards</a>

**Comment by MajesticPotatoe** [comment]
related to #9564
Usages are still actively being worked on (only about half the components have been finished)
Plans to add an output similarly to #9564 and have that be the codepen output/code view. This is mostly due to the actual code view of the usages are not static example, but dynamically generated.

**Comment by wysman** [comment]
+1

**Comment by jn-powerlan** [comment]
+1

**Comment by MajesticPotatoe** [comment]
this is available on all new usage examples.
