### ISSUE TITLE
[Bug Report] v-tabs: left element cut off when scrolled over

### ISSUE THREAD

**Issue by P4sca1** [vuetifyjs/vuetify#10358]
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.2

### Steps to reproduce
Open the Codepen and view the page on mobile (e.g. by enabling mobile viewport in developer console).

### Expected Behavior
The spacing before the first v-tabs element should be removed once scrolled over.
See this video: https://storage.googleapis.com/spec-host/mio-staging%2Fmio-components%2F1579302979877%2Fassets%2F1PFSLQSiqcpzbYgbOg0XKD1TpSQ_lgJcx%2Ftabs-scrollable-center.mp4

### Actual Behavior
The spacing is not removed.

### Reproduction Link
<a href="https://codepen.io/p4sca1/pen/jOERXgY" target="_blank">https://codepen.io/p4sca1/pen/jOERXgY</a>

**Comment by navi35** [comment]
duplicated #8294

**Comment by KaelWD** [comment]
#8294 is about the `right` prop

The space is intentional, it appears when the tabs start to overflow (see ["Scrollable tabs"](https://material.io/components/tabs/#usage)). It isn't supposed to cut them off though when scrolled over:
![image](https://user-images.githubusercontent.com/16421948/73264300-91c4b680-4226-11ea-9971-6ed93891bfac.png)

**Comment by P4sca1** [comment]
Ah, didn't know it's part of the spec to add the spacing on mobile. But it makes sense when not cutting off the elements when scrolled over.
I updated the issue title and description to correctly describe the issue.
