### ISSUE TITLE
[Bug Report] v-img with svg doesn't generate sizer element in firefox

### ISSUE THREAD

**Issue by davidbludlow** [vuetifyjs/vuetify#10386]
### Environment

**Browsers:** Firefox 72.0
**OS:** Windows 10

### Steps to reproduce
Go to that page in the latest Firefox for desktop. Look at the Tidelift button.

### Expected Behavior
It should look like it does when you see it on Chrome. Not that Chrome is important or anything. Firefox is the only browser anyone should use.

### Actual Behavior
It looks like an empty grey rectangle (without the word Tidelift in it)

### Reproduction Link
<a href="https://vuetifyjs.com/en/introduction/sponsors-and-backers" target="_blank">https://vuetifyjs.com/en/introduction/sponsors-and-backers</a>

**Comment by KaelWD** [comment]
https://codepen.io/kaelwd/pen/KKwLErK

**Comment by KaelWD** [comment]
Yep issa bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1328124

**Comment by KaelWD** [comment]
Related: https://github.com/whatwg/html/issues/3510

**Comment by davydnorris** [comment]
I was bitten by this just recently and there is more to it...

Images with svg do not generate a responsive__sizer on Firefox, but in my case that hid another issue, as the responsive__sizer on the other platforms miscalculated the aspect ratio and caused my pages to break.

My current work around is to set aspect-ratio="0" on all the affected images so that the responsive__sizer div doesn't get generated at all, but the aspect ratio calculation has a problem

**Comment by KaelWD** [comment]
SVG in general does not have a well defined natural size.
