### ISSUE TITLE
[Bug Report] [Bug] Web component avec Vuetify rendu CSS

### ISSUE THREAD

**Issue by ScottBreyer96** [vuetifyjs/vuetify#10435]
Hello,
I am currently working on the creation of a web component. I use the command "view build --target wc --name my-custom-element ./src/main.js" to create my web components from Vue components. When I use Vuetify to create a tree or an array of data in a Vue component, there are no problems, but when converting to a Web component, I have problems with the font, display and animation in the tree.

Here is my code and screenshots, thank you.

----------------- Treeview in Vue component -----------------

![Capture d’écran 2020-02-03 à 12 53 03](https://user-images.githubusercontent.com/39304258/73654822-e9cb4500-468c-11ea-8978-e32b15365b07.png)
![Capture d’écran 2020-02-03 à 12 53 10](https://user-images.githubusercontent.com/39304258/73654829-ecc63580-468c-11ea-9eb3-9aedaa49cb48.png)

----------------- Treeview in Web component -----------------

![Capture d’écran 2020-02-03 à 12 52 53](https://user-images.githubusercontent.com/39304258/73654833-f059bc80-468c-11ea-8fdf-4b14e97a076e.png)

Capture d’écran 2020-02-03 à 12 52 53

----------------- DataTable in Vue component -----------------

![Capture d’écran 2020-02-03 à 12 53 33](https://user-images.githubusercontent.com/39304258/73654861-ff406f00-468c-11ea-84f5-b14e5e5c1113.png)

----------------- DataTable in Web component -----------------

![Capture d’écran 2020-02-03 à 12 53 33](https://user-images.githubusercontent.com/39304258/73654883-0c5d5e00-468d-11ea-8daa-2414687f0597.png)

----------------- Code -----------------

<img width="742" alt="Capture d’écran 2020-02-03 à 12 51 54" src="https://user-images.githubusercontent.com/39304258/73654890-10897b80-468d-11ea-9c2c-84f65a6d209b.png">

**Comment by MajesticPotatoe** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue also appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).
This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.
