### ISSUE TITLE
[Bug Report] Expand transition jumps and stutters

### ISSUE THREAD

**Issue by datainvestor** [vuetifyjs/vuetify#10444]
### Environment
**Vuetify Version:** 2.2.7
**Vue Version:** 2.5.17
**Browsers:** Vivaldi 2.5.1525.46
**OS:** Windows 10

### Steps to reproduce
Have a element wrapped in `v-expand-transition` tag

### Expected Behavior
The expansion should be smooth on change

### Actual Behavior
The element, when expanding, visibly lags and jumps instead of smoothly transitioning from smaller non extended version to extended one.

### Reproduction Link
<a href="https://codepen.io/pokepim/pen/WNbVjYZ" target="_blank">https://codepen.io/pokepim/pen/WNbVjYZ</a>

**Comment by whoistobias** [comment]
This is caused by the way bottom margins aren't calculated into div sizes. They don't make the containing div bigger, so when js is animating height, it's not calculated until the animation is finished.

This isn't a bug with Vuetify and can be solved simply by removing the bottom margin of the text. or using a container for the contents.
