### ISSUE TITLE
[Bug Report] v-calendar wronng height on style change

### ISSUE THREAD

**Issue by MaximilianBaer** [vuetifyjs/vuetify#10463]
### Environment
**Vuetify Version:** 2.2.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
- Go to the V-calendar documentation 
- Go to the day view 
- if it has daily activitis  change the theme (light -> dark/ dark-> light)

### Expected Behavior
 the daily activities stays at the same place 

### Actual Behavior
the daily activities move down 

### Reproduction Link
https://vuetifyjs.com/en/components/calendars#usage

**Comment by yuki1079** [comment]
This sentence is written using Google Translate.

I had the same problem.
I think it's not a documentation issue, but a v-calendar issue.
The steps to reproduce illustrate the documentation, but also occurred in the implementation.

# Steps to reproduce
1. Go to the V-calendar documentation
https://vuetifyjs.com/en/components/calendars#events
1. Change the style in the sample(week -> month -> week)
Repeat several times

# Expected Behavior
  dayHeader events appear immediately below the date.
![ExpectedBehavior](https://user-images.githubusercontent.com/7569683/74815102-f235a800-533b-11ea-8e0b-492f994de48c.png)

# Actual Behavior
  There is a space between the dayHeader event and the date.
![bug](https://user-images.githubusercontent.com/7569683/74815088-e6e27c80-533b-11ea-87f7-6d80d07b2b8b.png)

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
