### ISSUE TITLE
[Documentation] VDataTable references hide-headers but it is not documented

### ISSUE THREAD

**Issue by edwardsph** [vuetifyjs/vuetify#10495]
### Environment

**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
Look at headers-length in the API. It says "Can be used in combination with hide-headers to specify the number of columns in the table to allow expansion rows and loading bar to function properly" but hide-headers is not defined elsewhere.

### Expected Behavior
Consistent documentation

### Actual Behavior
Inconsistent documentation

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/data-tables" target="_blank">https://vuetifyjs.com/en/components/data-tables</a>

**Comment by MajesticPotatoe** [comment]
remnants of 1.5, should be `hide-default-header`

**Comment by edwardsph** [comment]
OK - but I must say that I am still in the dark about the rest of the headers-length description. I'm sure an example would help but I don't think I need either prop right now.

**Comment by MajesticPotatoe** [comment]
When you use the headers slot, you typically use `hide-default-header` as you are customizing the entire header, which can mean you may have more or less headers then what you define in your `headers` array. things like progress and expansion row function using the length of your `headers` array. `headers-length` lets you override that value to account for any extra or less header items you may have so that they function properly.
