### ISSUE TITLE
[Bug Report] Chrome(on Android) doesn't show vuetify page.

### ISSUE THREAD

**Issue by Yoshihide-Nishimoto** [vuetifyjs/vuetify#10593]
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Android

### Steps to reproduce
Displaying v-text-field component with outlined = true, we get a chrome error. 

### Expected Behavior
display properly

### Actual Behavior
chrome error
![Screenshot_20200217-111630](https://user-images.githubusercontent.com/19885548/74619584-66741e00-5179-11ea-805f-324ce9591f4b.png)

### Reproduction Link
<a href="https://codepen.io/yoshihide-nishimoto/pen/YzXqaYe?editable=true&editors=101" target="_blank">https://codepen.io/yoshihide-nishimoto/pen/YzXqaYe?editable=true&editors=101</a>

### Other comments
vuetify:2.2.8~2.2.13(reproduce in all the versions)
Browser:Chrome80.03987.99
OS:Android10 Pixel3a Build

this problem does not occur any other browsers + OS combination.
(OS X + chrome / Windows10 + Chrome / Android + firefox are OK)

This problem does not occur unless outlined is set.
And not occur in code-pen.
(so the repro link is dummy)

**Comment by MajesticPotatoe** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by KaelWD** [comment]
Displays fine in chrome 80.0.3987.99 on Android 7.0

![Screenshot_2020-02-17-17-46-12-286_com android chrome](https://user-images.githubusercontent.com/16421948/74630021-bd93e600-51ad-11ea-8a18-a5e4aee24bc0.png)

**Comment by Yoshihide-Nishimoto** [comment]
@MajesticPotatoe 
@KaelWD 
thanks for replying.
Using vuetify without vuetify/lib did not produce any errors.

old code
```
import Vuetify from "vuetify/lib";

Vue.use(Vuetify);
const opts = {};

export default new Vuetify(opts);
```

new code
```
import Vuetify from "vuetify";

Vue.use(Vuetify);
const opts = {};

export default new Vuetify(opts);
```

I made a minimal project for reproduction, but no error was given.

Close the issue, as it is not a bug.
thanks.
