### ISSUE TITLE
[Documentation] Vuetify cheat sheet

### ISSUE THREAD

**Issue by mahammad8564** [vuetifyjs/vuetify#10657]
### Problem to solve
To easily get the common props, list of classes, saas variables and etc.

### Proposed solution
Should have a cheat sheet

**Comment by nekosaur** [comment]
You will have to more clearly specify what you are after. We do have the API explorer if that's what you mean? https://vuetifyjs.com/en/components/api-explorer

**Comment by gregveres** [comment]
@nekosaur I don't know what @mahammad8564  was looking for, but I will tell you what I would like to see in terms of a cheat sheet. 

CSS classes gathered together in a single page. 

These are the things that after a few months of working in Vuetify it will become second nature, but when you are learning vuetify, a cheatsheet would be heaven. I think that these are spread over a few pages right now. 

I just saw that the woman who  publishes the newsletter referenced a cheatsheet and I was eager to look at it since I am just learning Vuetify now. But I was disappointed when it didn't mention any of the CSS classes.

**Comment by johnleider** [comment]
This is currently in process.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by mr-mad-e** [comment]
@nekosaur @johnleider https://github.com/mr-mad-e/vuetify-cheat-sheet
