### ISSUE TITLE
[Bug Report] Overlay not clearing immediately. I have used overlay as loader and loader is stopping properly but overlay is still coming with 0 opacity. I've seen this using inspect

### ISSUE THREAD

**Issue by ETSmukesh** [vuetifyjs/vuetify#10668]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 77.0.3865.120
**OS:** Linux x86_64

### Steps to reproduce
Can't reproduce because we're facing it in our local development. 

### Expected Behavior
0 Opacity overlay should be removed.

### Actual Behavior
Overlay not removing.

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. Please open a new issue with the missing information.

Thank you for your contribution and interest in improving Vuetify. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
