### ISSUE TITLE
[Bug Report] v-data-table pagination infinite loop

### ISSUE THREAD

**Issue by zombiesplat** [vuetifyjs/vuetify#10718]
### Environment
**Vuetify Version:** 2.2.15
**Last working version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.116
**OS:** Mac OS 10.15.3

### Steps to reproduce
Make a v-data-table that uses external pagination.
and the v-on:pagination runs the fetch method, it will get stuck in an infinite loop

### Expected Behavior
the pagination event should only occur when a sort or page change has occurred and not when the items have been updated.

### Actual Behavior
every time the items data gets changed, it seems to trigger the pagination emitter

### Reproduction Link
<a href="https://codepen.io/zombiesplat/pen/gOpRdra" target="_blank">https://codepen.io/zombiesplat/pen/gOpRdra</a>

**Comment by amoliski** [comment]
I think the pagination event needs to fire on data change because if the data change includes a length change, it impacts the pagination.

Check out this example: https://codepen.io/paulpv/pen/zWPKao

You might have better luck doing a watch on pagination instead of reacting to the on:pagination event.

**Comment by amoliski** [comment]
Page events probably need to be emitted in the event that the data change changes the number of items, which will impact the length of the data and the pagination values that derive from that.

Try doing a deep watch on your page_options property instead of reacting to page events
(also you forgot a : on your loading prop which made it look like it was loading forever)

https://codepen.io/amoliski/pen/RwPZbrp?editors=1010

**Comment by zombiesplat** [comment]
Very good. that did the trick.

**Comment by claudiug** [comment]
```
:options.sync="options"
:page.sync="options.page"
```

a better fix
