### ISSUE TITLE
[Bug Report] Cant change $card-elevation variables

### ISSUE THREAD

**Issue by VasekProchazka** [vuetifyjs/vuetify#10730]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.1
**Browsers:** Chrome 80.0.3987.122
**OS:** Mac OS 10.15.3

### Steps to reproduce
Run new project, setup sass variables file and try setup:  $card-elevation

### Expected Behavior
If I set $card-elevation in my sass file, the box-shadow should change by set number

### Actual Behavior
Doesnt work at all

### Other comments
Every other variable (fonts, button size) works propertly except $card-elevation.

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. Please open a new issue with the missing information.

Thank you for your contribution and interest in improving Vuetify. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
