### ISSUE TITLE
[Bug Report] v-treeview disable disables both parent and children nodes when mode is independent

### ISSUE THREAD

**Issue by Geowan** [vuetifyjs/vuetify#10770]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Linux x86_64

### Steps to reproduce
By setting the parent to disabled to true and children disabled to false disables both parent and children

### Expected Behavior
I expected that by setting disabled to false on children even if the parent disabled is true the children should not be disabled.

### Actual Behavior
Parent disabled set to true disables the children nodes even though the children node disabled is set to false

### Reproduction Link
<a href="https://codepen.io/geowan/pen/PoqOOMX" target="_blank">https://codepen.io/geowan/pen/PoqOOMX</a>

**Comment by johnleider** [comment]
At first glance this seems like it would be intended. Need @nekosaur and @jacekkarczmarczyk to confirm.

**Comment by nekosaur** [comment]
This is expected behaviour

**Comment by Geowan** [comment]
@nekosaur my suggestion would be great in situations where you need to limit selections to only certain nodes.

A good example would be in category and subcategory selection where one needs to limit selections to subcategories only while at the same time displaying the parent category.

**Comment by Erik-Jonker** [comment]
Why is this expected behaviour? selection-type="independent" was specified so the parent should not disable the children.

Also it does not seem to be possible to expand / close the parent and its children if disabled. What if you wanted to the close the disabled item or open it to view the content?

Here is an example where it is not possible to see the children of "Bar"

https://codepen.io/erikjonker/pen/eYNXjKQ?editors=1010

**Comment by nekosaur** [comment]
I totally missed that independent was used. You are probably correct that things like disabled should follow the chosen logic.
