### ISSUE TITLE
[Bug Report] carousel with fade-transition forces view to the carousel

### ISSUE THREAD

**Issue by andreixk** [vuetifyjs/vuetify#10780]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Mac OS 10.15.3

### Steps to reproduce
1. Create carousel with cycle="true"
2. add items with transition="fade-transition"
3. scroll to the bottom of the page

### Expected Behavior
view should stay in the same place

### Actual Behavior
view jumps to carousel (top of page) on slide change

### Reproduction Link
<a href="https://codepen.io/andreixk/pen/LYVOMaX" target="_blank">https://codepen.io/andreixk/pen/LYVOMaX</a>

**Comment by anisabboud** [comment]
I ran into the same issue. Whenever the carousel is _partly visible_ and the slide is changed (e.g., using cycle), the browser window jumps up abruptly.

It happens only with some of the transition options (such as "transition-fade" and "transition-expand") but not with others (such as "slide-y-transition" or not setting transition and using the default one).

Could be related to https://github.com/vuetifyjs/vuetify/issues/10809 since they both occur with the carousel fade transition.

**Comment by mapkbalaji** [comment]
I too am facing the same issue.

**Comment by stonehank** [comment]
try this
```
.fade-transition-leave-active{
    position: absolute;
    width:100%;
}
```

**Comment by kglazier** [comment]
Also related https://github.com/vuetifyjs/vuetify/issues/10613

**Comment by joaomateuus** [comment]
> slide-y-transition
still happening this issue when we not set transition and use the default one and even not using transition property
