### ISSUE TITLE
[Bug Report] v-select click event does not fire

### ISSUE THREAD

**Issue by pmagix** [vuetifyjs/vuetify#10839]
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
use a v-select in your component - in the browser click on the resulting select input - no click event is fired

### Expected Behavior
Clicking on the select element in browser fires click event

### Actual Behavior
click event does not fire 

### Reproduction Link
<a href="https://codepen.io/pmagix/pen/yLNKZrX?editors=1111" target="_blank">https://codepen.io/pmagix/pen/yLNKZrX?editors=1111</a>

**Comment by Critneyhere** [comment]
The codepen works for me. Console shows "change" when choosing either "One" or "Two"Could it be caused by your browser?
Best regards

**Comment by pmagix** [comment]
This issue is to do with the click event (the change event was included as a working reference)

**Comment by basselAhmed** [comment]
@pmagix You can use `.native` modifier, see https://codepen.io/basselAhmed/pen/LYVmNgB?editors=1111

**Comment by pmagix** [comment]
Ok, so the documentation needs to be changed - possibly a distinction made between events? Currently the difference between the change & click events is not indicated:
![20200315_183438](https://user-images.githubusercontent.com/13918825/76707008-1478d680-66ec-11ea-9870-564293b4608e.jpg)

**Comment by johnleider** [comment]
The `.native` behavior is a Vue idiosyncrasy: https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components

@vuetifyjs/documentation Could possibly reword the default language for **change** and **input** events. Thoughts?

**Comment by pmagix** [comment]
@johnleider i've had several occasions where event behaviour has been not what was expected 
for example, the act of listening to the v-select click:append stops the normal dropdown behaviour
[codepen](https://codepen.io/pmagix/pen/qBdYerd?editors=1111)

**Comment by Dinuz** [comment]
The problem persists as mentioned by @pmagix also in version 2.3.19 .
I am trying to add a not scrollable header to the v-select menu, and after a bit of crazy work I was able to get it as I wanted. 
Clearly would be much easier and probably cleaner if we could access directly the v-menu component inside the select using an extra slot ( I used the append-outer, attached the menu to it, and positioned the header with css); you need to have the header or the footer outside the menu list flow, otherwise it scrolls with the rest of the items.

My solution "more or less works", but to make the header appear or disappear with the menu I need to rely on the focus, blur and click:append events. Focus and blur are working as expected, instead the click:append event completely blocks the dropdown behavior and the menu doesn't really work anymore.

[codepen](https://codepen.io/dinuz/pen/qBadXBQ)

@johnleider do you think we can add an extra slot (maybe a couple) to allow adding elements before and after the menu content inside the menu but outside the items list?
Just think of it as something like an header and a footer around the scrollable items list.

**Comment by hkiame** [comment]
I am currently experiencing this with version 3.1.10

**Comment by hkiame** [comment]
> I am currently experiencing this with version 3.1.10

update:modelValue works for change event

**Comment by johnleider** [comment]
@hkiame We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
