### ISSUE TITLE
[Bug Report] unknown syntax error in DOM, can't find syntax or syntax undefined, please define. BUT ITS VUETIFY SYNTAX

### ISSUE THREAD

**Issue by yobretyo** [vuetifyjs/vuetify#10896]
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.6.11
**Browsers:** Safari 12.1.2
**OS:** Mac OS 10.14.6

### Steps to reproduce
using Vuetify syntax for button

### Expected Behavior
creating a button

### Actual Behavior
button

### Reproduction Link
<a href="http://codepen.io" target="_blank">http://codepen.io</a>

### Other comments
does anyone else have syntax errors in their DOM, yet, its syntax from Vue, Vuetify and others?
it also says "UNDEFINED" yet.... its Vuetify code

**Comment by KaelWD** [comment]
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible.

You can find information on how to contribute to Vuetify below:

- [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
- [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
- [Codepen](https://template.vuetifyjs.com/)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
