### ISSUE TITLE
[Bug Report] v-select tag conflict vue-select

### ISSUE THREAD

**Issue by Nakachi-S** [vuetifyjs/vuetify#10933]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 80.0.3987.122
**OS:** Mac OS 10.14.6

### Steps to reproduce
First, I installed as follows
- "vue": "^2.6.10"
- "vue-good-table": "^2.18.1"
- "vue-router": "^3.1.3",

Then, I installed as follows
- "@mdi/font": "^5.0.45"
- "@mdi/js": "^5.0.45"
- "file-loader": "^6.0.0"
- "material-design-icons-iconfont": "^5.0.1"

### Expected Behavior
If I install additional packages, I should still be able to use vuetify's v-select.

### Actual Behavior
However, in fact, it became v-select of vue-select, and props such as: items could not be used.

### Reproduction Link
<a href="https://github.com/" target="_blank">https://github.com/</a>

**Comment by Nakachi-S** [comment]
![image](https://user-images.githubusercontent.com/40224073/77496221-d28b2580-6e8d-11ea-89c9-41eaaacc52d8.png)
明らかにこれはvue-selectを用いた時に、optionsが指定されていない挙動です。

**Comment by MajesticPotatoe** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by jacekkarczmarczyk** [comment]
Both use the name (v-select), you need to register vuetify or vue-select component under a different name
