### ISSUE TITLE
[Bug Report] v-form v-input rule stopping navigation

### ISSUE THREAD

**Issue by grant007** [vuetifyjs/vuetify#10976]
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Mac OS 10.15.2

### Steps to reproduce
Click on the link labeled "go somewhere else".

### Expected Behavior
Link's action would happen and google.com page would display in new tab.

### Actual Behavior
Appears that email v-input's rule validation fires. Link's action does not happen.

### Reproduction Link
<a href="https://codepen.io/grant007/pen/QWbYrVL" target="_blank">https://codepen.io/grant007/pen/QWbYrVL</a>

### Other comments
I think the rule validation stops propagation of any/all events e.g. click event. I want to be able to have a button or link to be able to do something like navigate away from the page regardless of the form's state. Please advise.

**Comment by jacekkarczmarczyk** [comment]
When you click on the link the blur event is fired first and validation is triggered cause the link moving down and `click` event not being triggered. Don't use `hide-details="auto"` or don't put your link below the input

https://codepen.io/jkarczm/pen/jOPgrRV?editors=1010

**Comment by havardthom** [comment]
I also encountered this problem using `hide-details="auto"` in a form. The validation on field `blur` event caused the button to move, button got focus from `button-down` event, but `button-up` event did not hit button (since it moved) and my click event was not triggered. Took quite some time for me to figure it out 😅
