### ISSUE TITLE
[Bug Report] Vuetify got exception on Microsoft Edge version 44 without Babel compile

### ISSUE THREAD

**Issue by billsliu** [vuetifyjs/vuetify#10987]
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Microsoft Edge
**OS:** Windows

### Steps to reproduce
Using vue cli to create an application, without select Babel, then using "vue add vuetify" to add vuetify. 
App.vue
\<template\>
    \<v-app id="app"\>
        \<v-text-field label="Regular"\>\</v-text-field\>
    \</v-app\>
\</template\>
\<script\>
  export default { data: () => ({})};
\</script\>

### Expected Behavior
It runs well on Chrome, Friefox but got exception on Edge version 44 without select Babel to compile,   the same code runs good on Edge if I use Babel to compile. The exception points to ./node_modules/vuetify/lib/components/VApp/VApp.js  with error message "0: Expected identifier, string or number"

### Actual Behavior
It should run well on Edge version 44 even without Babel compile.  I think the \<v-app\> caused the problem, some code inside the VApp.js break the Edge.

**Comment by jacekkarczmarczyk** [comment]
You need to add `transpileDependencies: ["vuetify"]` parameter in vue.config.js, see https://vuetifyjs.com/en/getting-started/browser-support/#ie-11-amp-safari-9-support

Also:
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. 

Thank you for your contribution and interest in improving Vuetify. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by billsliu** [comment]
It is Edge version 44, the latest version, it does not need babel-polyfill, only IE 11 or early version Edge needs babel. I can say Vuetify never test on Edg e without babel.

There is no way to reproduce the problem by using outside of your environment, this problem is easy to produce, using vue client without select babel, Vuetify will generate exception on any code.

**Comment by jacekkarczmarczyk** [comment]
Edge doesn't recognize even this simple code:
![image](https://user-images.githubusercontent.com/15625235/78703395-5d4a3680-790a-11ea-97b4-d0626d048c62.png)

Transpiling is required for a-la-carte, if you can't use babel you can use full version (`import Vuetify from 'vuetify') or CDN

**Comment by billsliu** [comment]
I currently use babel, but I really don't want to use babel to compile my code to ES5 standard. We may drop Edge support.
