### ISSUE TITLE
[Documentation] Quick Start

### ISSUE THREAD

**Issue by klenzoid** [vuetifyjs/vuetify#11049]
### Problem to solve
How to use to Vuetify

### Proposed solution
Add instruction how to add components.   Using the quickstart instructions it never says to import the components you want.   HOURS!  Took HOURS to figure that out from someone else's blog.

**Comment by billsliu** [comment]
Add tag to your html file to use Vuetify, it is too easy to use Vuetify. Here is a example to use btn component:

`<v-btn>Login</v-btn>`

**Comment by jacekkarczmarczyk** [comment]
> it never says to import the components you want

Probably because you don't need to import them. Either you use full version with all components preloaded or you use vuetify-loader aka a-la-carte which imports them automatically (with some exceptions that are [documented](https://vuetifyjs.com/en/customization/a-la-carte/#limitations))

So please describe more precisely what you are talking about @klenzoid

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
