### ISSUE TITLE
[Documentation] Multiple Snackbars showing at the same time

### ISSUE THREAD

**Issue by VWaleek** [vuetifyjs/vuetify#11041]
### Problem to solve
If we click the snackbar in "Multiline" and "Timeout" after one another.

Multiple snackbars are showing at the same while MD spec say only one snackbar should show at one time.

### Proposed solution
Only one snackbar should be visible at the same time

**Comment by MajesticPotatoe** [comment]
That would be because they are 2 completely different snackbars controlled by two separate v-models. Each example is its own entity, and the component itself still follows spec.

Thank you for your interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
