### ISSUE TITLE
[Documentation] Change Typescript Recommendation

### ISSUE THREAD

**Issue by nvitaterna** [vuetifyjs/vuetify#11127]
### Problem to solve
The docs recommend adding `"types": ["vuetify"]` to tsconfig.json to solve `Error: Could not find a declaration file for module 'vuetify/lib'`. This should not be the solution as it has side effects that may effect other typings. `If types is specified, only packages listed will be included.` from https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

### Proposed solution
Change the recommendation to add the following to a declaration file:

```js
import 'vuetify/types/lib.d';
```

**Comment by LZQCN** [comment]
create a file `src/types/vuetify.d.ts`
```
declare module 'vuetify/lib' {
  import 'vuetify/types/lib';
  import 'vue/types/options.d';
}
```

**Comment by kuzvac** [comment]
Also you can add `node_modules/vuetify` to typeRoots section? like this: 
```
"compilerOptions": {
    "typeRoots": ["node_modules/vuetify"],
}
```

**Comment by FossPrime** [comment]
I was having the following errors:

```
TS7016: Could not find a declaration file for module 'vuetify/lib/components/VTextField'. '/home/projects/tdps-learn-web/node_modules/vuetify/lib/components/VTextField/index.js' implicitly has an 'any' type.
  If the 'vuetify' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'vuetify/lib/components/VTextField';`

33 import { VTextField } from 'vuetify/lib/components/VTextField'
```

The issue was that I was importing the modules too directly and Vuetify didn't export types to dist. Meaning only a handful of entry points have types such as `vuetify/lib` https://unpkg.com/browse/vuetify@2.6.9/types/lib.d.ts

I was able to solve my problem with no typeRoots or types defined in tsconfig.json, just Triple-Slash Directives in my ambient types declaration, often `src/env.d.ts` or `src/vite.d.ts`. It is easy to accidentally make it a regular module by accident, use carefully.

here's my whole vite.d.ts file:

```ts
/// <reference types="vite/client" />
/// <reference types="vuetify" />

declare module '*.vue' {
  import type { DefineComponent } from 'vue'
  const component: DefineComponent<{}, {}, any>
  export default component
}

```

Which allows me to import components as such:
```ts
//src/main.ts
import {
  VApp,
  VBtn,
  VImg,
  VCard,
  VCardActions,
  VCardSubtitle,
  VCardText,
  VCardTitle,
  VProgressCircular,
  VTextField
} from 'vuetify/lib'

Vue.component('v-app', VApp)
Vue.component('v-btn', VBtn)
Vue.component('v-img', VImg)
Vue.component('v-card', VCard)
Vue.component('v-card-actions', VCardActions)
Vue.component('v-card-subtitle', VCardSubtitle)
Vue.component('v-card-text', VCardText)
Vue.component('v-card-title', VCardTitle)
Vue.component('v-progress-circular', VProgressCircular)
Vue.component('v-text-field', VTextField)
```
