### ISSUE TITLE
[Bug Report] v-menu max-height doesn't work with auto

### ISSUE THREAD

**Issue by kunalahirrao** [vuetifyjs/vuetify#11144]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 10

### Steps to reproduce
NA

### Expected Behavior
Apply max-height to it.

### Actual Behavior
max-height prop not working.

### Reproduction Link
<a href="https://codepen.io/spider007/pen/WNQwMJV" target="_blank">https://codepen.io/spider007/pen/WNQwMJV</a>

**Comment by KaelWD** [comment]
`auto` has overridden max-height with `200px` since v0.9: 82889ee27054802ac41806d00d037716cd3df44b

**Comment by coolKIH** [comment]
also wondering why so ...

**Comment by apertureless** [comment]
Any updates on this? Especially with https://github.com/vuetifyjs/vuetify/issues/2660 this is super frustrating. Because we need to set auto:true in order to render large lists, but auto:true will overwrite the max height, which you normally would increase if you have a large list.

**Comment by tahaphuong** [comment]
> Any updates on this? Especially with #2660 this is super frustrating. Because we need to set `auto:true` in order to render large lists, but `auto:true` will overwrite the max height, which you normally would increase if you have a large list.
> 
> In my case I have also a search field inside the select thus with overwriting the maxHeight to 200, I am able to only see 3 entries of 200. Which makes this component unuseable.
> 
> https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VMenu/VMenu.ts#L117-L120

Hi @apertureless 

I'm new to Vue and Vuetify, could you please explain in which case do we "have to" set `auto` to `true`, in order to render long list? 
I guess maybe we can just manually set all the attributes and classes as needed, can't we?
And I do think, they didn't spontaneously make `200px ` overriding `max-height`, there should probably be a reason behind. 🤔

Thank you and have a nice day ;)

**Comment by apertureless** [comment]
> I'm new to Vue and Vuetify, could you please explain in which case do we "have to" set auto to true, in order to render long list?

You have to set `auto: true` if you're loading async a large list that needs to be rendered. Otherwise the content of the list for example in `v-select` will be capped and you cant see all the entries. It is also a known bug here and the "solution" or workaround it to set `auto: true`

> I guess maybe we can just manually set all the attributes and classes as needed, can't we?

Well, `auto: true` is setting an inline style for the width. So, no you cant really set it manually.

> And I do think, they didn't spontaneously make 200px override max-height, there should probably be a reason behind. 🤔

Yeah propably, but this behaviour is not documented.

I solved this, by extending the vuetify components and overwrite / remove this 200 maxheight.

**Comment by truemoroz** [comment]
same problem

**Comment by HYPE-Thomas** [comment]
> I solved this, by extending the vuetify components and overwrite / remove this 200 maxheight.

A probably more convenient way is to do the following:

- Use `:menu-props="{ auto: true, contentClass: 'customClassName' }"` on the `v-select`
- Override the baked-in `max-height` of 200 pixels with an `!important` style: 
```
<style lang="scss">
.customClassName {
	max-height: 400px !important;
}
</style>
```

I tested this successfully with Vuetify 2.4.10 and Chrome/Firefox.

**Comment by andreyrk** [comment]
This behavior is really annoying. One would expect auto to actually mean auto

**Comment by andreyrk** [comment]
> > I solved this, by extending the vuetify components and overwrite / remove this 200 maxheight.
> 
> A probably more convenient way is to do the following:
> 
> * Use `:menu-props="{ auto: true, contentClass: 'customClassName' }"` on the `v-select`
> * Override the baked-in `max-height` of 200 pixels with an `!important` style:
> 
> ```
> <style lang="scss">
> .customClassName {
> 	max-height: 400px !important;
> }
> </style>
> ```
> 
> I tested this successfully with Vuetify 2.4.10 and Chrome/Firefox.

Thanks. For anyone passing by, if you're not using v-select but rather v-menu, this is done like so:
```
<v-menu contentClass="customClassName">
```
