### ISSUE TITLE
[Feature Request] Icon's clickable effect fade away after mouse moving out [in desktop]

### ISSUE THREAD

**Issue by allmonday** [vuetifyjs/vuetify#11185]
### Problem to solve
the default effect (darken background) keeps visible even after the mouse has been moved out.
 better to provide a prop to remove the effect after that.

### Proposed solution
prop: clickable-persistent , default: true
by setting false, the darken bg will disappear after moving out.

**Comment by johnleider** [comment]
Here is a workaround for your use-case but I wouldn't recommend it because it's specifically there for a11y https://codepen.io/johnjleider/pen/WNGrGyo

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
