### ISSUE TITLE
[Bug Report] PR #7759 for VAutocomplete breaks directly listening for paste event

### ISSUE THREAD

**Issue by rh78** [vuetifyjs/vuetify#11186]
### Environment
**Vuetify Version:** 2.2.23
**Last working version:** 2.0.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.113
**OS:** Windows 10

### Steps to reproduce
@paste event no longer issued after PR https://github.com/vuetifyjs/vuetify/pull/7759

### Expected Behavior
@paste event called correctly

### Actual Behavior
@paste event is completely omitted. It looks like the paste event is just internally overridden in the framework.

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

- [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
- [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
- [Codepen](https://template.vuetifyjs.com/)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by rh78** [comment]
Please look at 

https://github.com/vuetifyjs/vuetify/pull/7759/files#diff-4b16425902082484cc4380fd5e3e390bR72 

VCombobox.ts

Line 72

There the paste event is overwritten without considering event handlers already in place.

This causes the behavior.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by rh78** [comment]
Hello we did you close this issue? The bug is still there.
