### ISSUE TITLE
[Bug Report] App not loading in Firefox because of error on regexp

### ISSUE THREAD

**Issue by abbierwolf** [vuetifyjs/vuetify#11214]
### Environment
**Vuetify Version:** 2.3.0-beta.0
**Last working version:** 2.2.23
**Vue Version:** 2.6.11
**Browsers:** Firefox 75.0
**OS:** Ubuntu undefined

### Steps to reproduce
Load codepen example and look in console. Nothing is loaded

### Expected Behavior
App to be loaded and running

### Actual Behavior
Empty page and in console I found an exception:

SyntaxError: invalid regexp group

### Reproduction Link
<a href="https://codepen.io/abbierwolf/pen/WNQpQML" target="_blank">https://codepen.io/abbierwolf/pen/WNQpQML</a>

**Comment by johnleider** [comment]
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
* [Codepen](https://template.vuetifyjs.com)
* [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
* A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Ar4093** [comment]
Reproduction link: https://dev.vuetifyjs.com/en/getting-started/quick-start/

**Comment by johnleider** [comment]
Resolved in #11215 

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
