### ISSUE TITLE
[Feature Request] Add a props to each input to show a required mark near the label

### ISSUE THREAD

**Issue by marcomd** [vuetifyjs/vuetify#11279]
### Problem to solve
Show a required field before form validation, this is a common feature. A new Boolean parameter would allow you to handle it with vuelidate.

### Proposed solution
A new props, boolean, "required field" or "required mark", which shows a "*" near the label.

**Comment by marcomd** [comment]
Sorry, it should be on all inputs and not just on the text field, this could be more complex to do

**Comment by marcomd** [comment]
Example:
<img width="383" alt="immagine" src="https://user-images.githubusercontent.com/194608/80717720-7a34ec80-8af9-11ea-9ea1-72e832b32d08.png">

or 

<img width="328" alt="immagine" src="https://user-images.githubusercontent.com/194608/80717911-c2540f00-8af9-11ea-874c-4da7daf126e1.png">

**Comment by marcomd** [comment]
<img width="427" alt="immagine" src="https://user-images.githubusercontent.com/194608/80718272-3b536680-8afa-11ea-8ca3-140d0f0dc4e2.png">

**Comment by KaelWD** [comment]
`required` used to do this, it was removed because it should depend on the amount of other required fields in the form. 

https://material.io/components/text-fields#anatomy

- If some fields are required, indicate all required ones
- If most fields are required, indicate optional fields by displaying the word “optional” in parentheses next to the label text

**Comment by marcomd** [comment]
Ok.
I hadn't considered that rules which actually introduces a lot of complexity.

So, all that remains is to do it manually:
`:label='labelFor("first_name")'`

and the method:
```js
labelFor(field) {
  let label = this.$t(this.labelsPrefix() + '.' + field)
  if (this.$v && this.$v[field]) {
    // All this stuff to manage vuelidate...
    if (!!this.$v[field].$params.required &&
      (this.$v[field].$params.required.type == 'required' ||
        (this.$v[field].$params.required.type == 'requiredIf' && this.$v[field].$params.required.prop() ))) {
      label += ' *'
    } else {
      label += ' [optional]'
    }
  }
  return label
}

labelsPrefix() {
  return 'commons.labels' // override in the component if needed
},
```

and manually add a hint as well, one under each field or something else

**Comment by Tofandel** [comment]
Hmm, why is this closed?

Couldn't we add a class at least to the input element when required is set or an aria attribute, currently the required is only set on the input which makes it impossible to style depending on the required state..

Because this mark could very easily be added as a pseudo element on the label, you could also add a class on the form that represents whether there is more required fields than optional and change the pseudo element to be optional on non required fields..

Where is the complexity in that?

Right now this is a huge problem, with terrible workarounds.. https://stackoverflow.com/questions/52158705/vuetify-how-to-mark-field-as-required
