### ISSUE TITLE
[Bug Report] Icons in buttons are too large

### ISSUE THREAD

**Issue by ysb** [vuetifyjs/vuetify#11294]
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Mac OS 10.15.4

### Steps to reproduce
- Add a v-btn component.
- Add an some text and icon inside it <v-icon right>mdi-cloud-upload</v-icon>

### Expected Behavior
- Font size should be 18px.

### Actual Behavior
- Still 24px, 18px is being overrided. You can see in screenshot below.

### Reproduction Link
<a href="https://github.com/mpaksoy/vuetify-build-test" target="_blank">https://github.com/mpaksoy/vuetify-build-test</a>

### Other comments
Vue cli version: 4.3.1

I use vuetify for a big project. But some styles are breaking when I build project. There is no other library then vue, vuex, vuerouter and vuetify in project.
I created a fresh project and tested on it, same problem again. You can check it on GitHub link. I shared screenshots as well.

I’ve solved the problem on main project by creating an overrides.scss file and adding !important to all lines, but this is not an elegant way.

https://snipboard.io/bh4kxt.jpg
https://snipboard.io/r9MRlI.jpg

Thanks.

**Comment by YipingRuan** [comment]
Similar to https://github.com/vuetifyjs/vuetify/issues/8067 ?

**Comment by KaelWD** [comment]
3d9dc507ecaeedb3def0b93f7ad41ba6d2419a45

**Comment by jbergfi** [comment]
I've just struck into the same issue when trying to place icons to left or right in buttons. On the demo site it looks ok, it's probably depending on how you've installed Vuetify (using vuetify loader/A-la-carte or not?) since the order of styles in the style sheet are different there compared to my project. I also created a codepen from the vuetify template that displays the issue: https://codepen.io/jbergfi/pen/PoNmbmV

My workaround is to specify size="18" on the v-icon

**Comment by KaelWD** [comment]
In v3 I've made icons default to 18px, scaling with the button's font-size:

![image](https://user-images.githubusercontent.com/16421948/108189620-0be31880-7165-11eb-8d83-2601296e74aa.png)

This only applies to the default size, if you do `<v-icon size="large">` it'll use the non-scaled large size instead.
