### ISSUE TITLE
[Feature Request] v-calendar #outer-event slot

### ISSUE THREAD

**Issue by hackerESQ** [vuetifyjs/vuetify#11309]
### Problem to solve
**styling**
It is not easy to override the styling and appearance of events in the #events slot. Currently the #event slot is wrapped by the ```div.v-event``` element which has its styling applied inline -- thus each day shows in a new line. I am currently forced to use the #day slot and iterate through my events array for events that match the day. 

**performance**
Using the #day slot also causes an n+1 loop problem for each 'day' that is iterated through, there's another iteration through my events. In the case there are several hundred events, or perhaps thousands, this could be a significant performance issue. 

### Proposed solution
Create an #outer-event slot that encapsulates the current #event slot and solves both the styling and performance issues. 

**styling**
allows full access to the presentation of events

**performance**
allows the use of the pre-existing events prop from the #event slot and avoids the n+1 issue

**Comment by hackerESQ** [comment]
This is what I am currently doing:
``` 
                   <v-calendar
                        ref="calendar"
                        v-model="focus"
                        :type="type"
                        :events="events"
                        :event-height="0"
                        color="primary"
                        @click:date="viewDay"
                        @change="updateRange"
                    >

                        <template #day="{ month, present, past, date }">
                               
                            <div class="v-date-picker-table__events" style="position: absolute; top:1.75rem">
                                <template v-for="event in events">

                                    <template v-if="event.start==date">

                                        <div :title="event.name" :class="event.color"></div>
                                    </template>
                                </template>
                           </div> 
                        </template>

                    </v-calendar>
```


It would be much more efficient this way:
```
                         <template v-slot:outer-event="{ event, day }">
                            <div v-if="event" :title="event.name" :class="event.color"></div>
                        </template>
```

ultimately I am trying to emulate the v-datepicker dot notation for events in v-calendar:
<img width="406" alt="Screen Shot 2020-05-02 at 10 27 23 PM" src="https://user-images.githubusercontent.com/16628119/80898022-29bdba80-8cc4-11ea-8e0f-225ae4f5562c.png">

**Comment by ClickerMonkey** [comment]
The entire purpose of the event features of the calendar is to handle the complex logic involved in positioning elements. If you want to display them an entirely different way then you'll have to do your own logic. For example the event logic doesn't have a slot for every day, it picks the first day in the current week that the event is visible on. That might not work for your situation, or others, hence why changing the logic for a unused case (with respect to Vuetify) doesn't make sense. In other words, it's not just a matter of adding another slot - there's a lot more involved that can't be guessed since it might be different for each user. 

As far as efficiency goes, if you use the change event and filter down your events based on those dates you should be golden. If you want to use the same internal parsed event format the Vuetify does then set ref on your calendar and call the parseEvent function to convert it into what the calendar sees. The calendar takes the events you give it, has a computed property that converts that array into a parsed event array, then for each day checks each event and based on the calendar type and slot figures out if something needs to go in that slot. That's not going to be the same logic as what you want, hence you need to do that heavy lifting yourself.
