### ISSUE TITLE
[Feature Request] MD1 Dark theme as an option

### ISSUE THREAD

**Issue by Stoom** [vuetifyjs/vuetify#11308]
### Problem to solve
With the latest version of Vuetify there was an update to the dark theme to match MD2.  Would it be possible to have `theme: { dark: true }` take a boolean for light or MD2 dark, or a string of `"md1" | "md2"` for the MD1 version of the dark theme. 

### Proposed solution
extend the `theme -> dark`  to `boolean | "md2" | "md1"` to allow for the lighter dark mode **without** having to override all of the styles.

**Comment by ibrahimBeladi** [comment]
In my honest opinion, that will require a lot of tweaks if built into Vuetify. Given most of the changes are in style (css), you can do it after providing the correct sass variables their correct values. This can be done and exported as a preset if someone is willing to implement it, but might require some work because there are tons of sass variables now.

**Comment by Stoom** [comment]
Is it not just contained to the theme scss files?

**Comment by ibrahimBeladi** [comment]
I am not sure what does 'it' refers to, I will assume you meant MD1 dark theme. It was, but now it is overwritten by MD2 specs. Common style values will still exist, but you will need to overwrite the current variables to meet the specs of MD1. Changing the values is easy, but making the whole MD1 style specs will be a bit tedious. 

You will need to change hundreds of values to meet MD1 specs, I would encourage you to wait and see if some people in the community are interested in this, so that others help you in making a MD1 preset as a collective work.

**Comment by Stoom** [comment]
I guess really for me it's about the color.  As I'm making this app for my company I don't want an update to change the entire color scheme.  It would be nice to have a way to keep the old colors so that it's not a shock to my user base.

**Comment by ibrahimBeladi** [comment]
If it is just the colors, then you can get the colors and set the color variables to those colors and you are done. There are only about a couple of tens of color variables regarding theme colors.

Good luck in your upgrade process 👍

**Comment by Stoom** [comment]
Yeah but if you decide to use custom styles then the build times are horrible.

**Comment by KaelWD** [comment]
I don't think this is likely to be implemented, we don't have MD1 styles available as an option for anything else except text fields, and the theme system is currently based around light/dark only. I see you've already commented on https://github.com/vuetifyjs/vuetify/issues/10293#issuecomment-577016726, changing those variables should have little to no impact on build times if you're already using vuetify-laoder/a-la-carte.
