### ISSUE TITLE
[Bug Report] v-data-table inaccurately grouped if server-items-length is set

### ISSUE THREAD

**Issue by tantee** [vuetifyjs/vuetify#11349]
### Environment
**Vuetify Version:** 2.2.27
**Last working version:** 2.1.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Windows 10

### Steps to reproduce
1. create a v-data-table with grouping
2. set server-items-length to some value

### Expected Behavior
Data is accurately grouped

### Actual Behavior
Data is not accurately grouped

### Reproduction Link
<a href="https://codepen.io/tantee/pen/BaorzZq" target="_blank">https://codepen.io/tantee/pen/BaorzZq</a>

**Comment by nekosaur** [comment]
The reason this happens is because the current groupBy logic assumes that the items it should group by are ordered by the `groupBy` property. Which it always will be not using `server-items-length`.

The workaround for now would be to make sure the server items are always ordered first by the `groupBy` property.

**Comment by lennoximus** [comment]
Another option is to provide your own `groupBy` function that, in my case, ended up to be a slightly different version of the built-in `groupItems` helper method.
