### ISSUE TITLE
[Bug Report] Headings default configs doesn't work

### ISSUE THREAD

**Issue by LizanLycan** [vuetifyjs/vuetify#11343]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Windows 10

### Steps to reproduce
Declare a `<h...>` tag and check styles

### Expected Behavior
See the default styles (`$headings`) applied to the respective` <h ...>` tag.

### Actual Behavior
The last applied style noted is from the `user agent stylesheet` and by `.v-application`.

### Reproduction Link
<a href="https://codepen.io/LizanLycan/pen/ZEbxYXJ" target="_blank">https://codepen.io/LizanLycan/pen/ZEbxYXJ</a>

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/issues/9306
https://github.com/vuetifyjs/vuetify/issues/6258

**Comment by davydnorris** [comment]
I was caught by this as well. It turns out that direct manipulation of the styles attached to the heading tags has been removed, and instead the heading styles were mapped to the Material Design spec display-*, etc classes.

The next release is going to change that again and map them to text-head* classes, as per the new MD spec. See: [https://github.com/vuetifyjs/vuetify/releases/tag/v2.3.0-beta.3](https://github.com/vuetifyjs/vuetify/releases/tag/v2.3.0-beta.3)
