### ISSUE TITLE
Datatables "Select all Rows" is broken

### ISSUE THREAD

**Issue by mstaack** [vuetifyjs/vuetify#1135]
### Versions
v0.14.6 (latests docs online)

### What is expected ?
Action `check all rows`  should select all rows

### What is actually happening ?
No row at all is selected (All rows have an unchecked checkbox)

### Reproduction Link
Online docs have this problem: https://vuetifyjs.com/components/data-tables

**Comment by ChavaSobreyra** [comment]
Selecting individual rows isn't working either

**Comment by ChavaSobreyra** [comment]
Not broken in 0.14.5

**Comment by johnleider** [comment]
Fumbled ordering in refactor, whoops.

**Comment by Geowan** [comment]
This issue is still recoccuring in the version 1.3.15, Even in the official docs i have noticed that when none of the checkbox are checked and then i select the checkall on the header none get selected but on the indeterminate(one checkbox selected) and then click of checkall checkbox(on the header) all get selected.

Toggling all checkboxes to unselected state also fails

**Comment by nekosaur** [comment]
Please do not comment on old issues. If you're having problems, please create a new issue.
