### ISSUE TITLE
[Bug Report] Vuetify RTL on exsisting nuxt project

### ISSUE THREAD

**Issue by 1shaked** [vuetifyjs/vuetify#11449]
### Environment
**Vuetify Version:** 2.2.29
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
just trying to add rtl support when using new nuxt project but can not do it 
install vuetify and mdi/font on an empty nuxt project 
craete a file in the plugins folder name vuetify.js
add the follwing code to the vuetify.js 
`
import Vue from 'vue'
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css'
import '@mdi/font/css/materialdesignicons.css'
import colors from "vuetify/es5/util/colors";
Vue.use(Vuetify)

export default ctx => {
  const vuetify = new Vuetify({
    rtl: true,
    theme: {
      dark: false,
       themes: {
         dark: {
           primary: colors.deepPurple.lighten3,
           accent: colors.deepPurple.accent3,
           secondary: colors.amber.darken3,
           info: colors.teal.lighten1,
           warning: colors.amber.base,
           error: colors.deepOrange.accent4,
           success: colors.green.accent4
         }
        }
      },
  })

  ctx.app.vuetify = vuetify
  ctx.$vuetify = vuetify.framework
}
`
then add to the nuxt.config.js  the plugin

`
plugins: [
    '~/plugins/vuetify'
  ]
`

### Expected Behavior
haing the layout RTL

### Actual Behavior
LTR

### Reproduction Link
https://github.com/1shaked/webq.git
this is in the webq_ssr

### Other comments
i tring add the rtl:true to the vuetify object but no help

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

- [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
- [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
- [Codepen](https://template.vuetifyjs.com/)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by 1shaked** [comment]
you are right, i changed it to be simpler to follow.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
