### ISSUE TITLE
[Bug Report] V-Select still looks focused when calling focus() on other element

### ISSUE THREAD

**Issue by brease-colin** [vuetifyjs/vuetify#11476]
### Environment
**Vuetify Version:** 2.2.29
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
1. Select a value in the v-select component
2. The watch on the v-model associated with the v-select calls the focus() method on the v-text-field

### Expected Behavior
The v-select is unfocused (blurred) and the v-text-field is focused. Only the v-text-field should have the blue border, so that the user knows which element is focused.

### Actual Behavior
Both elements still have the blue (highlighted) border, making it hard to see which element has focus. Clicking outside the v-text-field removes the border from both components.

### Reproduction Link
<a href="https://codepen.io/brease-colin/pen/rNObjyB" target="_blank">https://codepen.io/brease-colin/pen/rNObjyB</a>

### Other comments
This issue is still present in beta.6.

**Comment by johnleider** [comment]
If you're going to manually focus v-text-field, you'll have to manually blur v-select as well due to how we handle events on selects.

Here is an example: https://codepen.io/johnjleider/pen/RwGGwVG

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
