### ISSUE TITLE
[Bug Report] Sorted column of v-data-table is reset when v-dialog activated

### ISSUE THREAD

**Issue by naokton** [vuetifyjs/vuetify#11517]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Safari 13.1
**OS:** Mac OS 10.13.6

### Steps to reproduce
1. add v-data-table with `:sort-by="['name']"` property
2. add v-dialog outside of v-data-table
3. sort column other than default sorted column ("name" above)
4. activate v-dialog

### Expected Behavior
The sorted column does not change.

### Actual Behavior
The sorted column moves to default sort column specified in `sort-by` property.

### Reproduction Link
<a href="https://codepen.io/naokton/pen/OJyexRK" target="_blank">https://codepen.io/naokton/pen/OJyexRK</a>

### Other comments
I found two workarounds:
1. Specify `sort-by` value by string: `:sort-by="'name'"` OR `sort-by="name"`
2. Move v-dialog block into `top` slot of v-data-dialog

**Comment by jacekkarczmarczyk** [comment]
It's an upstream issue for me, when dialog opens it rerenders the template, so the `["id"]` array is evaluated again which has the same effect as you set a new value of `sort-by` prop
![image](https://user-images.githubusercontent.com/15625235/84377383-cab46500-abe2-11ea-823b-3032279f0b0d.png)

This is not the case for your first workaround because watcher is not triggeres as the string value doesn't change

Solution number 3 is to declare a `sortBy` variable in data and use it in `sort-by` prop: https://codepen.io/jkarczm/pen/yLeOybY

**Comment by nhj7** [comment]
I had the same problem. I solved it by looking at this. Thank you.
