### ISSUE TITLE
[Bug Report] v-text-field + filled (v-slot:label not working)

### ISSUE THREAD

**Issue by Dinver** [vuetifyjs/vuetify#11533]
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Windows 10

### Steps to reproduce
Add prop "filled" in v-text-field;
Add v-slot:label.

### Expected Behavior
Same as without filled.

### Actual Behavior
No functionality.

### Reproduction Link
<a href="https://codepen.io/dinver/pen/oNbvxJM?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ftext-fields%2F" target="_blank">https://codepen.io/dinver/pen/oNbvxJM?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ftext-fields%2F</a>

**Comment by jacekkarczmarczyk** [comment]
works fine if you add `label="anything"`

**Comment by Dinver** [comment]
> works fine if you add `label="anything"`

May be need write in documentation? I did not find such a description prop.

**Comment by KaelWD** [comment]
Scoped slots don't exist until `render()` in vue 2: https://codepen.io/kaelwd/pen/rNLNYGL?editors=1011  
This seems to be fixed in vue 3: https://codepen.io/kaelwd/pen/gOMOXoB?editors=1011

If you use `slot="label"` instead of `v-slot="label"` then it works without the label prop. 

`this.$slots.label` is accessed before render by `labelValue` watcher -> `labelValue` -> `isSingle` -> `hasLabel`
