### ISSUE TITLE
[Bug Report] Unable to type into VAutocomplete if item-text is an arrow function

### ISSUE THREAD

**Issue by mvirkkunen** [vuetifyjs/vuetify#11585]
### Environment
**Vuetify Version:** 2.2.33
**Last working version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Linux x86_64

### Steps to reproduce
Use an arrow/inline function for the `item-text` property of VAutocomplete. The Codepen link is the first example from the docs, except that `item-text` has been changed into an arrow function.

### Expected Behavior
I should be able to type into the search input.

### Actual Behavior
When I try to type into the search input, the input is seemingly ignored.

### Reproduction Link
<a href="https://codepen.io/mvirkkunen/pen/bGEEpbw" target="_blank">https://codepen.io/mvirkkunen/pen/bGEEpbw</a>

### Other comments
Using a normal method instead of an arrow function works so it's easy to work around. Maybe it has something to do with the fact that the arrow function is a different object on every render, but a method stays the same.

**Comment by thegoldgoat** [comment]
Hello!

Wanted to say I can reproduce the same problem in latest Vue and Vuetify

The problem here is actually the `:search-input.sync="search"` line

Without that one - try it in the codepen - you can see that it just works.

Putting a `search` in `watch` and printing the variabile to the console you can see that whenever you type, the `watch` function gets called two times:

1. first time: `this.search` is the char you typed
2. second time: `this.search` is set to `null`

No wonder how that happens, but this is it.

### Workaround

Don't use `item-text` with an arrow function, use this templates inside v-autocomplete instead:

```vue
      <template v-slot:item="{ item }">
        {{ item.name }} {{ item.surname }}
      </template>
      <template v-slot:selection="{ item }">
        {{ item.name }} {{ item.surname }}
      </template>
```

Of course you would need to do a custom search function, since the component cannot search text, and then apply the `no-filter`

**Comment by jblachly** [comment]
Was also bitten by this today.
Replacing the arrow function (e.g. ```u => `${u.name} <${u.email}>` ``` ) with a method resolves it. Still, messy and inconvenient. Maybe has to do with different context of methods versus arrow functions (i.e. no `this`)?

**Comment by Shinigami92** [comment]
Also tested it  
Just adding
```js
  methods: {
    extractDescription(item) {
      return item.Description
    }
  },
```

and using
```js
:item-text="extractDescription"
```

resolves it

At least that's a workaround

**Comment by thegoldgoat** [comment]
> Maybe has to do with different context of methods versus arrow functions (i.e. no this)?

I guess that one is the problem

**Comment by webdevnerdstuff** [comment]
Just an observation, but the `.sync` modifier is a breaking change for Vue 3. Unless I'm reading this wrong.

https://v3-migration.vuejs.org/breaking-changes/v-model.html
