### ISSUE TITLE
[Documentation] Developing with yarn link

### ISSUE THREAD

**Issue by ghost** [vuetifyjs/vuetify#11602]
### Environment
**Vuetify Version:** 2.2.34
**Vue Version:** 2.6.11
**Browsers:** Firefox 77.0
**OS:** Ubuntu undefined

### Steps to reproduce
1- Clone the repository
2- Go to vuetify/packages/vuetify, where the root vuetify is the cloned rep
3- Run yarn && yarn build
4- Go to some other repository and run npm install vuetify@path/to/cloned/packages/vuetify
5- npm run serve
6- Solve linting problems
7- npm run serve

### Expected Behavior
I would like to be able to work with a fork of vuetify. The above procedure is the best I could come with after some hours of failed attempts

### Actual Behavior
Compilation goes through, but the application is blank on the browser and the following error shows up in the console:

"Vuetify is not properly initialized, see https://vuetifyjs.com/getting-started/quick-start#bootstrapping-the-vuetify-object"

### Reproduction Link
<a href="https://github.com/davidmoseler/vuetify" target="_blank">https://github.com/davidmoseler/vuetify</a>

### Other comments
It would be very useful to have a guide on how to use a fork of vuetify in another repository.

**Comment by KaelWD** [comment]
See #9319

**Comment by davidmoseler** [comment]
Thanks! The "resolve.symlinks: false" config solved it for me. If the docs are going to be written, please mind that someone might want to publish the fork to npm with a different name, such as @author/vuetify. Since yarn links do not support an alias as far as I know, I had to install the dependency as a folder instead of using yarn link.
