### ISSUE TITLE
[Bug Report] Regression on custom column filter matching behaviour in VDataTable

### ISSUE THREAD

**Issue by Ignigena** [vuetifyjs/vuetify#11600]
### Environment
**Vuetify Version:** 2.2.34
**Last working version:** 2.2.32
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Mac OS 10.15.5

### Steps to reproduce
1. Add a custom column filter callback which matches against the `search` param.

  Easiest to reproduce by doing a case sensitive or exact match on the column name.

2. Enter search term that only matches the column with a custom matcher.

### Expected Behavior
If the custom filter function returns a row, it should be shown in the table.

### Actual Behavior
Only rows are shown on the table that also match columns **without** a custom filter function when the search field is populated. This makes search and filtering with custom functions unpredictable since matches are suppressed that should otherwise be shown.

In the linked CodePen above, set a filter for "Less than 300 calories" and observe all rows are returned as expected. However, enter `Eclair` in the search box at the top (case sensitive, must be exact). Even though the Eclair row matches the custom filter we see "No matching records found"

### Reproduction Link
<a href="https://codepen.io/Ignigena/pen/dyYOmxj?editors=1010" target="_blank">https://codepen.io/Ignigena/pen/dyYOmxj?editors=1010</a>

### Other comments
This was fixed in 2.2.32 and regressed as a part of https://github.com/vuetifyjs/vuetify/pull/11575 If you pin the above CodePen to 2.2.32 you will see the table filtering and search works as expected.

While all tests are passing in the breaking PR, it is due to the original test case being modified so that it no longer prevents regression against the original scenario. In this case, we need to test the `search` variable in the filter callback to ensure that exclusive matches are still returned.

**Comment by simonbrunel** [comment]
Recently updated to 2.3.1 and my use case is also broken, most probably because of #11575. I use header filters to allow searching on nested data (e.g. a list of users) since I'm displaying multiple values in a single cell. So I'm expecting the row to be displayed if my header filter returns `true` **OR** if any of the other columns matches the search query.

```html
<v-data-table>
  <template #item.users="{ value }">
    <span v-for="(user, index) in value" :key="user.id">
      <!-- display user photos and name -->
      <!-- ... code edited ... -->
    </span>
  </template>
</v-data-table>
```

```javascript
headers: () => [
  {
    text: 'Name',
    value: 'name',
  },
  // ...
  {
    text: 'User(s)',
    value: 'users',   // This is an array of objects
    filter(users, search) {
      if (!search) {
        return true;
      }

      for (const user of (users || [])) {
        for (const value of [
          user.firstName,
          user.lastName,
          user.email,
        ]) {
          if (value && matches(value, search)) {
            return true;
          }
        }
      }
    },
  }
```

The header `filter` callback receives  `search` as second parameter, so it's not clear what the goal of this method. If it should be used to either customize search or provide row filtering, a solution could be to consider `true`, `false` and `undefined` as possible returned values:

- `true`: request to keep the row
- `false`: remove the row, whatever the other filters return
- `undefined`: no action

Then:

- row is kept if `!search` and all filters return either `undefined` or `true`.
- row is kept if `search` and at least one filter returns `true` and none return `false`.
- row is removed if `search` and all filters returns either `undefined` or `false`.
- row is always removed if at least one filter returns `false`.

Not sure that's the best API but I think it allows all mentioned use cases.

**Comment by CumpsD** [comment]
This seems to have broken over time. When I return `true` from my filter, the row is no longer being shown, while in the past it was.

**Comment by simonbrunel** [comment]
@CumpsD I didn't look for a workaround yet but I guess we would have to implement a custom filter for the whole table and match *all columns* manually. It's not convenient and, as @mk86 already mentioned, it duplicates the data table internal logic.

@johnleider Any recommendation on how to address this breaking change? Would the solution I suggested (i.e. `true|false|undefined`) be acceptable? Else do you think of any solution that would allow both use cases?

@mk86 Any feedback?

**Comment by CumpsD** [comment]
@simonbrunel so I guess, if we pass in the previous logic as a custom filter it should work again?

```js
function searchTableItems (
  items: any[],
  search: string | null,
  headersWithCustomFilters: DataTableHeader[],
  headersWithoutCustomFilters: DataTableHeader[],
  customFilter: DataTableFilterFunction
) {
  search = typeof search === 'string' ? search.trim() : null

  // If the `search` property is empty and there are no custom filters in use, there is nothing to do.
  if (!(search && headersWithoutCustomFilters.length) && !headersWithCustomFilters.length) return items

  return items.filter(item => {
    // Headers with custom filters are evaluated whether or not a search term has been provided.
    if (headersWithCustomFilters.length && headersWithCustomFilters.every(filterFn(item, search, defaultFilter))) {
      return true
    }

    return (search && headersWithoutCustomFilters.some(filterFn(item, search, customFilter)))
  })
}
```

**Comment by simonbrunel** [comment]
@CumpsD I decided to not rely on the data table search/filter features because it's easier in my case to filter items separately in a computed prop used to feed the `items` property of the data table. Though, it would still be great to be able to use the built-in header filter to do that.

**Comment by Ignigena** [comment]
I'm in the same boat. We held off the upgrade for a while hoping the regression would just get reverted but have since just moved away from the built-in component logic to using a computed prop to drive the `items` property.

I can confirm that simply going back to the logic as it existed previously works exactly as expected.

**Comment by mk86** [comment]
I wonder whether adding complexity here just makes it harder to use for not enough benefit.
The workaround for the functionality _we_ need (intersection of results) would be to pre-filter data using a computed property.
The workaround for those needing union of results is the aforementioned javascript, which definitely feels like more implementation detail than you should really need to know in order to use this component.
I think that when the previous issue (that it wasn't providing an intersection of results) was discussed, there was not enough context and so it appeared it was a bug rather than a feature which was being relied upon. This was exacerbated by the example in the docs, which felt very counter-intuitive (to me, at least). We found the associated bug in the backlog and so fixed it.
This is really a decision for the maintainers of whether they would like to increase flexibility at the cost of complexity, or keep it simpler to use and accept that some use cases need a (minor) workaround. It's tricky when there aren't good usage stats and clearly there are a number of people that want each behaviour. However, I think I would advise reverting the previous PR, accepting the previous behaviour and clarifying in the documentation that this is intentional and how to work around it if you want an intersection instead.

**Comment by ERPedersen** [comment]
Any update on this? It seems like the `filter` property on `DataTableHeader` is now completely broken.

I think we should either revert the previous PR, which in my case adds support for a less common use-case than what was initially intended, or remove the property entirely. Right now, it serves no purpose but confusion.

**Comment by alanscandrett** [comment]
Still seeing the same behaviour which is a shame, it forces us to choose bewteen filtering individual columns or having the standard search :(

**Comment by tim-koehler** [comment]
This is super annoying😞 Are there any updates?

**Comment by shunjilin** [comment]
Agree that the demo example and documentation is a little bit confusing, the docs seem to imply that the default filter function per column can be overridden but that actual behavior and demo behaves otherwise.

Would it be worth to clarify the docs in the meantime before the new composable feature #14035 is backported? I could take a stab at that

**Comment by pedrolamas** [comment]
> We're working on new options for this in v3 that will probably be backported to v2.7.0, leave feedback on #14035 if we've missed any use-cases.

@KaelWD, #14035 has been merged a few months ago, is there any timeline to get this backported so that we can mitigate this issue?

I completely understand that priority is now for Vuetify 3, however I believe this issue to be quite severe in Vuetify 2 to deserve some attention.
