### ISSUE TITLE
[Bug Report] Autocomplete clears on second selection made after blur

### ISSUE THREAD

**Issue by xon52** [vuetifyjs/vuetify#11626]
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
I have an autocomplete fetching data from an external source. After a selection is made I blur the box. 
I have noticed that after selecting one item and then going back to the box and selecting another, it clears immediately after selecting it.

![autocomplete issue](https://i.imgur.com/GzFtw3M.gif)

### Expected Behavior
It is expected to never clear unless I remove it myself (which works for every other case)

### Actual Behavior
The weirdest thing is if I select one of the first 2 on my second selection, it works.

### Other comments
I found a fix which exposes the problem I think. Within the `@change` method which blurs the box, I wrapped it in a wait function (just waits a number of seconds):
```js
this.$wait(0.5).then(() => {
   this.$refs.search.blur()
})
```
If I have anything less than 0.4s it doesn't work so there is quite a big delay.

Also, watching events, I can see where it's happening (without that delay):
![without delay](https://i.imgur.com/FdAmfO8.png)
But with the delay:
![with delay](https://i.imgur.com/jDRVNJl.png)

**Comment by johnleider** [comment]
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
* [Codepen](https://template.vuetifyjs.com)
* [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
* A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by xon52** [comment]
Yeah I can't reproduce this without going all out on an example so maybe it's too specific to my case. I'll keep trying if I can as I do think there's a sequence issue with completing a cycle on the autocomplete.
