### ISSUE TITLE
[Bug Report] Entire Google Chrome window lights up in dark mode on button click

### ISSUE THREAD

**Issue by valentingavran** [vuetifyjs/vuetify#11699]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.1
**Browsers:** Chrome 83.0.4103.106
**OS:** Mac OS 10.15.5

### Steps to reproduce
Open Google Chrome (only noticed it there). Set the theme property `dark` to `true` in the Vuetify settings. Then click on a button with the `icon` attribute .

### Expected Behavior
Nothing unusual should happen except the desired onClick functionality and maybe the ripple effect of the button.

### Actual Behavior
The whole browser window lights up very slightly. You hardly notice it but it is there. Also tested it in Safari. But I didn't notice anything there.

You can see it even more clearly when Night Shift (MacOS) is enabled. Then the whole thing is very annoying.

### Reproduction Link
**Edit:** https://codepen.io/valentingavran/pen/oNbZwdP

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

- [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
- [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
- [Codepen](https://template.vuetifyjs.com/)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by valentingavran** [comment]
I have now added a JSFiddle link.

It may be that this is only the case for buttons with the attribute `icon`. But I'm not sure.

**Comment by KaelWD** [comment]
I don't have a mac but I can't see it on linux, and there shouldn't be anything that affects the entire page. Does your monitor have any sort of dynamic contrast or adaptive backlight enabled?

**Comment by valentingavran** [comment]
It does not only concern the website. The whole Chrome browser flickers slightly for a moment.

I don't think it has anything to do with the dynamic contrast or something like that. Otherwise I would see the same problem in the Safari browser.
I wouldn't even know if there was such a thing. I just have a MacBook Pro without any special settings configured.

**Comment by valentingavran** [comment]
In the following video you can see what I mean: 
https://drive.google.com/file/d/1lLrFeNg1elMR9jm8Pjg8qYldVKpbLaKP/view?usp=sharing

**Comment by KaelWD** [comment]
Yeah ok def not a monitor problem then. I doubt we'd be able to do anything about this, it looks like a browser or gpu driver bug.
