### ISSUE TITLE
[Bug Report] v-expand- transition returns "Cannot read property 'visibility' of undefined".

### ISSUE THREAD

**Issue by aamirkhancr7** [vuetifyjs/vuetify#11700]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.106
**OS:** Mac OS 10.15.5

### Steps to reproduce
The Transition work fine for few mins and later throws this error

[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'visibility' of undefined"

### Expected Behavior
Should Transition properly.

### Actual Behavior
The Transition work fine for few mins and later throws this error

[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'visibility' of undefined"

**Comment by MajesticPotatoe** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
