### ISSUE TITLE
[Bug Report] VSelect is not working when lange and locale is fa

### ISSUE THREAD

**Issue by mrfarhadir** [vuetifyjs/vuetify#11716]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.106
**OS:** Windows 10

### Steps to reproduce
when locale and lang is fa it's not working

### Expected Behavior
show vSelect component

### Actual Behavior
triggers error: undefined of undefined

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

- [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
- [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
- [Codepen](https://template.vuetifyjs.com/)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
