### ISSUE TITLE
[Bug Report] Overriding vuetify styles is impractical

### ISSUE THREAD

**Issue by BennyAlex** [vuetifyjs/vuetify#11731]
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
apply a class to a vuetify element, eg `<v-list-item class="my-list-item">` or `<v-list-item-action class="my-list-action">`

and try to change it in the `<style scoped>` tag of .vue component

### Expected Behavior
Own classes go first and will override vuetify styles.

### Actual Behavior
The library styles will be placed above all own classes, so you have to use very specific selectors or !important.

You can use the generated vuetify class but this is really complicated too, **because not all generated classes are the same as the component name** (`<v-list-item-action>` uses .v-list-item__action as class and `<v-list-item>`  just became .v-list-item).
If vuetify will change the class name with an update, the selector will not work anymore.
Also the IDE do not recognise the class anymore, displaying the css selector as not used.
Another problem is, that webpack/template-compiler doesnt find the class in the template and discards it completely.

### Reproduction Link
**I cant get https://codesandbox.io/ to work with vuetify (importing components does not work, vuetify loader too). Please add an working preconfigurated project.**

```
<template>
  <div id="app">
    <v-list>
      <v-list-item class='list-item'>
		<v-list-item-content>test</v-list-item-content>

                <v-list-item-action class='list-action'>
			<v-icon>edit</v-icon>
		</v-list-item-action>
       </v-list-item>
    </v-list>
  </div>
</template>

<script>
export default {
  name: "App"
};
</script>

<style>
// does not work
.list-action {
	max-height: 16px;
	min-width: 16px;
	margin-left: 4px;
	margin-right: 0;
}



// will work, but is complicated and does not align well with the idea of simple scoped style
.v-list-item__action.list-action {
	max-height: 16px;
	min-width: 16px;
	margin-left: 4px;
	margin-right: 0;
}
</style>
```

**Comment by ibrahimBeladi** [comment]
You need to use `>>>` in scoped css.

**Comment by ibrahimBeladi** [comment]
That's related to [CSS specificity](https://cssspecificity.com/). I don't really think that is a problem at Vuetify's side.

**Comment by aleksey-hoffman** [comment]
I agree, I'm building a complex app and it's such a pain to override some of the Vuetify styles because they either have some ridiculous specificity level or the `!important` flag.

Are there any known ways to lower CSS specificity of a library? Does Webpack load Vuetify CSS before your custom components?

**Comment by BennyAlex** [comment]
@aleksey-hoffman 

It looks like, many if not all styles from vuetify are placed under (in the html hierarchy) your own code

**Comment by aleksey-hoffman** [comment]
@BennyAlex in my case, it seems like some Vuetify classes are added before my own classes and some of them are added after.

I think Vuetify CSS in general are loaded before the CSS of custom components because Vuetify is imported before the app is mounted:
```js
// plugins/vuetify.js
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css'
Vue.use(Vuetify)
export default new Vuetify({})

...

// main.js
import vuetify from './plugins/vuetify'
new Vue({
  router,
  store,
  vuetify,
  render: h => h(App)
}).$mount('#app')
```

But some styles are still cannot be easily modified because of the high specificity level. Here's an example of what you need to do to override the CSS of some elements:

```css
/* Using custom class + full selector string + !important */ 
.custom-class.v-btn.v-btn--active.v-btn--flat.v-btn--icon.toggle--active {
  box-shadow: 0px 2px 32px rgb(0, 0, 0, 0.1) !important;
  border-bottom: 1px solid var(--icon-color-1) !important;
}
```

This is quite ridiculous.

**Comment by aleksey-hoffman** [comment]
@johnleider @KaelWD guys the rule of thumb in making libraries is to never use `!important` because it increases specificity to `10,000`. Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

Can you please explain why does the border color of a toggle button need the specificity level of 10,051, making it so difficult to override (see previous comment)?
```css
.theme--light.v-btn-toggle:not(.v-btn-toggle--group) .v-btn.v-btn {
    border-color: rgba(0,0,0,.12)!important;
```

**Comment by aleksey-hoffman** [comment]
@johnleider @KaelWD guys the rule of thumb in making libraries is to never use `!important` because it increases specificity to `10,000`. Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

Can you please explain why does the border color of a toggle button need the specificity level of 10,051?
```css
.theme--light.v-btn-toggle:not(.v-btn-toggle--group) .v-btn.v-btn {
    border-color: rgba(0,0,0,.12)!important;
```

If you want to override some internal selector, why don't you just increase the specificity level by 10 by adding another class?

**Comment by aleksey-hoffman** [comment]
Libraries like Vuetify should never use `!important` in the first place because it increases specificity to `10,000`, making it difficult to modify. Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

There's absolutely no reason why the border color of a toggle button would need the specificity level of 10,050:
```css
.theme--light.v-btn-toggle:not(.v-btn-toggle--group) .v-btn.v-btn {
    border-color: rgba(0,0,0,.12)!important;
```

Dear devs, if you want to override some selector, just increase the specificity level by 10 by adding another class.
Don't just use `!important` flag everywhere, please.

**Comment by BennyAlex** [comment]
Another problem is, you cant use scoped style if you want to change some vuetify styles, because webpack/template-compiler doesnt find the class in the template and so discards it.

Change the padding of the select list
`.v-list.v-select-list {
		padding: 0 !important;
	}`

you can only place it in `<style>`, not in `<style scoped> `

**Comment by jacekkarczmarczyk** [comment]
For scoped styles you need to use deep selector

**Comment by BennyAlex** [comment]
@jacekkarczmarczyk doesnt work, it gets completely discarded

**Comment by aleksey-hoffman** [comment]
@Mert75 mate, could you please tell us about the workaround you mentioned? Currenty the only way you can override some Vuetify rules is by doing something like this:

Use `!important (10,000 pt)` + `full selector string (5 classes * 50 pt)` + `custom class (1 class * 10pt)`

It's a well known rule of thumb - a developer of CSS library should never use `!important` to override anything, and if they do, they are doing something wrong. I don't understand why this criticizm is considered `invalid`

**Comment by johnleider** [comment]
We have to clean-up some issues and this is not actionable within the v2.x branch. The framework is being rewritten from the ground up it and we are aware of the short comings in using !important in some areas.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
