### ISSUE TITLE
[Feature Request] Enable the use of Material colour names for all props that take color arguments

### ISSUE THREAD

**Issue by davydnorris** [vuetifyjs/vuetify#11744]
### Problem to solve
Currently most but not all props permit the use of Material colour names (primary, secondary, accent, etc.) in their values. Most notable exceptions are the gradient props, that currently only take explicit color values.

The request is to make color type props consistent across the board

### Proposed solution
Allow for expressions like :gradient="to right, primary, primary-darken3" or :gradient="0, red, orange, purple" to define a gradient based on Material color names within the theme. This would require the processor to work through the list of colour parameters and replace with the color values in a similar way to the current color="..." prop parsing.

**Comment by KaelWD** [comment]
This was easy to fix for sparklines as they are SVGs so you can just use `currentColor` (#6387). For other gradient props we would have to actually parse the gradient instead of just a string concat into `linear-gradient()`. Complex gradients should be defined in CSS instead and can use theme colours via [CSS custom properties](https://vuetifyjs.com/en/features/theme/#custom-properties).
