### ISSUE TITLE
[Bug Report] Calendar event ending midnight not visible

### ISSUE THREAD

**Issue by TheOnlyError** [vuetifyjs/vuetify#11767]
### Environment
**Vuetify Version:** 2.3.2
**Last working version:** 2.2.34
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
See codepen for 2.2.34 where it still worked: https://codepen.io/theonlyerror/pen/mdVqrzz?editable=true&editors=111%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fcalendars%2F

1. Scroll down to see event from 09 to 00.

### Expected Behavior
The event should show like it used to.

### Actual Behavior
The event no longer shows.

### Reproduction Link
<a href="https://codepen.io/theonlyerror/pen/rNxYMQW?editable=true&editors=111%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fcalendars%2F" target="_blank">https://codepen.io/theonlyerror/pen/rNxYMQW?editable=true&editors=111%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fcalendars%2F</a>

**Comment by Jaykob86** [comment]
It is reproducable also on documentation page, in drag and drop demo.

**Comment by dbettini** [comment]
I can confirm this, but also - events that start and end at the same time have a minimal height, i.e. they always appear on the calendar. However, events that start and end at midnight of the same day do not. 
At this point you'd think it's the same bug, but it isn't, since this is broken in version 2.2.34 as well (where events that ended at midnight were still working).

**Comment by FDebiesse** [comment]
Hello, any news about this issue ? @TheOnlyError did you find a workaround maybe ?

**Comment by DaanSterk** [comment]
> Hello, any news about this issue ? @TheOnlyError did you find a workaround maybe ?

My workaround: if an event ends at midnight, change its end time to 23:59 and override the template to display "00:00".
