### ISSUE TITLE
[Bug Report] Icon click event ripple effect

### ISSUE THREAD

**Issue by jahnli** [vuetifyjs/vuetify#11843]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
When I add a click event to an icon, a ripple effect appears when I click, but if I don't click elsewhere to trigger focus again, the ripple will remain

### Expected Behavior
Cancel the icon click ripple effect

### Actual Behavior
Cancel the icon click ripple effect

### Reproduction Link
<a href="https://null.github.com" target="_blank">https://null.github.com</a>

![image](https://user-images.githubusercontent.com/20943608/87263738-a523bf80-c4f0-11ea-9c85-824438251613.png)

**Comment by jahnli** [comment]
The mouse is no longer on the app, but the ripple is still there

**Comment by MajesticPotatoe** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
