### ISSUE TITLE
[Bug Report] text-field prepend-slot avatar is 13px too low. It should be centred on the text-field

### ISSUE THREAD

**Issue by fergusmeiklejohn** [vuetifyjs/vuetify#11851]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Mac OS 10.15.2

### Steps to reproduce
create a text-field
add `outlined` to see the shape of component
add an avatar to the prepend slot

### Expected Behavior
avatar should be centred on body of the text-field. See LinkedIn comments text-field for reference for example

### Actual Behavior
avatar is too low and needs to have `style="top: -13px;"` to bring it into alignment with the text-field
It looks like the prepend slot is centre aligned on the `v-input__control` when it should be aligned on the `v-text-field__slot`

### Reproduction Link
<a href="https://codepen.io/fergusmeiklejohn/pen/rNxrgxr" target="_blank">https://codepen.io/fergusmeiklejohn/pen/rNxrgxr</a>

**Comment by johnleider** [comment]
This is because those slots have assigned margin so that `v-icon` will line up properly. You can compensate for this with our negative margin utility helpers.

An example implementation: https://codepen.io/johnjleider/pen/JjRRjrj

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
