### ISSUE TITLE
[Bug Report] click event disappear in  v-app-bar & v-navigation-drawer When resize browser  to mobile size

### ISSUE THREAD

**Issue by carter8225** [vuetifyjs/vuetify#11862]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
1. Use Button or Custom Components in V-App or navigation-drawer
2. It's Ok in PC browser when open in normal size, ex 1080p for Dev Environment （SSR Mode, Vue + Typescript + Vuex + Router + Axios + Express）
3. Now for test mobile mode, reside the browser (Google Chrome) to less 580px (width)
4. some of components in App-Bar or Drawer,  click event can't be used. And the point don't change to hand.
5. when reside to normal size, the components can use again. 

### Expected Behavior
click success

### Actual Behavior
some components can't click in less 580px (width) mode

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

**Comment by KaelWD** [comment]
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

- [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
- [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
- [Codepen](https://template.vuetifyjs.com/)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
