### ISSUE TITLE
[Bug Report] Closing a filtered v-treeview node is slow with a lot of items

### ISSUE THREAD

**Issue by James-Hudson3010** [vuetifyjs/vuetify#11872]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Safari 13.1.1
**OS:** Mac OS 10.15.5

### Steps to reproduce
When not filtering, open and close of the _Core Team_ node is fast. Type **9** into the search field and it slows to a crawl, especially when closing.

The problem is trivially reproducible using the [Searching a Directory](https://vuetifyjs.com/en/components/treeview/#searching-a-directory) example as the base.

### Expected Behavior
It should be fast to open and close with and without a filter applied

### Actual Behavior
It is slow

### Reproduction Link
<a href="https://codepen.io/james-hudson3010/pen/mdVzmzV " target="_blank">https://codepen.io/james-hudson3010/pen/mdVzmzV </a>

**Comment by KaelWD** [comment]
This is from #6124

The culprit seems to be `this.treeview.isExcluded(this.key)` in VTreeViewItem's render function, removing this and filtering in the `children` computed property instead yields a 1000x speedup when closing an item with many children. 

@nekosaur is there any particular reason we're hiding filtered items with css instead if just not rendering them?

**Comment by nekosaur** [comment]
Mm I can't remember if there was a reason. But this change seems like a no-brainer.
