### ISSUE TITLE
[Bug Report] Cannot sort and show items per page on v-datatable server side

### ISSUE THREAD

**Issue by handhikadj** [vuetifyjs/vuetify#11877]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Mac OS 10.14.6

### Steps to reproduce
just play with the table

### Expected Behavior
Can sort and show items per page on v-datatable server side

### Actual Behavior
Cannot sort and show items per page on v-datatable server side

### Reproduction Link
<a href="https://codesandbox.io/s/eager-roentgen-o3h7u" target="_blank">https://codesandbox.io/s/eager-roentgen-o3h7u</a>

### Other comments
besides this issue,  I need a reproduction on how to scaffold the backend that fulfils the v-datatable server-side requirement

**Comment by KaelWD** [comment]
You aren't doing anything when `paginationOptions` is updated. There is an example in the documentation](https://vuetifyjs.com/en/components/data-tables/#paginate-and-sort-server-side), replace the `getDataFromApi` method with your actual API request. 

> how to scaffold the backend that fulfils the v-datatable server-side requirement

The requirements should be pretty obvious from that example, just implement the `getDataFromApi` sorting etc. on your server instead. There is no complete example of a real backend because it depends on what language, framework, or database you're using. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
