### ISSUE TITLE
[Bug Report] v-app-bar creates space under navigation drawer

### ISSUE THREAD

**Issue by ThomasKuhlmann** [vuetifyjs/vuetify#11882]
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Mac OS 10.15.2

### Steps to reproduce
use a navigation drawer and an app bar that's aligned to the bottom

### Expected Behavior
The app-bar that's aligned to the bottom should respect the navigation drawer the same way the top aligned app-bar does

### Actual Behavior
empty space under navigation drawer

### Reproduction Link
<a href="https://codepen.io/thomaskuhlmann/pen/xxZQdOW" target="_blank">https://codepen.io/thomaskuhlmann/pen/xxZQdOW</a>

**Comment by Mert75** [comment]
You could use a footer to achieve the same [result ](https://codepen.io/thomaskuhlmann/pen/xxZQdOW)

**Comment by johnleider** [comment]
This is due to the way the current layout system works. These components have designated ui regions. v-app-bar with the bottom property targets the **bottom** region and doesn't support inset states. This is not an issue in the v3 layout system. Follow progress here #12691.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
