### ISSUE TITLE
[Bug Report][2.3.6] v-text-field outlined border colour incorrect with validation on iOS 

### ISSUE THREAD

**Issue by andrewcowley** [vuetifyjs/vuetify#11942]
### Environment
**Vuetify Version:** 2.3.6
**Vue Version:** 2.6.11
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Exceed the character limit for validation and the outline stays blue
Reduce the number characters to be < character limit and outline goes red
Pinch zoom in and out and the line flickers from blue to red and back

### Expected Behavior
Outline to accurately reflect state of field

### Actual Behavior
Outline doesn't reflect state of field

### Reproduction Link
<a href="https://codepen.io/andrewcowley/pen/XWXQPLQ" target="_blank">https://codepen.io/andrewcowley/pen/XWXQPLQ</a>

### Other comments
Workaround:
``` 
 .v-text-field--outlined fieldset {
    border-color: currentColor !important
  }
```

**Comment by nayanbhana** [comment]
Seeing this same issue!

**Comment by rodrigues-t** [comment]
I got the same issue. 

I am on vuetify version 2.3.7. In the vuetify documentation itself, you can see the bug if you access it from iOS.
I've tested on IPhone 11 Pro Max and IPhone X, using both Safari and Chrome browsers.

**Comment by ByteFight** [comment]
Same here on iOS devices, doesn't seem to depend on the browser! Testes it with firefox, safari and chrome on iPhone.

**Comment by lacherogwu** [comment]
The workaround also doesn't work for me 😩

**Comment by lacherogwu** [comment]
I found a workaround using MutationObeserve, that's a quick fix until Vuetify will fix the issue on their side.

I set in the "mounted" lifecycle hook this function


```
const form = this.$refs.form.$el
            const list = ['success', 'error']

            const observer = new MutationObserver((mutationsList) => {
                mutationsList.forEach(({ type, target }) => {
                    const fieldset = target.querySelector('fieldset')
                    if(!fieldset) return
                    fieldset.style = ''

                    if(type === 'attributes' && target.classList.contains('v-input--has-state')){
                        const activeClass = list.filter(i => target.classList.contains(`${i}--text`))[0]
                        activeClass === 'error' ? fieldset.style = 'border-color: #ff5252 !important;' : fieldset.style = 'border-color: #4caf50 !important;'
                    }
                })
            })

            observer.observe(form, { attributes: true, subtree: true })
```


And this on the "style" block

```
.v-application div.v-text-field--outlined {
    color: transparent !important;
}
.v-text-field--outlined.v-input--is-focused fieldset, .v-text-field--outlined.v-input--has-state fieldset {
    border-color: #1976d2 !important;
}
```

Enjoy!

**Comment by shiouming** [comment]
Understood that this bug was raised for iOS Safari,
(a) **_I wonder if the fix was applied to MacOS Safari as well?_**
(b) Anyone getting this problem for Mac OS Safari?

I'm getting behaviour almost the same as the report, using Vuetify v2.7.0 on Safari 14.1.2 @ Mac OS 10.14.6:
- Chrome and Firefox working fine on Mac OS and Android.
- I don't have modern iphone, but it's working per expectation on Safari @ iOS 12.5.7 so far.

Observed behaviour:
1. Page loaded initially --> the field looks normal
2. Select the input field or make it in focus --> border color became black (expected: blue)
3. Enter an invalid value that placed the input field in error state --> border color became blue (expected: red)
4. Fix the input value to place the input field in success state --> border color became red (expected: green)

During step 2,3 and 4, while the field was showing wrong border color, if I switch the "desktop focus" away from Safari window, e.g. switch to a different virtual screen or open another tab/application, then revisit the initial Safari window/screen, the border will be repainted with correct color.

**Comment by KaelWD** [comment]
Looks like it was broken again in 2.6.9 by 0cc43e293c0f64e12b210a543e2c71cf084f1ebc

**Comment by shiouming** [comment]
> Looks like it was broken again in 2.6.9 by [0cc43e2](https://github.com/vuetifyjs/vuetify/commit/0cc43e293c0f64e12b210a543e2c71cf084f1ebc)
> 
> Safari is so incredibly shit, how does removing a transition prevent the color from updating?

Update: the behaviour is gone after rolling back from 2.7.0 to 2.6.8.

Although my background is more on back-end stuff, I did hear about the reputation of Safari as "successor of IE" 😅
