### ISSUE TITLE
min-height causes app to always have vertical scrollbar

### ISSUE THREAD

**Issue by DedDorito** [vuetifyjs/vuetify#1196]
### Steps to reproduce
Create an app with a toolbar and v-container

### Versions
Latest of everything.

### What is expected ?
There should only be a vertical scrollbar when the content exceeds the viewport height.

### What is actually happening ?
Since the `min-height` of the `v-container` is set to `100vh`, there's always a scrollbar when using a toolbar.

### Reproduction Link
https://codepen.io/anon/pen/wqGqKb

**Comment by thelolagemann** [comment]
https://codepen.io/TheLolageMann/pen/zdqPjr something like this? the container might need a helper class when the toolbar isn't fixed however, or maybe a transition to hide the toolbar

**Comment by DedDorito** [comment]
Yeah, does anyone know why the `min-height` is set to begin with?  I'm assuming it might have to do with the navigation drawer or menus being positioned correctly (but haven't actually tried).  If the `min-height` does have to be set to ensure other things work properly, then taking into account the toolbar's height would be the simplest way.  Whether the toolbar is fixed or not doesn't appear to affect the scrollbar issue.

On a somewhat related note, the `html` element also has `overflow-y: scroll` set, which forces a scrollbar to always show even if there isn't anything to scroll.

**Comment by johnleider** [comment]
You are missing the toolbar prop for ```v-app```. You must tell the application what you have in order for it to properly size your content area.

**Comment by msgeissler** [comment]
None of the examples in the documentation mention that (https://vuetifyjs.com/layout/pre-defined).
In addition to that the toolbar prop is for fixed toolbars (toolbar | Boolean | False | Configures the application to have a **fixed** toolbar), but the codepen that Ded provided does not use a fixed toolbar (toolbars are **not** fixed by default).
Unless I am missing something, this is a bug or the documentation is really wrong.

**Comment by johnleider** [comment]
You are correct, but it foes mention the complications of displaying the exact props in the docs and that it uses a special prop for vapp such as standalone. 

I'm always working on the documentation but if you feel something sucks, feel free to strap up your boots and make a PR.

**Comment by msgeissler** [comment]
I just started with vuetify ~1 hour ago and I am still trying to figure out the basics. Currently the layout and the scrollbar is a big hurdle.
I wouldn't want to start helping with the documentation unless I really know how to improve upon it (I don't know if I made a mistake, it's a bug or the documentation right now).

Coming back to this issue, I still think there is a problem:
Adding the toolbar-prop to v-app only solves the problem with the content being to big, but it will still result in an "empty" scroll bar (at least on Chrome). https://codepen.io/anon/pen/mMRJNZ

**Comment by johnleider** [comment]
The disabled scrollbar is due to ```overflow-y: scroll```. This is a design decision and has been debated heavily since the creation of the framework. However, the last time we spoke of it, I discussed it with the Vuetify devs and backers, and it was in favor of keeping it.

On a side note, you can check out https://dev.vuetifyjs.com to see some of the updates that are being worked on for the documentation. I have already updated all of those examples to be a little more clear.
