### ISSUE TITLE
[Bug Report] v-virtual-scroll not render items when using max-height with activator

### ISSUE THREAD

**Issue by PROgram52bc** [vuetifyjs/vuetify#11963]
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Linux x86_64

### Steps to reproduce
When page is loaded, click on "Show Virtual Scroll" button.

### Expected Behavior
items in the virtual scroll is rendered

### Actual Behavior
No items in the virtual scroll is rendered

### Reproduction Link
<a href="https://codepen.io/david_deng/pen/JjGQwrZ" target="_blank">https://codepen.io/david_deng/pen/JjGQwrZ</a>

### Other comments
I know the component is still under progress, but hope this report would be helpful as you improve the component!

**Comment by filips123** [comment]
I have the same problem on Vue 2.7.14 and Vuetify 2.6.15. I don't use a custom activator, but my `v-virtual-scroll` is inside `v-expansion-panel-content`. When the `v-expansion-panel` is expanded, `v-virtual-scroll` fills the entire space as expected, but renders only the first `bench` items, while the remaining space is empty.

This seems to work when I apply `height` property to the `v-virtual-scroll`, however, I cannot do this, because I want it to take all available space. It also works without `height` when it's not located inside `v-expansion-panel`, so it's probably caused because it's not rendered immediately after load, but only after the panel is expanded or the activator is used.

**Comment by filips123** [comment]
Was this issue fixed in Vuetify 3? Unfortunetely, I can't currently test it myself.
