### ISSUE TITLE
[Bug Report] text-field showing :messages even when an error form :rules is present 

### ISSUE THREAD

**Issue by totomaze** [vuetifyjs/vuetify#11979]
### Environment
**Vuetify Version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Windows 10

### Steps to reproduce
use the link https://codepen.io/totomaze/pen/RwrXdNK

### Expected Behavior
I would expect the :messages disappear and show the error message(from :rules), instead of showing the message in red

### Actual Behavior
When an error is present from the :rules the :messages content is showing up in red

### Reproduction Link
<a href="https://codepen.io/totomaze/pen/RwrXdNK" target="_blank">https://codepen.io/totomaze/pen/RwrXdNK</a>

**Comment by johnleider** [comment]
This is the expected behavior of **error, success, message** messages; they take precedence over anything done internally. As a workaround, use the **hint** property, https://codepen.io/johnjleider/pen/abJeNRN

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
