### ISSUE TITLE
[Bug Report] Radio group label padding issue on Safari and Legacy Edge

### ISSUE THREAD

**Issue by peteruithoven** [vuetifyjs/vuetify#11976]
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 2.6.11
**Browsers:** Safari 13, Microsoft Legacy Edge (based on EdgeHTML)
**OS:** Windows 10, Mac OSX Catalina (10.15)

### Steps to reproduce
1. Create v-radio-group with label and some v-radio's

### Expected Behavior
Space between radio-group label and radio button is consistent on supported browsers

### Actual Behavior
On Safari and Legacy Edge the bottom padding seems lost.
On Firefox and the the Chromium based Edge 84 the padding is there. 

![Legacy Edge](https://user-images.githubusercontent.com/523210/89111411-bf98eb00-d455-11ea-8194-02a06e9e438d.png)![Firefox](https://user-images.githubusercontent.com/523210/89111413-c0ca1800-d455-11ea-8e13-7f31e59c905a.png)![Safari](https://user-images.githubusercontent.com/523210/89111414-c0ca1800-d455-11ea-904a-e4e6fa69bc62.png)

### Reproduction Link
<a href="https://codepen.io/peteruithoven/pen/BajXQgJ" target="_blank">https://codepen.io/peteruithoven/pen/BajXQgJ</a>

### Other comments
When I remove the fixed height (20px) I get a consistent distance

**Comment by KaelWD** [comment]
Reproduced in Chrome 84 on windows but not firefox 79

**Comment by gregveres** [comment]
Yea, it seems like getting rid of the v-label on the label slot would be a good way to go. Right now the label is way too tight against the radio button options. But if I go into the debugger and remove the v-label, it feels much better.
Although keeping the height: 20px and getting rid of the line-height:20px feels good too from a spacing point of view. Maybe even better because it results in a bit less space than removing the v-label altogether.

**Comment by gregveres** [comment]
I fixed this issue in my code by unset'ing the height on the legend. The height gets set from the v-label class but that really screws up the label on the radio button group. It squishes it into the radio buttons and when the label wraps on a small screen, the wrapped text overwrites the first radio button. 

To solve this, I wrapped my radio group in a div and put a class on it. I called my class 'choices'. Then I used a scoped styles section in my component and used the deep selector to unset the height:

```
<style lang="scss" scoped>
.choices ::v-deep legend {
  height: unset !important;
}
</style>
```

I am not a big fan of this since legend isn't used in my component. I am relying on the knowledge of what Vuetify will turn my v-radio-group into. But... this fixes the squished height issue on the label and it fixes the wrapping of the label.
