### ISSUE TITLE
[Bug Report] "vue add vuetify" adds vuetify 2.2.11, which results in a module-not-found-error: Can't resolve 'vuetify/lib'

### ISSUE THREAD

**Issue by baermathias** [vuetifyjs/vuetify#12044]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Windows 10

### Steps to reproduce
"vue add vuetify" adds vuetify version 2.2.11, which results in a module-not-found-error.

1. vue create some-project
2. vue add vuetify

```
This dependency was not found:

* vuetify/lib in ./src/plugins/vuetify.js

To install it, you can run: npm install --save vuetify/lib
```

### Expected Behavior
compile successfully

### Actual Behavior
failed to compile

### Reproduction Link
<a href="http://jsfiddle.com" target="_blank">http://jsfiddle.com</a>

**Comment by jacekkarczmarczyk** [comment]
Can't reproduce using default settings, even after adding `yarn serve` or `yarn build` step (which you didn't mention, so not sure if they were required)

This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
