### ISSUE TITLE
[Bug Report] v-radio prepend/append slots do not exist

### ISSUE THREAD

**Issue by dchiquit** [vuetifyjs/vuetify#12046]
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Linux x86_64

### Steps to reproduce
Use a `v-slot:prepend` or `v-slot:append` in a `v-radio` element, as documented at https://vuetifyjs.com/en/components/selection-controls/.

### Expected Behavior
Code is prepended/appended to the v-radio.

### Actual Behavior
The slot is ignored.

### Reproduction Link
<a href="https://codepen.io/dchiquit/pen/VwaeZEQ" target="_blank">https://codepen.io/dchiquit/pen/VwaeZEQ</a>

### Other comments
The only slot that appears to be plugged in is `v-slot:label`. 

The documentation lists the same slots available for `v-radio-group`, `v-radio`, `v-checkbox`, and `v-switch`. Presumably that documentation was copy/pasted and never updated to reflect actual functionality.

**Comment by ricardovanlaarhoven** [comment]
Because v-radio uses v-input the doc-generator automatically creates the append and prepend slot documentation.
So either the is should stop using v-input or it should get those prepend and append slots

For now i'll make a PR that "deletes" those slots on the documentation generator of the v-radio but i'm guessing there should be an issue for adding this functionality
