### ISSUE TITLE
[Bug Report] On mobile only, a v-tooltip on a v-btn stays visible if a 'click' causes the btn to become disabled

### ISSUE THREAD

**Issue by AlexExarhos** [vuetifyjs/vuetify#12052]
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
On mobile, tap on the "Has tooltip" button. The button will disable immediately, but the "Here is a tooltip" message sticks around.

### Expected Behavior
The "Here is a tooltip" message should hide when the button become disabled

### Actual Behavior
There "Here is a tooltip" message persists

### Reproduction Link
<a href="https://codepen.io/AlexExarhos/pen/rNexZQP" target="_blank">https://codepen.io/AlexExarhos/pen/rNexZQP</a>

**Comment by johnleider** [comment]
My suggestion is to use the **disabled** property on `v-tooltip`. The reason this only happens on mobile is because of how the tooltip is shown from touch compared to click.

Here is a workaround: https://codepen.io/johnjleider/pen/YzGGzoV

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
