### ISSUE TITLE
[Bug Report] Treeview open nodes do not change when open prop is changed

### ISSUE THREAD

**Issue by skwh** [vuetifyjs/vuetify#12060]
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Mac OS 10.15.5

### Steps to reproduce
1. Create a component making use of Treeview. 
2. Use the open prop to reactively pass a list containing any number of treeview keys

### Expected Behavior
The treeview unfolds and opens to the entry with the specified key(s)

### Actual Behavior
The treeview reloads and does not open at all

### Reproduction Link
<a href="https://codepen.io/skwh/pen/BaKKVbP" target="_blank">https://codepen.io/skwh/pen/BaKKVbP</a>

**Comment by nekosaur** [comment]
`e-1-1` does not have any children. you want `e-1`

**Comment by skwh** [comment]
Hi @nekosaur , thanks for checking out my issue. I guess I was misunderstanding what values are valid for the `open` prop. Does this mean that the component will only react to the top-level keys in the treeview? If I create a child for `e-1-1`, and then pass `e-1-1`, the treeview does not open to anything.

My belief was that the `open` prop took a key from any level of the tree and then unfolded the tree as deep as need be in order to display the given key. Is this something that could be clarified in the documentation?

**Comment by nekosaur** [comment]
The `open` prop controls which parent nodes (nodes with children) are expanded. It will not automatically expand nested nodes. It is simply a register of which nodes are expanded (open).

In a scenario with the following nodes

```
- 1
  - 2
  - 3
    - 4
```

If you set `open` to `[3]` nothing will change visually because 1 is not open. You'd have to set it to `[1, 3]` if you want to show 4.
