### ISSUE TITLE
[Bug Report] Incorrect css class v-tab-disabled

### ISSUE THREAD

**Issue by towry** [vuetifyjs/vuetify#12194]
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 3.0.0-rc.10
**Browsers:** Chrome 85.0.4183.83
**OS:** Mac OS 10.15.6

### Steps to reproduce
no

### Expected Behavior
no

### Actual Behavior
no

### Reproduction Link
<a href="https://codepen.io" target="_blank">https://codepen.io</a>

https://github.com/vuetifyjs/vuetify/blob/dc37ebe138f588d02d66866747a8e31b85ee07d7/packages/vuetify/src/components/VTabs/VTabs.sass#L102

### Other comments
Is this deliberate or should it be `.v-tab--disabled` ?

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

- [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
- [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
- [Codepen](https://template.vuetifyjs.com/)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by towry** [comment]
Never mind, even though I think its a typo.

**Comment by jacekkarczmarczyk** [comment]
`:not` part doesn't even seem to be necessary at all

**Comment by KaelWD** [comment]
Yeah `.v-tab--disabled` already has events disabled: https://github.com/vuetifyjs/vuetify/blob/dc37ebe138f588d02d66866747a8e31b85ee07d7/packages/vuetify/src/components/VTabs/VTabs.sass#L221-L223
