### ISSUE TITLE
[Feature Request] v-data-table crud could not update data synchronized with axios

### ISSUE THREAD

**Issue by martinym28** [vuetifyjs/vuetify#12253]
### Problem to solve
v-data-table crud could not update data synchronized with Static array

### Proposed solution
But v-data-table crud could not update data synchronized with axios
https://vuetifyjs.com/en/components/data-tables/#crud-actions
save () {
        if (this.editedIndex > -1) {
          Object.assign(this.desserts[this.editedIndex], this.editedItem) //**it not updated data sync, need refresh manually. this.editedItem variables from axios** 
         axios.put...
        } else {
          this.desserts.push(this.editedItem) // **add line but not data, need refresh manually**
        }
        this.close()
      },
PS, V-treeview open-all not work if the data from axios
https://github.com/vuetifyjs/vuetify/issues/12151

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

- [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
- [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
- [Codepen](https://template.vuetifyjs.com/)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
