### ISSUE TITLE
[Bug Report] Nested tabs become inaccessible after visiting smaller tab list

### ISSUE THREAD

**Issue by edwardsph** [vuetifyjs/vuetify#12332]
### Environment
**Vuetify Version:** 2.3.12
**Vue Version:** 2.6.12
**Browsers:** Edge 85.0.564.63
**OS:** Windows 10

### Steps to reproduce
It starts with 2 outer tabs and 3 inner tabs. Click on Outer 2 and there are only 2 inner tabs. Click on Outer 1 and you can see all 3 inner tabs but Inner 3 is not accessible. It seems something has shrunk the maximum number of tabs allowed.

### Expected Behavior
When changing a set of sub tabs they should all remain accessible.

### Actual Behavior
They don't

### Reproduction Link
<a href="https://codepen.io/edwardsph/pen/poyXpqG" target="_blank">https://codepen.io/edwardsph/pen/poyXpqG</a>

### Other comments
Sorry I couldn't identify the route cause or a workaround. It took me a while to narrow down a simple reproduction.

**Comment by jacekkarczmarczyk** [comment]
You're using same model for triple and double inner tabs, double inner tabs can't have third tab selected so tab2 can't be set to 2

https://codepen.io/jkarczm/pen/VwaJQpr?editors=1010

**Comment by edwardsph** [comment]
Thanks for the quick resolution. That is a simple fix for me but I confess I'm still not sure exactly what causes this and which model you are referring to since the 2 tab sets use different models for the tab value. I assume you are referring to the model containing the tab data but since that is shared but I can't see why the 2 sets of tabs contaminate each other. 
Thanks again.

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/94858999-2590f700-0434-11eb-8b65-7ab7c78040da.png)

Since tabs are lazy initially you're displaying only `Tab 1 content` (so only first inner tabs), second tab is not mounted so it doesn't affect anything and you can switch to `Inner 3`. But after switching to `Outer 2` you now have `Tab 1 content` and `Tab 2 content` mounted and v-model applies to both inner tabs. Gosh, using words to describe this is difficult xd

Feel free to reach out to us in our [Discord community](https://community.vuetifyjs.com) if it still not clear

**Comment by edwardsph** [comment]
That helps, but yes it is tricky - thanks
