### ISSUE TITLE
[Bug Report] @mdi/js icons size prop overwritten by .v-icon__svg class

### ISSUE THREAD

**Issue by Albertbol** [vuetifyjs/vuetify#12372]
### Environment
**Vuetify Version:** 2.3.13
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.15.6

### Steps to reproduce
I cant reproduce, could not install @mdi/js in codepen/jsfiddle etc.
reproduce:
Follow official guide to install @mdi/js https://vuetifyjs.com/en/features/icons/#material-design-icons---js-svg
Add icont to project:
  <v-icon size="200px" left>{{ mdiPaw }}</v-icon>
Icon won't be resized and you can see .v-icon__svg is overwritting size behavior.

### Expected Behavior
Expected size to be increased

### Actual Behavior
Nothing happens, only span around is increasing its size

### Reproduction Link
<a href="https://codepen.io/albertb/pen/PozoQJj" target="_blank">https://codepen.io/albertb/pen/PozoQJj</a>

**Comment by johnleider** [comment]
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
* [Codepen](https://template.vuetifyjs.com)
* [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
* A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by KaelWD** [comment]
Someone reported this on discord already, fixed by #12319

**Comment by Albertbol** [comment]
> Someone reported this on discord already, fixed by #12319

Thanks
