### ISSUE TITLE
<v-card-media> images are not proccess in Vue Loader with "npm run build" 

### ISSUE THREAD

**Issue by jyacot** [vuetifyjs/vuetify#1239]
Hi! i've deploy my aplicacion with  `npm run build` of Vue Loader, but I see that the image in the **v-card-media** component is not processed unlike other tags _"img"_,etc
**Code**
![1](https://user-images.githubusercontent.com/5091152/28951529-a387c2e4-7899-11e7-8ec2-b49b72e323b1.png)
**Scalfolding**
![2](https://user-images.githubusercontent.com/5091152/28951530-a38cc24e-7899-11e7-99a8-f2afb2d6ced6.png)
**npm run build** 
![3](https://user-images.githubusercontent.com/5091152/28951531-a3924e6c-7899-11e7-8dde-caca9bff677b.png)

Sorry for my english! :)

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by vwxyzjn** [comment]
I believe @jyacot wants to do relative URLs static assets imports. Usually, if we just use regular vue file, relative URLs are automatically enabled. For example, in the [official vuejs template](https://github.com/vuejs-templates/webpack/blob/e1f781e3bd890112eded8b3c1781eaaa402d6432/template/src/App.vue#L3) we can see 

```vue
<img src="./assets/logo.png">
```

According to the vue-loader's [documentation](https://vue-loader.vuejs.org/en/configurations/asset-url.html
), the markup above is actually translated to 

```js
createElement('img', { attrs: { src: require('../image.png') }})
```

which is something [VCardMedia.js](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VCard/VCardMedia.js) doesn't have. It simply uses whatever url you passed into ``src`` prop of ``v-card-media`` component

```js
style: {
  background: `url(${this.src}) center center / ${this.contain ? 'contain' : 'cover'} no-repeat`
}
```
If you want a quick fix however, try

```vue
v-card-media(
  class="white--text"
  :src="require('@/assets/yourimages.jpg')"
  height="200px"
)
```

This solved my problem. 

@johnleider I believe this is a common gotchas since people are used to doing relative imports of images. Would you consider adding it to the official [Frequently asked questions |
 Vuetify](https://vuetifyjs.com/vuetify/frequently-asked-questions)?

**Comment by jyacot** [comment]
Thank you very much @vwxyzjn !!! It worked perfectly!

**Comment by vwxyzjn** [comment]
@johnleider Check out this minimal reproduction: [v-card-media_relative_import](https://github.com/vwxyzjn/v-card-media_relative_import).

Review especially [these lines](https://github.com/vwxyzjn/v-card-media_relative_import/blob/b406782a87295254c6ab4ffb1453faee8c0d63cb/src/App.vue#L57-L100)

And the result looks like this:

![image](https://user-images.githubusercontent.com/5555347/29462264-c03eff60-83fc-11e7-8f3b-434c0ac2d62b.png)

Notice directly using relative import on ``<v-card-media>`` doesn't work the same way ``<img>`` does. In ``<img>``, you can write:

```html
<img src="./v.png"/>
```

while for ``<v-card-media>`` you need to write

```html
<v-card-media v-bind:src="require('./v.png')" height="200px">
<!-- this does not work <v-card-media src="./v.png" height="200px"> -->
```

**Comment by Imanullah** [comment]
Hai to use for dynamic image 
<v-card-media v-bind:src="require(item.image)" height="200px">

is not working....

**Comment by RichAyotte** [comment]
@Imanullah Have your tried `:src="require('/path/to/yourimage.jpg')"`

**Comment by johnleider** [comment]
I'm not really sure how to solve this due to how vue-loader works. Any help is welcome

**Comment by johnleider** [comment]
I've added the information to the FAQ.

**Comment by chickdan** [comment]
Hate to open this back up, but I'm unable to get this fix working with dynamically populating the src attribute. In my code I'm looping through an array and using `:src="require(card.src)"` to assign the `v-card-media` and I'm getting this warning: `1:499-516 Critical dependency: the request of a dependency is an expression`. Because of this nothing renders.

**Comment by vwxyzjn** [comment]
@chickdan I am pretty sure the ``require`` function is evaluated at compile time, and you can use it during runtime. That's why you have the error.

**Comment by DanilChugaev** [comment]
@johnleider what do you think about this method: [Question in stackoverflow "Vue.js dynamic images not working"](https://stackoverflow.com/questions/40491506/vue-js-dynamic-images-not-working) ? Other methods not working for me, but, this method is worked.

For example, in my component it looks like this:

```
<template>
   ...
   <v-card v-for="card in widgetCards">
      <v-card-media :src="getImgUrl(card.img)"> 
      ...
      </v-card-media>
   </v-card>
   ...
</template>


<script>
   ...
   data () {
	return {
           widgetCards: [
		{ text: 'example-1', img: '1.jpg' },
		{ text: 'example-2', img: '2.jpg' },
		{ text: 'example-3', img: '3.jpg' }
	]
   },
   methods: {
	getImgUrl(img) {
		return require('../../assets/img/' + img)
	}
   }
   ...
</script>
```

**Comment by jacekkarczmarczyk** [comment]
This method is mentioned in [Vuetify FAQ](https://vuetifyjs.com/vuetify/frequently-asked-questions)

**Comment by DanilChugaev** [comment]
@jacekkarczmarczyk But dynamically, this method (in FAQ) not working. At least, it does not work for me.

**Comment by jacekkarczmarczyk** [comment]
Could you then please create an issue in docs repo to update the FAQ? Thank you

**Comment by Shadomax** [comment]
Hello guys am having the same problem but mine am providing a full image link from an api end-point: http://localhost:8000/storage/blogs/Test Blog.jpg in the <v-card-media :src=""> using a loop. but the image doesn't display but it works on <v-card :img="">

**Comment by prodigy2m** [comment]
This did it for me. "v-bind:src="require('@/assets/yourimage.jpg')"

**Comment by kevinrodriguez-io** [comment]
:src="require('@/assets/'+myDinamycFile)" doesn't even compile for me.

**Comment by vwxyzjn** [comment]
@kevinrodriguez-io `require` is evaluated at webpack "compile time", therefore you couldn't use dynamic links.
