### ISSUE TITLE
[Documentation] Unit Testing `import Vuetify from 'vuetify'` should be `'lib/vuetify'`?

### ISSUE THREAD

**Issue by paulpv** [vuetifyjs/vuetify#12420]
### Environment

**Browsers:** Chrome 86.0.4240.80
**OS:** Mac OS 10.15.7

### Steps to reproduce
Look at the provided sample in the Reproduction Link

### Expected Behavior
```
import Vue from 'vue'
import Vuetify from 'lib/vuetify'
Vue.use(Vuetify)
```

### Actual Behavior
```
import Vue from 'vue'
import Vuetify from 'vuetify'
Vue.use(Vuetify)
```

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/unit-testing/#bootstrapping-vuetify" target="_blank">https://vuetifyjs.com/en/getting-started/unit-testing/#bootstrapping-vuetify</a>

### Other comments
Maybe this is intended and isn't a bug, but `lib` seems to be required in other places.
If it is a bug then maybe exhaustively search for all similar strings and update them too.

**Comment by KaelWD** [comment]
It would be `vuetify/lib`, but the current examples are correct. `vuetify/lib` doesn't include any components which is fine for webpack because you can use vuetify-loader to automatically import them where needed, but this doesn't work with jest so we import `vuetify` instead to just include everything without having to manually import each individual component.
