### ISSUE TITLE
[Bug Report] <v-tab> :disabled computed property not work from v-for

### ISSUE THREAD

**Issue by Dinver** [vuetifyjs/vuetify#12508]
### Environment
**Vuetify Version:** 2.3.15
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.111
**OS:** Windows 10

### Steps to reproduce
At used v-for for v-tab, not working :disabled="computed property".

### Expected Behavior
Same as without v-for

### Actual Behavior
In v-for not working

### Reproduction Link
<a href="https://codepen.io/dinver/pen/rNLjXWz?editors=0001" target="_blank">https://codepen.io/dinver/pen/rNLjXWz?editors=0001</a>

### Other comments
I don't know if it worked before.

**Comment by jacekkarczmarczyk** [comment]
That's expected behaviour

https://codepen.io/jkarczm/pen/LYZxwQX?editors=1011

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by mahmed743** [comment]
because you add value in array data(), but you can create array in computed, you can visit this link below
https://codepen.io/mahmed743/pen/pobRMKw?editors=1011

**Comment by Dinver** [comment]
Sorry, I forgot about this. Me need more rest...
