### ISSUE TITLE
[Bug Report] Component with a v-tooltip as its root will often render in the wrong location.

### ISSUE THREAD

**Issue by ascott18** [vuetifyjs/vuetify#12552]
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.11
**Browsers:** Firefox 82.0
**OS:** Windows 10

### Steps to reproduce
1. Create a component with a v-tooltip as its root.
2. Use multiple of these components as sibling elements, rendered conditionally with v-if.
3. Change the rendering conditions. The components will often get placed in the DOM in completely the wrong places relative to one another.

### Expected Behavior
Child components render in the order they're declared

### Actual Behavior
Child components render in random orders.

### Reproduction Link
<a href="https://codepen.io/lakueyg/pen/yLJEjxV?editors=1111" target="_blank">https://codepen.io/lakueyg/pen/yLJEjxV?editors=1111</a>

**Comment by KenLewis** [comment]
I'm having the same (or at least similar) problem.

**Background Info**:
I have a table with an action column. If a user is allowed to edit the item, there is a **button** with a tooltip that says "Click to edit". If they are not allowed to edit the item, there is an icon with a tooltip that says "Staff in the following departments are allowed to edit this: ...". 

If the user edits the departments that are allowed to edit the item and thus are no longer allowed to edit it after they save the item, then the edit button goes away and the information icon is shown.

**Information found when troubleshooting**:
I found that the reference to the activator element is not being updated when the data is updated. Due to this, `updateDimensions` is updating the `dimensions.activator` with zeros for all the dimensions. Due to this, the tooltip shows in the upper left corner of the window instead of next to the activator.

Initial generated HTML
```
<button data-v-cbcf2ae8="" type="button" role="button" aria-haspopup="true" aria-expanded="false" class="v-icon notranslate mr-2 v-icon--link mdi mdi-pencil theme--light" style="font-size: 16px;"></button>
```
The referenced activator el: `button.v-icon.notranslate.mr-2.v-icon--link.mdi.mdi-pencil.theme--light`

HTML after updating the items
```
<i data-v-cbcf2ae8="" aria-hidden="true" role="button" aria-haspopup="true" aria-expanded="false" class="v-icon notranslate mr-2 mdi mdi-help-circle theme--light" style="font-size: 16px;"></i>
```
The referenced activator el: `button.v-icon.notranslate.mr-2.v-icon--link.mdi.mdi-pencil.theme--light`

HTML after reloading the page
```
<i data-v-cbcf2ae8="" aria-hidden="true" role="button" aria-haspopup="true" aria-expanded="false" class="v-icon notranslate mr-2 mdi mdi-help-circle theme--light" style="font-size: 16px;"></i>
```
The referenced activator el: `i.v-icon.notranslate.mr-2.mdi.mdi-help-circle.theme--light`

**Best Guess**
I think that the issue is on L136 in the `activatable` mixin. Since the `activatorElement` already exists , it's just returning what it was before the update instead of the new `activatorElement` as seen in `this.activatorNode[0].elm`.

**Comment by KenLewis** [comment]
I just removed that line in my dev environment and the tooltip shows in the correct location. But I don't know what other repercussions there are for removing it. I'm guessing that the ideal way to handle this would be to somehow invalidate and regenerate the `activatorElement` when the element is updated. But that's a lot deeper into the code than I currently understand.

**Comment by KenLewis** [comment]
I just realized that my extra information here may not be related to the same issue that was originally posted here. I'll have to make a new issue.
