### ISSUE TITLE
label covers invalid value of number text field

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1258]
### Steps to reproduce
https://codepen.io/anon/pen/vJybJV

### Versions
0.14.8

### What is expected ?
Label should not cover value

### What is actually happening ?
Label covers value

**Comment by johnleider** [comment]
When using the number type on a text-field, the browser will not return a value if the input is invalid. Starting with a period or comma, depending on your locale, will cause the return value to be empty since a period is allowed in a number input, but a period alone is not valid.

There is nothing that I can hook into in order to determine if the customer put a period or a comma withing really hard coding something specifically for that, which could also have unintended consequences.

My recommendation would be to bind to the @keyup event and detect what key it was and compare the v-model output, adjusting the value if needed.

**Comment by jacekkarczmarczyk** [comment]
@johnleider 
Try this code pen https://codepen.io/anon/pen/ayBgRx
It shows that we are able to determine if the input has non empty invalid value, later I'll try to make a PR
