### ISSUE TITLE
[Bug Report][2.3.17] Wrong event order "focus" <-> "blur" with v-select

### ISSUE THREAD

**Issue by jarkt** [vuetifyjs/vuetify#12626]
### Environment
**Vuetify Version:** 2.3.17
**Vue Version:** 2.6.12
**Browsers:** Firefox 82.0
**OS:** Ubuntu undefined

### Steps to reproduce
Click in the first text field and step through **with tab key**. You will get the expected output on console.
But if you **click** in the first text field, in the second and then in the select box, you will get the events in a wrong order.

### Expected Behavior
```
focus <input id="one" placeholder="v-text-field" type="text">
blur <input id="one" placeholder="v-text-field" type="text">

focus <input id="two" placeholder="v-text-field" type="text">
blur <input id="two" placeholder="v-text-field" type="text">

focus <input id="input-9" placeholder="v-select" readonly="readonly" type="text" aria-readonly="false" autocomplete="off">
```

### Actual Behavior
```
focus <input id="one" placeholder="v-text-field" type="text">
blur <input id="one" placeholder="v-text-field" type="text">

focus <input id="two" placeholder="v-text-field" type="text">

focus <input id="input-9" placeholder="v-select" readonly="readonly" type="text" aria-readonly="false" autocomplete="off">

blur null
```

### Reproduction Link
<a href="https://codepen.io/JT2809/pen/XWKoyPZ" target="_blank">https://codepen.io/JT2809/pen/XWKoyPZ</a>

**Comment by KaelWD** [comment]
Looks like currentTarget is null if the blur event is triggered by calling `focus()` on another element: https://codepen.io/kaelwd/pen/WNpJGwz?editors=1011
This seems to only happen because it's going through a `nextTick()`: https://github.com/vuetifyjs/vuetify/blob/67346dbb02cfd7f69076098b326d591738df8cbf/packages/vuetify/src/components/VTextField/VTextField.ts#L446-L449
This was added to fix #7916
