### ISSUE TITLE
Highlight is not working when using an Object in the :to prop of v-list-tile

### ISSUE THREAD

**Issue by jfrs** [vuetifyjs/vuetify#1262]
### Steps to reproduce
Replace `<v-list-tile :to="item.to">` with `<v-list-tile :to="item.to2">` in order to use an Object for the router.
The navigation works but the highlight doesn't.

### Versions
Vue 2.4.2
Vuetify 0.14.8

### What is expected ?
Only the current route should be highlighted

### What is actually happening ?
The Home route is always highlighted

### Reproduction Link
https://codepen.io/anon/pen/brgGdp

**Comment by nekosaur** [comment]
Upon closer inspection, this is not a bug. You need to add the router-link `exact` prop to `v-list-tile`. The reason it works when not using `{ name: 'whatever' }` is that we do an internal check when generating the router link. If `to` is either a string equal to `'/'` or an object with the path property set to `'/'` then we force the `exact` prop to `true`. We can't do this when you use the name property, since we can't know what name you give your root/home route.

**Comment by jfrs** [comment]
That fixed it. I just checked the `v-list-tile` API and it is indeed explained, my bad!
