### ISSUE TITLE
[Documentation] "Link to code" is broken an all pre-maid layouts

### ISSUE THREAD

**Issue by berlaga** [vuetifyjs/vuetify#12679]
### Environment
**Vuetify Version:** 2.3.19
**Vue Version:** 2.6.12
**Browsers:** Edge 87.0.664.41
**OS:** Windows 10

### Steps to reproduce
Go to pre-maid layout page. Click on any <> buttons.

### Expected Behavior
Page with vuetify markup opens

### Actual Behavior
404

### Reproduction Link
<a href="https://v2.vuetifyjs.com/en/getting-started/pre-made-layouts/" target="_blank">https://v2.vuetifyjs.com/en/getting-started/pre-made-layouts/</a>

**Comment by MajesticPotatoe** [comment]
v2.vuetifyjs.com is only temporary and is no longer actively maintained. It will be replaced with the current docs when v3 is released. the <> buttons fail because the actual code no longer exists on the main branch and has been replaced by wireframes. You can however still view the codepen version of the layouts which are accessible via the codepen icons
