### ISSUE TITLE
[Bug Report] DataTable Custom expand button not working 

### ISSUE THREAD

**Issue by MMohesen** [vuetifyjs/vuetify#12673]
### Environment
**Vuetify Version:** 2.3.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.67
**OS:** Mac OS 11.0.1

### Steps to reproduce
- Create Vutify table 
- Override body by own table body and create a button to expand with props.expand function 
- click on expand dose n't work no effect. i consumed my time on this issue, i think in datatable plugin is working fine, but here not work 

### Expected Behavior
expected to expand item 

### Actual Behavior
Not expanded 

### Reproduction Link
<a href="https://codepen.io/montaserfzy/pen/BaLBONm" target="_blank">https://codepen.io/montaserfzy/pen/BaLBONm</a>

### Other comments
i consumed my time. this not testable

**Comment by nekosaur** [comment]
If all you want to achieve is to expand on clicking the row, this is the easiest solution https://codepen.io/nekosaur/pen/eYdOxVg?editors=1010. But that does require you to update to vuetify 2.3. Your codepen is using vuetify 2.1.

If you need to use the `body` slot for other reasons, then you will need to implement the expanded row yourself, the `expanded-item` slot will not work, since you are overwriting the entire internal table rendering by using the `body` slot.
