### ISSUE TITLE
[Feature Request] Closeable v-chip without aria-label

### ISSUE THREAD

**Issue by paulamuchinski** [vuetifyjs/vuetify#12682]
### Problem to solve
Acessibility

### Proposed solution
Add aria-label in v-chip close button

**Comment by juddfranklin1** [comment]
Testing this out in my local playground, I see the aria-label on the close button. Is this issue resolved?
![Screen Shot 2020-12-09 at 11 02 34 AM](https://user-images.githubusercontent.com/1385995/101675627-ede39400-3a0e-11eb-8610-d9157588680b.png)

**Comment by MajesticPotatoe** [comment]
This is in the latest 2.4 beta per #12384

**Comment by paulamuchinski** [comment]
Doesn’t solve the problem, it would be necessary to present the value of the field as well, for the blind person to know what is closing

**Comment by juddfranklin1** [comment]
@paulamuchinski This is interesting, can you give me more detail about the experience? My general understanding of the purpose of the aria-label attribute is simply to provide verbal representation to elements that are not otherwise explicit in their purpose.

I do see an accessibility user experience issue that may be what you are referencing. When I try out a stand-alone VChip with a close button using a screen reader, I notice that the SR jumps past the chip content to the close button, so that the content of the VChip is not read aloud.

The below screenshot reflects how the SR does not speak "hi", it just speaks "close."
![Screen Shot 2020-12-10 at 11 47 44 AM](https://user-images.githubusercontent.com/1385995/101821992-8ea08500-3add-11eb-898a-0386e0f00708.png)

If it were read, would that resolve the issue?
