### ISSUE TITLE
[Bug Report] RadioButton color not working

### ISSUE THREAD

**Issue by maxnocker** [vuetifyjs/vuetify#12693]
### Environment
**Vuetify Version:** 2.3.19
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.67
**OS:** Mac OS 11.0.1

### Steps to reproduce
When i include RadioButtons in my project the color is white and the are not visible. It is also not possible to change the color.

### Expected Behavior
.

### Actual Behavior
.

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

- [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
- [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
- [Codepen](https://template.vuetifyjs.com/)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
