### ISSUE TITLE
[Bug Report] App has scroll bar when it should not

### ISSUE THREAD

**Issue by jacksonlauder** [vuetifyjs/vuetify#12728]
### Environment
**Vuetify Version:** 2.3.19
**Vue Version:** 2.6.12
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Go to page, notice full app is hidden behind bottom nav bar.

### Expected Behavior
Full app is displayed even with bottom nav bar

### Actual Behavior
Full app is not displayed even with bottom nav bar

### Reproduction Link
<a href="https://github.com/jacksonlauder/pub-quiz.git" target="_blank">https://github.com/jacksonlauder/pub-quiz.git</a>

![2020-12-04 00:26:57 +0000](https://user-images.githubusercontent.com/28573268/101109138-653ea100-3593-11eb-91dd-81c958b7efce.GIF)

**Comment by MajesticPotatoe** [comment]
Likely due to not using `app` prop

You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by jacksonlauder** [comment]
@MajesticPotatoe Could you elaborate on not using ```app``` prop? I am using it everywhere the documentation tells me to use it

**Comment by MajesticPotatoe** [comment]
Hard to say, there isn't a valid reproduction to accurately debug.

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
