### ISSUE TITLE
v-select with autocomplete positioning problem

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#1278]
### Steps to reproduce
1. Visit https://codepen.io/darkside73/full/qXRVov/
2. Select device view Portrait - keyboard in devtools
3. Start typing

### Versions
latest

### What is expected ?
Autocomplete results do not cover select itself

### What is actually happening ?
![codepen io-darkside73-full-qxrvov- nexus 5x](https://user-images.githubusercontent.com/339596/29006380-1abd755c-7af7-11e7-9427-d46673a45309.png)

### Reproduction Link
https://codepen.io/darkside73/full/qXRVov/

**Comment by johnleider** [comment]
I am not able to reproduce this with the steps provided.

**Comment by Darkside73** [comment]
What exactly you cannot reproduce? Starting with some height the v-menu cover v-select entirely:
![peek 2017-08-07 09-55](https://user-images.githubusercontent.com/339596/29015484-d83cc20e-7b56-11e7-9e0c-b2f1a0a1b173.gif)

**Comment by jacekkarczmarczyk** [comment]
@johnleider I can reproduce, here is my setup in chrome 59.0.3071.115 / Win10. However it happens when the orientation is set to landscape, not portrait as described in the comment

http://imgur.com/a/P42ni

**Comment by Darkside73** [comment]
It depends on device height in general

**Comment by johnleider** [comment]
I think I better understand the issue now. The main issue though is that it's trying to display the entire list on the screen. So it will re-position in order to do that. I'll see what I can do about fallback situations like this.

**Comment by chancet1982** [comment]
@johnleider I think this issue should be re-opened as it does not really work as expected. I think that when "autocomplete" is activated the textfield should never be covered. This is evident in the material design documentation for autocomplete:
https://material.angularjs.org/latest/demo/autocomplete

As you can see, if you adjust your window so that the items menu would no longer "fits" under the autocomplete, the menu positions itself above(!) the autocomplete so it would not cover it. If there is no room above the auto complete for the whole list it should limit the amount of visible items to the amount available above the list.

**Comment by nekosaur** [comment]
Not to be flippant, but that is not the material design documentation. That is an implementation of MD for angularjs. See here (https://material.io/guidelines/) for the official specification.

**Comment by Darkside73** [comment]
The problem with positioning remains if viewport height becomes smaller (e.g. device orientation changes to landscape or mobile keyboard appears)
