### ISSUE TITLE
[Bug Report] Calendar component with current time integration (Month initial View) doesn't work

### ISSUE THREAD

**Issue by 08BRYLL23** [vuetifyjs/vuetify#12794]
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 3.0.4
**Browsers:** Chrome 86.0.4240.111
**OS:** Mac OS 10.14.6

### Steps to reproduce
On calendar load, click the menu to change calendar view to either week or day 

### Expected Behavior
should show the current time (red line)

### Actual Behavior
current time is not being shown
this.cal.timeToY(this.cal.times.now) returns false

### Reproduction Link
<a href="https://codepen.io/08bryll23/pen/LYRyBdr" target="_blank">https://codepen.io/08bryll23/pen/LYRyBdr</a>

**Comment by arnaud16571542** [comment]
Hello, I have met this bug during my development.
The problem appear when i switch the calendar from day/week mode to month mode.
When i go back to day/week mode, nowY is not updated anymore.
On the submited code by 08BRYLL23, the red line is show correctly is on v-calendar,  type: 'week' (instead of month). On the UI / select box : go from week => month => week : the red line is not present anymore.

Unfortunately, I have n't found an workaround :(

**Comment by ArturWesner** [comment]
The nowY computed property gets updated before the calendar type switches. Because of that and the previous type being month (no timeToY function defined) the timeToY functions returns false. The best solution would be to update the type before the nowY computed property recomputes, but i didn't get that to work.
What i did was to replace the nowY computed property by a function which is basically the same as disabling the cache in the computed property. This is normally not the recommended way, but in this case it's ok for me. Only 7 calls per Minute to the function.
**Working codepen**: https://codepen.io/Artwes/pen/zYNMyKg

**Comment by arnaud16571542** [comment]
Great reply : it works. Thank you !

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
