### ISSUE TITLE
v-select is hidden behind v-edit-dialog

### ISSUE THREAD

**Issue by vuras** [vuetifyjs/vuetify#1283]
### Versions
Vue 2.4.2, VuetifyJS v.0.14.8

### What is expected ?
v-select should over dialog window

### What is actually happening ?
v-select is hidden behind dialog window
![hidden](https://user-images.githubusercontent.com/14833197/29106151-fa27f100-7cdb-11e7-90db-855accbae810.png)

Maybe something related to #697 ?

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by vuras** [comment]
This is the sample code:

[https://codepen.io/vuras/pen/ZJKdgJ](url)

Also, I think there is one more bug, when cancel is pressed, then select dropdown do not dissapear together with edit dialog.

**Comment by johnleider** [comment]
This has been resolved with https://github.com/vuetifyjs/vuetify/pull/1274.
You can now set the zIndex of the inner ```v-select```. This will be the only way due to how Vue processes components and how the menu's content is bound to the container. In your example above, in dev, I was able to set ```z-index="10"``` and it worked properly.
