### ISSUE TITLE
[Bug Report] V-text-field is not emitting an event in tests when triggering click

### ISSUE THREAD

**Issue by mtwolak** [vuetifyjs/vuetify#12927]
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.12
**Browsers:** Firefox 84.0
**OS:** Linux, Ubuntu undefined

### Steps to reproduce
`npm i && npm run test`

### Expected Behavior
Test passes.

### Actual Behavior
It seems v-text-field is not emitting an event in tests.

### Reproduction Link
<a href="https://github.com/mtwolak/vuetify-v-text-field-event-not-emitted" target="_blank">https://github.com/mtwolak/vuetify-v-text-field-event-not-emitted</a>

### Other comments
I apologise for not using Codepen/CodeSandbox, but I couldn't find any template with pre-configured tests.

**Comment by ElijahKotyluk** [comment]
I cloned your repo and it seems like the issue is not being able to target the `v-text-field` input by using the `.v-text-field` class selector, I got the test to pass when targeting using an ID or more specific selector. 

Also in your reproduction repo, make sure the event name you are emitting and testing for match.

**Comment by mtwolak** [comment]
Right, it was issue with selecting `v-text-field`. After retrieving `input` element by its id it worked.
Thank you, issue can be closed.
