### ISSUE TITLE
[Documentation] Add Alternative Way to Integrate Vuetify with Nuxt

### ISSUE THREAD

**Issue by iwgx** [vuetifyjs/vuetify#12965]
### Problem to solve
Currently [@nuxtjs/vuetify](https://github.com/nuxt-community/vuetify-module) seems not actively maintained anymore, the project leader seems [can't found another person to replace him](https://twitter.com/K_Marrec/status/1342519109796376577) and looks like [he lost interest](https://twitter.com/K_Marrec/status/1317152985718378501) too

Meanwhile the project have so many issues and some abandoned pull request, so It really worrying If using @nuxtjs/vuetify in this situation

Using it directly seems better but I can't found how to integrate it with Nuxt since the Vuetify documentation just suggest we use @nuxtjs/vuetify module to do it

### Proposed solution
Update [getting started page](https://vuetifyjs.com/en/getting-started/installation/#nuxt-install) how to use vuetify in nuxt without @nuxtjs/vuetify and another related page that mention @nuxtjs/vuetify

I want to help but I don't know how to do this too, really sorry

**Comment by MajesticPotatoe** [comment]
duplicate #12271
For the most part it isn't documented as the only support we have at the moment is the community module and we don't officially support it. Any updated documentation will come as a part of that FR

**Comment by iwgx** [comment]
Well, to be honest that's different

since #12271 is more like suggest to actively maintained that module again
meanwhile I suggest to add another way to integrate it without using that module

but If that mean that module will actively maintained again, it's even better 🙂

**Comment by MajesticPotatoe** [comment]
Correct its not a direct duplicate, but any alternative means of installation of Nuxt will come from that FR when/if there is one that we decide to support. Easier to track it in one issue then multiple separate ones, and this issue is now mentioned in its comments so there's a paper trail.

The Vuetify team doesn't maintained that module, its maintained by the Nuxt + Vuetify community, and is still our current suggested means of Vuetify support w/Nuxt, and should work for the most part with the current version of vuetify (maybe not so much the current version of Nuxt). If you are having trouble with getting it to work you can feel free to ask questions in our [Discord community](https://community.vuetifyjs.com), as any community members who actively work with the module are likely better to assist there.
