### ISSUE TITLE
High cpu usage with data-tables on IE11

### ISSUE THREAD

**Issue by Laurent50** [vuetifyjs/vuetify#1301]
### Steps to reproduce
Create a data-table with basic options, some content, and check resource usage while moving the cursor over the table with IE11.
### Versions

Vue.js 2.4.2, Vuetify 0.14.8, IE11 on Windows 7
### What is expected ?

Almost no CPU usage (<5%) / not enough to affect ui reactivity
### What is actually happening ?

High cpu usage increase (up to 40-50%), when moving cursor over a data-table, even with little content.
On bigger tables (200+ items) it slows down the whole ui.
### Reproduction Link

https://codepen.io/anon/pen/YxQqQN

**Comment by johnleider** [comment]
That pen does not work properly on IE11

**Comment by Laurent50** [comment]
It was the wrong polyfill. Should be ok now.

**Comment by Phlow2001** [comment]
The problem seems to be caused by software rendering mode in IE.  If you can enable the hardware rendering in your IE settings, it's less severe.
If you must support software rendering, the cause of the persistent CPU usage is the border-radius on the .btn class, and the high CPU usage on hovering the data-table is caused by the transition on the tr.  You can disable both with minimal visual impact:

```html
<style type="text/css">
  .btn {
      border-radius: 0;
  }
  table.table tbody tr {
    transition: initial;
  }
</style>
```

**Comment by Laurent50** [comment]
Thanks for your help, the css solved it. 
Can't really test the IE parameter since it's blocked by gpo.
