### ISSUE TITLE
[Feature Request] Export Vuetify types

### ISSUE THREAD

**Issue by vegerot** [vuetifyjs/vuetify#13043]
### Problem to solve
I am using Vuetify with TypeScript, vue-class-components, and vue-property-decorators:

I have something like 

```html
<template>
  <v-form>
    ref="form"
  >
......
  </v-form>
</template>
....
```
```typescript
...
@Ref('form') form!: unknown;

....

this.form.validate() // sad 😞 
```

How do I know what functions `this.form` has?  Now, I need to have [v-form api](https://vuetifyjs.com/en/api/v-form/) open in a browser window to reference.  But one of the main benefits of TypeScript is having the documentation in your editor.

### Proposed solution
Export Vuetify's component APIs

Let me rewrite the above as 

```typescript

import type { VForm } from 'vuetify';
...
@Ref('form') form!: VForm;

....

this.form.validate() // happy 😊 
```

**Comment by MajesticPotatoe** [comment]
duplicate #5962

**Comment by vegerot** [comment]
@MajesticPotatoe with all due respect that issue is from three years ago.  I am in interested in hearing from the Vuetify team what they think of this proposal

**Comment by MajesticPotatoe** [comment]
@vegerot though that issue is from 3 years ago, its still relevant, and open because it has yet to be fully addressed (which will likely happen as we work on v3). You are welcome to propose ideas on that thread, in our discord, or a discussion. If you have questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by vegerot** [comment]
Good idea.  I have left a comment on that thread.  Thank you
