### ISSUE TITLE
[Bug Report] v-autocomplete using item slot with v-list-item-title and v-list-item-subtitle is rendered too wide

### ISSUE THREAD

**Issue by everhardt** [vuetifyjs/vuetify#13133]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 88.0.4324.182
**OS:** Mac OS 11.2.1

### Steps to reproduce
Click on the first autocomplete

### Expected Behavior
Menu should be as wide as the autocomplete itself (as the other 2 do have)

### Actual Behavior
It is too wide

### Reproduction Link
<a href="https://codepen.io/everhardt/pen/bGBRrVa" target="_blank">https://codepen.io/everhardt/pen/bGBRrVa</a>

**Comment by mostafa7904** [comment]
I think this is because you're setting the width of the parent component ` <div class="ma-3" style="width:350px">`. 
which affects the width of the autocomplete component and therefore it can't fit wide content in the menu.

It's not a vuetify problem it's because of the style you're setting. The child component is bigger than the parent width and that's why it's overflowing.

**You can fix this by either removing the width from parent (or make it larger) or make the item contents smaller.**

Also try the `dense` prop it seems to fix the problem.

https://codepen.io/mostafa7904/pen/QWGMXXv

**Comment by everhardt** [comment]
I'd say the v-list-element content would easily fit in the 350px width the input field has, but still it grows wider:

![image](https://user-images.githubusercontent.com/1840153/108623170-c7de6500-743d-11eb-88b7-f811c8185607.png)

**Comment by everhardt** [comment]
While if I only take the title or subtitle, it does adhere nicely to the 350px width of the input field:
![image](https://user-images.githubusercontent.com/1840153/108623232-2f94b000-743e-11eb-84b3-8ee760dc60f5.png)
and
![image](https://user-images.githubusercontent.com/1840153/108623242-3b807200-743e-11eb-803f-f096addf9163.png)

**Comment by KaelWD** [comment]
It looks like the width is first calculated as the intrinsic width of the children
![image](https://user-images.githubusercontent.com/16421948/129754380-daacfbcc-f0df-4c0c-a121-a3e15147787a.png)
And only then is the padding added
![image](https://user-images.githubusercontent.com/16421948/129754437-206a44f2-c963-40ca-a57e-4b5e2b61bed3.png)
This is the case because `.v-list-item__content` has flex-wrap enabled. To fix it should probably be a flex column instead so the title and subtitle are always on separate lines
![image](https://user-images.githubusercontent.com/16421948/129754896-0bf64f75-af45-4cf8-9cad-29188849ff52.png)
Maybe explore grid layout for this in v3 @johnleider

**Comment by johnleider** [comment]
Not using **flex-column** was probably a decision based upon IE11 support, which is no longer an issue. I agree @KaelWD, grid is probably be the best way to go about this.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
