### ISSUE TITLE
[Feature Request] Apply color to false state simple-checkbox

### ISSUE THREAD

**Issue by adarshmadrecha** [vuetifyjs/vuetify#13178]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.11
**Browsers:** Chrome 88.0.4324.190
**OS:** Windows 10

### Steps to reproduce
1. Use v-simple-checkbox
2. Add color prop

### Expected Behavior
The box color should also change to the color specified

### Actual Behavior
Only the `true` state has color. The false state does not have color. Just the standard grey box.

### Reproduction Link
<a href="https://codepen.io/adarshmadrecha/pen/dyOmvOd" target="_blank">https://codepen.io/adarshmadrecha/pen/dyOmvOd</a>

### Comments
As seen in the image, even though the color prop is set to blue, the box (in false state) is grey.
![image](https://user-images.githubusercontent.com/11911938/109412170-6afa2600-79cc-11eb-98aa-4968b6186ac2.png)

**Comment by MajesticPotatoe** [comment]
per discord: This is intended and should be a FR

**Comment by yogarasu** [comment]
I also agree with this feature request.
This is because it is easier to distinguish when the check box can be colored, but it is easier to distinguish if the color does not change when it is false.
Checkboxes such as Google Calendar change color even when it is false, but I think this is reasonable.

<img width="46" alt="スクリーンショット 2021-09-21 0 05 12" src="https://user-images.githubusercontent.com/68766032/134025892-9a3e8d7e-a643-4678-8cc0-41739b63ef7a.png">

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
