### ISSUE TITLE
[Bug Report] vue add vuetify Overrides the files and not adding to them.

### ISSUE THREAD

**Issue by IgorIlgiyaev** [vuetifyjs/vuetify#13223]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.192
**OS:** Mac OS 10.15.7

### Steps to reproduce
Hey
I cannot upload a local dev and the issue is:
When everything is working properly I have installed the vue add vuetify to make the app more pretty, but when I installed it, it first broke the app and second changed a lot of files.

### Expected Behavior
to display the app

### Actual Behavior
overrided the files

### Reproduction Link
<a href="http://codepen.com" target="_blank">http://codepen.com</a>

**Comment by IgorIlgiyaev** [comment]
![image](https://user-images.githubusercontent.com/20319110/110222920-b3d74080-7ede-11eb-80d7-6b5070702dc1.png)

**Comment by MajesticPotatoe** [comment]
Template changes can be skipped by selecting the advanced install option during install as noted in the docs
https://vuetifyjs.com/en/getting-started/installation/#vue-cli-install

**Comment by IgorIlgiyaev** [comment]
This is not an answer - I need those changes to be applied as expected to add those line if they needed without overriding the existing files as all extensions do, for example json-server only add a dependency and not override the entire page.

**Comment by MajesticPotatoe** [comment]
Based on the information you provided, it seems like your issue was with the template files (App.vue and HellowWorld.vue) bring overwritten, which are completely optional and hold no bearing on the functionality of the install.

If you are still having issues please open an issue on the proper repo, as this is an issue with vuetify cli not the vuetify library itself. That repo can be found here: https://github.com/vuetifyjs/vue-cli-plugins

be sure to include a functional reproduction and clear explanation of your issue to help us better assist you (this can include a simple repo outline the issue with commits).

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by IgorIlgiyaev** [comment]
The screenshot I have provided is only one file been overwritten, the package.json is too overwritten.
I will try to explain my issue again in the provided link as I am a newbie in Vue (Just started to learn a few days ago :-) ).

**Comment by paddotk** [comment]
I think the CLI installer should explicitly ask or warn about this. I installed Vuetify and then, without having seen any warning of such, noticed that my App.vue was overwritten completely (luckily I hadn't done too much here yet, but still).

**Comment by KaelWD** [comment]
Vue-cli warns you when you install a plugin with uncommitted changes.
