### ISSUE TITLE
v-select's label shakes during transition

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1325]
### Steps to reproduce
Create v-select component with many items and click on the input

### Versions
0.14.9
Chrome/Win10

### What is expected ?
Label transition should be smooth

### What is actually happening ?
Label is moving backwards and forwards (by tiny but visible amount, it's more visibile in the browser that on gif)
![gif](https://user-images.githubusercontent.com/15625235/29243710-0d923cc4-7fa6-11e7-8e38-601050de93a2.gif)

### Reproduction Link
https://codepen.io/anon/pen/YxxvXz

**Comment by mfferreira** [comment]
@jacekkarczmarczyk I don't see the issue using your codepen. I'm macOS.
Do you see that on other browsers?

**Comment by jacekkarczmarczyk** [comment]
Also on Edge

**Comment by DedDorito** [comment]
I can repo it on macOS and Firefox.

**Comment by Sydtrack** [comment]
I can reproduce this when the page itself is filled with dom.
![flicker](https://user-images.githubusercontent.com/1519135/29283937-3101d1a6-80ff-11e7-8449-fe11ed4ecfcc.gif)

**Comment by mfferreira** [comment]
Some wild css, most likely. I'll take a look.

**Comment by mfferreira** [comment]
@isaaclyman @DedDorito @jacekkarczmarczyk 
What Firefox version?

**Comment by jacekkarczmarczyk** [comment]
Fx 54, Ch 60, Edge 14 / win10

**Comment by mfferreira** [comment]
Please check example #6 on the [Selects doc page](https://vuetifyjs.com/components/selects). Check if the same happens there. (doesn't for me)

Also, please check [this sample](http://jsfiddle.net/r9f8cdre/).

**Comment by Sydtrack** [comment]
There are 2 classes starting the label animation. The :focus from input-group and the .input-group--focused class. Since the :focus is browser based, it may start a bit earlier if the page is heavy loaded and vue takes a bit to add the .input-group--focused class.

`.input-group--text-field:not(.input-group--single-line):focus:not(.input-group--textarea) label`

and

`.input-group--text-field:not(.input-group--single-line).input-group--focused:not(.input-group--textarea) label`

**Comment by Sydtrack** [comment]
You may simulate the browser behavior changing line 230 from VSelect.js from:
`this.focused = true`
to
`setTimeout(() => this.focused = true, 100)`

This is somewhat close to what happens when Vue takes a while to add the correct --focused class.

**Comment by mfferreira** [comment]
@Sydtrack That's a very good catch.

**Comment by mfferreira** [comment]
Commenting [this whole line](https://github.com/vuetifyjs/vuetify/blob/daca5190a5ac3ec28fa84f3d6873828e16612273/src/components/VSelect/VSelect.vue#L225), so the input doesn't get `:focus` seems to fix the issue.
Need to investigate more and see the impact.

**Comment by Sydtrack** [comment]
Does the autocomplete still work without focusing the input?

Alberto Wagner

**Comment by johnleider** [comment]
This has been fixed. I ran across this accidentally while looking at events being fired and it turns out that the focus method was being called twice. This was causing a reevaluation of properties that were triggering the select to try and boot up twice. This caused a fluctuation in the applied styles and the shake is the select being focused, then very quickly blurred, then refocused again.
