### ISSUE TITLE
[Bug Report] Expand transitions do not work with v-alert

### ISSUE THREAD

**Issue by pongstylin** [vuetifyjs/vuetify#13294]
### Environment
**Vuetify Version:** 2.4.7
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.190
**OS:** Windows 10

### Steps to reproduce
The CodePen is a copy of a vuetify example that was updated to vuetify 2.4.7.  I also replaced v-cards with v-alerts to demonstrate the problem.  Just click the "Expand Transition" and "Expand X Transition" button.

### Expected Behavior
The alert expands open.

### Actual Behavior
The alert pops open.

### Reproduction Link
<a href="https://codepen.io/pongstylin/pen/wvoLWOq" target="_blank">https://codepen.io/pongstylin/pen/wvoLWOq</a>

### Other comments
Search of the issues list only turned up this comment that resembles my problem: https://github.com/vuetifyjs/vuetify/issues/9033#issuecomment-606730664

It would be nice if using the "transition" prop worked for "JavaScript" transitions like this as opposed to only "Simple" transitions.  But even if that is not feasible, I would expect the expand transition components to work.

**Comment by johnleider** [comment]
When you use `v-model` with `v-alert`, it's controlling the visible state of the component. When you put it inside of `v-expand-transition`, it's unable to actually animate because they happen at the same time.

Use v-if or v-show on a root element inside of the `v-expand-transition`. https://codepen.io/johnjleider/pen/MWmpLBQ

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
