### ISSUE TITLE
[Bug Report] v-data-table value only accepts lowercase for custom formatting

### ISSUE THREAD

**Issue by amizer12** [vuetifyjs/vuetify#13310]
Time column formatted via function defined in JS sectiong

### Actual Behavior
 Time being simply represented as timestamp e.g. function is not launching at all

### Reproduction Link
<a href="https://codepen.io/amizer12/pen/qBRWRMJ" target="_blank">https://codepen.io/amizer12/pen/qBRWRMJ</a>

**Comment by jacekkarczmarczyk** [comment]
html is case insensitive, use .vue files or `script type="text/x-template"` (like in the codepen templatehttp://template.vuetifyjs.com/)

**Comment by amizer12** [comment]
For some reason the entire content of this bug report was cut down - this is about value in v-data-table header expecting only lower case strings - if it`s upper case and its also reflected everywhere else it won`t launch unless changed to lowercase.
change value: 'createdtime' into value'cretaedTime' in teh pen i submitted above and you will see what i mean

**Comment by jacekkarczmarczyk** [comment]
As i said it is the limitation of html, template is parsed as `v-slot:item.createdtime` and that's why you need to use `createdtime` (lowercase) property.
Similarly if you have `<something propName="foo">` it will be parsed as `<something propname="foo">` and it will work properly only if you name your property `propname` instead of `propName`

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
