### ISSUE TITLE
[Bug Report][2.4.11] not possible to enter number values using scientific notation with double digit exponents (e.g. 1e-10) with v-model.number

### ISSUE THREAD

**Issue by Wafje** [vuetifyjs/vuetify#13520]
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.128
**OS:** Windows 10

### Steps to reproduce
Enter a number using scientific notation with double digit exponents (e.g. 1e-10) in the input field of the v-text-field.

### Expected Behavior
1e-10 should appear in the input field.
Expected functionality can be tested with a regular &lt;input&gt; element (see jsfiddle)

### Actual Behavior
As soon as '1e-1' is typed, the value changes to 0.1

### Reproduction Link
<a href="https://jsfiddle.net/y16fv2uL/2/" target="_blank">https://jsfiddle.net/y16fv2uL/2/</a>

**Comment by lioneaglesolutions** [comment]
I'm not sure if this is going to be fixed. The issue is still present in V3 but I think the better workaround would be to cast the number outside of the `number` modifier yourself.

Repro in V3 for @johnleider 

https://play.vuetifyjs.com/#eNqNUs1OwzAMfhUrF0BaGgkmIY0ywYWXoBy61tMCSRolbhma9u44DRNlE9ouVfPZ/n6cvO7Es/fF0KNYiJLQelMTLisHUA4yYPSdi3rABAA0po7xsRJ2K+ueukpk2NZb+alb2nDpbj7P8MgBkL/Mpp3vCQZpuxZN4Xq7wsD9+acSP+0sSrgludZo2sOsqVdouPdFh0jgaosHZYCNblG2SLU2ydnUFvyvlhuWpZrK5dQM/cZmqFSTrfAxNkF7gojUe0a09V0g2AVc72EdOgtXvMyrh8RVuYZp2PGoCo/ATdeuN+aGy6XKTEsxE0a7j1i8x87xLezGUdHEWIkFvP6sUWyIfFwo1bSOOzmVHkLhkJTzVrEk6fXX011xW9yqVkc6QJKXF4uRLDG9VW7Pgtm1tLU/Us2FUXlEEsZM6XzGwhO3qdA70pYvpLOjl/l9NjPBC4xWrkL3GTEwSyVmE53k+AKtc3FZ4oRasd6AgS/XtRjSI7gs0tHYn1hHtZNoSX6fNr6fiTzHux9Ni7dvnZQp2A==

**Comment by johnleider** [comment]
We can leave it open for a fix in v3.

**Comment by KaelWD** [comment]
Nah this is pretty similar to https://github.com/vuetifyjs/vuetify/issues/17275, not really fixable without decoupling the internal model.
