### ISSUE TITLE
[Bug Report][2.5.3] Dense text-field append-outer icon not vertically centered

### ISSUE THREAD

**Issue by davidbielik** [vuetifyjs/vuetify#13767]
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.13
**Browsers:** Chrome 90.0.4430.212
**OS:** Mac OS 10.15.7

### Steps to reproduce
```
<v-text-field
            outlined
            dense
            label="My Label"
            value="icon is not vertically centered"
            hide-details="auto"
>
    <template #append-outer>
         <v-btn icon>
                <v-icon color="error">mdi-delete</v-icon>
          </v-btn>
    </template>
</v-text-field>
```

### Expected Behavior
append-outer icon is vertically centered

### Actual Behavior
append-outer icon is not vertically centered

### Reproduction Link
<a href="https://codepen.io/codepen123456789/pen/jOBKNEJ" target="_blank">https://codepen.io/codepen123456789/pen/jOBKNEJ</a>

![image](https://user-images.githubusercontent.com/7410770/120940041-1d870680-c6e9-11eb-8193-294059e748fa.png)

**Comment by johnleider** [comment]
Form controls that support prepend/append functionality expect a `v-icon`, not a `v-btn`. The slot has top margin in order to facilitate the default usage. Your reproduction workaround is the expected behavior.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
