### ISSUE TITLE
[Bug Report][2.5.4] v-data-table the sort by chip icon is opacity zero in mobile mode

### ISSUE THREAD

**Issue by lgou2w** [vuetifyjs/vuetify#13832]
### Environment
**Vuetify Version:** 2.5.4
**Vue Version:** 2.6.14
**Browsers:** Firefox 89.0, Chrome 91.0.4472.106, Edge 91.0.864.54
**OS:** Windows 10

### Steps to reproduce
Create a data table, switch the mobile mode and choose any sort

### Expected Behavior
chip icon visible

### Actual Behavior
chip icon is transparent 

### Reproduction Link
<a href="https://codepen.io/lgou2w/pen/oNZOaJy" target="_blank">https://codepen.io/lgou2w/pen/oNZOaJy</a>

### Other comments
`.v-data-table-header__icon`: `opacity: 0`

**Comment by lioneaglesolutions** [comment]
@johnleider 

The issue is the sorting icon doesn't show (unless hovering). 

![A Pen by lgou2w](https://user-images.githubusercontent.com/61766491/235775978-090f35da-14aa-4dd5-847e-ab37a84873b4.gif)

Mobile view for v-data-table isn't in V3 yet but this issue is ~2 years old and is stale.

A solution is to add CSS which will resolve the issue;
```css
.v-data-table-header__icon {
  opacity: 1;
}
```

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
