### ISSUE TITLE
[Bug Report][3.0.0-alpha.9] The `variables` property of the `ThemeDefinition` interface should be optional

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify#13914]
### Environment
**Vuetify Version:** 3.0.0-alpha.9
**Vue Version:** 3.1.4
**Browsers:** Chrome 91.0.4472.124
**OS:** Windows 10

### Steps to reproduce
n/a

### Expected Behavior
The `variables` property of the `ThemeDefinition` interface should be optional (according to #13822).

### Actual Behavior
It's [required](https://github.com/vuetifyjs/vuetify/blob/7e75cf9023707f9040d22a3c3279d52595b68d6f/packages/vuetify/src/composables/theme.ts#L59).

### Reproduction Link
n/a

**Comment by johnleider** [comment]
This is because every theme is expected to have all of those values. If you make changes to either dark/light, it will merge with the default properties and anything not there is added to the theme options.

If you create a new theme, you are expected to provide all of these values because they are not merged with any defaults values.

@nekosaur What are your thoughts on making `dark` default to **false** and merging dark/light with partial themes to fill in the blanks?

**Comment by glen-84** [comment]
Ya, I'm not creating a new theme, I'm overriding the dark one, but it's the same interface so I suppose you still need to enforce the existence of variables, unless, as you say, all theme definitions are merged with defaults so that it can be made optional.

**Comment by nekosaur** [comment]
Yes that was always the plan, it's just fallen between the cracks
