### ISSUE TITLE
[Bug Report][2.5.5] v-btn's value prop error

### ISSUE THREAD

**Issue by skadiD** [vuetifyjs/vuetify#13924]
### Environment
**Vuetify Version:** 2.5.6
**Last working version:** 2.5.6
**Vue Version:** 3.1.4
**Browsers:** Chrome 91.0.4472.124
**OS:** Windows 10

### Expected Behavior
Button should be hidden

### Actual Behavior
"value" prop doesn't hide the button

### Reproduction Link
<a href="https://codepen.io/skadiD/pen/ExmZrLM" target="_blank">https://codepen.io/skadiD/pen/ExmZrLM</a>

**Comment by jacekkarczmarczyk** [comment]
Button should not be hidden, it's a bug in documentation

**Comment by KareemDa** [comment]
![image](https://user-images.githubusercontent.com/42810389/147786493-fda6d048-358b-4791-91a1-93c685352833.png)
here is a descitpion about value attribute in a "button"

I thinks It's showing this description because button uses `ToggleableFactory` mixins which has this prop, right ?
@MajesticPotatoe
