### ISSUE TITLE
[Feature Request] Ability to customize styles on component basis?

### ISSUE THREAD

**Issue by tar-aldev** [vuetifyjs/vuetify#13999]
### Problem to solve
Let's say I have a v-card component. By default in dark mode, it has a background color of `#1E1E1E`

I see no good way of customizing the background for the card.
Changing `themes -> dark` colors seems to have no effect.
I can, of course, pass the `color` prop to every card, but it is not a good way. I want to change the `background-color` globally.
The way I do it now is by overwriting `.vue-card` class globally (which still is not a perfect solution to me)

```
.v-card {
  background-color: #546e90cc !important;
}
```

### Proposed solution
Maybe it is possible to at least add sass variable for this?

**Comment by KaelWD** [comment]
It's `cards` in `$material-light`/`$material-dark`:https://github.com/vuetifyjs/vuetify/blob/7877beff68013bb46c4c8d34d4a33c69ca1115c7/packages/vuetify/src/styles/settings/_light.scss#L24

> Changing themes -> dark colors seems to have no effect

In v3 cards use the `surface` theme color instead of a sass color.

> I can, of course, pass the color prop to every card

In v3 you can define prop defaults globally.
