### ISSUE TITLE
[Bug Report][2.5.8] Bug using v-rating as item slot in v-select

### ISSUE THREAD

**Issue by fl4ko92** [vuetifyjs/vuetify#14187]
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Firefox 92.0, Google Chrome, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
Ready!

### Expected Behavior
Is expected to show the five options with te amount of stars according to the value

### Actual Behavior
After 5 o 6 clicks the items to be selected start show an incorrect amount of stars 

### Reproduction Link
<a href="https://codepen.io/fl4ko92/pen/eYRjyyE" target="_blank">https://codepen.io/fl4ko92/pen/eYRjyyE</a>

**Comment by nekosaur** [comment]
The v-rating component has an internal state that unfortunately ignores the `value` prop. You could add `readonly` to fix it. But since you only seem to be interested in showing the stars and not using the actual functionality of the component, I would suggest just rendering the star icons https://codepen.io/nekosaur/pen/PojBErZ

**Comment by fl4ko92** [comment]
You´re right, both solutions do the job!
