### ISSUE TITLE
[Bug Report][2.6.0] v-otp-input : the component does not update the value correctly

### ISSUE THREAD

**Issue by TheoPez** [vuetifyjs/vuetify#14437]
### Environment
**Vuetify Version:** 2.6.0
**Vue Version:** 2.6.11
**Browsers:** Firefox 95.0
**OS:** Linux x86_64

### Steps to reproduce
Type an otp code and press the "Reset Form" button.
As you can see, the otpValue becomes null, but the otp field does not update.

### Expected Behavior
We expect the field to be updated

### Actual Behavior
The v-otp-input field is not updated

### Reproduction Link
<a href="https://codepen.io/the0pe/pen/vYJoYJb" target="_blank">https://codepen.io/the0pe/pen/vYJoYJb</a>

### Other comments
I did some research on this problem, and found a clue.
Currently, when clearing, the `otp` value (declared on https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VOtpInput/VOtpInput.ts#L55) is not updated.

**Comment by ndmgrphc** [comment]
I love that this component was included in Vuetify.  My solution to this issue in the meantime was to just include a :key="`otpvs-${otpIncrement}`" on the v-otp-input element and then bump up this.otpIncrement++ when I needed to redraw the input (like when the user entered the code wrong).

**Comment by mathiasconradt** [comment]
I found a related issue here, you can also test it in the above mentioned Codepen.

**Instead of typing the character into the OTP fields one by one, copy/paste an entire 6-digit string into the first OTP-field. The printed out value below does not update.**

My issue should probably go into a different bug report, but just wanted to mention it here, because this issue title is a bit misleading, it sounds like the other way around than in the description.

IMO this bug title should be: _"v-otp-input : the value/model does not update the component"_ instead of _"v-otp-input : the component does not update the value correctly"_... which is actually what my problem is. Which is why I found this issue report here when googling for my problem.
