### ISSUE TITLE
[Feature Request] textfield mask with multiple input

### ISSUE THREAD

**Issue by krazye05** [vuetifyjs/vuetify#14532]
### Problem to solve
Make masking feature with split inputs like this.

https://www.jqueryscript.net/form/Simple-Input-Mask-Validation-Plugin-With-jQuery-maskedinput.html

### Proposed solution
Make masking feature with split inputs like this.

https://www.jqueryscript.net/form/Simple-Input-Mask-Validation-Plugin-With-jQuery-maskedinput.html

**Comment by lioneaglesolutions** [comment]
Doubt this will make its way into the core library - plenty of masking solutions out there already. @johnleider happy to reopen if this is planned.

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
