### ISSUE TITLE
[Feature Request] Vuetify 3 beta

### ISSUE THREAD

**Issue by ArishSultan** [vuetifyjs/vuetify#14557]
### Problem to solve
Its 2022 and vuetify beta has still not been released.

### Proposed solution
Please change the expected dates on your website

**Comment by DRoet** [comment]
Its 2022 and you haven't contributed anything to the project, yet complain 🤔

**Comment by ArishSultan** [comment]
Ah, you get me wrong, I am not complaining. I am just curious. I tried contributing to this project last year but haven't got time since then. Sorry if i did anything wrong

**Comment by Shujee** [comment]
I agree. ETAs should be updated if nothing else.

**Comment by Hexodus** [comment]
I need to evaluate for our company if we should go with vuetify 3 or our own framework. I just tried out Vuetify 3 and stopped when realized that there has been no update since November and not even a branch with a hint of a new version. The projects board has been last updated in August and John's last Patreon post is from September. 
Sorry to say that, but it makes me very concerned when there is no new info.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/commits/next
https://vuetifyjs.com/en/getting-started/installation/#nightly-builds

**Comment by Hexodus** [comment]
Oh tanks for the info @KaelWD !

**Comment by subdavis** [comment]
We now have a Beta checklist, thanks maintainers!

I think this issue should be closed and linked to https://github.com/vuetifyjs/vuetify/issues/14729

**Comment by Shujee** [comment]
mm... not sure. The checklist doesn't convey any information about when those items will be completed, not even a rough estimate. The v3 discord channel is much more informative. I saw John still being positive for a beta release within Feb 2022.

**Comment by MajesticPotatoe** [comment]
closed in favor of #14729
