### ISSUE TITLE
[Bug Report][2.6.3] Broken label in outlined input with a prepended icon

### ISSUE THREAD

**Issue by flosca** [vuetifyjs/vuetify#14661]
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 97.0.4692.99
**OS:** Windows 10

### Steps to reproduce
1. Create any input component, e.g. `v-text-field` with an `outlined` style and with a label.
2. Via `v-slot:prepend-inner` put an icon in the input with `v-if` condition for showing this icon
3. Create a button that would toggle the condition

### Expected Behavior
Prepended icon should disappear, label of an input remains still.

### Actual Behavior
Prepended icon does disappear, but label is shifted to the left.

### Reproduction Link
<a href="https://codepen.io/flosca/pen/podJWKB" target="_blank">https://codepen.io/flosca/pen/podJWKB</a>

**Comment by hollote** [comment]
Have a similar issue, with the `prepend-inner` slot and the `outlined` style label being shifted to the left. 
<img width="514" alt="Снимок экрана 2022-02-22 в 13 26 42" src="https://user-images.githubusercontent.com/5200388/155123126-97acf90a-79e7-4c0f-9f0e-2e69f4ca012e.png">
When changing layout (change width of browser) it re-calculates label position correctly. 
<img width="426" alt="Снимок экрана 2022-02-22 в 13 27 35" src="https://user-images.githubusercontent.com/5200388/155123237-3a2f2a51-3f9a-46b9-afc6-acdae37e1fec.png">

Probably the fix for this issue can fix this error also.
