### ISSUE TITLE
[Feature Request] Add Scss variables to change the default font color in light and dark theme

### ISSUE THREAD

**Issue by MarceloLuis1997** [vuetifyjs/vuetify#14759]
### Problem to solve
Be able to change the default font color of all components in light and dark theme.

### Proposed solution
Add scss variables to change the default font color of all components, something like the `$body-font-family` variable that changes the default font of the application.

```
// variables.scss
$light-default-font-color: #3c4043;
$dark-default-font-color: #f9f9f9;
```

**Comment by KaelWD** [comment]
Most text colors are here: https://github.com/vuetifyjs/vuetify/blob/7877beff68013bb46c4c8d34d4a33c69ca1115c7/packages/vuetify/src/styles/settings/_light.scss#L35-L42

**Comment by frederikheld** [comment]
@KaelWD Thanks for the hint, but where would I put this in my `plugins/vuetify.js` file?

The docs are very scarse with information about theming... Can you recommend a source that explains theming in its entirety?

**Comment by JoachimTillessen** [comment]
@MarceloLuis1997 @frederikheld and other people who might be wondering. 
You can define text colors via sass on a per component basis, but this is pretty tedious if you want to maintain a consistent look. Global theme colors on the other hand are not based on sass variables but by passing a theme property to the Vuetify constructor. (https://v2.vuetifyjs.com/en/features/theme/#customizing)
Unfortunately all the resources describing the process only give examples for defining background colors.
As @KaelWD was saying in order to define text colors you need to define them relative to their background colors by prefixing the background color names with 'on-'.
For example if you want your text color to appear on the app background as well as on cards and sheets (I think this should cover your default color use case), you need to define:

```
themes: {
  light: {
    colors {
      'on-background': string,
      'on-surface': string,
    }
  },
  dark: {
    colors {
      'on-background': string,
      'on-surface': string,
    }
  }
}
```
It's logical but not very obvious and should definitely be featured in the documentation more prominently.
