### ISSUE TITLE
[Bug Report][3.0.0-alpha.13] Dialog "scrollable" does not create scrollable dialog.

### ISSUE THREAD

**Issue by pgoy-dod** [vuetifyjs/vuetify#14763]
### Environment
**Vuetify Version:** 3.0.0-alpha.13
**Last working version:** 2.6.3
**Vue Version:** 3.2.31
**Browsers:** Mozilla Firefox
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Visit https://next.vuetifyjs.com/en/components/dialogs#scrollable
2. Click "Open Dialog" to open the example scrollable dialog.
3. Observe the card contents extend beyond the bottom of the dialog, where they are unreachable.

### Expected Behavior
The dialog is scrollable.

### Actual Behavior
The dialog is not scrollable.

### Reproduction Link
<a href="https://codepen.io/pgoy-dod/pen/GROXWEb" target="_blank">https://codepen.io/pgoy-dod/pen/GROXWEb</a>

**Comment by pgoy-dod** [comment]
Please note that while i included a link to the documentation for the example, this is occurring in general as well. This is not a documentation bug—although maybe it is, if the "correct" way to make a scrollable dialog is not correctly documented.

**Comment by xbogdan** [comment]
I am experiencing a similar issue, but related to full screen dialogs. https://vuetifyjs.com/en/components/dialogs/#fullscreen

### Steps to reproduce
1. Visit https://vuetifyjs.com/en/components/dialogs/#fullscreen
2. Change the browser window size so that the content of the dialog does not fit in the view port.
3. Notice that the dialog content does not fit in the viewport (vertically) and the scrollbar is missing.

If you open the dialog first and resize the window so that the content of the dialog does not fit vertically in the view port, the scroll functionality works.

### Expected Behavior
The dialog is not scrollable.
