### ISSUE TITLE
[Feature Request] Why is `VTabs`/`VTab` components not exported?

### ISSUE THREAD

**Issue by cdll** [vuetifyjs/vuetify#14788]
### Problem to solve
i 'm using `vuetify@3.0.0-alpha.13` with `vite + vue3 + tsx`, but i couldnt import VTabs and VTab components individually and i found 
```js
// file: node_modules/vuetify/lib/components/index.mjs#Line88
export * from "./VTooltip/index.mjs"; // export * from './VTreeview'
```

even though i 've tried 
```js
// file: src/pages/Demo.tsx
import Tabs from 'vuetify/components/VTabs'

export default {
  render () {
    return <VTabs />
  }
}
```
i got error in vite serving.

i wonder why is that some components likes VTabs, VTab and so on were not exported.

### Proposed solution
may Vuetify supports tsx developing.

**Comment by KaelWD** [comment]
Because they aren't done yet. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by cdll** [comment]
thank u all the same.  🙏 And feel sorry that i tried to get touch into [the Discord chat room](https://community.vuetifyjs.com/) but my Chinese network wont work.
