### ISSUE TITLE
[Bug Report][2.6.4] v-select 

### ISSUE THREAD

**Issue by xjagan** [vuetifyjs/vuetify#14823]
### Environment
**Vuetify Version:** 2.6.4
**Last working version:** 2.6.4
**Vue Version:** 2.6.4
**Browsers:** Chrome 99.0.4844.51
**OS:** Windows 10

### Steps to reproduce
select dropdown scroll not working 

### Expected Behavior
give the items in data

### Actual Behavior
added 10 more iteam is not showing

### Reproduction Link
<a href="https://codepen.io/anon/pen/RjYmJb?editors=1010" target="_blank">https://codepen.io/anon/pen/RjYmJb?editors=1010</a>

### Other comments
when i click the select field just showing 4 or 5 values only  othere values are hidden the inside of the fiels.....

**Comment by TheoPez** [comment]
Hi !
Your reproduction is broken, I made a correct reproduction of your codepen but it does not reproduce your problem :
https://codepen.io/the0pe/pen/rNpaWpp

I see you are using v-flex and v-layout on your original reproduction, are you sure you are using vuetify 2.6.4 ? and not an older version like 1.5.x ?

(Since Vuetify 2.0 `v-layout` and `v-flew`  have been replaced by `v-row` and `v-col`)

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). If you don't speak english there are channels for other languages.
