### ISSUE TITLE
[Bug Report][3.0.0-beta.0] Always flat v-btn inside v-window

### ISSUE THREAD

**Issue by Foresteam** [vuetifyjs/vuetify#14844]
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Firefox 98.0, Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
Follow the default instructions (my GitHub repo)

### Expected Behavior
It should be of variant "contained"

### Actual Behavior
It is flat

### Reproduction Link
<a href="https://github.com/Foresteam/vtfbug" target="_blank">https://github.com/Foresteam/vtfbug</a>

**Comment by nekosaur** [comment]
They look the same to me?

https://codepen.io/nekosaur/pen/RwxRPxg

**Comment by Foresteam** [comment]
I forgot to change something, my mistake. Updated the repo. But even without it, the both buttons are flat, while they shouldn't be by default

**Comment by KaelWD** [comment]
The "default" variant is `contained`

**Comment by Foresteam** [comment]
Well, i removed "variant" properties at all, and result is still the same.
![image](https://user-images.githubusercontent.com/28836012/160198478-a040fd27-8c0d-427f-b162-10f2c4f970c1.png)

**Comment by tve** [comment]
Same issue with simple repro in codepen:

### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.30
**Browsers:** Chrome 98.0.4758.136
**OS:** Linux x86_64

### Steps to reproduce
See the codepen:
- Button 1 is plain in the app and has a color background with white text, as expected
- Button 2 is identical, except it's in a v-window, it looses the bg color
- Button 3 is like Button 2 but forces the variant, it regains the bg color

### Expected Behavior
All three buttons should look the same

### Actual Behavior
Button 2 switches variant

### Reproduction Link
<a href="https://codepen.io/codesurfr/pen/ZEveqLe" target="_blank">https://codepen.io/codesurfr/pen/ZEveqLe</a>

**Comment by johnleider** [comment]
fixed by 8ef06ae75
