### ISSUE TITLE
[Bug Report][2.6.4] v-menu immediately closes first time it's opened without activator

### ISSUE THREAD

**Issue by reynard80** [vuetifyjs/vuetify#14903]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Firefox 98.0
**OS:** Windows 10

### Steps to reproduce
- Open codepen
- Click/focus text field
- Observe menu being opened and immediately closes
- Second focus works correctly

### Expected Behavior
Menu is opened and not closed

### Actual Behavior
Menu is opened and immediately closed

### Reproduction Link
<a href="https://codepen.io/m-fitch/pen/vYpJwXJ" target="_blank">https://codepen.io/m-fitch/pen/vYpJwXJ</a>

**Comment by guillaumeduhan** [comment]
Hello @reynard80,
Can you explain what you want to do with this double intrication?
Indeed, menu is immediately closing by clicking v-text-field. You could use instead of focusin, click and apply true to showMenu.

`@click="showMenu = true"`

Otherwise, if you are trying to use an autocomplete, please use [https://vuetifyjs.com/en/components/autocompletes](this component.)

Best!
