### ISSUE TITLE
[Bug Report][2.6.4] Open all for v-treeview not working after load the items asyncronously 

### ISSUE THREAD

**Issue by pedro-gilmora** [vuetifyjs/vuetify#15016]
### Environment

|Info|Value|
|--|--|
|**Vuetify Version:**| 2.6.4 |
| **Vue Version:** | 2.6.14 |
| **Browsers:**  | Edge 96.0.1054.41 |
| **OS:** | Windows 11 |

**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Edge 96.0.1054.41
**OS:** Windows 10

### Steps to reproduce
Create an async method to update `VTreeview.items` property. `VTreeview.openAll` properties is set to `true

### Expected Behavior
Open all nodes after being loaded asyncronously 

### Actual Behavior
All nodes are still collapsed after `items` property is set asyncronously

### Reproduction Link
<a href="https://codepen.io/pedritin91/pen/JjpPWKz" target="_blank">https://codepen.io/pedritin91/pen/JjpPWKz</a>

**Comment by MajesticPotatoe** [comment]
`open-all` is only intended to fire when the component is mounted. You would need to fetch your data in `beforeMount` hook instead of `mounted` hook. Note it also only happens once (theres a FR for having it dynamically happen on added/removed items).

eg: https://codepen.io/majesticpotatoe-the-bashful/pen/LYQPdZQ

Also your reproduction is invalid.

**Comment by pedro-gilmora** [comment]
Sorry for late reply. Why is it wrong the reproduction? Also I updated it with `beforeMount` and neither

**Comment by MajesticPotatoe** [comment]
The reproduction was wrong because it initially didn't do anything (wasnt even functional, had to copy it all into a working template) Also didn't have any async properties to it. Looking at it more `beforeMount` would work if its not async. I doubt there is much we can do on our end to fix that (naturally the open FR i had mentioned would fix this).

Your best luck for the time being would be to load the data async in a parent component, and then mount the component once data is retrieved.

**Comment by pedro-gilmora** [comment]
The idea is wait 3 secs (simulating a fetch service) to set the items and then finish the loading. that's the desired

Also.. I reproduced your solution with the same behavior and neither... It didn't resolved my issue

you can check it here: https://codepen.io/pedritin91/pen/MWQgqMz

**Comment by MajesticPotatoe** [comment]
The codepen i attached in my last comment does essentially that: in mounted, waits 3 seconds, sets the data (and then follows the second suggestion which is to set the opened items via props), yours is missing that last part.

**Comment by pedro-gilmora** [comment]
I don't see what you're saying here 
https://codepen.io/majesticpotatoe-the-bashful/pen/LYQPdZQ

**Comment by MajesticPotatoe** [comment]
> Other option is to manually set open values via props once data is loaded eg: https://codepen.io/majesticpotatoe-the-bashful/pen/GRQKXaW

**Comment by pedro-gilmora** [comment]
that's odd... but ok... that's solved my problem... but my suggestion, it should behave like even after set the items property in a async context it should force to initially open all items... that way the property should make sense 100%

**Comment by MajesticPotatoe** [comment]
Which is why there are open FR for this eg: #9192 / #6113
