### ISSUE TITLE
inside a v-menu, a v-selector hidden behind the v-menu

### ISSUE THREAD

**Issue by xaayin** [vuetifyjs/vuetify#1502]
### Steps to reproduce
Inside a v-menu , a v-selector has z-index issue, the v-select is hidden behind the v-menu
### Versions

vue vesrion  0.14.11
### What is expected ?

v-select should be in front of v-menu
### What is actually happening ?

v-select is behind v-menu , both have same z-index value
### Reproduction Link

![screen shot 2017-08-28 at 2 35 20 pm](https://user-images.githubusercontent.com/7368402/29768101-6800921e-8bfe-11e7-9651-4859d50b3509.png)

**Comment by GadjiHunkere** [comment]
Yes, i have this problem too.

**Comment by Hunkere** [comment]
![v-select](https://user-images.githubusercontent.com/9562326/29763402-9e2e7da6-8bdb-11e7-8dc4-10018633ffa8.png)

**Comment by kvijay0007** [comment]
I am also facing the same problem.

**Comment by johnleider** [comment]
People are no doubt having issues, but we still need a reproduction. You can observe https://vuetifyjs.com/components/dialogs #5 and it is working as expected.

**Comment by jcczmetal** [comment]
Same problem!
![seleccion_022](https://user-images.githubusercontent.com/3679367/29783331-993e6946-8be5-11e7-83ed-af75788b8c5e.png)

**Comment by baroncurtin2** [comment]
When I had the css file linked in my index.html using the unpkg link, this was happening. However when I imported the css via webpack, it restored functionality to my menus/selects.

Try importing the css file from node_modules

**Comment by jcczmetal** [comment]
It works! Thanks @baroncurtin2

**Comment by johnleider** [comment]
Has anyone been able to reproduce this in a codepen?

**Comment by xaayin** [comment]
@johnleider i have reproduce the issue in code pen
[https://codepen.io/xaayin/pen/dzgaxG?editors=1000](url)

**Comment by johnleider** [comment]
That is unfortunately due to using the lazy prop. Because of that, the order in which the components are booted causes the detached content areas to line up in a way that makes the menu fall behind the dialog.

Here is an example of how to handle that, using the new **z-index** prop on ```v-menu``` https://codepen.io/anon/pen/eEPXYX?editors=1000

**Comment by xaayin** [comment]
@johnleider  thanks 😃

**Comment by kvijay0007** [comment]
Hello....

I am still facing the problem.  
Can you just brief me about the solution. My app is mostly dependent on v-menu and v-select and I am facing problem in both the components.

Please help me out

**Comment by johnleider** [comment]
Create a new issue

On Aug 30, 2017 2:51 AM, "kvijay0007" <notifications@github.com> wrote:

Hello....

I am still facing the problem.
Can you just brief me about the solution. My app is mostly dependent on
v-menu and v-select and I am facing problem in both the components.

Please help me out

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/vuetifyjs/vuetify/issues/1502#issuecomment-325899187>,
or mute the thread

**Comment by kvijay0007** [comment]
Hi @johnleider ..
Thanks for your reply.

I have rectified the problem.

**Comment by braday** [comment]
I have a similar issue on `<v-list>`
Here is the issue when I click the button, the sub-menu hidden behind.
![image](https://user-images.githubusercontent.com/11016500/36241724-19197522-126c-11e8-857c-ccccb6c70c62.png)
 I tried the above solution can't help.  Thanks for look at this issue in advance. vuetify version is 0.17.
