### ISSUE TITLE
[Bug Report][2.6.5] v-icon got a weird offset with lang="zh-*" on Firefox

### ISSUE THREAD

**Issue by zetaraku** [vuetifyjs/vuetify#15131]
### Environment
**Vuetify Version:** 2.6.5
**Vue Version:** 2.6.14
**Browsers:** Firefox 100.0
**OS:** Windows 10

### Steps to reproduce
Open the link with **Firefox**.
Change the lang to any language with the language code `zh`.

### Expected Behavior
The icon should display normally.

### Actual Behavior
The icon got a weird offset.

### Reproduction Link
<a href="https://codepen.io/zetaraku/pen/WNMOYeX" target="_blank">https://codepen.io/zetaraku/pen/WNMOYeX</a>

### Other comments
I've tested this on these browsers: Firefox, Chrome, and Edge.
**This behavior only appears on Firefox.**

**Comment by KaelWD** [comment]
It looks fine to me, got a screenshot? Do you have any browser extensions installed?

**Comment by zetaraku** [comment]
Here it is.

I just test on Firefox with a new profile and the problem still exists.

![Screenshot 2022-05-21 at 13-37-53 WNMOYeX](https://user-images.githubusercontent.com/9212875/169637349-62d3b2b4-9a52-4021-8f6e-648b07c25580.png)
![Screenshot 2022-05-21 at 13-38-06 WNMOYeX](https://user-images.githubusercontent.com/9212875/169637355-66b9f14b-d59c-4215-ad03-4a6d933fcf8c.png)

**Comment by KaelWD** [comment]
Firefox 100 on linux
![Screenshot_20220521_154431](https://user-images.githubusercontent.com/16421948/169637586-b9672098-0f6a-4a87-b3e2-8dd879a5995e.png)

**Comment by Ostabo** [comment]
![grafik](https://user-images.githubusercontent.com/34040518/219772997-e462bca5-012b-4300-8952-4cd0f1507164.png)
![grafik](https://user-images.githubusercontent.com/34040518/219773093-25404b11-2859-4a72-91f2-d235a8dbe9d6.png)
![grafik](https://user-images.githubusercontent.com/34040518/219775275-6edfca0c-f81a-43c9-9285-196df5424e34.png)
![grafik](https://user-images.githubusercontent.com/34040518/219775477-fb2c5317-2bae-419c-b71d-1b59f068bc87.png)


Firefox 110

For me the offset only happens when selecting [zh-Hant](https://www.wikidata.org/wiki/Q18130932) or [zh-TW ](https://en.wikipedia.org/wiki/Zh-TW)

**Comment by Ostabo** [comment]
I think this issue can be closed since it's a general [firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1280900)
see also [material-design-icons#956](https://github.com/google/material-design-icons/issues/956)
