### ISSUE TITLE
[Bug Report][2.6.6] Content overflows combobox when many items are selected

### ISSUE THREAD

**Issue by dcb99** [vuetifyjs/vuetify#15218]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.14
**Browsers:** Firefox 101.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Selecting many or all items in a long list of items causes content to overflow the combobox contianer. 

### Expected Behavior
Selected items remain inside the bounds of the combobox. Scrolling should happen automatically or display one or two items with some additional info text like, "Vuetify + 32 others selected"

### Actual Behavior
Content overflows combobx and ends up behind other elements

### Reproduction Link
<a href="https://codepen.io/dcb99/pen/OJQojee" target="_blank">https://codepen.io/dcb99/pen/OJQojee</a>

**Comment by lioneaglesolutions** [comment]
Closing as the overflow issue is fixed in V3.

You can use slots to change the rendering of the selected list if it's long

https://play.vuetifyjs.com/#eNqNVG1P2zAQ/iuW96EgkYTBpElRQbyJiYmujJZpE+kHt3FbD7/JdkMr1P/OxQltHCrBB0Tvec53zz296+MLPtc6LhYUp7jrqNCcOHqaSYS6RTQhJkfPLHfzkwwfHx7qZYY9V7FKOsIkNWjKFyyvCU8Z9bwJ61yO4M9Cna9HmyINWozVWC2bMEJFJFROObwpCF/QDId0ykBvWdH/b7M5lZa5FdBQXJOJaydwMva1L3fTYsEd05w20dNustXaHNDDfOsAxFsLKrb2qrK2RMBbCLpJw/SunRimnc+hS62MgzGmBJSgl6pWThxJ0d4+OjlFezWGkDcgRY9bRZ07o2aGCMHkrHPQwK+oZTMZQH8WtB07Nl0FWA8EGkY42vH+4SZ5+Bsgl1+C8CcpyMBPFsDDlaY7YNhHHgr6odSsBfUG18MAGPy+DROUnKmrcYDdKetmhtoA7BsyaRW/uegF8T8yV6rlItdzFkC3zOqwGzU8lCgI547wp9Cr/kU/lH7dvx/en/8KGzI7UZ03YLSh/GGkqDPdClzv+w/rcrfqfcIHmDP5ZOP/Vkk4dL84cBgWrmazNhmeO6dtmiSTXEImXB4rTCypS6QWCfxElFtxdhwfxUdJzqx7gyK4JBv7YmWlUSbX0JCJcn8jQXSra0X4zvUCw32X151+JOEM0hKzkI4JGuVKeC3fvldiGnhMrYjGcICWGqiS4doZ36dU/IleH40LLd6VTqBfQU1kqMypoeazI7WeBWO1uHej1V/1Gq8PcPUOvPei8egVdj6x9A==

**Comment by dcb99** [comment]
> Closing as the overflow issue is fixed in V3.
> 
> You can use slots to change the rendering of the selected list if it's long
> 
> https://play.vuetifyjs.com/#eNqNVG1P2zAQ/iuW96EgkYTBpElRQbyJiYmujJZpE+kHt3FbD7/JdkMr1P/OxQltHCrBB0Tvec53zz296+MLPtc6LhYUp7jrqNCcOHqaSYS6RTQhJkfPLHfzkwwfHx7qZYY9V7FKOsIkNWjKFyyvCU8Z9bwJ61yO4M9Cna9HmyINWozVWC2bMEJFJFROObwpCF/QDId0ykBvWdH/b7M5lZa5FdBQXJOJaydwMva1L3fTYsEd05w20dNustXaHNDDfOsAxFsLKrb2qrK2RMBbCLpJw/SunRimnc+hS62MgzGmBJSgl6pWThxJ0d4+OjlFezWGkDcgRY9bRZ07o2aGCMHkrHPQwK+oZTMZQH8WtB07Nl0FWA8EGkY42vH+4SZ5+Bsgl1+C8CcpyMBPFsDDlaY7YNhHHgr6odSsBfUG18MAGPy+DROUnKmrcYDdKetmhtoA7BsyaRW/uegF8T8yV6rlItdzFkC3zOqwGzU8lCgI547wp9Cr/kU/lH7dvx/en/8KGzI7UZ03YLSh/GGkqDPdClzv+w/rcrfqfcIHmDP5ZOP/Vkk4dL84cBgWrmazNhmeO6dtmiSTXEImXB4rTCypS6QWCfxElFtxdhwfxUdJzqx7gyK4JBv7YmWlUSbX0JCJcn8jQXSra0X4zvUCw32X151+JOEM0hKzkI4JGuVKeC3fvldiGnhMrYjGcICWGqiS4doZ36dU/IleH40LLd6VTqBfQU1kqMypoeazI7WeBWO1uHej1V/1Gq8PcPUOvPei8egVdj6x9A==

This is a really disappointing resolution. I can't use Vuetify 3 because it doesn't have feature parity with Vuetify 2. This is why I've had to abandon Vuetify in most of my apps, which is a shame, as it's generally a great product. 👎
