### ISSUE TITLE
Expansion panel color classes no longer work

### ISSUE THREAD

**Issue by shongololo** [vuetifyjs/vuetify#1530]
### Versions
Vuetify 0.15.0

### What is expected ?
In prior versions it used to be possible to override the color of the expansion panel, e.g. with primary or accent colors, or a custom class using a background-color.

### What is actually happening ?
It is now only possible to have a white or dark grey background depending on whether light or dark mode is selected.

Overriding the color now requires setting the color classes for the panel-content items individually, or overloading the `expansion-panel__container` CSS class to negate the color set internally by the expansion-panel component, e.g.:
```
    .expansion-panel__container {
        background-color: rgba(0, 0, 0, 0) !important;
    }
```
### Reproduction Link
https://codepen.io/shongololo/pen/Jyegob

**Comment by nekosaur** [comment]
The reason it no longer works as before is because the `expansion-panel` got light/dark theme support in 0.15.0-beta.1, which means that we now explicitly set the background color of the header.

I have a hard time thinking of a solution to this, and I think I'm fine with applying colors to each `expansion-panel-content`.

Any ideas? Otherwise I'm inclined to close this as a wontfix

**Comment by johnleider** [comment]
This is not something that was ever officially supported and no longer will work due to adding theme capabilities.
