### ISSUE TITLE
[Bug Report][2.6.6] When a v-dialog has the fullscreen and scrollable props set with a nested v-toolbar, the v-toolbar height gets stretched

### ISSUE THREAD

**Issue by richbowen** [vuetifyjs/vuetify#15362]
### Environment
**Vuetify Version:** 2.6.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 103.0.5060.53
**OS:** Linux x86_64

### Steps to reproduce
Create a `v-dialog` that has both the`fullscreen` and `scrollable` props set, then add a `v-toolbar` to it in place of `v-card-title`.

### Expected Behavior
The toolbar height should display normally without being stretched.

### Actual Behavior
The toolbar gets stretched beyond it's default height

### Reproduction Link
<a href="https://codepen.io/rgb-one/pen/dymPayv" target="_blank">https://codepen.io/rgb-one/pen/dymPayv</a>

**Comment by MartinX3** [comment]
I can confirm it with vuetify 2.6.7.

If I display enough elements for the scrollbar to render, everything is fine.
But if I don't have enough elements, then the toolbar will be stretched.

**Comment by erthi16** [comment]
The bug is caused by a **missing style** applied to the **v-card-title** if dialog in fullscreen but lacking for the v-toolbar!
The missing style is: **flex: 0 0 auto;**

I've made **2 CodePen** to illustrate the bug:

1. **no bug** because v-card-title direct child of v-card inside fullscreen v-dialog: https://codepen.io/-ric-thibault/pen/KKeXyKZ?editors=1010
2. **with bug** because v-toolbar direct child ov v-card indise fullscreen v-dialog: https://codepen.io/-ric-thibault/pen/VwdMbyN?editors=1010

If you apply the missing style  with the button "Apply styles" in the v-dialog header of the second CodePen, the bug disapears.
