### ISSUE TITLE
[Feature Request] v-snackbar app

### ISSUE THREAD

**Issue by qxygene** [vuetifyjs/vuetify#15744]
### Problem to solve
Respects boundaries of—and will not overlap with—other app components like v-app-bar, v-navigation-drawer, and v-footer.

https://vuetifyjs.com/en/api/v-snackbar/#props-app

### Proposed solution
v3 doesnt have this.

**Comment by mcfarljw** [comment]
I'm running in to this issue as well with bottom navigation. I think this is more of a bug or regression rather than feature. Here is a reproduction link:

https://play.vuetifyjs.com/#eNqVVE2L2zAQ/SuqL97C2i79OoRkSSmUnlpoS3tY70GxxxvVsmQkOd0Q/N87kmyv4nzAGgIZzei9mSfp3R+iXQeGVfv0r44WEWtaqQw5kEIBNfDb50hPKiUbEg+1cS5yAU+utJBCGzIkyOp4480hF4SYLTSwQNASKtpx88vHcUlVHZP+Nhf961xEt9Gntk0RCftYGmhajkB3FmC5S2jbur8uaCgTQ+TijcF+fETIuuCsqFd5pAUt6g1V2JRRHeTRWDNtJeR7C4L8HAonxMxBTmUB04j5jIDdyBJ4wHeW6HAgBp4M6Xur3bg6jYkwmkuzoIVhKGiw8XRA+xWSS4WcLRP1M9/QEVWMCoNZyzjPnpOnolwH+sxat99nLrEibGqmkV05OrOxaKQ5p+ZGGiObRNAde6R28BDO4eMwvAPsVkEBAoeZK8Pw/t01JUu2TBup9pbSrYUyE/LDbw+aHdu/yFjRnVTMgL5GClSZC5Rfpv0vYRWIuNlfoWxoiz9Vg7rA+80jnCEN4gvC29z0uGzgn93R0WKoC8VaQzSYzqYn01BQhVbhbML7g7v7K1twE38FziX5IxUvX8X48H1FcB1tlbuSmFxmngxp0CA8k9UA7UoKNApnMPmQwKNCm/Gj5NbYbJxHW2NavciyTrT1Y1rIJltjLlOdMKyBpJTN+l36Nn3/ISvxEoXrKegm2Sj5T4NCxjxCr5rArcFdIhjSiPsm/ehhR59FyBOoDPF3oBIFogQFaCFX+p7VHvU+y530bznRgXrUkqN16JmMhXYS3j/Ykv428tBY7OaIHv4DO3fouQ==
