### ISSUE TITLE
[Bug Report][3.0.0-beta.13] v-btn flat and variant="flat" have different behaviour

### ISSUE THREAD

**Issue by stratdev3** [vuetifyjs/vuetify#15860]
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Vue Version:** 3.2.40
**Browsers:** Firefox 105.0
**OS:** Windows 10

### Steps to reproduce
use the link to see the issue

### Expected Behavior
flat and variant="flat" should render the same in a <v-card-actions>

### Actual Behavior
- flat is render as text instead of flat
- variant="flat" is correctly render

### Reproduction Link
<a href="https://codepen.io/cp10/pen/jOxQbPE?editors=1010" target="_blank">https://codepen.io/cp10/pen/jOxQbPE?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment]
`<VCardActions>` provides default `variant` prop for `VBtn`, not sure if that's intended, imho it shouldn't be there

https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VCard/VCardActions.tsx#L13

**Comment by nekosaur** [comment]
It's intended, talk to @johnleider :>

**Comment by KaelWD** [comment]
Not sure why `flat` was kept. There seems to be three separate ways this is modified instead of just using the variant system:
 - `variant="elevated"` - applies both `v-btn--elevated` (hover/active shadow) and `v-btn--variant-elevated` (base shadow)
 - `variant="flat"` - applies `v-btn--variant-elevated` which has no shadow, and removes `v-btn--elevated`
 - `flat` - replaces `v-btn--elevated` with `v-btn--flat` which overrides shadow to `none`
 - `elevation="0"` - applies `elevation-0` which overrides shadow to `none`

**Comment by stratdev3** [comment]
Agree. Same problem in other components where `flat` flag was kept or maybe not deleted since v3 rewrite.

I prefer the new variant syntax.

**Comment by johnleider** [comment]
The flat flag was used / intended for components that did not support variants but had a default elevation.

**Comment by stratdev3** [comment]
What about adding a note in the documentation ? to clarify flat != variant flat
