### ISSUE TITLE
[Bug Report][3.0.0-beta.13] vuetify 3 v-select @change does not fire

### ISSUE THREAD

**Issue by cookiejest** [vuetifyjs/vuetify#15881]
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Vue Version:** 3.2.39
**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Select a value in v-select in the helloworld.vue component. It should fire the function.

### Expected Behavior
Should output to console log a message when value is changed.

### Actual Behavior
No function is fired.

### Reproduction Link
<a href="https://codesandbox.io/s/vue?file=/src/main.js" target="_blank">https://codesandbox.io/s/vue?file=/src/main.js</a>

**Comment by KaelWD** [comment]
`@update:modelValue`

**Comment by vciloglu** [comment]
Hello,

While the update:modelValue feature is useful, having an @change event would be more beneficial. For example, when using the v-select component, I need the v-model to update as a string, but also need to perform separate actions with the selected option's text or value. The update:modelValue alone does not facilitate this. When I use return-object, the v-model becomes an object instead of a string, which complicates what I'm trying to achieve.
