### ISSUE TITLE
[Bug Report][2.6.12] index.ts:163 Uncaught TypeError: el.hasAttribute is not a function 

### ISSUE THREAD

**Issue by lukicenturi** [vuetifyjs/vuetify#15977]
### Environment
**Vuetify Version:** 2.6.12
**Vue Version:** 2.7.10
**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
I got this error
```
index.ts:163 Uncaught TypeError: el.hasAttribute is not a function
    at VueComponent.shouldScroll (index.ts:163:14)
    at VueComponent.shouldScroll (index.ts:184:21)
    at VueComponent.shouldScroll (index.ts:184:21)
    at VueComponent.checkPath (index.ts:218:60)
    at VueComponent.scrollListener (index.ts:153:14)
```

when trying to scroll on `<v-dialog>` overlay.

### Expected Behavior
It should not show that error.

### Actual Behavior
It show error, that shoul be removed

### Reproduction Link
[https://github.com/rotki/rotki](https://github.com/rotki/rotki)

**Comment by Vitomir2** [comment]
Hi,

I am also facing this issue when I have more elements in my v-dialog and the scrollbar appears. It happens when you are at the top or the bottom of the dialog and keep scrolling (overscrolling).

**Comment by noah-lackey** [comment]
Fix doesn't work. This happens when the scroll event target is outside of the v-app. el.parentNode is always defined for every element in the DOM, so the new check does nothing. The issue is that we arrive to the top of the tree before finding v-app. When at the top of the tree, el.parentNode returns a Document, not an Element, which does not support hasAttribute. Would be best to use el.parentElement instead, guaranteeing an element or null, meaning the new check prevents going too high in the tree, and removing the cast to Element.

**Comment by mwilk-dev** [comment]
Changing

` if ((alreadyAtStart || alreadyAtEnd) && el.parentNode) {`

to

`if ((alreadyAtStart || alreadyAtEnd) && el.parentNode && !(el.parentNode instanceof Document)) {`

helped me (the Uncaught TypeError was triggered when scrolling through a tabulator.js select in a v-dialog)
