### ISSUE TITLE
[Bug Report][3.0.1] `v-card` title not visible when you use prepend or append slot in small screen

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#16087]
### Environment
**Vuetify Version:** 3.0.1
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to use the append/prepend slot with the title

### Expected Behavior
It should fall down when there is no space.

### Actual Behavior
Title get hide 

### Reproduction Link
[https://codepen.io/Alokdev/pen/JjZJrYx?editors=1010](https://codepen.io/Alokdev/pen/JjZJrYx?editors=1010)

![image](https://user-images.githubusercontent.com/80033712/201634437-83a643ab-7405-48b3-990d-f0947869beaa.png)

**Comment by lioneaglesolutions** [comment]
Card titles are `text-overflow: ellipsis;` by default, regardless of if a slot is present or not. This looks to be expected behaviour - as seen below with a card, no slots but a long title;
![image](https://user-images.githubusercontent.com/61766491/235818380-d5c1b439-cb3a-474e-97d9-68a1fc3e80b4.png)

@johnleider
