### ISSUE TITLE
[Bug Report][3.0.3] VSelect item-title function gets inconsistent arguments

### ISSUE THREAD

**Issue by magyarb** [vuetifyjs/vuetify#16210]
### Environment
**Vuetify Version:** 3.0.3
**Last working version:** 2.6.12
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10

### Steps to reproduce
```vue
<template>
  <v-select
    :items="values"
    :item-title="(item) => 'Item: ' + JSON.stringify(item)"
    item-value="id"
  />
</template>
<script setup lang="ts">
const values = [
  { id: 1, name: 'a' },
  { id: 2, name: 'b' },
];
</script>
```
Try selecting a value.
![image](https://user-images.githubusercontent.com/10029157/205359359-ce0c136b-2b49-439a-8785-272f80b44a8e.png)

### Expected Behavior
The item-title function should always get the whole selected object as an argument.

### Actual Behavior
The item-title function gets only the value of the key specified by item-value as an argument, but only for the selected value.

### Reproduction Link
[https://stackblitz.com/edit/node-nykzap?file=pages/index.vue](https://stackblitz.com/edit/node-nykzap?file=pages/index.vue)

**Comment by magyarb** [comment]
It works with v-model. Sorry for that.

**Comment by magyarb** [comment]
Tried looking into the code, the solution is somewhere around `useProxiedModel` `transformIn` `transformOut`, but it gets too complicated for me: console.logging the `item.value` in `VSelect`'s `select` function logs the correct value, but it gets transformed later. So when changing line 181 from `model.value = [item]` to  `model.value = [item.value]`, the value is somehow undefined.

But there is a workaround:

```vue
<template>
  <v-select
    v-model="selected"
    :items="
      values.map((val) => (val.title = 'Item: ' + JSON.stringify(val.name)))
    "
    item-title="title"
    item-value="id"
  />
</template>

<script setup lang="ts">
const values = [
  { id: 1, name: 'a' },
  { id: 2, name: 'b' },
];
const selected = ref(null);
</script>

```

**Comment by DSergiu** [comment]
I can confirm the issue. Still present in `3.0.4`.

**Comment by KaelWD** [comment]
Yep, when you select an item the external value `1` is transformed to 
```js
{
  title: 'Item: 1',
  value: 'Item: 1',
  props: { title: 'Item: 1', value: 'Item: 1' },
  raw: 1
}
```
in `model.value`. `selections` then matches `value` in there against `item.value` to find selected items. 

This is definitely a bug but I'm not really sure how to fix it without breaking anything else.

- Can't change [the value fallback](https://github.com/vuetifyjs/vuetify/blob/dcc1fccea0c154ee6cb3a551b15adc13b7ba8783/packages/vuetify/src/composables/items.ts#L57) from `title` to `item` because you'd get unexpected results if items don't have values provided.
- Can't not run `itemTitle` and `itemProps` on modelValue because they're both needed to match values with transformed items.
- Can't revert 917284f55a4d150a6b8891a94126e0ab75117b69 because then `itemProps` won't work with string items.

---

Kinda crappy workaround but you can return undefined from itemTitle if it's a bare value, forcing the fallback to be used:
```js
(item) => typeof item === 'number' ? undefined : 'Item: ' + JSON.stringify(item)"
```
Or use `return-object`, which will result in the same transform behaviour for both modelValue and items.
