### ISSUE TITLE
The align-end does not work

### ISSUE THREAD

**Issue by dxcqcv** [vuetifyjs/vuetify#1623]
### Steps to reproduce
add align-end on v-flex
### Versions
 "vue": "2.4.2",Vuetify 0.14.8, window 7, chrome

### What is expected ?
button at the right side, no gap

### What is actually happening ?
the button has gap from right side, align-end does not work

### Reproduction Link
https://codepen.io/dxcqcv/pen/RZOqWE

**Comment by johnleider** [comment]
align-end when using a flex direction of row (default) changes the y axis, justify-end seems like what you are looking for.

However, due to flex not actually being a flexbox in current version (doesn't make sense huh) won't allow this to happen. I have already resolved this in dev with the updated grid system.
