### ISSUE TITLE
[Bug Report][3.0.4] v-btn background not transparent

### ISSUE THREAD

**Issue by flahol** [vuetifyjs/vuetify#16266]
### Environment
**Vuetify Version:** 3.0.4
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
In  a `<v-app-bar color="blue">` the icon `<v-app-bar-nav-icon>` has a white backgound.
It used to be transparent

### Expected Behavior
icon `<v-app-bar-nav-icon>` with a transparent background

### Actual Behavior
icon `<v-app-bar-nav-icon>` has a white  background

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9kctOwzAQRX/FeFOQmhhB2URpVXb8AYu6izSZFFO/ZDsBVOXfmTwa0hbIKnPv9RnPeHOkz9bGdQU0oanPnbCBeAiVXXEtlDUukCNxUJKGlM4oMsPojGuuc6N9IMrvybL1b2cvIKUhr8bJ4mZ2x3XKehyCsAigrMwCYEVIWkeZbTsQ/LBQmdBD1dUBPkNUCpAFQdMUIJecYitOCZvmEBLtMkdyI43DyE5WwOlP4tQUKV6akFgHFnQxBqaQSGd1JHCqVcp+EUcmO5ukl8b8aSRUxpkGG//PztI57feLSRu/e6PxBY7tAT4YntOEdEqr4d7bmtO3EKxPGKu0Pezj3Ci2Ro+5SgehICqMWj/GD/HiiRXCh6keg1fRzpkPDw47cjqfwIMov/5qMNjIvY8XPXaQWuQViiG/Bhc53DU4cP/e+yJ7dvcL7+r+bc+G6wZ3KYU++Is15r5b4WbbRpo57dEY7uag228n2vqB)

**Comment by jacekkarczmarczyk** [comment]
Already fixed in https://github.com/vuetifyjs/vuetify/commit/41111a7d3ad529aaf8d044c9ff4ea60d8b632359
https://play.vuetifyjs.com/#eNp9UctuwjAQ/BXXF1oJx5SWCwJEb/2DHjCHkCzg4pdshxYh/r1rAml4iOTinRnPaNazPf1wLttWQId0FAovXSQBYuUmwkjtrI9kTzwsyYEsvdWkg9KOMMIU1oRIdFiRceKfO5+glCVf1qvyqfMizIjXdmiEQwTtVB4BJ0JGW5a7lEDww0Hn0pym4xzhN7KlBFUSJG0JaiwoRglKeFuHJmyRe1JYZT1KFqoCQf8V51B0CcrGofPgwJSNoG3CTL5lEltNRvwO2HjyiyY11OjPlRBpOp1oPF/cpV1a7xeVLvsO1uAL7NMFcSKCoENyRBKGe0+zoOsYXRhyXhm3WWWF1XyKHPeViVIDK62evmX97H3ASxliG88gaLbw9ieAx0RBuy3zKJe7RwGJ50au1lHtMKCXDZhJz9Tv9fuv+Ge9Ou8kTVk3GRyDt+CZx0cAD/5hoSvtRakr7qZYyjwIc8AlK2k24Wq/RTjudjZPkkOX1tYovtuLzv8AsNMGBg==
