### ISSUE TITLE
[Bug Report][3.0.6] Vuetify does not pass the data-* attributes from components to the relevant HTML elements

### ISSUE THREAD

**Issue by omakhalin** [vuetifyjs/vuetify#16276]
### Environment
**Vuetify Version:** 3.0.6
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
- add the data-* attribute to the `<v-text-field/>`
- observe data-* attribute on `<div class="v-input" ...>`

### Expected Behavior
Vuetify ***passes*** the data-* attributes from components to the relevant HTML elements
as described here
https://next.vuetifyjs.com/en/getting-started/unit-testing/#e2e-tests

### Actual Behavior
Vuetify ***does not*** pass the data-* attributes from components to the relevant HTML elements/

### Reproduction Link
[https://codesandbox.io/s/vuetify-data-attr-5rt3qd](https://codesandbox.io/s/vuetify-data-attr-5rt3qd)

**Comment by omakhalin** [comment]
Same issue appears for other form components. Like v-autoselect, v-checkbox for sure

**Comment by tobi-fis** [comment]
I can confirm this for `v-button` and other components, too.
This is breaking most of my unit tests as the element selectors don't work anymore. 
Guess I have to resort to using classnames as a workaround instead, but I hope this gets fixed soon.

**Comment by KaelWD** [comment]
This was an intentional change: #7295
Applying the attributes to the root element means you can select anything inside with a compound selector, whereas before you had to use xpath to traverse back up the tree. 

@tobi-fis v-button isn't a vuetify component. If you mean v-btn it seems to be working correctly for me, if you can reproduce the problem please open a new issue.
