### ISSUE TITLE
V-Select doesn't display chips without multiple prop

### ISSUE THREAD

**Issue by ashireman** [vuetifyjs/vuetify#1628]
### Steps to reproduce
Create a v-select as provided in the examples and remove the 'multiple' prop.

### Versions
0.15.2 -> Affected
0.14.X -> Unaffected

### What is expected ?
A v-select using chips without the multiple prop should still render the chip and all markup in the selection slot.

### What is actually happening ?
The v-select without the 'multiple' prop seems to ignore the selection slot markup.

### Reproduction Link
https://codepen.io/anon/pen/VzJKOv

### Working Link (0.14.11)
https://codepen.io/anon/pen/aygBOe

**Comment by johnleider** [comment]
The problem with this will only occur when you are using a single select with autocomplete. Unfortunately, this will no longer be possible due to the newly created structure to support all of the functionality expected to come with autocomplete.

I tested a few tweaks to make it work, but ultimately, they all felt like hacks and I am not going to include them. I'm sorry for the inconvenience.

**Comment by johnleider** [comment]
Reverting my opinion, this should work, and in fact, it now does again! Coming with 0.15.3

**Comment by MTandi** [comment]
This bug is reproduced in 0.15.7.

**Comment by LouisMazel** [comment]
This bug is alway here in 0.17.0-beta.1. Can you re-open this issue ?

**Comment by KaelWD** [comment]
@LouisMazel This issue is closed. Create a new one **with reproduction** if you are still experiencing this.
