### ISSUE TITLE
[Bug Report][3.0.6] v-chip on vuetify 3 doe not have 100% opacity

### ISSUE THREAD

**Issue by ninjapanda47** [vuetifyjs/vuetify#16354]
### Environment
**Vuetify Version:** 3.0.6
**Last working version:** 2.6.13
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Use the v-chip component and the color is not opaque/solid and there doesn't seem to be a way to make it opaque/solid

### Expected Behavior
The chip color to be opaque/solid

### Actual Behavior
The chip color is not opaque/solid

### Reproduction Link
[https://github.com/ninjapanda47/app-log/blob/main/src/views/StatusChip.vue](https://github.com/ninjapanda47/app-log/blob/main/src/views/StatusChip.vue)

### Other comments
This also on the official vuetify 3 documentation.
https://vuetifyjs.com/en/components/chips/ ( Vuetify 2 the chip color is solid/opaque)
https://next.vuetifyjs.com/en/components/chips/ (Vuetify 3 the chip color is transparent)

**Comment by lioneaglesolutions** [comment]
### Missing Reproduction

You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

- [[Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)](https://vuetifyjs.com/getting-started/contributing/)
- [[Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
- [[Codepen](https://template.vuetifyjs.com/)](https://template.vuetifyjs.com/)
- [[Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)](https://codepen.io/zikeji/pen/ypeQNm)
- A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/api/v-chip/#props-variant
