### ISSUE TITLE
[Bug Report][3.1.0] Impossible to set text-color for v-chip

### ISSUE THREAD

**Issue by mediafreakch** [vuetifyjs/vuetify#16386]
### Environment
**Vuetify Version:** 3.1.0
**Last working version:** 2.6.12
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Open playground example above

### Expected Behavior
Text on v-chip appears in white

### Actual Behavior
Text on v-chip is invisible

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9kM1OwzAQhF/F+BKQmpjfSxVQufEGHJoeQrJtTeMfeTctqMq7s04CLS3i5tkZfTve+V4+e59tW5BTmRMY35QET4UVIt+mpff9sxem1HZUva7W2ovKNS48FtIHbcrwWchDAn1pRdWUiOwTfFC6W2sCjhAg5Sr6h7QagN/rWP7si2JokqujhiyxCtqTQKA22tp4F0jsRYCl6MQyOCMS/loSw5WzSMLgSjxG/zJ5gaZx4tWFpr5IriJ8wDFITuTA4hI+e0dn+Tr72KUYDSzkVPSTOOMdURdyTeRxqlRr/WaVVc6oGXsqtJa0gbR2ZnaX3Wb3D6rWSMfzDNCkb8HtEAJvLOTkCE56yaf9e8FoM/cmux6w4ygiz1CK+VsIaQBbQ4Dwb++T7K/uJ95Z/7izK2zHt2y03eDJGSvsTzhfxEg3kQOaw/0/5OILBsTcRw==)

### Other comments
`v-chip` in vuetify 2 used to have a text-color prop, like `v-badge` still does. I wouldn't mind if the API is actually the same everywhere, no matter the type (`v-chip`, `v-badge`, `v-tooltip`, ...?)

**Comment by mediafreakch** [comment]
A workaround is to use css classes for both background and text, instead of the `color` prop:   
`<v-chip class="text-white bg-primary">chip</v-chip>`.  
[Here's an example](https://play.vuetifyjs.com/#eNp9kMtywjAMRX9F9YZ2hsR9bhjaobv+QReYRUgEuMSPsRRoh8m/105ShkKnO19d+ehK84N49T7fNSgmYspofF0wvigLMN1lhffdsxOm0HZQnS432kNZF0TPSjB+crbfaEZYrjMftCnClxLHfgBG4uNv2X//gUd5pCfRz53KkzxRUhm0ZyDkJtnaeBcYDhBwBS2sgjMwiouMUnPpLDEYWsNz8q9Hb1jXDt5dqKur0U2C97gIEmPRs2IIn3+Qs/EWh5RFDQYpMYGukmpxRtJKbJg9TaRsrN+u89IZOYueDI1lbTCrnJk95Pf545OsNPFpPUcy2TK4PWGIE5UYn8BZr+Lp/h4w2JF7l9/22KGUkBcoGfk7DFlAW2HA8G/us95f2c+8i/xpZqtsG29Za7ulszOW1J1wvkgt7Vj06Njc7SEW32yc1Z4=)

**Comment by lioneaglesolutions** [comment]
This is because the default style of `tonal` places the chip underlay over the top of the next. The white text is indeed there in your repro, but the style of the default `tonal` chip makes it hard to see. 

If you check it with `text-secondary`, you can see this more clearly;
https://play.vuetifyjs.com/#eNqlkMtOwzAQRX/FeBOQmljisalSVHb8AYumi9SZtqZ+yeMEUJV/x3ZSGlqJDTvfmet7ZmZ1pC/WFl0LdE5LD8rK2sNzpQkpu7y2Nj2TULXQo0qa74Ul3EjjFhW1TqjafVX07EBba8JljRj6Hj59jsCNbgabB/Qli57zDzaEnpBB/jCjGKYp2WTKIJE7YT1B8G1sC2WN8+RIHGxJT7bOKJKF9bJoDnj0ROGOLGL/NnsFKQ15M042N9ldDB/iQhCd0SErDGGLdzQ6XOgYZ6nGBlZ0TlIl1gIj6oruvbc4Z6zV9rAruFFsGXrMtdoLBXlj1PKhuC8en1gj0E/rBaDKN858ILhArOhsEu7FNtxtCuCNDq4GpOhcocEzbRUbnQlxPxDGUi7rDUbEVTQLvA5c7kA34MD9uceF99cuF72rfSKzr3QfbiuFPuDFWTmmk65Oo/1r0RQWk9YR2M/oMGhApx90/Q0Wq/6I

I believe this is the desired appearance/behaviour.

@johnleider

**Comment by johnleider** [comment]
For whatever reason, the CSS color utilities aren't present. Maybe something @KaelWD or @nekosaur could speak to. With that being said, this works as expected in an application:

![image](https://user-images.githubusercontent.com/9064066/235798181-77415547-41f9-4847-a7f8-ad5e762cb5e6.png)

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
