### ISSUE TITLE
[Feature Request] Remove opacity for VListItemSubtitle

### ISSUE THREAD

**Issue by llamington** [vuetifyjs/vuetify#16446]
### Problem to solve
VListItemSubtitle currently uses the opacity CSS property. All child elements inherit this opacity, however the Material Design docs allows for [black subtitles](https://m2.material.io/components/lists#anatomy). This is currently impossible in Vuetify 3, as black is not attainable with an inherited opacity of 60%.

### Proposed solution
Use the RGBA CSS function instead of the opacity property

**Comment by johnleider** [comment]
This is what we did with VCard but specifically for it's text, which by default should have lower opacity. Using opacity allows the element to inherit its color and achieve the same reduced opacity with any color.

I'd like to solve this one by adding some new opacity css classes so that you can get around this by doing `<v-list-item-subtitle class="opacity-100" />`.

**Comment by HendrikJan** [comment]
Currently you can do:
```html
<style scoped lang="scss">
  :deep(.v-list-item-subtitle) {  opacity: 1;  }
</style>
```
