### ISSUE TITLE
[Bug Report][3.1.2] Potential v-tabs color regression

### ISSUE THREAD

**Issue by drhouse82** [vuetifyjs/vuetify#16478]
### Environment
**Vuetify Version:** 3.1.2
**Last working version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Firefox 108.0
**OS:** Windows 10

### Steps to reproduce
set color attribute for v-tabs

### Expected Behavior
Setting a color attribute for v-tabs used to set this color for the slider and the selected text.

Here is a link with vuetify 3.1.1 for comparison.
https://codepen.io/drhouse82/pen/jOpavoB

### Actual Behavior
The color is not used at all.
(see reproduction link above)

### Reproduction Link
[https://codepen.io/drhouse82/pen/ZEjaMdv](https://codepen.io/drhouse82/pen/ZEjaMdv)

### Other comments
Note: attributes slider-color and bg-color still work.

**Comment by sebastienbredard** [comment]
It's like the CSS class v-tab--selected is missing somewhere...
Adding it in the style tag does the job:

`.v-tab--selected {
  color: #ff7900;
}`

**Comment by KaelWD** [comment]
Combination of #15897 and 578fd0bc. There doesn't seem to be any way to disable the active overlay now if I revert 578fd0bc.

**Comment by johnleider** [comment]
I've been toying around with this one and the issue lies with the logic we use to determine if something has support for color. This change worked the best in all scenarios that I tested:

```ts
const hasColor = (
  (group?.isSelected.value && (!link.isLink.value || link.isActive?.value)) ||
  (!group && link.isActive?.value)
)
```

1. If an item is selected from a group and is not a link
2. If an item is selected from a group and is a link and is linkActive
3. If an item is not in a group and is linkActive

Tab sets active to false which removes the active state, but it still needs the ability to apply color from being selected in a group.  This worked before because hasColor wasn't influenced by the active state. 

It's worth noting that even with the above change, we don't have a way to have the group model change when the route changes from a currently active item that is also itself a router link.

This also might be a good candidate for an **active-variant** prop and get away from using the overlay/underlay stylistically.
