### ISSUE TITLE
[Bug Report][3.1.2] item-title function not work when item is array and return-object in v-autocomplete

### ISSUE THREAD

**Issue by nella17** [vuetifyjs/vuetify#16494]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Edge 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create v-autocomplete, give props
- return-object
- items: array of array
- item-title: function
Select item is array.

### Expected Behavior
item-title function should received same args when item selected.

### Actual Behavior
item-title received different args when selected item is array, and function call twice.

### Reproduction Link
[https://codepen.io/nella17/pen/gOjvwOz?editors=1011](https://codepen.io/nella17/pen/gOjvwOz?editors=1011)

**Comment by nella17** [comment]
May related to #16210

**Comment by yuwu9145** [comment]
Thanks, this issue is not related to #16210, it should be an new independent issue or improvement:

- function called twice when make a selection
- args are different between these two calls.

Here is a simplified reproduction [link](https://play.vuetifyjs.com/#eNqdUr1OMzEQfJWVm3yfyPkISBRHQFBCAQUll8K52wSD/2TvBaEo7876LkAIPwWlZ3Zndka+X4vLEOSqQ1GJKaENRhGe1w5guioSGmwoPwAqzWw6q8VKmQ5TLXbggjQZZI6icmnho32je7bfYFa3A1yy/rTcMZumJupAkJC6AEa5ZdZiD+Ya7xLBYApncJ8F1qDbCiZjcMpiBSM1gs34gzh6J+YDMTut3aJzDWnv4P3Gf/m4/7DOi9nFG5TGLwc4g5HPiQ5GVwywGBzA9d3tjUwUtVvqxcvb5CbHGSKci7HQNvhIhVVBPibvuNjegvP3BMeqBtOMcfP5XYsHopCqsuxceFrKxtvygrkydo60xaL19uJYHsvDQpnwoORJ2epEu7TEZIt59M8JIxvXom9k60F87k8+W5rlJ3JyNOhuscKoecrCXwRLdllhLCK6FiPGX0PszX4XZG/kS5hszT1vuF+j3VPaq7ZJfa3978jvP6TsJfL+LNtsxuLTlew7bIrZKwzhETk=)

**Comment by yuwu9145** [comment]
Solution in #16210 has been optimised.

After [v3.1.15](https://github.com/vuetifyjs/vuetify/releases/tag/v3.1.15) release, in the context of this issue, `item-title` function behaves as expected:

- It is only called once when initially calculating item-title value
- Its argument is item object itself

[demo v3.1.15](https://play.vuetifyjs.com/#eNqlkkFz0zAQhf/Kji6BIZYIHTiYtFOOcIADxzoHxd6kovJKI63NMJn8d1Z2WtKU4cLR76322/fGdwf1KUY9DqhqtWbso7eMNw0BrMfKDhzaIBoyFgmgdjKTrxs1Wj9gbtSZXLFjj+JxspR3IfWP9uROL8R13SwboazNGXKd2+QiQ0YeInhL+7JLGOK1gTLDDIVruCsLDuC6GlZLINtjDQu7gOPyj/HuydjOxuZjQ7uBWnaB4OnGV+W413AoDwsleNQ+7Ge5iEnOSQSLzyLIMngDX75/+6ozJ0d7t/v1OHksceYIN2qpXB9D4qq3Uf/IgaTeCSH5J0Ni1TO0aNJ/+W7UPXPMtTEDxYe9lu7NrXgmDcSux6oL/e2VvtJvK+vjvdUfTOcyn9sac19tU/iZMQm4UVMjJwbLuc85bUcy1aF3Y9KEbCj25jQppJVevZ8RJ63ydpsL48VuI8ARU5WQOkyY/pnnYvZvmS5GXuQqaKn8KFV7Rw/5ouU2Tw1PP0r5/r/A07ayalOIx6V6drCcML9Um98lUxwa)
