### ISSUE TITLE
[Bug Report][3.1.2] Md3 blueprint / default button color config overrides close button color in alerts

### ISSUE THREAD

**Issue by funkybg** [vuetifyjs/vuetify#16524]
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Create a clearable alert component
2. Set a default VBtn option in vuetify default options OR use a blueprint ( md3 )

### Expected Behavior
Alert close button should prioritise the alert default

### Actual Behavior
Alert close button prioritises VBtn default

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9U9tu2zAM/RVCL+mAxMLa7SVIh277haEvVR8Um3G06gaJThcE/vdRtuOlKVbAsE0e8vCYOn46iUOHZHbH6ncWa2FcDIngBHVCTfg4YtDDLgUHi6l2obzy+GcorYPPBBMA928bb07KA9AeHa6ZtMGd7iz9GuOFNe2eFssRz1xQigGG9BwBxGScTkdueN0bQh5esn159NAvy1NKyMZ1VpPxLbjmrsjambZg09B//I8/yF/Qc+/PvfYtgkMICbqMoD2gi3SETKkwSvCdteeOOtiQWM7WdkWNIkWjGuX7T8qLpfgeY8Ur4YVuiIlYF34rFZvDSsc4vA6B08ZP0Qha5JVyPjRo75VwuVUCahuy3loEOkbkLKYUEucPOhntiTMUvLZKzFQAOjfzlTXf5ylyGnNWwfEsYwAHgRt5IZzDXCcTCTJSV+DZJwl3l+4YnDFagrWzHRi/odQh72UjRxJu5xWNDDw6svOC51UNJ6ImICsxn5EqHi2xEnuimNdSdj6+tFUdnHxgTKbOk3G4aoJ7uKtuqy9fZWMyXeYrzG61TeE1Y+KJSgzGmciLV/83YIKZ93N1O9KefxmmfEclmf+AaZXQN5iQz+kD3Ve1b7RfYe/0nx3Hu7TGv+SrNdZ5WOHTcynpl2Kk5uLhO8TzX3rVU0o=)

**Comment by stephanharmse** [comment]
I encountered this issue too. It seems that in the [md3](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/blueprints/md3.ts) blueprint, the VBtn component's `color` is set to `'primary'`, defaulting all v-btn components to use the theme's primary color `text-primary` in the case of the v-alert banner.

The fix for me was to delete that property from the object before setting my blueprint:
```
import { md3 } from 'vuetify/blueprints'
...
// Ifs to shut up my linter
if (md3.defaults)
  if (md3.defaults.VBtn)
    delete md3.defaults.VBtn.color
...
const vuetify = createVuetify({
  ...
  blueprint: md3,
  ...
})
```
