### ISSUE TITLE
[Bug Report][3.1.5] The v-file-input with variable="underlined" density="compact" label is located on the align bottom.

### ISSUE THREAD

**Issue by jieun94** [vuetifyjs/vuetify#16681]
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.2.13
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
Try to use v-file-input with variant="underlined" and density="compact".

### Expected Behavior
There should be proper spacing between the label and underlining.

### Actual Behavior
underline and label does not have any space.

### Reproduction Link
[https://codepen.io/jieun94/pen/zYJxpww](https://codepen.io/jieun94/pen/zYJxpww)

**Comment by KaelWD** [comment]
Looks more like a text field bug to me, the label should be where the input text is.

**Comment by johnleider** [comment]
Fixed in v3.3.0 https://play.vuetifyjs.com/#eNrFks1OwzAQhF9l5UsvNAEVLigg8RyUg3E2kiX/rDabAKr67vinqhKinrntjD9bY82+n9TIpn0jauYJ1bPqBD05Lfh6DADdvNdEZSzCaxsuqmgTgyQL+WoWm+PXwriQbmUVc7AO9zbQJOsjAKc/0b0cVSagEuovM2u2OkiiptAju5Sj31I9htHKT6JM9KTN5qF2HbXdZr0VX/Bb0h/Q9bfiZwIq8V/xs7PsoxLr2rJ3rTaLWnrXLpYhydGwJYERZao7YT1FFjgB4wBnGDh62KU92uW7lU6cOt+pQ/PYPDypPByae/XxCz6jrs0=

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
