### ISSUE TITLE
[Bug Report][3.1.6] Cannot build Vuetify locally for contributing

### ISSUE THREAD

**Issue by amal-qb** [vuetifyjs/vuetify#16768]
### Environment
**Vuetify Version:** 3.1.6
**Vue Version:** 3.2.47
**Browsers:** Firefox 110.0
**OS:** Ubuntu 20.04.5 LTS

### Steps to reproduce
Follow the steps in https://vuetifyjs.com/en/getting-started/contributing/#local-development.
Errors were seen after executing "yarn build" command.

### Expected Behavior
Build completes without errors

### Actual Behavior
Build fails with errors

### Reproduction Link
[https://codesandbox.io/p/sandbox/elated-ritchie-291uop](https://codesandbox.io/p/sandbox/elated-ritchie-291uop)

**Comment by santiagoaloi** [comment]
The errors realted to `@vuetify/api-generator` aren't breaking the build process.
Though certainly we should check the root cause of those missing files.

Following these steps. Compiles and works.

`git clone https://github.com/vuetifyjs/vuetify.git
`
# Navigate to the vuetify folder
`cd vuetify
`
# Install all project dependencies
`yarn
`
# Build the packages
`yarn build
`
`yarn dev docs
`

**Comment by MajesticPotatoe** [comment]
duplicate #16653

**Comment by amal-qb** [comment]
"**yarn build**" command fails for me.
I'm getting "Cannot find module..." error and "JavaScript heap out of memory" error.

In the end, there's log: **lerna ERR! yarn run build exited 129 in 'vuetifyjs.com'**

Please see the logs in https://codesandbox.io/p/sandbox/elated-ritchie-291uop?file=%2FREADME.md.

**Comment by amal-qb** [comment]
@santiagoaloi Do you know why I'm also receiving **"JavaScript heap out of memory"** error during build?
