### ISSUE TITLE
[Bug] Select Menu Content misaligned after browser resize 

### ISSUE THREAD

**Issue by JacksMyth** [vuetifyjs/vuetify#1680]
### Steps to reproduce
Open the select dropdown, resize the window (causeing the select to resize).
Can be repro'd at https://vuetifyjs.com/components/selects

### Versions

Latest versions
Occurs on chrome, ie (I think others as well)

### What is expected ?

The select dropdown menu should reposition over the select component

### What is actually happening ?

The menu content sometimes does not repositions properly and becomes misaligned 

### Reproduction Link

https://vuetifyjs.com/components/selects

![screen shot 2017-09-11 at 4 55 09 pm](https://user-images.githubusercontent.com/10218691/30281308-54d9cace-9712-11e7-8a76-648f68671ff6.png)

**Comment by JacksMyth** [comment]
@johnleider your fix did improve it substantially when resizing the window, but it still occurs (albeit very occasionally). However, when using 'maximize' and 'minimize' the bugs still occurs very frequently

**Comment by johnleider** [comment]
Can I say, common man lol

**Comment by johnleider** [comment]
Ty, I'll take a look

**Comment by johnleider** [comment]
I have tried multiple approaches to alleviate the issue, however, every solution yields a new potential issue.

Increasing debounce on resize
Creating an additional debounce for onResize method along with deactivating and reactivating the menu
This bug is caused by the width of the content menu being calculated before it has initiated its resize. You'll notice, that when increasing the window size, the issue is not reproduce-able. This is because the menu has a minimum width of its activator width.
