### ISSUE TITLE
[Feature Request] Add a VCheckboxGroup component, similar to the VRadioGroup component

### ISSUE THREAD

**Issue by ocratravis** [vuetifyjs/vuetify#16858]
### Problem to solve
It's common to present the user with a list of checkboxes, so they can select zero or more items from a list.

It's common for such a list to have a label, validation rules (and accompanying error), hint text, etc. which apply to *the group of checkboxes as a whole*, rather than to any individual checkbox.

This is essentially an alternate way of presenting a [select multiple] control. As such, it's really a single control. Really, it's just a VRadioGroup that allows selecting multiple values. If VRadioGroup is justified, then surely VCheckboxGroup is, too.

It would be great to have an out-of-the-box implementation of this.

### Proposed solution
Pretty self-explanatory: implement this as a VCheckboxGroup, which works much like VRadioGroup, but is meant to wrap VCheckboxes instead of VRadios.

**Comment by mstralka** [comment]
This would solve the problem where you want a multi-valued list of selectable values to be visible - like the `<select size="10" multiple>` [HTML element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select).

In Vuetify version 2, `VRadioGroup` has a [`multiple` attribute](https://v2.vuetifyjs.com/en/api/v-radio-group/#props-multiple), and you can change the `off-icon` and `on-icon` of the nested `v-radio` elements to be `$checkboxOff` and `$checkboxOn` respectively, but the `multiple` attribute doesn't appear to work because the boxes won't uncheck.
