### ISSUE TITLE
[Bug Report][3.1.7] v-slider causing out-of-memory 

### ISSUE THREAD

**Issue by SeriousFresh** [vuetifyjs/vuetify#16864]
### Environment
**Vuetify Version:** 3.1.7
**Vue Version:** 3.2.41
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
Inside reproduction link you have v-slider with initial value 1, min 1, max 2500, step 0.0001
First when you enter the vuetify play link you will see that it's frozen for some time(v-slider is probably building itself or whatever). After some time it will be fine.
When you change max value from 2500 to 25000 it will cause out of memory error.

### Expected Behavior
v-slider to work with initial value 1, min 1, max 25000, step 0.0001

### Actual Behavior
Out-of-memory error

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUstOwzAQ/JWVTyA1ccpDSKEgEP/ABXMwzRYMsWPZTimK8u+snbQNrUAih8Szu57ZmfapY/fW5usWWckWAbWtZcBbYQAW60xam44JaKnMiBL2tarQATWaCusbwZatc2jCo6xbFAxKrQxV6Z2A3EQgNxH4gJZQ/Ai25+Rb0n1pqx+fRFxC102F+n5/fbcsEe22jWDwseATfwT90ikb6Ky0bVyADipcKYMPDWFDAtDDyjUaBKN8BLsWBjdpkuZkW6fvdP6ki4JGatpSxFwFm8VKJYM8OYXUBXAYWme2CGDqpoR5uhGfmE4JRV4Uxb5IaU5nKM8Szi6LYij0tCK9qd2f0nHBdxbZjA0uKRibv/vG0O+dVhBjwwtG2Q48o+Ho4i0E60vOW2M/XvNlo/kd9bhrTVAas6rRd+f5WX4x55XyYVrP0evsxTWfHh0pjlmM5EGtvn4TGNvEO8+vBtqxlNXyxUfeIz5OImt0GSVJ/x90fy5/MPvDwEHvyEQKmPKlQGtlPvxBlkufcnzarvZ/d4khXn+OKv2MDduRXrrBnr8BUSMyiw==)

**Comment by nekosaur** [comment]
We were generating individual ticks even if we weren't showing them. For a range of 1-2500 with step precision of 0.0001 that's 25 million ticks.

Are you actually interested in having step precision be that small? Or do you simply want to cap the decimal scale at 4? If so a workaround until the fix is released is to do this

https://play.vuetifyjs.com/#eNqVUstu2zAQ/JUF0YMNWA+nKQqoTuGiQI899hLmQFvrlo1IEXyoLgT9e5aUbCsOEiA6SJx9zO6MeN+zb8bkXUBWsY1HZRrh8SvXAJsuE8akYwJKSD2hhF0ja7RQqbbGJutEE/COs32wFrX/FSFnsA2mJsI3iuAOfga1Q7v4gB0Fc9/+kEesF7fLJRFUSmrqoHcC4hiBOHJ2WaU47XIJndaOT5pSQd/Ppw7Dpf2skYjOIiMY5W+KmS0E3d5K4+kslWmthx5qPEiN31vCmgbAAAfbKuCMbOXsC9d4TJVUJ0KTvvP6RR8HaqFoSx5/B2erGCHjxGIJKQtg0QerTwhgrqaCdeqIj/NoKijzsiwvQbJvXkMGVnDzqSzHwEAr0pvSw5KOm+Iska3YqJKMMflf12q6JmkFPiUcZ+TtyDMJjir+eG9cVRRBm8ff+b5VxZZyhQ3aS4VZ3artx/wmv10XtXR+Hs/RqWxn238OLU2cvJjIvTz8f23AlCbedf55pJ1CWSN2LvK+4CtoSIc2Iyfp/qB9c/mr2mcCrnIvRCSDyV8ytJH60V15uXfJx/vTau9Xlxhi+0OcMqzYuB3NSx3s4QlPfEYV

**Comment by SeriousFresh** [comment]
@nekosaur Yes, I need to have the possibility for step with that small precision. 
Workaround with 4 decimals is not an option. :\

**Comment by SeriousFresh** [comment]
@nekosaur  Ofc it would be nice if there is possibility to add specific ticks, but not all of them, especially if there is 25 millions of them.
