### ISSUE TITLE
v-select display extra blank line when place in v-flex

### ISSUE THREAD

**Issue by mementototem** [vuetifyjs/vuetify#1691]
### Steps to reproduce

Add `v-select` inside `v-flex` and use data that contain text long enough, after selected value and blur, `v-select` will add some black space below selected value.

### Versions
- Vuetify: 0.15.5
- Vue.js: 2.4.2
- Firefox/Chrome: latest

### What is expected ?

Text must display in single line without blank line below text.

(It would be good if have an option force to display in single line even the text is longer than `v-select` box.)

### What is actually happening ?

Text value inside `v-select` has extra space below, if text is too long.

### Reproduction Link

https://codepen.io/mementototem/pen/rGBbNL

**Comment by johnleider** [comment]
I'll actually have to re-open this as the change causes other issues.

**Comment by flybayer** [comment]
I'm also affected by this issue. 🙃

**Comment by dbweb-io** [comment]
Hello guys!

think have found a good solution x this one. I hope :) ... in the sense that on codepen, with chrome, analyzing the css, not going to touch or change v-flex or wrap css cascade classes, I saw that the problem is tied to the field height , and its management whether focus or not.

With the so compiled css vuetify library, it resolves by bringing the text field height to 0px.

If you remove the rule the problem remains, if bring it to 0px it resolves, but then from problems on focus.

So I applied 2 css rules to the example, and now it goes (the line stays in line of the text field, and follow in height according to the content)

I've also tried to replicate it outside the v-flex so it's an invasive modification, which then ruins the single use of the select component .... but it seems to be fine .... what do you say? :)

Is it possible (who knows the structure well and how is the whole code rendered) apply the modification, or fails something? :)

The codepen:

https://codepen.io/dbweb/pen/oGPeOY
