### ISSUE TITLE
[Bug Report][2.6.10] Nuxt warning: postcss-import: @charset must precede all other statements

### ISSUE THREAD

**Issue by rompeldunk** [vuetifyjs/vuetify#16989]
This should be straight forward fix:

Getting this error also on `npx create-nuxt-app` too

This file has `@charset "UTF-8"` on
`node_modules\vuetify\dist\vuetify.css:328`

Move it to the top removes the warning.

**Comment by Suniron** [comment]
I got a similar error, see bellow:
![image](https://user-images.githubusercontent.com/36677774/228921365-4ee1c30d-13a2-4237-8409-101ede8549b9.png)


I'm using pnpm & nuxt bridge in my project.

The problem is the same with nuxt 2 latest or nuxt edge.

Dependencies:
![image](https://user-images.githubusercontent.com/36677774/228921557-51474c1b-adbf-4d97-a813-87d641a9b839.png)

**Comment by sioniks** [comment]
v2.6.14 the file contain charset in vuetify.js
![image](https://user-images.githubusercontent.com/12643271/229585675-c7bcd700-322a-4496-8397-2d6b4307f0d1.png)

**Comment by sioniks** [comment]
@KaelWD can u please look into this problem
