### ISSUE TITLE
[Bug Report][3.1.9] v-select drop down menu doesn't align with input box at first click

### ISSUE THREAD

**Issue by efesezer** [vuetifyjs/vuetify#17126]
### Environment
**Vuetify Version:** 3.1.9
**Vue Version:** 3.3.0-alpha.1
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
At the first click of v-select, options of the select field are displaying not aligning under the input field. It is sometimes left-shifted. In my local machine it is left-shifted In the example of the playground, it is right-shifted.
Could you please help on this issue?
Here is the screenshot of output in my local machine [link](https://i.stack.imgur.com/OOGri.png).Could you please help on this issue?
Thanks.

### Expected Behavior
Values must be aligned with the input

### Actual Behavior
Values are not aligned with the input

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUcFO3DAQ/ZXBl4C0jlvRS6MF0R6Q+g3rPZhktrjYjms7KQX23zt2ErosiAuJFGdmnue9N7N5ZN+8r8cBWcPWCa03KuGldFCedadHaI2K8UKyju8M3kP+8LY3g3WSPSMBnv/WI49osE0wctt3aOjulJAMGk0kuVs5cyIMBnNiM8LFJZycjPD0BNUPKoOOEPD3oAN21ZawRt2UbrkomXQyTe8COlCzFouK/2YEuaFoLQ58UhjboP0Ew3vfhwQd7tRgEjxOVzuVVAOnZ1nf6ZwDmLo3UFWrJVU8NbCprvu+WkH1XYV8XOuHhxIOdG5n9P6s/OyznlkBWzFtswBula9/xd7RUgofjasUaGDNokoy2lqOJbtNycdGiMH5u59121txRTURBpe0Rd719uq8Pq8/cWX8raq/0CBiOizXGC2/Cf2fiIGIJZtFFo6kd39f8rSdIxRtVo+hdpiE81bMSGL6XH+dGOYUp73FTPGqtSC+EQMP6DoMGN61c4R9y9IR5JWteeJ7mrTR7i4eDbmNZcCbReGH/JZmudM2E+5X7IVeUlAusu0/gCYjbA==)

**Comment by Mohib834** [comment]
It seems like this is happening when v-select isn't wrapped inside a div with a fixed or max-width container.

**Comment by yuriincentro** [comment]
This happens to me when i put the v-select inside a dialog. It seems to not know where to align the dropdown on the page at first render. At first the dropdown is rendered out of screen bounds. After scrolling the dropdown pops into place

**Comment by yuriincentro** [comment]
I've found another workaround. It seems to work when to set eager="true" on the select:
https://vuetifyjs.com/en/api/v-select/#props-eager

**Comment by AndreySyagrovskiy** [comment]
> I've found another workaround. It seems to work when to set eager="true" on the select: https://vuetifyjs.com/en/api/v-select/#props-eager

eager does not work for me

**Comment by yuwu9145** [comment]
Reproduction can be simplified to when select components not in full width of the viewpoint

```vue
<script lang="ts" setup>
  import { ref } from 'vue'
  const age = ref()
</script>

<template>
  <v-main>
    <VCombobox
      v-model="age"
      label="Age"
      :style="'width: 200px'"
      :items="[18, 19, 20, 21, 22, 23, 24, 25]"
    />
    <v-row>
      <v-col cols="6">
        <VCombobox
          v-model="age"
          label="Age"
          :items="[18, 19, 20, 21, 22, 23, 24, 25]"
        />
      </v-col>
    </v-row>
    <VCombobox
      v-model="age"
      label="Age"
      :items="[18, 19, 20, 21, 22, 23, 24, 25]"
    />
  </v-main>
  
</template>

```

**Comment by AndreySyagrovskiy** [comment]
> > I've found another workaround. It seems to work when to set eager="true" on the select: https://vuetifyjs.com/en/api/v-select/#props-eager
> 
> eager does not work for me

vuetify 3.3.3 does not have this issue.
Sorry, for bothering

**Comment by yuriincentro** [comment]
this happened to me because of some overwritten v-overlay styles. Since the list renders the options in an overlay it messed up the layout. Make sure to have your vuetify css overrides as `scoped` to avoid debugging for two weeks.

**Comment by Dawid-Kwasowski** [comment]
Upgrading to a newer Vuetify version has solved this problem for me :fire:

**Comment by isheebo** [comment]
Still experiencing this issue on v3.3.8

**Comment by veredcon** [comment]
Still experiencing this issue on v3.3.10. Is this issue going to be addressed soon?

**Comment by JakobMiksch** [comment]
I have the problem when my `v-select` is inside a `v-navigation-drawer`. See example: 

https://play.vuetifyjs.com/#eNqlkj2P2zAMhv8Kq8UtEFs4XKfAOaRbtw4dOsQZHJvOqacvSIqDwvB/LyU5lyBZDrjJEvWSz0vSu4n9sLYaT8jWrA6orGwDvjQaoB7L1tp0TBfdjuLYBmF02bv2jA7GUpke5aZhOdCwRU16+zII5wMYi1roI5gBPErsAvhXc/YgiOXBaDg7Q8/WeBFL1/xCTMwlZZ3UxNkVgzHFCopD6+KHbvG0J3LNL/KLZQo8eL620xkdWqEpBNOk/HGeU8Y1/K48BA3bToru7b3TTXAnJOgv6g5+ix7JRcwmaZ4dnfPwan4zVLr6zglLQ8Bwyp0KZY0LMIHDAWYYnFFQ0D6KKAcgPzRF8gebqPha/EQpDfwxTvZfim9XybKTrIr26K3mGUcgtmKZVKrWVn+90bTwKaY3y4Nv2BpSJMbIQbw37DUE69ecd72mNFq3GF2lMXBtFd+SjLuTDkJh2Ru1fa6eq++8Fz7chiv0qjw42js6KtKw1Q0miOHfB1CLMhGenjJiiZWyPfjIeKjNCTiiKx3qHl38Qz/W0l3abVt3Tw+tRfrc6JkGLoV+83ez7nya8+5i8nM9p2qx1D4S5xVLRgmdM9j+P+aYTuE=

![image](https://github.com/vuetifyjs/vuetify/assets/15704517/09c75a33-652b-4444-b193-1c37ae3dc5f5)

**Comment by bbaappss** [comment]
> > This happens to me when i put the v-select inside a dialog. It seems to not know where to align the dropdown on the page at first render. At first the dropdown is rendered out of screen bounds. After scrolling the dropdown pops into place
> 
> I have the same issue
> 
> Workaround is
> 
> @update:menu="onUpdateMenu"
> 
> onUpdateMenu(open: boolean) { if (open) { // WORKAROUND: fixes dialog menu popup position setTimeout(() => window.dispatchEvent(new Event("resize")), 50); } }
> 
> ![image](https://user-images.githubusercontent.com/3393402/244119416-f4d10e9e-30b5-413a-9edd-61a406f2fc74.png) ![image](https://user-images.githubusercontent.com/3393402/244119808-8a813fe5-8624-4227-9df5-95e297247edf.png)

Thank you for this workaround, it worked for me!

**Comment by DurtyFree** [comment]
We are still experiencing this with with vuetify 3.3.15, mentioned workaround seemed to work. 

This should really be fixed

**Comment by DurtyFree** [comment]
Reproduction for 3.3.15: https://play.vuetifyjs.com/#eNqlUltuwjAQvIrlH1opicuraiOoQL1DfzAfkBhwGz9kmwBC3L1rG9oIhERppJWys96Z2bUnezzWOqvXDOd44JjQ1cyxNyoRGny8KzFXc7X1GUJ1KlTJqiHFsyWjOILVbB6g8S+UW7erGGCtDS/dKkedpye9bf2UOahYKE/aLwlqvyZQh2hDdCC6ED2I/jQ2kOilTo3ahN+QFKpCEJ7mmeIjfmn5qu0r1u/w57/oEeRJcBYdw//J8t2b/PuqBqRxh5DawnDtgFwugcdZipFlbq2DLy60Mg7tkWELdEALowRqwVNo+WKhpHUIDKKhrz88evJIB804wbE7FTOdfVol4f3sfR89FkAqRwHxGLD6nOKVc9rmhBSlhDbYAq9NJpkjUgsygmPErKXjgqWlEqNu1s16pOTWNeGMWZHOYbuWGSChOGnIOL7Y3SB1PBkU2v0occRSuArrNS64CQjWzKSGyZIZZm4d6aytOdZZ6WI0r36g8gALr7j8sme7LmzY8+Rk8n8zBzZPNfWKhwQHoyAdO/D0Gz9MSzM=

Also tested with latest/nightly builds :(

**Comment by DurtyFree** [comment]
Still an issue with 3.3.20

**Comment by DurtyFree** [comment]
Still a very annoying issue with vue 3.3.6 and vuetify 3.3.22

**Comment by trc-mathieu** [comment]
Here's also a reproduction with different scenarios. This is not necessarily related to having a parent with fixed width.
I also found that the issue was introduced in v3.1.3, maybe this commit is the culprit: https://github.com/vuetifyjs/vuetify/commit/a11138e5f75a9ef81bb3b39daeb8bd1cb07997cb#diff-312fd7cab65a29a514839a42d5046f2d933832994e4a70e4644e6ba00bc6d59c

[Reproduction 3.1.3 (broken)](https://play.vuetifyjs.com/#eNrdlbFu2zAQhl/lylmU7SpGgcAt0KVLgWZo0CXOQEtniw1FEuTJrlD03XuSaitxIndJNXQT9fN4/3d3Eu9+ihjy2Ufv032N4lqsCCtvFOGHtQVYvZESbkuETb2Dg4qgLQVX1DkW/AgcQnrbQJYu0gykfBqz1SESkK4QGldDbnT+AM4CsRbRYE5J9+z2GIxqQHmPKkTYGqdI291xb9C7ktLuyIi5swW0aU7nOo8WNJ+lCXQE76Im7axliz6wGEyT9t46d3sZS0SCgy6ofL8Wy/l8LTrjvdgZ65cA15rLEXnX3SKBtwlkCVzdr8VRLtBysob13FVecdxJMmqDhoVPQxG+3Ny+6G4IarPJvTI1cqQuzgTSZFrBqgoHKSDVwUq3+X7yPev7MPuDekY+xpobFVvUg3y3HI7/HyvwtPcn8MrIbKJRuPkMGx74omjHPFbKGDC4JahU2Gk7YTkeIQ79X3JV+ncXoUeRRzrP0K6mqAuEb19bH8f9I5SjjM8IW76/EEH1Q6qa3KuTPaPi6aLyPN2rIl6e4cWEvzP30NOqfogxTD/Bl4px7MFE33TyYuv/YQ1Ws0e3tfiViCy9SudSGV+qNBPtmi9mcf8bx/l1kw==) 

[Reproduction 3.1.2 (working)](https://play.vuetifyjs.com/#eNrdlbFu2zAQhl/lylmU7ShGgcAt0KVLgWZo0CXOQItniw1FEuTJrhDk3UNJsZU4kbMkGrKR+nm8/7s7Sdd3LPh88sO5dFshu2ALwtJpQfh9aQAWXziHqwJhVW1gJwIoQ97KKkcZlxBDSK1ryNJZmgHnz2PWygcCUiVCbSvItcpvwRqgqAXUmFPSru0WvRY1COdQ+ABrbQUps9mf9WpTUNpeGTC3RkKT5nCvdWhAxbsUgQrgbFCkrDHRovNR9LpOO2+tuy0PBSLBTkkqvi3ZfDpdstZ4J7bGui3AhYrlCPHU9SyBswSyBM5vlmwvSzQxWR313JZOxLiDpMUKdRR+9kX4fXn1qrs+qMnGt0JXGCOVPBJIkW4EI0rsJY9UecPt6t/B96Trw+QR9Yh8iDXXIjSoO/513l//GSvwvPcH8FLzbKRRuPwFqzjwUjZjHkqhNWhcE5TCb5QZsRxPEPv+z2NVumcnoQeRBzofoW1FQUmEv38aH/vzA5SDjC8IG743iKD8z0VF9t3JXlDF6aLiON27Ip6e4dmInzN729GKbojRjz/Bp4qx78FI73Tyaus/sAaLyZO/NbtPWJaep1MutCtEmrFmP0vP2M0Dx/Z1kg==) 

[Reproduction 3.4.4 (latest broken)](https://play.vuetifyjs.com/#eNrdlbFu2zAQhl/lylmU7cpGgcAt0KVLgWZo0CXOQItniw1FEuTJrlDk3UNJsZU4kbMkGrKR+nm8/7s7Sdf/WfD55Ltz6a5CdsGWhKXTgvDbygAsP3EOVwXCutrCXgRQhryVVY4yLiGGkNrUkKWzNAPOn8ZslA8EpEqE2laQa5XfgjVAUQuoMaekXdsdei1qEM6h8AE22gpSZns469W2oLS9MmBujYQmzfFe69CAincpAhXA2aBIWWOiReej6HWddt5adzseCkSCvZJUfF2xxXS6Yq3xTmyNdVuACxXLEeKp61kCnxPIEpjfrNhBlmhisjrquS2diHFHSYs16ij86Ivw6/LqRXd9UJON74SuMEYqeSKQIt0IRpTYSx6p8obb9d+j70nXh8kD6gn5EGuuRWhQ9/zLor/+I1bgae+P4KXm2UijcPkT1nHgpWzGPJRCa9C4ISiF3yozYjkeIfb9X8SqdM/OQg8iD3Q+QtuKgpIIf343Pg7nBygHGZ8RNnyvEEH5j4uK7JuTPaOK00XFabo3RTw/w7MRP2f2tqMV3RCjH3+CzxXj0IOR3unkxda/Yw2Wk0d/a3aXsCydp1MutCtEmrFuP2c398gLdZc=)
