### ISSUE TITLE
[Bug Report][3.2.2] V-autocomplete menu selection not closing by clicking arrow icon

### ISSUE THREAD

**Issue by ngobinh105** [vuetifyjs/vuetify#17280]
### Environment
**Vuetify Version:** 3.2.2
**Last working version:** 2.6.11
**Vue Version:** 3.2.27
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
cannot close input selection, only work when click outside or 'esc'

### Expected Behavior
clicking arrow will open & close the input selection

### Actual Behavior
only opening the menu but not closing it

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlULtOwzAU/RXjJSA1sSgDUpSisvEHDHWHNLkBg1+ynQCq8u9cO6kU2qUSk31f57U70mdri6EHWtIqgLKyDvDENSHVkNfWpm8qVC30XKU6wHfIOwGyJTg0LcgNp8q/cUrYcq/ug2kMAkMAUgrk8Li4y+L9fbZK73p+H7I9nsv6gGDY8IEsr7MTbsUWcmIxCa3YwgCWvnHCBuIh9HEslDUukCNx0JGRdM4okqHzLC43RiMbyiebOL/NXkBKQ16Nk+1NdhfBJzgEois6YaEIW3x4ozG8Y9TC54HntCSpE3vIEWtO30OwvmSsaTWeYWJicIWGwLRVbItrzPU6CAV5a9T2oVgX60fWCh+W/QK8yg/OfHlwiMLpasETRPdzBde8OVFMDHMrx/B9pLiAZsg3gMsd6BYcuGstnZ39sXU2u7AW6UeuR0xcCv3pz8JufAp6d1L5L88JLCLtI+G4opNQpE4fuv8Fa/wP+w==)

**Comment by yuwu9145** [comment]
As per my investigation, fixing this would require bit refactoring, because:

In VTextField, due to input has `onBlur={ blur }`, clicking appendInnerIcon will blur input, which means clicking the arrow icon will have to completely blur the whole VTextField.

My refactoring plan:

- Remove `onBlur={ blur }` from `input`
- Port V2 logic instead (manually trigger blur in VTextField via "click outside" & "mousedown tab") to V3

Do you have any better suggestions @vuetifyjs/core-team ? If not, I am going to proceed my plan
