### ISSUE TITLE
[Bug Report][3.3.0] Unable to override sass VInput variables

### ISSUE THREAD

**Issue by stevenhurth** [vuetifyjs/vuetify#17419]
After upgrading to 3.3.0, we are no longer able to override VInput variables in our custom settings. ONLY VInput variables (all of them) throw this error when we try to override them, every other component variable works just fine.

“This variable was not declared with !default in the @used module.”

Checking the source for 3.3.0, the input variables are indeed declared with !default though.

nuxt 3.5
Vite
Sass 1.62.1

**Comment by lioneaglesolutions** [comment]
@johnleider can confirm this is a bug - facing the issue myself. Seems this could be somewhat breaking?

**Comment by johnleider** [comment]
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
* [Playground](https://play.vuetifyjs.com)
* A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).****

**Comment by lioneaglesolutions** [comment]
@johnleider repro here

https://github.com/lioneaglesolutions/vuetify-issue-17419

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/blob/9b880146746fc0b7d8b92f26a7084dfe0c3c6abd/packages/vuetify/src/components/VField/_variables.scss#L2

**Comment by lioneaglesolutions** [comment]
@KaelWD I'd be interested in an explanation as to why this breaks it if you get a chance

**Comment by KaelWD** [comment]
`with` is only inherited if the module is forwarded before being used

**Comment by SergkeiM** [comment]
After fix for me stayed the same with error:
![image](https://github.com/vuetifyjs/vuetify/assets/3294939/7d6e24d1-6cd9-496d-a7b5-97000ac5b8e7)

I guess I will need now to re-work how I `@forward "vuetify/settings"`

**Comment by KaelWD** [comment]
https://github.com/lioneaglesolutions/vuetify-issue-17419 works for me with 3.3.1

**Comment by stevenhurth** [comment]
I can confirm this fixed the issue for us. Thank you kindly!
