### ISSUE TITLE
[Bug Report][3.3.1] [Bug Report][3.3.1] v-text-field have TypeError with scrollStrategies.ts

### ISSUE THREAD

**Issue by tak-ho** [vuetifyjs/vuetify#17486]
### Environment
**Vuetify Version:** 3.3.1
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
When the page include v-text-field, the console will have some kind of error, although the page still load correctly

scrollStrategies.ts:85 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'classList')
    at Object.blockScrollStrategy [as block] (scrollStrategies.ts:85:22)
    at scrollStrategies.ts:57:47
    at EffectScope.run (reactivity.esm-bundler.js:38:16)
    at scrollStrategies.ts:53:27

### Expected Behavior
no error in console

### Actual Behavior
no error in console

**Comment by GaborTorma** [comment]
Same issue in VOverlay component

**Comment by MirzaeiDev** [comment]
Error with `scrollStrategies.ts` when root is undefined

I encountered this Sentry error but wasn't sure what caused it initially. As @GaborTorma pointed out, I investigated and found the issue occurs in 
`scrollStrategies.ts`:
```
const scrollableParent = (el => hasScrollbar(el) && el)(offsetParent || document.documentElement)
if (scrollableParent) {
  data.root.value!.classList.add('v-overlay--scroll-blocked') // Error when root is undefined
}
```

The error occurs because `data.root.value` is undefined in some cases. However, when I add this dialog implementation:

```
<v-btn
  @click="stateModel = true"
  color="surface-variant"
  text="Open Dialog"
  variant="flat"
></v-btn>
<v-dialog max-width="500" v-model="stateModel">
  <template v-slot:default="{ isActive }">
    <v-card title="Dialog">
      <v-card-text>
        Lorem ipsum dolor sit amet...
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn
          text="Close Dialog"
          @click="isActive.value = false"
        ></v-btn>
      </v-card-actions>
    </v-card>
  </template>
</v-dialog>
```

The root value is properly defined and the classList error doesn't occur. Other dialog components don't produce this error either.
