### ISSUE TITLE
[Bug Report][3.3.2] V Navigation Drawer or V List Open/Close Child Issue When Child Has Same Title With The Parent

### ISSUE THREAD

**Issue by irsyaadbp** [vuetifyjs/vuetify#17498]
### Environment
**Vuetify Version:** 3.3.2
**Vue Version:** 3.2.37
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click on Users (Parent) then click to Users (Child) is auto close
but if i click Management (Child) not auto close

### Expected Behavior
If i click all child list even though it has the same title as the parent on navigation drawer/v list is not closing the parent menu

### Actual Behavior
If i click the child has same title with parent on navigation drawer/v list is auto closing the parent menu

### Reproduction Link
[https://codesandbox.io/p/sandbox/zen-sky-1p4nyi?file=%2Fsrc%2FApp.vue%3A37%2C27](https://codesandbox.io/p/sandbox/zen-sky-1p4nyi?file=%2Fsrc%2FApp.vue%3A37%2C27)

**Comment by lioneaglesolutions** [comment]
It's because your `v-list-group` and `v-list-item` both have the same `value` of `Users`. The value needs to be unique.

https://play.vuetifyjs.com/#eNqlVMtu2zAQ/BWCpwS1pCJpL6oTpLdeeuzJ8oGW1jIb8QGSUmoY/vcuKcmmJSEIEMAAxX3OzC69OdGfWqddCzSnawdCN8zBcyEJWXcJ0zp8hkvDjqp1wz1YJOt4zRxXMqkMewNDNBjBJMhrWJ/KbWy52BKOHYk2oEFWCS+VfCqoqHhyUAIKShx3DaDpV7g+r7MoDestVayNajXpWNP6xD8WjMXMOBJjR56kS2yjXM5KxzvmlMGUE+JR2pLzLO0W9tRHsNiOywpLhAIFnUcsMGVlqVrpkpKbskGS86RRhIHLNGCmyg3gLBrpxPUOly7ZBy3uNqH5injAWzzuCZeEVYLLBST5KxwxiS94Rg7hXPBPhPHHQtQ41VCFfCGzTu9ocfGEBYnXc3BcFxsNs82O5EPhBEMZrDsGTgfg9cHl5OH7V/3vZmkw0jMJ6t0udhZFMVvhL+7uy4/vzqO7Pjx/7R/lZLJrWxquHbHgcP0bJmuv07j6XGhlHDkRA3tyJnujBCkoPvqC/uiJIULrhsmSJx93t+kRbAr6m0lWg8BnXdAVJsZ7K9rGcd1AghAbLrHidnVJHFZ2zClVPQ3b3iOAddajR6x0RXuwKIJO/1ol8X/p5CNxK4ID6+UkWLwtcMjx4+CctnmWlZXEtAoa3plUgsukFtkLhmUG4XIBSaXEy2P6mH7LKhx7bE7BimRn1BvCxiIIPGrj+P74gVZDZOjw0HcYTDjHnfUtZqUz7NeBSQw+ATBgPspokhazmrhmzHz3cyHPqDeO49VOpC5tkHlYgU9SDsXCsH3D84oGnNg5JNDtf4tdAgg=
