### ISSUE TITLE
[Bug Report][3.3.2] v-autocomplete selection slot not shown while control has focus

### ISSUE THREAD

**Issue by drennenb** [vuetifyjs/vuetify#17573]
### Environment
**Vuetify Version:** 3.3.2
**Vue Version:** 3.3.3
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
Select a Building.  Then click whitespace.  Then select another building.  The selection slot is not shown when control has focus as it did in V2.

### Expected Behavior
Always show selection slot template while an item is selected.

### Actual Behavior
Selection slot template hidden while control has focus. When focused, item.title is shown instead.

### Reproduction Link
[https://stackblitz.com/edit/vuetify3-krppgl?file=README.md](https://stackblitz.com/edit/vuetify3-krppgl?file=README.md)

### Other comments
Not sure if this is different by design, but if it is, the part that makes this bad UX is the user must backspace out the current text, or must click the closeable button to enter a new search,

**Comment by nemoneph** [comment]
We are facing the same issue here.
We have not found an alternative yet.

**Comment by VicentSE** [comment]
Same here! 

I believe this was not always the case. As I understand this behaviour was introduced in **v3.2.2** https://vuetifyjs.com/en/getting-started/release-notes/?version=v3.2.2. I think in an attempt to fix other issues related to selected content overlapping the user input. In order to fix this `opacity: 0 ` was given to the selection when the input is focused.

Unfortunately, this change makes for a rather bumpy experience when using custom slots that involve images or a more complex layout since these will be completely hidden on focus to display only a text, and then this text will be replaced by the original selection slot content on blur.

But perhaps I am missing something, would be nice to know how to avoid this from happening since I am trying to migrate a project from v2 to v3🙂

**Comment by glacierPEgli** [comment]
I am currently migrating from v2 to v3 and facing this issue as well. I also haven't found a workaround yet.

**Comment by drennenb** [comment]
Im sorry if this kind of comment is unhelpful, but I wanted to re-iterate how important I think this is.  The autocomplete with templating is essentially broken, and is preventing the deployment of several updated apps we work on, and I see others have commented the same.  I am wondering if I need to find a different control.  I appreciate this is a free product, we want so badly to use it because its great.

**Comment by BrahimMasmoudi** [comment]
hello, can you try adding :key="selectedBuilding?.name" to the v-autocomplete? 
that's the workaround i did in my project so that the selection slot works when i click on item in the autocomplete list.
i hope that helps

**Comment by drennenb** [comment]
> hello, can you try adding :key="selectedBuilding?.name" to the v-autocomplete? that's the workaround i did in my project so that the selection slot works when i click on item in the autocomplete list. i hope that helps

Thank you, you can see your work-around implemented here:  https://stackblitz.com/edit/vuetify3-krppgl
unfortunately does not seem to help.

**Comment by KozakoPolako** [comment]
I found workaround. when combobox has multiple prop selection slot works as indented so you can bin your model-value like it is a array and watch @update:model-value:
```
<v-combobox
        :model-value="[model]"
        @update:model-value="(val) =>model = val.length ? val[val.length -1] : null"
        multiple
        ...
>
```
In downside you had to use custom item slot to hide default checkbox in menu, but when you use selection slot, you probably want use custom item anyway...
Solution in playground: https://play.vuetifyjs.com/#eNrlVF1L8zAU/iuHvBdVWDvkVYTSTWWgiOJAB7tYd5Gt2QymSUjSqpT+d5PUuXTihdde9Zznec5HTw5n0SCt1sMrKZO6IihFmSGlZNiQcc4BsjrGUnrTO2vBDaacqE+oA7EqYkMNI+OH6Qzm08e724ebbNhjQr0oV2Il3nYQQB2XoiBslCP/zdGeYnjlickuKOBSapvVllxEE8zoRihOcTSAaCKYULgQzr62Ji08fEOE2naKGXnD2hnzd1FSvo2W+8Rfvdpud9OAf5owsjZUcFuvAVcZ2hwFWqvWEvPx0/10lkLTOEmi8Cu0bTb0TJB32BtzB+0n88N050K92F5/M9nUDzSuMauIG5R3g38FuKxkYfs4EB5Z4xhGY4/CCKybMMK35hkunLMIgPhkCSnwivUerqyYoZKRP/iUvWIudl9nAFIJqVOQ3yrWMaPaxF5WxyvKCxsmcwT+ma19ENAP+VyGoNm29Tt1qOjVDPlfr2cHhQfBId296GXI9FpRaUATU3XHhJZSKAMNKLKBFjZKlBDZAxTl3NE2qzaw2z2rOXLbdezSdqlsEtQO0P/kNDlH7nuWnKDlB6G2eSU=

**Comment by Lisiadito** [comment]
this bug seems to be back in version 3.5.14. I'm not sure in which release it got introduced again but it worked fine in 3.5.8.

**Comment by VicentSE** [comment]
I can confirm this, in fact I went from a version where this bug happens to a newer version where it happens again 👎

**Comment by johnleider** [comment]
Can you provide something for us to go off of? If there's a regression, creating a new issue or giving a reproduction helps solve the problem.

**Comment by drennenb** [comment]
I just checked this out by taking my app back to 3.3.2 and verifying the original bug was in place.  I was on 3.5.8.  I then took Vuetify up to 3.5.14 and its still fine.  I do not see that this bug has "returned"

**Comment by VicentSE** [comment]
I just tested this again in version 3.6.7 and the issue seems to be gone 🥳 . I created this playground in case anyone wants to test it:

https://play.vuetifyjs.com/#eNrtVF1v0zAU/SuXbCyt1DYdAjSFtKiwBwYSb4iHderc2M0s3NiynWojyn/n2km6NC0PPPC2lyg+Oud+nWvfloHRabRQarIrWBAHiWVbJYhl82UOkOzGRCn/6w+pzC3hOdMNVDMKK1OJKmYZxBwDmNkyKAzTZhnsiUhtQ8OZYYKllssciaVTVAdM5FK+g1QQ04Yakx2xRPdoSOTb7BCBU7rVyvGCPjPG5pGYMbvwtIGrZbIjomATp/5OtmzYl0X9Ev5S62pl2aM9qrgWzJP1vPStd9Ld0KpKovU8iRzjpOxI40p0qmPFMdZHkqjj9kmjXDLnkdJSmRH8m1WwG695ThH28hfv/pt3LXR4Gdt7i/DhxfVEf697G5CYVHNlwTBbKBAkz3AstnWOb5XUFkrQbAMVbLTcQojPRlgvD+YwFur5/dACZhA+WKtMHEUFb+ZqJlhcRBSPPq5J+ivTssAFmV5fLT59vkilkHq22WwuDP/NZm+nB4H9g4JBb+uuSg/c0BjC6fRNOPJHN1AEvrndvZYshGp0gn15yP4qH/Iu+66bdb9emHnwLDJW8zwbtj8wm8P9ebnvvbrIkTY7L/cu33/oRt0alLgxDsIvTAgJP6UW9FU4dI7UHjR+2CdR++gXppkilHVXaaGN1DEoyXPLNKZwKOUGHX2KYSPYY4MRwbN87N/mGFLWYWdExXD5XrVMRSjFjmK4aqCqLryb39/ItohnH3HL0MAYziilTbS11BRlmlBeYOZ309dtTOyz6S2oRnkhhP/c/QFgfQdW

Many thanks!
