### ISSUE TITLE
[Bug Report][3.3.4] VDatePicker failed to parse a date with any format except mm-dd-yyyy

### ISSUE THREAD

**Issue by rosales-mirwing** [vuetifyjs/vuetify#17615]
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Firefox 114.0
**OS:** Linux x86_64

### Steps to reproduce
- Set locale provider to `es`
- try to select the date `June 2` from the datepicker

### Expected Behavior
The date picker show `Jun 2`

### Actual Behavior
The date picker shown `Jan 6` (because the date format in `es` is `dd-mm-yyyy`)
![image](https://github.com/vuetifyjs/vuetify/assets/136642121/8297783d-b316-4367-84bf-3fef398d7418)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUk1v4jAQ/SuWL1AJJ4fuCQFi/8Jqt5e6BzcZFhd/yXZCK5T/3rEdINBLpZ6S+fB7M+/N84n2HUS5+6jeAl1SqZ31kZxI40FEeCo1MpCdt5rMxt4ZN9zAe25trAmRjAWyvn04P3FDSNyDhiWCtrATnYp/SzxrhT/MyLDgZnjghi7ob+cqRMI5VhG0Uwi0SQCrngnn8m8OkDMKacCPqZxUthEKmPO2ly14UuI1pxA4vTTm1haBmZPNAfw1T8i2c6my1LYFxXqhuvR8L0yr4F8ucTrt3yMPE02UKME1v1nVNwzXGTF/N+R5Jazc7pQyZeVVPZECw9B46SIJELuiyMWyaP+I49SqbBMZHZqugTYZOD6lBcl6Q7JJpc8qqJT9P89Y83PTA9pDyJCGKfRIjHYVZqaFw+OxBm3LSHwsoOxoesHm6cxSjHrG6MKyrpvW4DNUWva+MhBr43S9xbbadyZKDay1evtYPVa/6laGOE1XEDR79fYYwCMIp3hDF5p0eN+gGjunDGOKKfEaEsUX6Br5evDMg0H38Hq+udHdsynnXenLZqPyA+qtpDmEO6mbkGV+Pg/5o5UzWEJ6SYTDguZGZC7fl093CWeg)

### Other comments
If the first date selected has a day greater than 12, the date picker return an empty array

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/pull/16234/files/b65513ba79b2a74891357e32508e24f07b38fecc#r1214185273

**Comment by eguvenc** [comment]
👍 Hi, thanks, in which version this error has been completely resolved or is there a planned version?

**Comment by aelstad** [comment]
It is not clear how the date composable https://vuetifyjs.com/en/features/dates/ supports parsing of localized date strings.   `date (value?: any): Date | null` in the vuetify adapter seems to have custom logic for  yyyy-mm-dd and otherwise uses the Date constructor.  @date-io/date-fns  simply calls the Date constructor.  The Date constructor is unreliable for localized parsing.

So I don't see how eg the date picker keyboard input mode can work out-of-the-box in localized mode without first creating a clearer/better adapter-interface. 

However, after extending the date-fns adapter and replacing the   `date (value?: any): Date | null` with a version that in addition to iso/date constructor parses my localized format (dd.mm.yyyy)  the DatePicker seems to work as it should.

**Comment by KaelWD** [comment]
It doesn't, hence this issue. Date parsing has been removed in 3.4.0.
