### ISSUE TITLE
[Bug Report][3.3.4] VDatePicker doesn't set the correct timezone

### ISSUE THREAD

**Issue by rosales-mirwing** [vuetifyjs/vuetify#17613]
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Firefox 114.0
**OS:** Linux x86_64

### Steps to reproduce
- Set the OS timezone other than UTC (example UTC-4)
- Try to pick any date

### Expected Behavior
The component show the date that was clicked

### Actual Behavior
The component display date -1
Example: if I click in `Jun 1` the component show `May 31`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkctu2zAQRX9lwI0dwBIX6cqwA/cXirabMAtGHNesxQdISklg6N8zJJVAcTYBspLmwXtnztxf2Dhg0seX9n9kW6aNdyHBBbqAMuHfWoMJjsEZWM29K2GFxefS2jkbE8wF2H98uL4IC5BOaHBLogqPcujT7xqvlAznFUwbYacbYdmG/fS+JSWaY5fQ+J6E7rLAbmyk9+W3BOSZpLYY5lRJKupuvO7OGOCkFTayS5qGg8Pgc21rnMK+GWU/4F6wk7Sqxz+lJBjwN3V+LZ8z1X3HF1NRGLugfYKIaajDvdNL7pd8WlIrxGCGtbQmYl4GaWB/BwVWbXI9tr37ty5C69JxQ4wApjxGNSZLYlY9GyM9XdBZYldkxFyIghH5KizyrXNM26fk45bzTll6Rlz0GFqLiVtv+IHaeBhs0gYb5czhtr1tf3ClY1qmW4ymeQzuKWIgEcHokO82+fpfsJo7lw5zqunlY8wWn6Q5+Y0YmoBWYcDw1Y2uni09r0qfNpvJT8S71/Ycr1B3sWC+fxvyWysXsaz0kA2nDSuN5Fy/D69z5kPi)

![image](https://github.com/vuetifyjs/vuetify/assets/136642121/216dbe6c-c40c-41fb-8fc6-31443e8bcd33)

**Comment by abea** [comment]
This seems rooted in how Vuetify uses `Date.parse()` and the value fed to it [in the `date()` method](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/labs/date/adapters/vuetify.ts#L207-L219). The calendar buttons have data attributes with dates like `2023-05-23`, a standard date format. Passing this to `Date.parse()` then the result to `new Date()` like the method does, gives me this since I'm in CDT (near Chicago):

```
> Date.parse('2023-05-23')
1684800000000
> new Date(1684800000000)
Date Mon May 22 2023 19:00:00 GMT-0500 (Central Daylight Time)
```

Interestingly, if I pass another date format, it give me what I expect:
```
> Date.parse('23 May 2023')
1684818000000
> new Date(1684818000000)
Date Tue May 23 2023 00:00:00 GMT-0500 (Central Daylight Time)
```

This looks to be because `Date.parse()` assumes standard formats to be in UTC unless specified, while [non-standard formats are assumed to be in local time](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#non-standard_date_strings). Another interesting and confusing quirk of JS.

I don't think the solution is to use non-standard date formats. Instead it should probably get the UTC offset and include that in the parse string. A date string like `Date.parse('2023-05-23T00:00:00.000-05:00')` will result in the correct date object I was looking for. [Others have shared approaches for getting that offset value](https://stackoverflow.com/a/15304657/888550) that could be used here.

I'd be happy to work on updating the `date()` method with something like that if you think it's the right approach. You may want to make the time zone configurable in the method at some point, but this could serve as the immediate solution to this problem.
