### ISSUE TITLE
v-select with 'chips' and 'tags' throws null error on form clear

### ISSUE THREAD

**Issue by Aps05** [vuetifyjs/vuetify#1762]
### Steps to reproduce
Create a v-select inside a v-form with only the  following props: [v-model, chips, tags].
Create a clear button to run the reset() function on the form "this.$refs.form.reset()".
Click the clear button.

### Versions

I tested this on the following:
Vue 2.4.4
Vuetify 0.15.7
MacOS Sierra (10.12.6)
MacOS Safari 10.1.2, MacOS Chrome 60.0.3112.113

### What is expected ?

One of two possible behaviours:
- On clicking the clear button, the v-select should clear.
- The v-select should not accept tags that are not defined by the 'v-bind:items' prop without the 'multiple' prop.

### What is actually happening ?

Upon clearing the form, the value in my 'sources' clears but the v-select input field does not remove the added chips. Once this happens. You cannot remove/add new chips.

### Reproduction Link

[https://codepen.io/anon/pen/ZXbYLN](https://codepen.io/anon/pen/ZXbYLN)

**Comment by jacekkarczmarczyk** [comment]
> The v-select should not accept tags that are not defined by the 'v-bind:items' prop without the 'multiple' prop.

Actually it should be rather "v-select should not allow to enter many tags if there is no `multiple` prop"

In this codepen form.reset() sets the v-select value to null (because there is no `multiple` prop, with `multiple` prop it would set value to an empty array), but v-select treats model as an array, hence the "TypeError: Cannot read property 'length' of null" error

**Comment by johnleider** [comment]
I will update the docs to reflect this. Tags should not be used without the multiple prop.

**Comment by Aps05** [comment]
Thank you for the response.
