### ISSUE TITLE
[Bug Report][3.3.4] DatePicker header-color doesnt work

### ISSUE THREAD

**Issue by arekusu04** [vuetifyjs/vuetify#17631]
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Chrome 93.0.4577.99
**OS:** Linux x86_64

### Steps to reproduce
open link

### Expected Behavior
primary for header

### Actual Behavior
No color for header

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNkU1uwjAQha8SeY3tBV2hFNFzYBYmngpD/KOxkwoh7t6xU6Q0LGCV+HnmfW/G+xv7ilGMA7ANazO42OsMW+Wbph15F3zW1gNWoUoYfprzkLL9vn4qlqLugGsMgzeK/VXVOkM2PNruAth0oQ9I1RGt03hVrDmBNoDkv7jYtvJf64NLKoGnWPQ/z9XKWWq2Yr31lyTOKXia6FY6FOtSUmzT7Cc3xU45x7SRsjOeKg30dkThIUsfnaRdlOl2a7EWH9LYlB8S7/UxiWpWnA7K3wloXQyYudNxQZ0uKrkqRSOncn4RYUdlEgefrQNugptnmckCkuNHWkwCJBPFVjNMCfwG6tW0hHiylsQb6fkQPL0i4LsTLdrmzMXV02SFfi/7vq9YbaPFT9/DLxX672Y=)

**Comment by johnleider** [comment]
This has been resolved as of the latest version: https://play.vuetifyjs.com/#eNpVjtEKAiEQRX9F5jmV2p7Cgr4jexDXwNpVGXVjif69wS3Ynma4HM69lxdktPKckpiqgwOo4sY0mOJOOjCmJm5jKMYHhy1oEcYnu9dc/G0+asjJWMcNxhp6DV+qcT1pePL24ZDZOEQkOqEfDc4EKvlH/PSUkn9pp39dr+RqHLw30IlO7GG5uy1cP/PVQs0=

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Arinono** [comment]
> This has been resolved as of the latest version

Partially I'd say.

While the `color` prop now works, the documentation mentions a `header-color` prop that seem to not exist
https://vuetifyjs.com/en/components/date-pickers/#colors.

Either the docs should remove this mention, or the `header-prop` should be implemented and used in the `headerProps` at the start of the `useRender` function.

For my use case, I'd prefer to have the `header-color` prop as I'd like a blank header but keep the selected dates coloured in the calendar.

note: I'm not reopening because it depends on what you choose to do, if the `header-color` will not be added, then the docs just needs to be adjusted, which is something else.
