### ISSUE TITLE
Layout problem with grid lists on mobile

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#1769]
### Steps to reproduce
Try to get rid of padding on ```v-container``` with ```grid-list-*``` property:
```html
<v-container class="pa-0" grid-list-md>
...
</v-container>
```
* clone repo https://github.com/Darkside73/nuxt-vuetify-layout-problem
* run nuxt server and open index page in browser
* switch to responsive view in devtools
* try to scroll page in various directions

### Versions
vuetify 0.15.7

### What is expected ?
No scroll should happened

### What is actually happening ?
extra space on scroll in both directions
![peek 2017-09-16 22-56](https://user-images.githubusercontent.com/339596/30515532-44191324-9b32-11e7-9996-e211e3646253.gif)

### Reproduction Link
https://github.com/Darkside73/nuxt-vuetify-layout-problem

**Comment by johnleider** [comment]
This is happening because you are applying **pa-0** on the root container, removing all of the padding. The problem with this, is layout, when a child of container with a specified grid-list, has a negative margin to account for the padding that is expected to be there. Either remove the pa-0, or add ma-0 to the layout component.
