### ISSUE TITLE
[Bug Report][3.3.8] VDataTable - Boolean values are not shown in table

### ISSUE THREAD

**Issue by ssierputowski11** [vuetifyjs/vuetify#17810]
### Environment
**Vuetify Version:** 3.3.8
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create an array items for a v-data-table that has a boolean value and see that the boolean is blank in the table view.

### Expected Behavior
expect to see true/false or some form of radio/checkbox or some way to view the boolean value in the table

### Actual Behavior
Column with boolean value is blank all the way through

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVU1v2zAM/SuCL22ByM5HP42s6NBhwNZLr0PdgxIzqVZZNiTaW1bkv4+yHcex6yJbTqLIR75H0czTm/c5y/wiBy/05ghJpgTCbaQZmxc8Fig4ioUCd8FYwZM0BhVKCrQ8A8MzsYZPkVdePIJ5JDPyquDwBUQMxpK7PjWeMpzuY7AWDDYOd88LoXKXU4ukybVUwjoAKCgEylTzSeW6nQdtmkR8HrRUkGmXRmZYKoLfWWqQxbASuUL2VuV26NOzncWYAcyN3tsVrZ26kF2M9p5aWMie9nesDXU/lKgId/KlUstOJ+PxmtGxkHp9dtJK535CybWmaIvCYNdpib/TGbKVUBY63lfYEND17RC3PbDeGkL3QqVGgj0ZNVVBx2RViZY792CCr4LUOAnv4lcCh6H3wizsB+Cl8w/DH02KIPUHCbIqYjjFN5PqAax0rgPgc+u8m9qPX909g2uRSf+AZj/Sdd5/zl2HQza5uOn4qHshu/THPQj1JWTT8859LTdk5z2IUxMyNPnhvHT68i7776DUhi1AUKeGqM+u2l9EQ308RP1mkHofUlHvz/ox3B8kPtAEDvK+mFy/x3s62PPLrs6G+NW/d3w/UNvqUDnJmAfNyvJGnpL61fo/bappQZdCI29paWM200frFTGzYRAsY02RtKBlYXwNGOgsCe5ot6NcbQIt1y+oNnczf+Zf80RYBONPx9MZH1/xyXkQS4tBHcyVWFi/rOOKPEd6S1xk4vYnQbMOocpRkqrfIvIok7OPYBeYXKNMgMdpUrKrubSufbAJX5j0F314lCTy6u6VZRzhI0v9ZyOoeq9q4BY4/QMaWhxgwBwrtgNrC+64eqLrAdl625FXwuhNBkR4z38BsiQ+5w==)

**Comment by websitevirtuoso** [comment]
Yes this is correct behaviour. because component recognize only strings. 
Let's say you passed date object. but it will display as a string.

IN this case to display boolean just contert to string. This is not a bug

**Comment by websitevirtuoso** [comment]
iron: true.toString(),

**Comment by ssierputowski11** [comment]
> Yes this is correct behaviour. because component recognize only strings. Let's say you passed date object. but it will display as a string.
> 
> IN this case to display boolean just contert to string. This is not a bug

I'm not certain about the date example but similarly with an int/number object it displays just fine in the table. Why is that? Why can't that happen for boolean values?

**Comment by websitevirtuoso** [comment]
if you want to get more details and how works code you can open source code and check.

**Comment by rti-Austin** [comment]
Currently, nothing displays for boolean values... so this does kind of seem like a bug (not just a feature request).

From [past responses](https://github.com/vuetifyjs/vuetify/issues/8554#issuecomment-544257467) to this issue, it appears the intent is to have custom icons displayed for `boolean` values, which is awesome! However, it requires multiple, custom templates... one for each `boolean` property/column. For example:

**Workaround 1:** Custom Templates Per Property/Column
````
<template v-slot:item.prop1="{ item }">
  <v-icon v-if="item.raw.prop1 === true"> mdi-check-circle </v-icon>
</template>
<template v-slot:item.prop2="{ item }">
  <v-icon v-if="item.raw.prop2 === true"> mdi-check-circle </v-icon>
</template>
...
````

**Workaround 2:** Convert Boolean Values to String Values
The previously suggested workaround of manually converting `boolean` types to `string` can definitely work, but it could lead to downstream problems with logic expecting the original type (i.e. the string "false" is truthy). The value would likely need to be converted back to the original type before using the data. Additionally, it still requires custom templates for each property/column in order to display custom icons, defeating what seems to be the original intent.

**Possible Enhancement:** 
What would be nice is if we could specify a default template by property **_type_** (not just by property **_name_**), such as `boolean`. For example, the following uses a new slot for items of type `boolean` (`v-slot:itemType.boolean`):

````
<template v-slot:itemType.boolean="{ itemValue }">
   <v-icon v-if="itemValue === true"> mdi-check-circle </v-icon>
</template>
````

This approach could provide an internal mechanism to display a value for boolean properties by default... and also allow them to be customized.
