### ISSUE TITLE
[Bug Report][3.3.9] text/placeholder in v-textarea and v-text-field are not aligned

### ISSUE THREAD

**Issue by yuwu9145** [vuetifyjs/vuetify#17837]
### Environment
**Vuetify Version:** 3.3.9
**Last working version:** 3.3.3
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
load reproduction playground

### Expected Behavior
text/placeholder in input and textarea should be aligned

### Actual Behavior
text/placeholder in input and textarea are not aligned

### Reproduction Link
[https://play.vuetifyjs.com/#](https://play.vuetifyjs.com/?preview=false#eNrtVUtu2zAQvQqrLtwCppQgbYGqTpH2Cl10EWVBiyOLjfgBOVJiBL57h5JT0wra1Mg2Cxvi/N7M4yN5/ZB9cy4fesjKbIWgXScQvlaGsdXAhXPj57iorUGhDPi9aTR6e/dnuY/qGP3CZZV9qrLEN3oR7lF4EKmZsYFrK6HL0StNecq4HqvsOKYkpFj0fO6ghmtobSfBk/unVwhsa3vPNIQgNpDn+TxlEF4JgxRue+xoJDmPkGCCwi1F1FY31qNYdzAPEj1avqG+js2tksAlEFddSD1HXBAbj2Szt86DAyO5Mim7CW2KuGfxjxrSUnGtam9daw31FNm2cfSNhy0tizlOkezqzPWGc/aDkNl3NIzzv3dIQjipwUDRJ7aWmg9CScVFZip4qtx4o6CTr4J7Fdyzgpuk8g/JxXV6462kGg7RdSdCVMwdPz87S/cu4LYDcqSYLahNiyU7d/dfUruzpANlTckadQ/yyIfWlezjPKODhuqcHdnWor4lofRGloy4AJN4D3080jONmd7u0TJd/rPdXIXaK4csAPbT26C0I7myB+ahWbI7gXXLdqzxVrMFPSuLSQNUPiAbDxq7jKHvFov3sfpUjyply2wqxbVw+a9gDb1IDzGXDujoCFVWstESbVQ7rqusRXShLIpaGkqjY60GnxvAwjhdXFFY4XuDStMZsfrqIr/IPxRSBUzNOQTN1/HEg6ciVbZMYFA1JKZnofaRI8LnCWFv4p1YhwjxpHRBeAN47km+4MH/70SztHSqmevJZBF9V5kd8U030W2YUV2HkebrxyZfNPJYLFa6iYC7ZTb2SchjQnbzG6B7fYI=)

**Comment by XStarlink** [comment]
Hello @yuwu9145 , I wanted to update vuetify in my app which was in 3.3.3 and when I switched to the latest my v-textarea was no longer aligned. (It's a pity because it's a central element of my app).

I made a reproduction, and you can see that the bug was introduced between 3.3.3 and 3.3.4, but by varying the versions between 3.3.3 and the latest, you can see that there are several times when the inputs vary in size.

[Reproduction link](https://play.vuetifyjs.com/?preview=false#eNrNVc9r2zAU/lfevENTqOyW7BSSwhiMXXYpgx2WHTT7ORHYlpDlrCHkf99TZMeyo4R0K6OHONb7re/7ZP3YRbVOk49KxZsGo1k0N1iqght8XFYA8w3jSh1eD4tUVoaLCnVrIuM7xuAbPhuukQNjvWPDtPx9XLbphWc4mEyb6psBNOaLZdT5njBfRsOAGdWuKeRh7KDZU1zLIkNN7u9aGIStbDSUWNd8hXEcj1M2XAteGQqXjSlod9k4IsOqFmZLEaksc6kN/1XgOIg3RrIVzTU0r0WGLEOCrah9zwAIgqLDHd4rjQqrjInKB9rDTBANYB80UJkJVopUS7WWFc0EhLG0W19p3NIyGfdJBgQHByDKX9S/pui/7jxPehH4aiHzUC6tfuALitXazGC3gy7PmWC/V88niXbthHgiWfgssMiAwaee1VMJQ1rw2mqtNOzhfhldJWmW29LnRH3o6zUNCPyVRDk8Dk+YrlHbX+AYnBOqz+PVrIx3+AoMKZ6a/8qObfjvzNgqb40VO9N1jPTl/Q+/tbh7YXCoaVmnWigDNZrGXRuiVCQB2Fl870BWX2VTGcxgD7mWJdzQrXPjiKcWtTkeaQIeFjZpcnvqbGd3/vtRQOBwhSud0ejlqq0oLlf08O2r2dDj/ieTW1g8ws4hnCTHK9QZRA4TD4l4w4sGb7twGAHh3NTqJCWWeU5cuDCXvO+OWds09BEcDhEANDhQGM9uuF6cF2u+cOLD6QpO2xJ1cdKepwGEwRLhwehB1M4Tp3tSfLS/i6bxNP4Quf9p9PMPcvXavA==)

Thank you very much for the incredible work of the Vuetify team!
