### ISSUE TITLE
[Bug Report][3.3.11] VAutocomplete comporator don't work with simple type of modelValue

### ISSUE THREAD

**Issue by oruman** [vuetifyjs/vuetify#17997]
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Firefox 117.0
**OS:** Windows 10

### Steps to reproduce
Use comparator function for select item by ModelValue with simple types, example number.
In version 3.3.10 code in Reproduction link work fine. But when change work with comarator - return undefined for get value by item-value. In code don't uses v.value.

### Expected Behavior
Show "b"

### Actual Behavior
Show "2"

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUsFu2zAM/RVCFyeAba3NTkbcdt+wY92DbCubNlsSJNrDEPjfR8kK4iYYUKAnm++RfOQTX8/sm7XlPElWsSPK0Q4C5VOjAY5zIayNvzHojEahtHQJWjMmNJ2hKonyAgPMxWh6OdQNi9+GXalKkYgnJn63TACKWQyTDGz/rijCNMFohRNoHGWEwMTgmskv0/LbcQOybnPkmy0p9J1TFsFLnNZlVeiLcAYnT7DAyZkRMjIoC+kA1NdjHNZDDa+r4BlUX0H2kOWACgdJ/yKDJX/HPm7Y9o49bNjuwr5tNaOXpElz7R73W+bqBdE7kUO7h/oJzquAOhEGdV0H2NGeTgO6Kb1X6hAL4fkZsmxfovmOTukfO1K55vQhp/1fTmpMjUioD9gSzF7tJWNZzlZni1HY8pc3mi4uTkivHQm6huoyc8PI8RA37Cei9RXnXa+pjCxQsyu1RK7tyF8ojbtJoxpl0Zvx5VAeyq+8Vx63cCn9WLTO/PHSUZOGJe+jDKrT3w9Ipcyo8PBllUhYMYjWB4273pwEZ+kKJ3UvnaRb/dhKN2XbtW6ou9WS9QsZPij929943fnoczrcz+4cu6VLXdiSszgoSa8V7O0f1N9l6A==)

### Other comments
 Bug added by this commit https://github.com/vuetifyjs/vuetify/commit/ee84fbbb529216135c14cd6fd979bdf637cfab83

**Comment by s-rigaud** [comment]
`value-comparator` props is not called since 3.11 see https://play.vuetifyjs.com/#eNqlU01vm0AQ/SujvZBIBmS7J2SiVK166q3HkMMaxvWm+6XdhapC/PcOC7YwziFSxAEN7828mXnDS8++Wpt1LbKCHQIqK3nAp0oDHLrUo8Q6jAFAlyrToCwrxq04uVaEik1IISjPT8CPEfgpfBD69wWX/BjzfsVqwOEme0xOgwgSiaK5wmvZjssW09ooyx0PxhEumm/X8MJzGFqnU3N8m3vNY/t9fx4GsJU+5IuxKPS1EzaApzQbmUJZ4wL0VOkEA3VnFCS0kWSkA9RGe+r6djYo4WWS70E0BWw3MPZeQGKRuwSGzRLdXVFurcQ1vL/CR67pueCv9/LfMXAhSf39whuiS+ModthQZJ2oCd1lOxhW00QTqBAN/XBb/XHJPM+URJsANZeS6t4QlpYQ92H0k7YxvnaPUD5BP416zqKfREnmMkv7In+biQbKspySKRgZ1Pchnzwjt9iGTXalitvszRtNdxsV6Dgi4CtWXDQrRjaOccXOIVhf5HndaEqjQxadyzSGXFuVPxMtd60OQmHaGPW8z/bZl7whr5efM/QqPTrz16OjIhWbXYwyQZz+fUBqZkaF7XaSmL+l9KP4UeOudk6CHbrUoW7QIZ3+x0ZapS3HWkF3o82rH2jhUug/frXr2sc9z//AZ2eO1eaLH9iwYbFRkp4y2Ot/vSiKtA==
