### ISSUE TITLE
[Bug Report][3.3.14] VTextField ignores every second keystroke

### ISSUE THREAD

**Issue by hhmarco** [vuetifyjs/vuetify#18175]
### Environment
**Vuetify Version:** 3.3.14
**Last working version:** 3.3.13
**Vue Version:** 3.3.4
**Browsers:** Edge 116.0.1938.62
**OS:** Windows 10

### Steps to reproduce
Enter a text in the input field

### Expected Behavior
Each letter entered via the keyboard is output and displayed in the text field.

### Actual Behavior
Only every second letter entered via the keyboard is output and displayed in the text field

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVE1vm0AQ/StTVAlbMqAqPVEndQ899JZTLiEHAkO6DeyudgdSy/J/7+wu2PijVaTaF+bzvRnm8biLvmmdDj1GebQm7HRbEt4VEmA9JKXW/tEblZJUColmdHlno0x3sNmjS2vflKkTIXVPMCSdqrG9LaKqNwYl3Y/xIoKhNKKUxDHVU8uNnTM7Ns9OujvzlIHzBILrbEacTVsZoQksUq+hLeULY5AtohnR8BOdVoZgBwYb2ENjVAcx7yI+Jo4pE+8ffqyQmGYnXrdELgx/ACZrCc7GhlsHtYjjpWMdeDKraBUFnKQrdfrLKslvY+e6FGOA2efgPc7HSM4uop9E2uZZVtWSy3jTYjCpRMqk7rINp2WmlyQ6TGrVbW7Sm/RzVgtLc3eKtkuejXqzaLhJEa1mMCSa7TugxkyP8GmEGH1JWz5bh3HRO2PAAU3CC6rRoHnvSGdl87HOQhejOfR9Ife8cL64V3u268r6PT9OJP9vZt/NtXoKiBfXck1yhL8paQS2dSCRD2XbIx+wF9KDM0JTgI3XGIf40H1g8REHPraUSvOCjOB8yyk7Z63wWliYLKBE8Hly5STXB2HFc4vwFeKuFgluMYb88JyopokPfWirHZ8rpY67r5tih6JN1Yrq9YTClRa38OHMFervnNSPizlX/L/1/leNf3HRGhv+oNwbpe16B8cd52DJCPkC+7vF0mcGPV9SdnpuytbiPA07QRwL3b+z4brHva6ZcX5EifnW/Fua4J6OeE0vKxJKurHC29W8QqxP6C2nb4IDXFwBWMGsKjTm+59/evaryAuIDzRccvT0B0OqD9k=)

**Comment by johnleider** [comment]
Because you're not targeting the correct property. `value` -> `model-value`.

https://play.vuetifyjs.com/#eNqlVE2PmzAQ/StTVIlEikHV9kSzaXroobc97WXJgcCQugu2ZRu2UZT/3rENCflotVKTC/P53gzzeDlE35RK+g6jLFpabFVTWFzlAmDZs0Ip/+iNUgpbcIF6cHlnLXV7ssmjCmPepK4YF6qz0LNWVtg85lHZaY3CPg3xPIK+0LwQlmKysw01ds703Dy96O7MSwbOEwgu0wlxMk2pubJg0HYKmkLsCMOaPJoQDT/eKqktHEBjDUeotWwhpl3E58QhZeT9w48VEpP0wuuWSIXhD0BkjYWrseHRQc3ieO5YB57EKlpEAYe1hUp+GSnobRxcl3wIEPsMvMf5CMnZefTTWmWyNC0rQWW0ad7rRKBNhWrTNaWluhOWt8gq2a4fkofkc1pxY6fuBE3Ltlq+GdTUJI8WExjL6/07oIZMj/BpgBh8rCm2xmHc9E4JsEfNaEEVatTvHemqbDrWVehmNId+zMWRFk4X92qudl0av+eXkeT/zey7uVabgHhzLfckZ/G3ZTXHpgokMi8g1hdNh3TG3np2RmgNsPZKoxCduw/MPmJPJ5fYQu+QcJxvPmZnpBhaDsmTZMQ4HSlVjqJ95oZvG4SvELcVZ7jHGLLTM5N1HZ/62L1yfO6Uugl83Rg7Fa3LhpevFxTutHiED1euUL9ygj+v51r3/1b9X5X+xUUrrOmz8qSlMssDnHecgbGaix0cV7O5zwyqvqXsVF0XjcFpGrbcUix0/06G6x53qiLG4b16lJguzr+lEW5zxqs7UVouhRsrvF1FK8Tqgt58/DI4wNkdgAVMqkJjUsH0A3RcRF5GdKbhnqPNHyBGEhc=
