### ISSUE TITLE
[Bug Report][3.3.14] VList with selection doesn't work when children is an empty array

### ISSUE THREAD

**Issue by mlankamp** [vuetifyjs/vuetify#18172]
### Environment
**Vuetify Version:** 3.3.14
**Vue Version:** 3.3.4
**Browsers:** Edge 117.0.2045.9
**OS:** Windows

### Steps to reproduce
Using the prepend template the checkbox is added with the needed events. When the children property is set to an empty array, the select functionality doesn't work. When the children is set to null or undefined it does work

### Expected Behavior
Allow the children to be set to empty array.

### Actual Behavior
An empty array causes the children to behave differently

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVM1u4jAQfhXLPUAlTATZU0Sr7nHPeyQcQmwWbx3Hsp3soijv3rGdPwKVUMuFeGb8/cxMsm/wT6XWdcVwgneWFUpklr2mEqFdTTKl/KM/5KW0GZdMdyEI5iVlr01jmGC55aVs213kY0NFTQQ3tj8ilHDgMC8p9v8pHjMuQCy3gkFWZgW7SdaZqFyS02mqJgUwiiSIYBQKBj3TuhAkxmow+OcCZbnIjOH5WDTIBuF9K9CT0kwx6XAbr2OFuPndka06WNSmeHI79OvM8vdj+Z8crZymoAle8ehngJvqdb+3SlHQMKsPlNe10VR7dDXHEAqD6KcJx+txukiY9tXtnck1VxZc2iqsAi9UqS1qkGYn1KKTLgu0gPVZpN4koBpX3g0Avbi65f7wPCb95CGxD1qaXqObeYIWvyCNnjZoCSrsBWVaZ5fnxaqv4jRBm+GUn7mgmsmkR7tCvEUlmxFpQBvhZpCHSaIdnvtoH7lvYIuWlaTsBB2mM/nbr8rf3pO//Uz+QP8NFzFaykqImYH4qwbiewbizww45ge0H9zOhj2FDcUrHFaUFJla/zWlhA+bVwQvmk/AVyfpNaYYVtedU3y2VpkkinIq4Rq8b7zWa8lsJFURvUFZpCtpecEILYu3eB2vf0QUXqlpeM1MQY66/GeYBpAUd0I9jeWnywNUXaVn2HQUXYyI7Ggcxw12BIQ10wT6Rplm+lFLs2tTW7PUjTXH3qayhYYLLt/NrNe58X3u1uK7nj1aN+wWtyvshQJ1uIEPH2r2A48=)

**Comment by mlankamp** [comment]
The empty array causes the children to render differently:
![image](https://github.com/vuetifyjs/vuetify/assets/8513556/3c8ca797-06ac-4e7f-92d2-0514b3703514)

**Comment by mlankamp** [comment]
I did some research, and maybe  here https://github.com/vuetifyjs/vuetify/blob/08c806c013b48943687dfee61d174d90f50f3a38/packages/vuetify/src/components/VList/VList.tsx#L59C89-L59C89

we can add an additional check, to see if the items is an array and has items
```children: type === 'item' && children && (Array.isArray(children) ? children.length > 0 : true) ? transformItems(props, children) : undefined,```

**Comment by KaelWD** [comment]
I believe this is intentional so you can load children on-demand: https://play.vuetifyjs.com/#eNqtVktv3DYQ/iuEcvAaWEkp0l4W3iBBm0N7KpC2F69R0NLIYkqRAkmtkRr73zt8raiHs24SXSQNZ75vHuQMb5+y931fHAfIdtmNga7n1MDbgyDk5pjTvnef7qeSwlAmQAWRE3KmDTnmnayB72QPAur9IbMfh4zsGAJq/HfvQ3Y2RNNIRV61QGtQqPVEeiV7TU4TzTNNblGQ654Jy+F0Z5op7jFnDapxSWsmHoqW6o0zKY6UD3CN7r3C8EDUMwTHh5oPCrTOK6aqgVNFkBQMqI4JC67Zv4DguqOcI1I596KcZHIUJ5GkyViqR9WYfvyd5t9KfHkm1virK8V6QzSYwVePdb1UhjyRSnb9YKDeEgUNOZFGyY5cYe2vrCHBdYHVdMUie6uzufX0T9EtwwyHHbn6U4PSV9sodilF8TAVVy3jtQKxI7d3QXhy77vrlDCUKFAKeCQfwWyuJzp/2y0VnbLmcSHIY2ib4OqDRRj9VpgMJTyK3wCpO8Qma4PixMKjozN/UY74t3dJrEUj1QdatdZkALJ/O5phthuySXgKJio+1KC98nVCkTjmeYp+0AHUReif0/jpncKNOXCDTtWN3rhqeaqtr0Nian3x2kWsRcFBPJh25sYX+QlwDVP9eKp8iLSuF1aENGCq9udAG9YL0+J39GWWOfukmVv1ZsmOnQdP5qriLHa7T8JnqndaS/YoTFxCAJ+pdPdYTftuBlEZJsVYlliQGCRuG7IZDxmRjT9sSTFsxaws8u33M4xk01i9s7vehwlEjHVi+8wWOit/aRNdR2b/m3CfX8EPz4Ld4Ajq19BPvlsvGV2bbJ6I977GJj0apph0ubSKu8BO8X+TrSC/SJjipDSfUCOvlxqx21ymoAIuUKDGZYrYdecrq3n7UDMj1XriYGXtKzP3sWOmvZA7vabz/7J3icbm7wU06xmcTTO/56n+LKqxC6y1v+gzfaTMDRfyO45gpsEeMMmPbpbgLPqDdSAHE6Vb8tPr13YePnOAk3M2Pb4r/X85FOcDoqO9awkrc+35tnJGm1WlKAprNMvxysVgMevWxs5K41tp2XPLOGMHvKtNOtVN6e9KeEvKtpm/JuUYfvFJS4H3YYeAt1e3gHfNXcQ8ZHhpsv+HrDWm17uyrGqBZjiL2FEVAkwp+q58h2qlGoTBeuJp7d69Kd4UP5Y1XuxScQG6y++VfMRCIsghCzlxNIY1n19AFTQdww+BIshyTu+15Vhgl37n5FgKvIKDemlIM7M0rNnSIrSQ+hMmnDPxj57lutIuz6GjfGvMDi0c0VN22mbOUaT2Ftndf0L/3NI=

**Comment by mlankamp** [comment]
I will check if this conflict with my proposed change. If so, I will close this PR

**Comment by mlankamp** [comment]
Closed the PR, doesn't work for an async scenario

**Comment by mlankamp** [comment]
Closed the PR, doesn't work for an async scenario
