### ISSUE TITLE
[Bug Report][3.3.5] v-data-table @contextmenu:row  is not working

### ISSUE THREAD

**Issue by teguhsatria892** [vuetifyjs/vuetify#18197]
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Windows 10

### Steps to reproduce
with that code i just wanna rightclick event every row

### Expected Behavior
if do right click , the event will trigger

### Actual Behavior
nothing trigger

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVMFu4jAQ/ZXIF1iJJOy2p4hdUbWXlXa/oEErEw/Ei+NY9kBbVfx7J04CIWkQh3IJeXme9+aN7ed39mBMdNgDS9gCoTCKI/xKdRAsDiE3xv/1L1mpkUsNtoE8KDjyEPlaQQsGQZIDF2Ddz5Q9v5/h/g8lKkiCyUOGstST2TiTK7nVxHTILV4jutJ6L0mw4crBFeYO3qggr6U/px1Hlt/SkuK2CH4/fXFTaPc39FRp/5PiWskXKTAn7o/5fIx2XKWsM1JJW8MPdMgey6MOl1QQ3HiDrd3WORkfMo9D6MLestqb8IoF6H1iyxcymnMtFDzW+F/CL/lKZrtLZoWcOec9Hnc3eXsaCLw8DhVSn5ZF3DlF9OoyKw16ErwammUgYMP3CtvgCsC8FC45B9lxNIUDaJwFVf7fulGTvCsVRKrcTicKNvj4h+iThtnyznt4kMdoZY9HxvrnU+11eqrYU7Zym6N3OiZdP2mCi/gUBZsxWVRZhAU30X9Xarp9vIW0+eBSdgokZXQ9Ve80K0TjkjjOhKZlApQ82EgDxtoU8ZJosd1rlAWEoiyWd9FddB8L6bALR+CKcE2zd2CpSMoao14G5ebtBqmGSQr30TzkyuQ8+l4rNZ9CxdeukhpIxKR7ABta0HRLgr21s96ybne9T4MOmwkcKXcl9c71Is+cj7s521/Uui9aVVxVwscZ837JwcVCtvoAGbbZSQ==)

**Comment by MajesticPotatoe** [comment]
atm there is no `@contextmenu:row` in v3 of v-data-table (`@<event>:row` from v2 hasn't been ported over)

**Comment by martn001** [comment]
I would expect that the `@click:row.right.prevent` would work as well or instead of `@contextmenu:row`, because `@contextmenu` has now become really specific for the KRow. (you can also use `@contextmenu` for something like VImg, but that doesn't make sense if you can do `@contextmenu:row` on a VImg right?)

Something I was still searching for was `@contextmenu:row.prevent`.

Will the documentation be updated with this new feature?
