### ISSUE TITLE
[Bug Report][3.3.15] disable option in Vselect feature doesn't work anymore.

### ISSUE THREAD

**Issue by velly** [vuetifyjs/vuetify#18192]
### Environment
**Vuetify Version:** 3.3.15
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
1.  Set a disabled property on item-disabled props and item values.
2. Disable not work

### Expected Behavior
Items Can be an array of objects or array of strings. When using objects, will look for a title, value and disabled keys. This can be changed using the item-title, item-value and item-disabled props. Objects that have a header or divider property are considered special cases and generate a list header or divider; these items are not selectable.

### Actual Behavior
Disable not work

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVU1Fr2zAQ/itCDLKBZTG6vRivtJStL6Mveyp1oHJ8adXIkpFkdyP4v+8kx46TQpM+Wfedv++7O50etvS6adKuBZrR3EPdKOHhstCE5B1zoGDlQ0BIx2pTgfpR0B1KBzx7ltoj+vhpOyRS51GiT8gEiLK0/eNEkGjjkBG/IxoC5qVXEByCwkGmE6oNmSB1kKikE6WCCnPjccwrUcZ6/xzU24B10nnQnoXKB9CCb61mpnyZ+nVSPylgSmoIwGXOx3ngdHI+GxWGbmVlExKEwN/GWE8qWItWebId1CrhxecvYzQa7mP0i9oZ2ZLYfUYWv5SxshKLhISuA/B7QfpkT4kDzMjDHiEn6AkZh5QRb1s4kJuTb8HYJzkj316fT76D0gq3mbHvfp7PvhFKro3Vc/ebD7m/kntjNzP3+/fZy+ncD4chiUHOp5ulCcVd2Lj0xRmNjyVeXUFXDld4uoOCPnvfuIzzVaXxT3wwsrOpBs91U3N8Zl6u/11dpBfp1+8cS/IjxnBbXRrVgtSy0D06yjosE6tFc2Q7JKL1bocKikohPlHDFf7Gbau9rIFVpo7FfBtqmcEpuJqV1rw6sChS0N2Mok0o+Ayrk+2ixxttjoYdWGZBV2ABX/t5LR3R5m0dpd60trvsnvYJjTSc/FAzXf4HIuukIg==)

**Comment by websitevirtuoso** [comment]
Just add prop "disabled"

**Comment by velly** [comment]
https://github.com/vuetifyjs/vuetify/issues/3079
[Feature Request] V-Select Disable desired options #3079

**Comment by websitevirtuoso** [comment]
if it never worked in v3. then you have to create feature request

**Comment by velly** [comment]
> if it never worked in v3. then you have to create feature request

Yes, I would like to keep watching the status.

**Comment by mlankamp** [comment]
use ``props: { disabled: true }`` instead of ``props: { disabled: true }``

https://play.vuetifyjs.com/#eNqdU8Fq3DAQ/RUhCtuCZVPSXowbEkKbS8mlpxAvRF7PJsrKkpBkp8X43zuS117vhpI0J2neaN57M5LuenppTNq1QHNaeGiM5B7OS0VI0TEHEjY+BIR0rNE1yG8l3aN0xPNHoTyi9x/6MZE6jxRDQmaAV5Ud7ucCgTIOK+I6oSFgXngJQSEwHGU6LtuQCVRHiVo4XkmoMTdtp7zkVfT768ivAeuE86A8C85H0IJvrWK6epr7dUI9SGBSKAjAeZFN88DpFNliVBi6jRUmJAiB30ZbT2rY8lZ60o9sNff846cpmgQPMepF7pz0JHafk9UPqa2o+SohoesA/FyRITmUxAHm5O6AkP8pXx6+Bm0fxOLw9SXujdUGBXoyjTYn3rZAhn/y3EBludstiG6+v4voikux1VYtPV2919MzudV2t/B0ezyJ9bwfxs2YxKDI5qulCcXHsHPpk9MKf0u8u5JuHL7h+RJK+ug9+suyTa3wJP4Y0dlUgc+UaTL8Z15s/1ycpWfp568ZtuAnjOFzdWlkC1TrUg2oKJrwmljDzYnsmIjS+0dUUmQK8SseLvBYZlvlRQOs1k0082X0soBTcA2rrH52YJGkpPsZRZlg+A1Sr7aLGi+4MxTswDILqgYL+N3f1tJJ2bKtk9SL1vaXPdAhobEMJz96puu/J3ikOA==

**Comment by sebastianvitterso** [comment]
This is not documented anywhere for v3, which is a shame. Any chance it could be added to the documentation?

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/components/selects/#custom-item-props

**Comment by MaciejJanyska** [comment]
Please correct the documentation as the current use of the 'disabled' parameter is very misleading.

**Comment by KaelWD** [comment]
Where is disabled being used in a misleading way?

**Comment by MaciejJanyska** [comment]
> Where is disabled being used in a misleading way?

Here: https://vuetifyjs.com/en/api/v-select/#props-items

> Can be an array of objects or array of strings. When using objects, will look for a title, value and  🫸 disabled 🫷keys.
