### ISSUE TITLE
[Bug Report][3.3.17] How to use link tag in Vuetify 3 Expansion panels 

### ISSUE THREAD

**Issue by mursalin3sit** [vuetifyjs/vuetify#18338]
### Environment
**Vuetify Version:** 3.3.17
**Last working version:** 3.3.17
**Vue Version:** 3.3.4
**Browsers:** Google Chrome
**OS:** Windows

### Steps to reproduce
How to use link tag in Vuetify 3 Expansion panels inner (text) variable

### Expected Behavior
Skip

### Actual Behavior
Skip

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVk1r3DAQ/SuDzmubZhcKwQ0Eemigh156qnvQSpMwRF+RRmZD6X/veF3vbkkL6SGHhD1Jnqd5M5r3EP72Q5VsuuuU2rGiulQ9o09OM14NAaC3NO438xaM06V8GBTjjptSt0zssLkAv20uBnX1EW91ddx3J2ljg7ukQ6EYGlnRld/I37AFARib25ilEgEFWA/qiFze4+MEnMb2fUjwRrr/Iy59SvhzzOiBUqkebHQxQyEG7ZFXYGIoaBi5ZtCWEhVD4Q7QkYAFrSQAUi0+WqHzSZIpGLJka2CoDE5vhR6QZ2oEr++CBu3ooeoWvjJgIC/c4GnajPKp/QoeKhUIsXCuFnCH2RBrllFAdU57E2fm6RAVmirtKSnJYUAtjXvpKc4XkFLcHm9+GLEMOcfKmBtH4R44yjQ6UepT9Nh3J9BRlO6JKouUT5FJy+fYg5vN4pFrY2K2wrC45J8+gVFn0mESUC9JQnB2z4u756U9cCM1D6/Ec/SnKWFQB3L/2GzOVngLVvgSkzxC/+OFtM84m+E1mGECZmX77uTHQv1cqXW7bjdqXt+9V99/AS+D20c=)

### Other comments
Skip

**Comment by KaelWD** [comment]
Use `<v-expansion-panel-text>` instead of the prop.

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
