### ISSUE TITLE
[Bug Report][3.3.22] v-menu doesn't close when menu item opens a dialog

### ISSUE THREAD

**Issue by zub0r** [vuetifyjs/vuetify#18526]
### Environment
**Vuetify Version:** 3.3.22
**Vue Version:** 3.3.6
**Browsers:** Chrome 118.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
- open the menu and click any menu item to open a dialog
- close the dialog
- the menu stays opened

### Expected Behavior
the menu closes right after the dialog is opened

### Actual Behavior
the menu never closes

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVE1v2zAM/SuEL22BOF7X7ZK5BpJhxw277LTsoNiKJ0CWBEkxGhj+7yXljyhu0QI9yaIeHz8e6b9d4myZbY1ZtyeebJLc88ZI5nmxVwB5JVooJXPucZ94/uTTkivPLTQsvf+0TwJogBUNV6dN1wGd0Pd5RsbxvU2DFQ9dcYlcdJ3dETBFRYiT2m9Y6UXLvLaI7cBYbRz0kUPgPHgFLbOCKY8wffJSKF7tEyQ5CFWhLTiiG/z88esP5FnwuUTNomJnY5tK4fx1JLKkAtFzMwxLL/WPuLhZ+P4ZDnVqKaFiu93G/Zh5K8GkriGu1jCLLV5QL8iR11jRMHtG3Mhx0NX5lRhY8gCIC0LjXNFHCi11Y4rdbpdn4es95sk6TQNeSf9hwsaUF1rkrrTCDB6iMdp6+I6h4Gh1AzfrjC40sTeDcPwpQCp+ZCfpoRsCUXJaYTfdZjJBoFkNl348K+bZBm7v4LGA2xkY5hmOTDo+4e/CR0/Zzvklq7BBU0IvV2ghwNujHgY2HvSg+3KeX0xZbTlX1+tB3JBFGkTrGPf6A8N1NVSvCweSqZr+GbR9g0ajjF3Dbc1/hzpHOUnHb28JuRToXYnoyf/XVSz8Je4IHXiu1aQC/FnyKX9XOqoAEWQluftV8rB+WH9B3em8/5r8ewaNL6SS)

### Other comments
In vuetify 2 this could be handled manually by changing menu model value. (https://github.com/vuetifyjs/vuetify/issues/11521)
This is not the case for vuetify 3, because changing the model value closes all nested components, including the dialog.

**Comment by hanaTsuk1** [comment]
I modified vuetify in the local environment and it works normally

The following are the factors that affect normal work:
1.dialog's activator (v-list-item) [click event](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VOverlay/useActivator.tsx#L101) called stopPropagation , causing the [click event](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VOverlay/useActivator.tsx#L179) of the menu content (v-list) not to be triggered.

2.Closing the menu will cause the dialog to disappear altogether

Solution:
1.The function of stopPropagation may be to prevent the entire menu from being closed directly after clicking instead of opening the inner menu when nesting multi-layer menus. That is to say, conditions are needed to determine whether to call stopPropagation.
For dialog, my idea is to add ["allow-propagation"](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDialog/VDialog.tsx#L102)
Check props.activatorProps["allow-propagation"] when availableEvents onClick

2.menu props eager set to true
