### ISSUE TITLE
[Bug Report][3.3.23] Long Label Overflow in Inputs (e.g. v-text-field)

### ISSUE THREAD

**Issue by peter-mueller** [vuetifyjs/vuetify#18568]
### Environment
**Vuetify Version:** 3.3.23
**Last working version:** 2.3.0
**Vue Version:** 3.3.4
**Browsers:** Chrome 118.0.0.0
**OS:** Windows 10

### Steps to reproduce
Long labels in Inputs (v-text-field, v-select, ...) overflow  out of the available space. Using the `v-slot:label` with `overflow: hidden; text-overflow: ellipsis;` does not completely fix the problem. In `variant="outlined"` the problem is the most noticeable, as the bottom border also overflows.

### Expected Behavior
Long Labels get cropped or an ellipsis if there is no more space

In Vuetify 2 the too long label got an ellipsis: 

![image](https://github.com/vuetifyjs/vuetify/assets/9094815/b5bc6532-db30-47f4-b5ed-651636247a0e)

### Actual Behavior
Long Labels just continue outside of the element

![image](https://github.com/vuetifyjs/vuetify/assets/9094815/d0dca328-f7ca-4a4c-b07a-f977b3ae8622)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVt1KwzAUfpVDru3KNhGpUxC8koEPYL3ImnQNnCYhydoN8d1Nu7n+eqMOkXlRen6+9px+50s5z6/EmiS813pSbDiJyMLxXCN1/C6WAIsiSJXJa7v2EiUdFZKbQ6gOGlUe3QMKwV/2NibTWUzA5t66ikkLVeMc37ogFRxZOwGQK8YxKChuuH/wUWUSHhSPSReFdMXR55dKrmFZOfC0cei7Y980+pUKagSVztdKBeIwb90Oq05XyjBuIpjqLViFgkGyo7KL7nIQtklok+gTnsFzoVV9gjglsb9A7cl05Hv7OLdQBBaVi+ox9kAexkTRjzV1hxmAMhOOB1bThEcgVWmovhnDqYKbFFUZQSYY43IUVNPXIDmi0FbYUWxOzVrIwIh15iK41tsR1LDlwRcDtIQsZLeFYwdQcTai2MHLvib8/hRCP4b+AMPOn/evCPnHT+6/lM9Yyo3f7BT7bHvtqCKHtaRTirxdkPlkPrkk+/tsTl7eAZQgeoI=)

**Comment by stavro-gh** [comment]
its even worser with variant outlined. because the the border get messed up as well
![14 11](https://github.com/vuetifyjs/vuetify/assets/55558571/75cef5e7-ca5b-4819-95e8-307411081828)

https://play.vuetifyjs.com/#eNrtVlFPgzAQ/itnX9BEYNl8MAtb4pv/wAfxoUJZSA7atB3OLPvvHmVxFF2MxJho4AG4r9d+991d0nvcM6Oz+E6pqNkKtmSJFZVCbsU6rQGSJuRKuV9nZLK2vKyFPkIOLKSu3m2HaPnSA4470YMcaMXOhkUpMIcmrGQucJWyymxSBkvkzz2z4brktSVbbi1SBHnK+sfF6yT+SDLxfot3PpK4RfyS/3wPjI1taoLf4f3XPTA137gmaG3vdvjktsjLBjLkxhBTHhYodkRu7CsKAjZcLWE+Uzv3StlQ40mOr3SgzV/0hQ42fqHaiT6xUjxnIxqTYMrq3zkvial252rdNUd/WmiRbphI4t6QQabJdKksGGG33axRVkpqC3vQooADFFpWENB8EnTppnONBYoSVq3HZXAvECU8SI35RXDlucx9H+TaPRvRc0/iLgLiZodrtogW0S1rvzfRjD29ARe2qHA=

**Comment by yuwu9145** [comment]
resolved in the PR #18637
