### ISSUE TITLE
[Bug Report][3.4.0] VStepper with VStepperItem's not working

### ISSUE THREAD

**Issue by mtdvlpr** [vuetifyjs/vuetify#18664]
### Environment
**Vuetify Version:** 3.4.0
**Vue Version:** 3.3.8
**Browsers:** Firefox 119.0
**OS:** Windows 10

### Steps to reproduce
Use VStepperItem inside VStepper as per [documentation](https://vuetifyjs.com/en/components/steppers/#errors)

### Expected Behavior
The Stepper content should be shown

### Actual Behavior
The stepper content isn't shown

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNkM8OgjAMxl9lqVfZBDwYM0l8Bo/iYcEmkiA2MHYxvrt0qNkSYjit+7Vf/3znJ/RdpY5E0g0Ie9AW79QYi0XZCqFdYoh86D/Vo7WmbrH7IA97i0QBCmFyQ3ONclG2HqcJW9sGDyUwFGkJwplmYMCxWi7NAinHoVSrPyv9bhYr7irT4uRX0SoyY744m4qzmeJg6NfCkcQeMpksjhrAaw25zOUO+N3KDVzeqHGByw==)

**Comment by Mohib834** [comment]
@mtdvlpr It seems that when you use `v-stepper-header`, instead of `items` prop on `v-stepper`, you need to use `v-stepper-window`

```vue
 <v-stepper-window>
    <v-stepper-window-item value="1"> step 1 </v-stepper-window-item>
    <v-stepper-window-item value="2"> step 2 </v-stepper-window-item>
  </v-stepper-window>
```

Here is the working [example](https://play.vuetifyjs.com/#eNqVkd8KgjAUxl9lnOvcSruIWELPkV0MHTSwOXTqRfTuOWd4RgZ6tbPf+fN98N1e0NQ5uxpDu1bCGbiVT1MKK9NME8K7SBgzluMnr7QVSst6QiNsrDQGIQyjhxRF0Au6alAjVtlSXjJwkBwyIJ0oWwdczdavxmjV1XiVswVLi4Z7pYuq/6fqu14c2UyJNx/ooNkt5wbr07l4xbnfiTmaufVNcCBhhI74hDlDycN7BwlN6Ance6R7uH8ASXKrug==)

**Comment by mtdvlpr** [comment]
@Mohib834, thanks! Although the stepper actions are still missing. I guess you'd need to add those manually as well...

**Comment by Mohib834** [comment]
> @Mohib834, thanks! Although the stepper actions are still missing. I guess you'd need to add those manually as well...

Seems like that.
