### ISSUE TITLE
Dialog and Text-Field with Autofocus 

### ISSUE THREAD

**Issue by alvinkonda** [vuetifyjs/vuetify#1870]
### Versions

Vue 2.4.4 Vuetify 0.15.7

### What is expected ?

When you click on the dialog for the first time it set the text-field autofocus fine, but for the other times it won't. Any idea? Thanks

### What is actually happening ?

The text-field dont get autofocus anymore after the second time the dialog opens.

### Reproduction Link

https://codepen.io/alvini/pen/rGWJqP

**Comment by johnleider** [comment]
This is more of a question than anything. Autofocus happens when a component is initially created. Once you load the dialog, it has been created. Any further focusing would need to be done automatically by you, through either specific "if" conditionals to force a re-render, or by manually focusing the input yourself.

**Comment by alvinkonda** [comment]
Hi, Thanks sorry was a bit late yesterday. For any one else who might came across this just adding v-if="autofocus" on the "v-dialog" component and then watch the dialog for changes

```
watch: {
    dialog: function () {
      this.dialog ? this.autofocus = true : this.autofocus = false
    }
  },
```
