### ISSUE TITLE
[Bug Report][3.4.3] VDialog (retain-focus prop) Tab focus is kept on the activator

### ISSUE THREAD

**Issue by ErneMiralles92** [vuetifyjs/vuetify#18779]
### Environment
**Vuetify Version:** 3.4.3
**Vue Version:** 3.3.7
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open the dialog by clicking on a v-text-field.
The dialog is opened but the focus is kept in the v-text-field.
The same happens if the dialog is opened from a button, to see it more clearly open the dialog using the keyboard to click the button(Using tab key and then space or enter key), the button keeps the focus-active styling.

### Expected Behavior
If retain-focus prop is true(it is by default):
Tab focus should return to the first child of the dialog by default.

### Actual Behavior
The focus is kept on the activator.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9U9tu2zAM/RVCz41TIB0GFGmwYnscsA9Y9sBITEZMljSL9gYE/fdSTpzaTtonyzyHh/efR5Mbu3xOqepaMo9mLVQnj0KbbQBYdwtMqX/2PzYGQQ7UnE290TH6eIB/7OT309Z8ur/fmguujEERukX2UR7RCncosVHyEVITU4aXiUsvK/RfFnsm78YAqMqOg1Pf3nNrpqj1mLOCtSwe5pjHHXnFfiQKcMp6Stmsl+O484x2Eq6iQ6EPmt/OmhsoQkoft2E56uwH3XG0x9YXySNwfi69olvtsdg4EBZPSr0EnhZ8pvUlzSCA77GhGjjltgYXfWwgswDWJHegc85khaRtAB0nzpbDAcizgpmcOszliNtcR01J61EtDpYduzYItFI6r9GA5BSJoMZDQEDPf1usZklr68ZZ3y6pLJEmeVWV4jmh1Q0tOufnXGSY5twKwzS/+pjpMs5r2hfr2f5R4jChqkPfEjzBHn2ma5c+m+lCTGq9Vc4AvrdEb6zTLg9nWtwmd1ospzOe+JuXO7OqVtVnU74P1cr8egX0gyxT)

**Comment by Redpoint1** [comment]
The problem is in the focusing element.

https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDialog/VDialog.tsx#L93
`overlay.value!.contentEl?.focus({ preventScroll: true })`

The `overlay.value.contentEl` doesn't have `tabindex="-1"` and therefore `focus()` does nothing (by default `div` can't be focused unless `tabindex` is present). The closest element that has `tabindex="-1"` is `overlay.value.$el`.

So you need to add `tabindex="-1"` to the `overlay.value.contentEl` or use `focus()` on `overlay.value.$el` instead.
