### ISSUE TITLE
[Bug Report][3.4.0] February not showed in DatePicker

### ISSUE THREAD

**Issue by KarlNilsson** [vuetifyjs/vuetify#18794]
### Environment
**Vuetify Version:** 3.4.0
**Last working version:** 3.3.23
**Vue Version:** 3.3.9
**Browsers:** Chrome 119.0.0.0, Mozilla Firefox
**OS:** Windows 10

**NOTE: This is a regression introduced in 3.4.0. Works fine in 3.3.23 and prior**

### Steps to reproduce
Navigate to February, any year (locale independent). The month in the dropdown is displayed as March instead of February

### Expected Behavior
The month picker to display "February"

### Actual Behavior
The month picker displays "March"

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVUEFuhDAM/IqVC6y0AQp76YpFqlT1AT30UnpIwYi0EKIk0CLE3+sFulpu9ng8Hs/7xKwpwqFHJ6sx+LLszGSrO+NggsKgcPi2zmCGynQteBvXy1Wu8HehFp2yDrYBXPaL/jQfcsWOy6EnrQPi0ZXUYasbomW5AkgHLrReyqUhRSekQrNBBNZx9oKfphdmBA5CjTCiMFRKC6pzUEpLeiOWIBW4GqEljRq0LL7RpCGt36QGXtJhvo7g3HYlNnwQTY+XnF1Hr1jlLIM03DH/7RG693dFVvtpePcWtbYwUjuw6Pr1u1u4Bqv7SClO2HLcDFCOxPEV/sAzIb4XR/GJRzGPHrwDJZqGqzjJsvnIkiAJHinlJDgFCfv4A9xPnRY=)

![image](https://github.com/vuetifyjs/vuetify/assets/6853470/39c31aa5-3328-465b-b36b-d16463bf026f)

**Comment by alfianwahid** [comment]
Also happen on the latest version vuetify 3.4.4.
Clicking february displays as march.

https://github.com/vuetifyjs/vuetify/assets/2808896/00a69c3d-cfd7-4dff-97db-42fd89d56ce7

**Comment by louisbourque** [comment]
I've done some troubleshooting on this issue as it's affecting us as well. It looks like this issue only appears when the current date of the month is greater than the last day of the month in Feb. It's related to JS date handling.

In summary, the date picker is trying to use today's date as the day of the month. Today is Dec 29, so it's trying to set the date to Feb 29th, which doesn't exist so JS is setting it to March 1st. This causes the month to show as March, and no dates are highlighted.

You can see for yourself:
```
const date = new Date('2023-12-29 00:00')
date.setMonth(1) // set to Feb
console.log(date) // Wed Mar 01 2023 00:00:00 GMT-0700 (Mountain Standard Time)
```

This affects setMonth in /packages/vuetify/src/composables/date/adapters/vuetify.ts, which in turn affects adapter.format in https://github.com/vuetifyjs/vuetify/blob/7f3ebe8bd94ab68ddca4ae68661f5c08db02eb64/packages/vuetify/src/components/VDatePicker/VDatePicker.tsx#L122

Here is an example in the playground I was using to find the root cause of the issue:
https://play.vuetifyjs.com/#eNqVUstqwzAQ/JXFF9vgZxwICW4hUNqTTwmU0vSgWnJjGstCklNKyL93JTmvHgoF29KOdndm5H09eErW6VKIZD8wb+GVmnViRzS733CAch8TIezWBnXPNWk5kyNkQYrZsWjrT4TL9DYeKxG9LTWI61ymV4ylqmUrNCimB0fbdqKXGg4wKPaASXCERvYd+ChXt823v+EmDbsrDYQSoZmEu1N2EF6O+x1Ldv1H4CSNqUnTy47oEbzAKOCFERlcxRUa2J4BYzIII8jxnWSTaRidWvidSVxyahqgPIOhDPxAmkJFZL21FU5ZM/Batz03lh2D6Ryh4oHrEA6u3tmjaIyzL7DOTJptC0Av8lyZgyVeouRATXR0bChAbxmYWhBEKUah5UCahtVa2SP8KUQyrsG6WPy+vDORjxaKOM/jIvPNLVhzz9gPDUKWG4cF5LNFluEDT9U6zma4CSojEOcAVppwSiSFdds5I3/zTK54VgOHR/YO+fz/PGXqZgynyztGXpEUydwz6xTXtx8LjvW9

Hopefully this helps in reproducing the issue. I don't know what the best solution would be here. Either a check for this condition or always set the day of the month to 0 when formatting for this particular text?
