### ISSUE TITLE
[Bug Report][3.4.7] Time Input Field Misalignment

### ISSUE THREAD

**Issue by timolson** [vuetifyjs/vuetify#18890]
### Environment
**Vuetify Version:** 3.4.7
**Vue Version:** 3.3.12
**Browsers:** Chrome 120.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
playground

### Expected Behavior
input heights and bases aligned

### Actual Behavior
misalignment

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUMtOwzAQ/JXFl4BE4pYikKoUiRt/wIFwCMmmsuSX7E0AVf131k6hOXHpwZJnZzzrmbeDiKGTz95X04hiK2pC43VL+NRYgHoqW+/zNYPOWWqVxXAa5WFwn2BduR+JMMQ/5vRAA5+4a8RDIxZcZgm/qBwU6h6m0rgeNetM3DcC5NJHZqOLnUkZZGv69nhG/y1KmNP95s/ssoA0mfup5aI3hrELyhNEpHGuTxnvAsEBAg5whCE4AwVXXiQ5cBIbCTg67JLiunhBrR28uqD7q+LmLEm/Zk2xXm3Xd/y4lvMqXiKOt2JT3Ver8gOprTZiho/i/QfuUpKD)

**Comment by BlackMinds** [comment]
I will address this issue in the next few days.

**Comment by yuwu9145** [comment]
I'm not sure whether this is worth to fix, as it would be replaced by future `v-date-time-picker`. John will announce Vuetify 2024 roadmap in [this year's Nation Conference](https://vuejsnation.com/), stay tuned with that.

I guess since we have dedicated input type components (e.g. v-number-input, v-date-time-picker etc), it's worth to list supported types on v-text-field in doc

**Comment by timolson** [comment]
Not worth it?  Our site requires time fields and it looks -bad- rn.

What do you suggest we do, other than rip out Vuetify?  We took a chance developing with Vuetify 3.x beta and I guess the joke's on us?  "Waiting for a 2024 roadmap" is not an option.

**Comment by timolson** [comment]
I can put in some time to fix this, but I haven't dug deeply into the Vuetify css and would need guidance for a PR.

**Comment by timolson** [comment]
The native time icon is pushing the inner height to 58px from the 56px used by Vuetify.  We can easily solve our site's alignment problem by either setting the max-height of the input element to 56px or by setting the min-height of the Vuetify components.  I would assume constraining the max-height of the native time component would be a better solution that would scale with larger Vuetify line heights / font sizes.

Sorry to sound bitchy before. I got excited by "we're gonna fix this..." and then reacted to "yeah no we don't care."

**Comment by yuwu9145** [comment]
Workaround is downgrade input line-height. [demo](https://play.vuetifyjs.com/#eNqlUMFOhDAQ/ZWxF3YTgV0xmiBr4s0/8CAeEAa2SUubdkA3hH+3LavLycsemnTmvXkz771PzJo6fdE6GQdkOSsIpRYV4XPZAxRjXGkdvqGoVU8V79GcW6Fp1Bf0Ku4GIjT2DzkPCHDPHkr2ULIVFlDCb4pbjqKBMZaqQeF40nYlg3Stkwahq5WJS3TSdNJ4qf5b5Gvn7td/QNcB+M6ST5GucnOlrQ3XBBZpWOLjUitDMIHBFmZojZIQucgjTwfnpLcEzjocPGMTvaIQCt6UEc1NtL1Q/NWOE+13+f7ODRfpssrfYOkkEGytNDZhad4g6g3v9UBbmBYXwl0fH5F3R8phn2QG5ZNH5qDlFdwom29Zltwnu/gTqUoytpSP7OMHeFOrwg==)

By default, input line-height is 1.5rem. Time icon with 1.5rem probably has bigger size than normal text font, which is why they look different.

Above demo decrease overall line-height to 1.3rem which stops line-height overflow min-height, so they have consistent heights now.

**Comment by yuwu9145** [comment]
Instead of using css override, you also should be able to tweaking `$input-line-height` variable to change vuetify framework overall behaviour if you want

https://vuetifyjs.com/en/features/sass-variables/
