### ISSUE TITLE
[Bug Report][3.4.7] Active tab indicator only animates when switching to a previous tab

### ISSUE THREAD

**Issue by Gawdl3y** [vuetifyjs/vuetify#18892]
### Environment
**Vuetify Version:** 3.4.7
**Vue Version:** 3.3.12
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Have a VTabs component with multiple VTab children
2. Click on a tab that comes *after* the current active tab and observe that there is no animation of the indicator line below it
3. Click on a tab that comes *before* the current active tab and observe that the indicator line animates properly

### Expected Behavior
Active tab indicator line animates for moving between tabs in either direction

### Actual Behavior
Active tab indicator line only animates for moving to a tab before the current active tab

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFkMEKgkAQhl9lmIsFqahBIBp06QXqlh1MVxLUXXbXvYjv3qxrEEF0m5/v2+GfvU2oZBWehAjMyDDFTLNedKVmx2IAyIxfCrGMS9DlQ4Hxe16zLi+QYoErfXNITdmNjGhE7NxKpbNwIT/FmMQLq/hQ/zMTMq/PVn6Ja1KuMwVXOgs/jqGoKtkKDYrp0d3U9oJLDRNI1sAMjeQ9ePQPntUBqJHSYAvk1thEW7vTbaH3OO8wCZIgitEO++CA9xd2KGkJ)

**Comment by MarcHartwig13** [comment]
This is happening to me even when passing in the v-model correctly. I've narrowed it down to line `46` in `vuetify/lib/components/VTabs/Vtab.mjs` which is: 

```
const prevEl = rootEl.value?.$el.parentElement?.querySelector('.v-tab--selected .v-tab__slider');
```

The issue when clicking an element after the active tab is that `prevEl` comes back as `undefined` which fails the check `if (!prevEl || !nextEl) return;` on line `48` This explains why it is not animating because the `animate` function is fired after the `if` check on line `48`

Looking into it more closely it looks like the `querySelector` in `prevEl` is what is failing when clicking a tab after the active tab. What I think is happening is the `querySelector` is firing before the class `v-tab--selected` is moved to the new element.

### Workaround

Ok, working with a coworker and we've narrowed it down to being an issue with with the vue version. If using vue version `3.3.8` or earlier it works fine. If using `3.3.9` or later the issue exists. I'm assuming a change in `3.3.9` may have negatively effected the Vtab component and the `updateSlider` function

**Comment by MarcHartwig13** [comment]
This may be resolved when this issue is fixed in vuejs: https://github.com/vuejs/core/pull/8639

**Comment by KaelWD** [comment]
It was 3.3.11 actually, the first button now re-renders before the second one gets the update event.

3.3.10:
![Screenshot_20240116_222730](https://github.com/vuetifyjs/vuetify/assets/16421948/566ff1db-c68b-45ed-972b-39986b9b9af0)


3.3.11:
![Screenshot_20240116_223046](https://github.com/vuetifyjs/vuetify/assets/16421948/8cacdcab-535a-4698-875c-4cf6f8ab6494)
