### ISSUE TITLE
[Bug Report][3.4.8] v-data-table v3 cannot filter based on a header like in v2

### ISSUE THREAD

**Issue by sw34** [vuetifyjs/vuetify#18914]
### Environment
**Vuetify Version:** 3.4.8
**Vue Version:** 3.3.13
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
add a data-table with a filterable header column like used to work in v2

### Expected Behavior
the "frozen yogurt" row should not be shown

### Actual Behavior
nothing is filtered

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVVN9v2jAQ/ldOkSqoBGGUrl0jijR1Q+rbniZNhQfjHGDVsTPbScsQ//vsxKFJIK3KC5f78fm+z3d+2gda0dH3NA3zDIMomBpMUk4MzhYCYJoPY2LI0JAVR+cAiLZIYlT6fhF4axH4CLO1zh+j1qjMMUA50c6PHHNimBTDcRVyJcOc8AxtXJAEy0B5+Kh+eumKWQ7a7LhLT4jaMDHkuDYRTBQmi6BIKtqmW6TPK/kKFXhOBOOcLALIh4mMkVufth1Rg/Gck1wqW/67THInVwAVZDrb75v5h8N0lPpObV/Wmo5q6k01VSw1RQK+plIZiHFNMm5gX2I6chH0L+F+Bn3vA9BIFN1G0OsNKhclXCqGuuGsVI7gqXJBhVz+nJ62ZK7kPxTwR24yZd7qm8Djr3eNyJpYUW/CL610tbK5V9cNb6qkQSYiuG6lMyWttze+aB66LtRzZLRR5GWFSu0GQLeSSiddPflQs89Re6QIVCFJQBMRvzC67eJ3Nbk95Xd3nl8rtcZv8jl+fuY+w+inXRamOlncXJ2yGHddU7PbI412uqdx+xGND+9oebSaixJBJuzoM4GxzzhceoPKJM1sYvQmhn9V7FrU9FFoMiXqk96SD8Aww52CP8q9aJIBIJxtHE1tyGnwGXc25K6gHVkzbtAy6BfvyAD+Zuim1b1bxd62mrBqrqFvtkyHTQ0abFqsHFjo5Q6ZoDyzu30WpA1xaDs8olGZf67PzV37a3/U7sFPWm9w1AtFbL9KgapB7HUCzImB/uayo96Oa3fpg5vad4qLqe4u/1WO9zsAfgG6IR7tIkD/oqve7UmzeFmZlbP8t7cyHR1f/+AwCCbhJBxPAmdch9+C5X8VwxKT)

### Other comments
I grabbed the base of this sample from a sample posted on discord, there is a workaround shown in discord where you just filter the items

https://discord.com/channels/340160225338195969/1172135840173002762

**Comment by lsdch** [comment]
@sw34 I stumbled on the same problem, which I fixed by passing the prop [`filter-mode="some"`](https://vuetifyjs.com/en/api/v-data-table/#props-filter-mode) to my VDataTable component. 
This works on Vuetify 3.5.11, not sure how that behaves in previous versions.

**Comment by jaysonpotter** [comment]
Having the same issue when upgrading to Vuetify 3. Just like in the reproduction @sw34 created, the filter-mode did nothing to the results. 

@sw34 that discord link no longer works. Did you happen to have a workaround example somewhere?

I also have a non-working reproduction of this issue using the latest version of Vuetify at https://codepen.io/jaysonpotter/pen/KKYZBWW <- is based off of a working version provided by veronika at https://codepen.io/rveruna/pen/gVBJmq

Because I've got flack for using codepen being in development mode before I also created a repro at [VPlay](https://play.vuetifyjs.com/#eNrVVttu2zAM/RUtL02wJM29jZEUGHrZuvYHhrYPss00QhXJk+W0WZF/H31LZMdqm2XAsD40Mknx8JAUpbvXWqi84y9B0F5GUHNqEw2LgFMNZ/eCkMmyRYMgWSYfnhSaMgEqEyVCn2ra0tTlkAsJceZAfVDh9L6Wre5rhpYhSqzzIQxB6YIy1rWeYIVqQRdgqjxOw3gbcFhSzaRodbfqTUgYVE6CLFshl9pxpb9qBwoCEL5hF1tuqeSSokVGUsOLbs0YcL+sJAiykD7wioDzP70KANWxkyo1p26y/SJNB6l2czY5NuMox328E/hBVDzKpWJQKE2JjogWLqi3CN0iIaLnVPxrNjNamfj/j4hHlXtYTS5fqIctZrHbkw0KzAOEn+b4SEXmhMhHCQqLsySWpKOm4AM/Q0+xQCdG8BJIPB4+zGjENXlNncXeHVJvkOkZqWcykpwhhxwdNXNB3tAFIfZFyQjTW5DkI8ohd1ueGxQD6UrJXyDID/kYKb3dX4TuDscFTYI/andK5kkQvYEhXRvrKvRrD4ingC5ISIX/zLy5LYRe/2Q3hHF1CAXT90K4xPHMlBV21NuF7dqo9/fAPY8Cjz6BDbjfGe4C99vFJGS4o334fmXiEZSLSfet2MPRx0kPzNZ4D/w7cL4iLlBhxT6p4N2phh7v02q3knMWyMAKPK6odKddFObAp3sAf5MCVp5cuDbkQcd0tyl1JfLpPqW+kCKynunBsIJvb1id6WF3D9gbpm+oFXfYrWDbszTXyGyGLe5Dtlo3sgWmN4g0+M42oOwBhwPWiFGBjpQwZ2KJAt5ITPMkedmrpt7tdB4JLpd4cBpFVnjFUR7F1jH1si7EqR/fHg7RKoKScsa4BoUXQOKhSX5GoFbN5BmZXAmlqDahp/bkMw77xu5t2dbyVj6DOqch1Kv0THg8wsuhrucsbMdRF7eU9pilLn9Z8naeVdqWqbwTyvo8ISm/qgywGal/SuLOfTTyrMQJtiQs9TchAVUhXAudMt94OJjvFcUesTcGtvchTHH7n5OMN/+FeuJJfIthclQPqyY6+DjL6XSnlvH+jxJ9yJe5MP1dx0+4zaOttm6KiPPk38NvCQ2mcQ==)

**Comment by sw34** [comment]
@jaysonpotter this is the Vuetify playground link that I should have posted.  I used this exact approach.  For my purposes it works perfectly and is clear how it works.

[Filter Data-table results](https://play.vuetifyjs.com/#eNqVVd9vmzAQ/lduSGuIlJCl6VoVhU7Ttkp92p4mTU0fHHMEq8ZmxtBmUf732fxIgIZW5QVzd99x3/k7+37nZIrOvqapV+To+M5SY5JyovFmJQCWxTQkmkw1WXO0BgA/RhKiyoKVU69WTu1hBmvtEeMaFYbfMUOlD37KSWbdyLEgmkkxnTcui5wWhOdo/IIkWDmqGmbtIipTyArI9Jbb8ISoDRNTjpH2YaEwWTllUFk9jZE+ruUzNMkLIhjnZOVAMU1kiNzYMlMR1RjeclJIZeC/qyD75yZBkzK92e268fv9cpbWlZq6zGo5azVxmVHFUl0G4HMqlYYQI5JzDbsqpyXngzuG4Abc2gaQIVE09mE0mjQmSrhUDLOOMcSs7LIP940JmszVY/tpILdK/kMBf+QmV/qI7yaef77ueCJimnrpfeqFq7WJPb/oWFMlNTLhw0UvnClprKP5x+5Po7J7lkymFXlao1LbCdBYUmlb1w7et9anqN1RBKqQJJARET4xGg/xO19cveR3fZpfL7TFb/E+frXm3sPohxkWpgZZXJ6/ZDEf2qZutQca/fCaxtVbNN7co4fDqjsoPuTCSJ8JDOuI/bheUJmkuQn0j83oHSJmPFp9UqhzJUDHLPOaAfAqhFt/m2lq0yhDe4PecgN8aSbJqxl7TFCeG6N7Ajvugv0GfDQfIo6Nqc/Lk1Raw2sUAZppbnVg2Nu0owkQzjZ2fzJNyu9H3JovK5dRR01t9LdaMS04ivAAbgQ1nOCWaHA34wG8kd1r/zbqewVcqnMY/quS6SsJaiEPp7gzggb34xDe6r0LfuhvWfNOUMcyNDPQU6db3ioT+JujPbvsLXZqb912fSUEPgQgcs7h7KztK/MM+PQ2RRnV8CAIymOTic2oF2eL8Mx52pJxiM8/I7dMPjbZAzAX77BOq/feXmOHq8vZT5yFt/AuHPs2B/x0jZp4c+fhP6YCVr4=)

**Comment by jaysonpotter** [comment]
Thank you for sharing that @sw34!

**Comment by jaysonpotter** [comment]
I've also created a workaround to share while this gets worked out that supports multiple filters: https://codepen.io/jaysonpotter/pen/abxYgbp
