### ISSUE TITLE
[Bug Report][3.4.8] VDataTableVirtual displays only one row after reloading of items

### ISSUE THREAD

**Issue by 09Skyfall** [vuetifyjs/vuetify#18926]
### Environment
**Vuetify Version:** 3.4.8
**Vue Version:** 3.4.0-beta.4
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Scroll down the list until virtualization is 'activated' (as in, rows start to be replaced in the dom)
2. Set the items to an empty array and subsequently to a new array with new items (to mimic a fetch)

After this, only one item is displayed but if you start scrolling the items appear again. 

Notice that this happens even if items is not set to an empty array but instead any array that won't completely fill the displayed table. In this case, the table will display as many rows as the length of the array assigned to items before the fake fetch.

### Expected Behavior
The table should be completely filled

### Actual Behavior
The table only shows 'n' items where n is the length of the array (or 1 if the array is empty) that is first assigned to items before the fetch result is assigned

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptU02T2jAM/SuaXAizkGS79GNoYNrpqYeeujfgYBKReNY4GVuBZhj+e+U4kLCzlzh6kp6lJ3lzCazJ4p91HZ0aDJZBSnislSBcbzVAepqLuu5+OyOrNAmp0fRQB+aCxJzEXuH8JA01Qt2cAMsSRY7GrrZB/7cNRl7Jtzlfd449JcqiJPYskmSMu8D5SagGXVY+uNZp/FElXOeo0j1p+JEpmb1xdqV/lUIX+NvfDZZa5ViPwhRSz6mql/Apqf9tg3uzAFmX0pVh78R8MzPfVGLrUSaHeBXTeKQumzYzsiawSI0XWR7ryhBcwOABrnAw1REmPJiJb4N5LYEROmd8BeEUVmsI/wgqIw8y8gTP04iqv2SkLsKXL9PINnvrra/TgSUzyHW45gemC8h82fMzdP0w3HK8duEX37D3d4qwZ7Pz6KEyECpkB4PJdz5S0Hw8PU1viX6aNqobW4YDfzjtrgW4+sOwOkYPkjM8lHW7lvUaUdjwc+JYhrh++frIzQVIksIlTGQ+mYFQstBsWBKG2H7D1rvgunugediZu259P3EMryWCsJbZMIduTSETGvaMauDRUwvCGNFCKDWcS5mV7LfIvKrlD4KpznCWSrmUXFrelRbzXg/mZ1GFvnGcy4pTFeqCSpjoiU/UFQ+r4i1DQiY9OIy4rDsbdA/kTukqoVJaX4iL7PyerE/y9bkrOr37evz0fJfD4HmZX+URq4bCB3Xex7+bVj/yGTwnibd4zmnsXwi/jeA6C16iRZTM90giWgTe/Bbs/gMOF4H+)

**Comment by UglyHobbitFeet** [comment]
I'm experiencing this as well

**Comment by UglyHobbitFeet** [comment]
Hi, is there any eta for this being fixed? Thanks!

**Comment by IceflowRE** [comment]
The issue only occures if refreshing when the scrollbar is not at the top.

**Comment by grolu** [comment]
I have a similar issue. This also happens when filtering the table. See this reproduction link: [Vuetify Playground](https://play.vuetifyjs.com/#eNqtWG1v2zYQ/iuEMSAOECWObDepkQ1ouqXD0G5DHKwbmn5gpLNFhJY0inLtBfnvO9J6s+xj40D5EIt35PG5Vx755amXqeDsXZqeLnPoTXpXGhap5Bp+uo8Zu1p6Idfc0/xBgrcUSudcGgZjkwh4CCr78b5XfN33Co5AGYZuf0tqBGIeaaSOB4OSZiZ4Sy5zQHrMF7DFqFf46arkzMQKQmSZHYvtMuAqiHDeTEiNVDtzA/9sH/4NKxRLFkieGaAL7o1Z6M0k4D6WbVXPvgkdRGzpLZIQJM6TkKE+LEhkonCYKrHgao0UyR/shI84gV0nXJtpZ7UkDSvtzQTIcENi9dbSG5e6MbbgK++bCLXRZjgY1GoztuRK8NiYI49RdyliCGvuDqSSUSK7sbZhd8YQDaGVak3bofWM5WrQhTHRZPh1ddYIERxmgRKptlNglSZKsxBmPJeaPW2EGQ/0j8sRYwp0ruJ6bJxqNp+wo6OTmlhE1YR9qWmMPTEttASca8zM7tYpHJ0wLsU8RlqmudI4foQ1jkxEHbHnhszm+mkKELL+Y5zo7JiUkZlZtJCPEM91xPoLWoK0U2gRfyoRAOv/QEtApwYORf7B+CfXrg1za+nXxveDCdW2hZsDxowRS2tl6KWmi8yfNdCEDcct+kbtCfP9FsNqgwsG5q/FM2hxycA/32K0NN8L8I8AePyJOyD6FMQd7AVErFQOiNuMl0D8K1nzOQ2vvVMJb0TAu3DBO397MLzPfAm3eRyTCEcUwtZmFULfWpAy4HZgvAThFPi1AvgPU36/CS8pD2/HUwVw5AJ4vi3tJQB/5eohUR9yrkICYktoDXHchlFAvHR6+eJwG0oRPN6ImMrjIZXHIyKPnT4+PI+nOlEL9DJ/pDOlXVIqN7eNW2B803EifxZxOOVCUj6mCs2YyOS3HWfyDZbBOxFSaTLcjpqGj4kY9G0QdpfH7/7N+W+Ah9R+eJR7/XZsliHodxuC19iQmmJIhd8bKvwI842c5js8/KZ5/D7iGZ0f7VStThIC4NhlwFfE3y3A7JdVii0piXHnyKhyhOgXLp2l+vA6aPJjmqs5mSSUl1sBVUfhebdJ8gkbfjyL/6acTCXxkCjUI1sFu8uSnwHSTUdDIWwbqgpDwsUXHZ/Gd5G9KjlSeefA+G5HY0t1hx1NhDnibLp2ikoVh8RhN7KddXfVxjbW15LTXRfVMuykUHkcuzLlFeXmfaK4dHmZCsSdSl6asOO7yVTIJShH00UVbJ8IQ2ff+poTxTRdt1gRySikEoVsC53V5vBE+R1SncfgLjhU4zAiQF50fO7hwTwFcDSu5P2E8PPYRmJ3FfGDRB87L8n0HY8oN769hh7u6OYzhHlXm7AZlxlU1OfNR7kkSBZprg3CSjP7vNh8WELSjPV1JLJTI3GLUz07WbZ99zjN8CoE/cEJGx/XE4t9966osBWgNr+44uqsegXrPZ/EuZT239f/AcyfKWc=)

You can either reduce the items using the switch or filter the items using the text input. In both cases the table will not render all items after resetting the switch / filter text. This only happens when the scroll position is not initial (at the top). The issue resolves itself if you start scrolling the table.

I hope that this issue gets some attention as it is blocking our feature right now. It is not even categorized as bug yet.

**Comment by 09Skyfall** [comment]
@grolu A simple fix for this is refreshing the table component with a key when its items change. Although not a good solution, it should work. See [example in vuetify playground](https://play.vuetifyjs.com/#eNqtWG1v2zYQ/iuEMcAOEMeObDepkQ5o2qXD0G5DHKwbmn5gpLNFhJY0inKcBfnvO9J6s+xj40D+YEl35PG5Vx757amTKn/wPklOVhl0pp0LDctEcg0/30aMXaz6Ade8r/mdhP5KKJ1xaRiMTe/h8d1tB/9vOzklBB6ASpGav5UcgVIN3T4LaghiEWqkTobDgmYG9FdcZoD0iC9hi1HN8JJ1wZmLNQTIMivmy6XAlR/iuLmQGql25EahwT6NNqxArJgveWqALnl/woL+XAKuY9nWGOmD0H7IVv1lHIDEcRJS1If5sYwVfiZKLLlCizDJ7+yAzziAXcZcm2GDSpKGte7PBchgQ2LV0rI/KXRjbMnX/QcRaKPNaDis1GZsxZXgkTFHFqHuUkQQVNwdSAWjQHZlbcNujCFqQkvV6rZD6xnLVaBzY6LJ8O1iUAsa/Ex9JRJth8A6iZVmAcx5JjV72ggzHugdFV+MKdCZiqpv41Sz+JR1u8cVEWNtyj7iMidR/NA7qnHyeJuybxWNsSemhZaAUowD2M1jAt1jxqVYREhLNVcav63Urom1LnuuyazPnyUAAevdR7FOj0gZqRlFC/kM0UKHrLekJUg7hBbxpxI+sN5PtAR0t+9Q5B/MDHLuo2FuTf1ee78zQdy0cP2DMWPEwlop+q/uPPOzBpqy0aRB36g9ZZ7XYFhtcMLQ/Bo8gxanDL3TLUZD870A//CBR1+4A6JHQdzBnkPEGuaAuM14CcS/4ke+oOE1VyrgjQl4Zy54p28PhveVr+A6iyIS4ZhC2FisROhZC1IG3A6MlyCcAb9UAP9hyu834Tnl4e14KgGOXQBPt6W9BOCvXN3F6lPGVUBAbAitIE6aMHKI504vnx1uQyn8+ysRUXk8ovJ4TOSx08eH5/FMx2qJXub3dKY0S0rp5qZxc4xvWk7kryIKZlxIysdUoZkQmfy25Uy+wjJ4IwIqTUbbUVPzMRGDng3C9vL4/b8Z/w1wk9oPj3Kv14zNIgS9dkPwEltVUwyp8HtDhR9hvrHTfIeH3yyLPoQ8pfOjmarlTkIAnLgM+Ir4uwaY/7JOsFklMe5sGWWOEP3CubNUH14HTX7MMrUgk4TyciOgqig8bTdJvuBRAPfivyknU0k8Igr12FbB9rLkI0Cy6WgohE1DlWFIuPis5d34JrSHKEcq72wYP+xobKlusaMJMUecTddOUSnjkNjsxrazbq/a2Mb6UnK666Jahp0UKrZjV6a8otx8iBWXLi9TgbhTyQsTtnw2mQm5AuVouqiC7RFh6OxbX7OjmKbrGisiGYVUopBtobPaHJ4ov0OiswjcBYdqHMYEyLOW9z3cmGcAjsaVPJ8Qfp7YSGyvIn6S6GPnIZk+4xHlxrPH0MMdXb+GMDduUzbnMoWS+rx5Kab48TLJtEFYamYvHutXTkias54ORXpiJG5xygspy7b3HicpHoWgNzxmk6NqYL7u3hklthxU8XzgeIPoRmaF4JUMe1e77dovDxFcDMr7ts7zcZRJaf++/w9NAUtb)

**Comment by grolu** [comment]
@09Skyfall Thank you for proposing this. However we have real-time data. Most of the time the item data changes. Sometimes items are deleted or added. However, we also have views where items are added and removed more frequently as we only show items with a certain (temporary) classification, e.g. error state. Changing the table key would trigger a rendering of the items and also reset the scroll position. So this won't work in our case.

**Comment by 09Skyfall** [comment]
@grolu I see. Hopefully this issue gets some attention.
