### ISSUE TITLE
[Bug Report][3.3.11] Not able to user select entered text in v-select search

### ISSUE THREAD

**Issue by nyfer** [vuetifyjs/vuetify#18972]
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
1. Click to open dropdown.
2. In Search placeholder, type text.
3. Now to try to select it and it doesn't allow to select

### Expected Behavior
User should be able to select the entered text in the search placeholder.

### Actual Behavior
User is not able to select the entered text in the search placeholder.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVl1v2zYU/St3eokNRPa67smwMzTZkgJrt6IpMGB1H2jx2iJCiSo/lBiF/3uvKEsWaQVIizxYPPfjnHt5Sebzt8TobP6mqma1w2SRLC0WlWQWr9YlwLJODUrMbLMAqNNCcZSrddKiyG+1E9ask9a+EBRtyLwNYMk2PuiW1UqTC4RRhZNWVBKblWcl3k4FURqp7KLSWGHJ04bg6ENeXNSQSWZ6SlLLdJanG/W0Tno/X4fFJ5tuBUoOueCYcrRMSANEk2GuJEdNWe59/DqB+YllTjSdrvmgPc9IZdWI0jqlJESre73FJv2NNC7nvalP6f2lMNYngYVxGyusxKbvx09SuOiwDuDCsI1EPqz7mT4OXDwZq5llGkSmykYaF+lWKZ5SKT5zpqRqulNpUTC9D1rrdzAMGOam8trkQ1XDLp78+orHmt26tGNHy2gjlibTomoMAPhUKW2B45bRYMG3NhknDQuYTGF1BZMjBtDO6QI+n8Rd0FmQaC4uA0hTa2wE1ipjXAXYNSvpL/S7lg43qLWIkl7T4D2MGtTeYDlq0ch4KzrAb1hpmVSuQgOTrF1UOA198pGEN5qNEt24zBVkiFFN/lEb/qQ9CJG/djvamTKUeCt2odedZiT3HDqv7s7RBAXIW1XinuMjFChVGSZ567IHOdrwv8WjiBBXfHUsZHuHRZzynSiiVO9ZuVMR5OQY6XtnHrzKAP2HpphpUUbO/0pRxxB1fBdhH1jF9mFHPiDL8tiN7rIY0UYUVF+Ikg5/cENUuiKKVgXuSA5teIB/ZKYaK/2jMgj+NAXwPVV+vsn3VrPHsSyfmvrPW/VJFcyqCPyPpOmRmfjfZVkuSnECv/Rf4UtGV0FnOkzpo/3MVFE58ll0twm9aeIBzRspfRhdK70BQKN1ugSbCzMLs88kljubw2q1as3t/XOEuwyHXpsnuae2/xTLFfx6ntI/FmEmsYWJTxPUNB1e40cyOnhyD6ZQ5HcJhoTRQYSMSUk6sL2YoFJSZPjLxek1iyn6iqZ9Yr+EG+Xo2hgGnogfaRccPd575aBU1vemZfyDIuIyu3fyRZV2LK6kR4Mmjf+I9Oc3YKyOOwUsp0v8EgpG+tlx/IQqgW1U7dsW1tL8Hv9PQpsrTiPaV2TVbvfSGgcuFHguGlY0+iefA6Ck4/uCqOEgm2brJ4PROYyV4+HlvH+zk8Nl8nr2evZ70v6+epV8+Q4zxSV3)

**Comment by AlexSchemman** [comment]
[Discussion]
Probable root cause 
https://github.com/vuetifyjs/vuetify/commit/2db6c841a3495bc03a9ed3901d759d09a973f5d3
(Prepend-item slot is present inside VList)
Default behavior on mousedown was blocked to address https://github.com/vuetifyjs/vuetify/issues/15206

prevent click may also work and enable selection at the same time?
[Vuetify Playground](https://play.vuetifyjs.com/#eNrlkz1PxDAMhv+KleUGaDuUhVM5gZiQYEJMlCGXGmRdmkSJW4QQ/520tDR04fabHD/+iP1Kfv4Uwavixrm871BsRcXYOi0Zd7UBqPpMOjc+R0dZw5IM+gmNUFNg0JGGq1pYg7X4jQI8okbFcq9xYVNNRvGvhQL02av1sYcBMlDWIo1tD/gxhFaUiTVGvrmLvWADZ7DKCN1+zrm3PuaQC10LjdXWQyAG2SJD3CvEMZE7D7IhR4EUmTdATZz221VFMvsiwkQjWOtyrTSpQ+489miOkQluh4ITFau1XcDGvpt/BXsyiWQPc9lpyDa7f69xID/HWhXJEYuvc1HmZX4pBnsR7cs3CJouMQ==)
