### ISSUE TITLE
[Feature Request] VExpandTransition group

### ISSUE THREAD

**Issue by TimoCuijpers** [vuetifyjs/vuetify#19210]
### Problem to solve
A v-expand-transition doesn't have the prop "group". 
I want to add the transition to multiple v-cols for example but this isn't possible now.

### Proposed solution
Add the group prop to the v-expand-transition like all the other transitions

**Comment by websitevirtuoso** [comment]
Could you provide use case? provide current implementation and extected behavious with "group" option?

Based on:
https://vuejs.org/guide/built-ins/transition
https://vuejs.org/guide/built-ins/transition-group

Thanks

**Comment by ascott18** [comment]
I would love to see the same - the use case is very simple. I have a list of elements created by a v-for. I would like elements that are removed from the iteration animate out with a collapse animation, and elements added by the iteration to animate in with an expand animation. 

Simple code that I'd like to have work:

``` html
<v-expand-transition group>
  <div v-for="item in myItems" :key="item.id">
    {{ item.text }}
  </div>
</v-expand-transition>
```

Instead, the following warning is present and the UI doesn't work because v-expand-transition doesn't support `group`:
```
[Vue warn]: <transition> can only be used on a single element or component. Use <transition-group> for lists. 
  at <BaseTransition onBeforeEnter=fn<onBeforeEnter> onEnter=fn onAfterEnter=fn<resetStyles>  ... > 
  at <Transition name="expand-transition" css=true onBeforeEnter=fn<onBeforeEnter>  ... > 
  at <ExpandTransition> 
```

**Comment by websitevirtuoso** [comment]
Yes, I know that it can be implemented. but we already have it in vue and using documentation you can implement group transition. 
I don't see any sense, to copy paste this from vue to vuetify.

**Comment by ascott18** [comment]
> we already have it in vue

Could you show me where [this code](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/transitions/expand-transition.ts) already exists in Vue?

> using documentation you can implement 

Yes, by using documentation you can implement almost anything. I'm not sure that's a strong argument for deciding whether to implement something in a framework like Vuetify, since that logic taken to its extremes means that Vuetify should not exist at all since everything in Vuetify is implemented in accordance with Vue's documentation and APIs.

> I don't see any sense, to copy paste this from vue to vuetify.

90% of the work for this already exists in Vuetify, whereas I'm not sure any of it already exists in Vue. But I'd love to be corrected here if this does already exist in Vue!
