### ISSUE TITLE
[Bug Report][3.5.4] VFileInput: @click:prepend, prepend-inner and append-inner also trigger @click:control

### ISSUE THREAD

**Issue by HtheChemist** [vuetifyjs/vuetify#19232]
### Environment
**Vuetify Version:** 3.5.4
**Vue Version:** 3.4.15
**Browsers:** Firefox 122.0
**OS:** Windows 10

### Steps to reproduce
Clicking on each icon.
@click:append does not trigger @click:control but the three others do.

### Expected Behavior
Each icon slot should behave similarly (either triggering the control or not)

### Actual Behavior
3 out of 4 icon slot trigger @click:control but one does not.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFUztPwzAQ/isnL7QSScVrIIIKFkY2pqaDca7UqhNbtlNRqvx3LnbSNtDHZt99j8vl82zLnBWTV2PSdY0sY08eS6O4x2leATytk4VUmMjK1L4tAKyTUheonnPWdlzOYpk4ApdaFWip9WGU5gVsdG2h0KIusfI7qOKfgf9GfIjKXaeslZdGYSdp0WBVJFLoiuBlIRPDDVqhpNnZ9piqQnsWyc1FsR5yUeuFLmKVdeaEGo3heQolOse/0KWmdsvRVdeGAL4a/yGTvLe63cNRctc+QY6TnuLG7llq/MjzAhFzQmaw+AsbOCYU4kUB6+NGuXJK+8yhQuFl2P0W2oi9c1KFJmcdZUha6Na9x1Gc9pycQbbCzUH7QCNkWyylASd/kDCu5EoRJaQThFZB2FhZcruhulDcuTYQmNwOdAC2+0GhaQ4cJtFiP/hk8Lr+FVrC/r2FEmn3Sw3aAwZdnbDSRCh+G209FLjg9I5gGy0K7nkG8feMuhqEeV0Gs/l1X+ldDorNOByC686HNdfsLr1Pbx5Ze3hI79n8F51wZNs=)

### Other comments
Similar to #17406 and #16678.

However, I believe that this behavior should either be documented or normalized.

**Comment by ramseyfeng** [comment]
Although the @click:control won't be emitted, the menu options will still be opened.
Is there any way we can use preventDefault to avoid the menu options to be opened when user click the append-inner icon.

**Comment by lukke1603** [comment]
@ramseyfeng did you find a solution for this particular behaviour? I am also struggling with this problem

**Comment by ramseyfeng** [comment]
@lukke1603 I would suggest you use the append icon instead of using the append-inner icon.
[example](https://play.vuetifyjs.com/#eNp1VttuGzcQ/RV2UUAt4JURuHmo4DQN7CZxU19gpzUK24BH3JF2Ki65ILmyVUFAP6JfmC/JkNRlqSR+0XAuhzNnZri+WxZv2nY477AYFccem1aBx1/utRDH81KCraK8PZWevEIhFTj36r7w+OzL+qWYGO3LJ6Rp7UuL006BFeNpOVYdllOLi/tiDSPElTUTUrhGPezDss/eZQy/DTyuaJ5fLKH1ZLRooTziG25rtCgqIxamE4rm+Pr4kGO2qBEXOm+k4TLRr3MIf/OyMRUqBo6/98XONKpJezZ8R+63ijzpqXgtBieK5Ez4GgVJzsAbgWwciNHXTA7mOMgwiZkOZTjPbLvMpGAcE3m8CTbx6b//xffL7O4gwlhhvO0aoTJaLQarxwzGrvVZ5n2P1mKLuipDkqHuikpJnjvVc0HryHnk3gYSNoZtR5jQzcQwg04ZP4I2gPY8IulOUYXlM4/GnCGx9Ba044yYnsA3X286X5Lujck2NuSXK7m6GYbCHoOt7LGTc7D2lUYZy94Zh66TEp2LFJKemKw9myYlZrK4SFONclZyxop0akIiz0qFZRiDre1L0F9lmI4M9ZX4eoMi1WFBQh45o6z8NqX99hxmG72J7e/AZr23i7hZuY2GDxkMH5201CYvfG6N9aLCCXTKi2VCq8CD+OHHzVEIi76zencWYlvySExAOTzYmeIKjoTulOpp06qMxF2ficEbXhdoYHAQRTdLUoOWJGhxA41JGkv/Gs1iHmxnTBq44HECiibGaor+J2FmeIGSrDVKT7Lze/GnqOAJLAavU14UvtQLMxEc3TXjhPQWK7SceSXiPrtgPydpjUYXPDLAt3wrVTHuHRo7TRDvOmjC73u+jChIZxXUnFsWe6Z45AzFYs50RRDKZdE8xd8P20o/8D53crbYi//DdMQZpahzCOMbBetqUEqcOQW6igCsW4TDHsA5v8wg686h98mPZE1T0ElmEp3xCZ0cvyuO2paryTFYbTobizznb8o6nQsc201zL3AOgaIs7gKfxHtoWldTakdQ/B4Wg8tMp3N85kXanP42draPwYNcixOwholMV0XNKczWeccz8hwzA4GpPimXNe135HKmuE1pOC/5q2giE1egoIsCau0Wag7rmbvq0PLH4jpmmQFd17wR68uC5w2/L3mmSbPL9CNj8/OGzEWG9BGf0xD86aEOv3+hbZjnKBIPnO5dkxRfDOktMMt66lM5t+i82Hmyghy/V46SdWEa9u0jPGzlVRJWUcGH48P1w1IcFFzYzA3/cUbz/yXL+0I6/kqO7h5WbKMmvDllA23PISmD03K1KlYHxdHwp+GLn9n9aPhy+OKoOPC2w4fPbxKyxg==)
