### ISSUE TITLE
Incorrectly displayed pagination items

### ISSUE THREAD

**Issue by Antway** [vuetifyjs/vuetify#1924]
### Steps to reproduce
Incorrectly displayed pagination items, if you add a Pagination to the Tabs.
### Versions

0.15.7
### What is expected ?

should be without `<span class="pagination__more">...</span>`
### What is actually happening ?

 Incorrectly displayed pagination items, if you add a DataTable to the Tabs.
### Reproduction Link

https://codepen.io/anon/pen/OxmjjE?editors=1010

**Comment by nekosaur** [comment]
Because of how both the pagination component calculates how many buttons to show, and how the tabs component renders its tabs, this is might be a hard one to fix.

There are two solutions right now. 

1) Put `lazy` prop on the `v-tabs-content` that has the pagination component. That way it won't calculate the width until you switch to the tab.

2) Use `total-visible="2"` on pagination component to force it to only render two buttons (if that's your use case)

**Comment by johnleider** [comment]
Please reference nekosaur's comments as a workaround for this use-case.
