### ISSUE TITLE
[Bug Report][3.5.6] vDatePicker component: Range selection is dropping a value

### ISSUE THREAD

**Issue by ericadam** [vuetifyjs/vuetify#19313]
### Environment
**Vuetify Version:** 3.5.6
**Vue Version:** 3.4.19
**Browsers:** Firefox 123.0
**OS:** Windows 10

### Steps to reproduce
Today is March 1st. This bug is currently only happening when the month of March is selected. The year does not  seem to matter as long as it's March.

Use a vDatePicker in a template. Set the multiple prop to 'range'. Select a range that spans from a full calendar row (7 days) to another. 

### Expected Behavior
All dates are selected.

### Actual Behavior
The next-to-last date in the selection array is being dropped and does not display as selected on the calendar.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVjlsKwjAQRbcS5tumiA9QouA6jB8hHSWaJmGaVIq4d8eqUP8uh/s6PqAjWx9Skn1B2ILK2CZvMu51EEL1lY0hGxeQRjAiindxLV1252GnoUvGYmUoltBo+LpGX8M1VXL2hiRs9JHYnci1hgYNoi0+u+SRIZlwQc6q+i/0W2TKk59DrKePVD35C88ZLORSzjfwFiu5htMLiflJqw==)

### Other comments
It appears that this bug may be an interaction between the current date and how that effects selecting a range? Maybe because this February had 29 days?

**Comment by alexkunin** [comment]
I've prepared PR that does "adding a new value for unit?: string parameter that uses Math.round instead of Math.floor" part. Rationale is, there are lots of similar calculations in `getDiff`, fixing only one of them feels weird, fixing all of them expands potential backward compatibility issues even more.

Proposed solution will increase bundle size by several dozens of bytes, but on the other hand it's pretty self-contained.

**Comment by alexkunin** [comment]
I think the bug was fixed as part of #19372 which is currently merged into `master` but not yet released.

**Comment by johnleider** [comment]
Fixed in f4055aab2b3e4abe843608e874ab35940bc327ba
