### ISSUE TITLE
[Bug Report][3.5.9] Error: [Vuetify] Could not find layout item "bottom-navigation"

### ISSUE THREAD

**Issue by jaketig** [vuetifyjs/vuetify#19403]
### Environment
**Vuetify Version:** 3.5.9
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
I'm using multiple v-bottom-navigation components on nested pages in nuxt.

When routing between 2 pages that both have different bottom navigation components it's throwing the following error in the console:

```
Uncaught (in promise) Error: [Vuetify] Could not find layout item "bottom-navigation"
    at layout.ts:301:26
    ...
```

The active styling with exact links also seem to breaks

### Expected Behavior
Active link styling should respect exact prop
![image](https://github.com/vuetifyjs/vuetify/assets/29202067/a0fdbab2-c254-4b2f-a92c-7135d104427b)

### Actual Behavior
Active link styling is applied to both links in the v-bottom-navigation, console erros are thrown
![image](https://github.com/vuetifyjs/vuetify/assets/29202067/f0f7e9bc-501b-4314-9dfe-4b7e01c91d49)

### Reproduction Link
[https://stackblitz.com/edit/nuxt-starter-1i1tdq?file=pages%2FrouteA.vue](https://stackblitz.com/edit/nuxt-starter-1i1tdq?file=pages%2FrouteA.vue)

**Comment by jaketig** [comment]
Thanks for the suggestion, but this error is occuring on 2 pages of much larger app.
Moving v-app out of the layout file onto each page isn't really a feasible solution

**Comment by De-Hann** [comment]
@jaketig from what I can pick up, the issue is caused by ```useLayout``` function in the VBottomNavigation component. Seems like it is called a second time during navigation by Nuxt and by that time the component is already destroyed (Still need to do some more research).

A less intrusive "fix" on your side would be passing the different name props for each navigation component.

```vue
    <v-bottom-navigation
      :name="'route-a-navigation'"
      :selected-class="null"
      grow
    >
      <v-btn to="/routeA" exact>
        <v-icon>mdi-alpha-a</v-icon>

        <span>A Home</span>
      </v-btn>

      <v-btn to="/routeA/test">
        <v-icon>mdi-alpha-a-box-outline</v-icon>

        <span>A Test</span>
      </v-btn>
    </v-bottom-navigation>
```

I am unable to recreate the issue using just a VueJS project but can recreate it with Nuxt and will continue with my investigation
