### ISSUE TITLE
[Feature Request] Make VListGroup selectable

### ISSUE THREAD

**Issue by 11mad11** [vuetifyjs/vuetify#19479]
# Problem to solve
Right now, there is no way to make a VListGroup selectable. Only the leaf node are. 

# Hack
I tried to write a [hack](https://play.vuetifyjs.com/#eNrdVM1u2zAMfhVOG5oUiOUOHXbw+rfDhh2604pd4hxUi0k02JIhKe6KIO8+SnZsxx2wXXZZENgm+ZH8SJFa7pmzRfqxrnmzQ5axK49VXQqPN7kGuGqSQlgJRSmcu85Z9TMRO29yBk9K+i1pLi8uchaxEV0q50Gidso/k7UwVS0KT/jM1KgT5y2F3gSTcUGrKF0IHN99IAp1pAGvg4kQe6itqR0cRqg+ZRJAgxagSR6VluQWnXI2tmXESDVIxlevHJZIktHLCOSNKHe4OsUXpjQ2hlKVsM9j45hJOqIy1JGe9HNS2haFxBD6PynuCGtnh4QwPCScAEl0hVW1B4d+V0Mp9IYI+OH4VVUb62EPFttq4ABrayqY0YzOQoSWuaZZ62uE6x4+3x/Ox5g4XGRfHonvh8q88iVmMPPo/Gwx6GOvSP8w0RdbVUqLOoPlvnf+bMxs0bsECQ6r3unQfa3aV5p+v6ceLXP2pju/FX2H9fjWbQdpxvRN4N5TDsAM5vIcrm/GhRzRXtgNevKQHBvU/pa3mg9jqFrDvAMqchK6QLOGLw9f7z+VWJEXnJ11kXjc/cCYUwIvCD+ni0CqnJ13XR5+kgd6KPlWuLnkiljeDkpJZ+Wx02eDXkjZKsfhsHQ4DT8MdICDcEAXitKbFZU7mvaJ8aRySzNndZ97ekbHHL/v8D/MHz7ocZW2u0GbwBasXYSkEjX/4Yym6znSoesyGmh0siPBnNFuBDlnW+9rl6VpITW5UdNVY7lGn+q6Su8Iltqd9qrCRJrq7pJf8rcXqaQDHus5uip5tObJoaUoOesaFPN4taYh/WOuDkkp3vH3bYZOlZTi0YUUL0KnlK9Bm9CK0dWI9m9LmridlDWxvSit6z392WHBWk/qfqTNVr8A+m05MQ==) but this [line](https://github.com/vuetifyjs/vuetify/blob/12cc8cc4068bbcead456b31e31e39afbe0ffe64e/packages/vuetify/src/components/VList/VListItem.sass#L320) prevent me from using the overlay of the VListItem for the background color

# Proposed solution
Either make the Activator of a VListGroup selectable or offer to configure the background opacity.

**Comment by websitevirtuoso** [comment]
If you need to set opacity or remove it you can do this via css
.v-list-group__header.v-list-item--active
  &:not(:focus-visible)
    .v-list-item__overlay
      opacity: 0
      
 like
 .my_class.v-list-group__header.v-list-item--active
  &:not(:focus-visible)
    .v-list-item__overlay
      opacity: 0

**Comment by YSHgroup** [comment]
Hi all,
I'd like to make an addition here.
In my case, the VList used for VNavigationDrawer and every VListItem works as RouterLink with `to` props.
Also, there are some cases VListGroup must work like that too. For example, When clicking the VListGroup, sub list should be dropped down and the appropriate page will be opened at the same time.
So, I've tried the following way:
```
 <v-list-group
    :value='item.title'
  >

    <template v-slot:activator='{props}'>
      <v-list-item 
        v-bind:='props' 
        :value='item.title'
        :title='item.title' 
        :to='item.to ? item.to: undefined'
        rounded
        color='secondary'
      >
```
However, after that, the page reloaded while navigation works, and therefore the sub list never open.

Currently, I've implemented the way with other one, but also, I've left comment `// TODO: To be fixed` because this one doesn't follow the best practice.

Could you please let me know the best solution?
