### ISSUE TITLE
[Beta] navigation-drawer variables doesn't exist

### ISSUE THREAD

**Issue by cayaner** [vuetifyjs/vuetify#1951]
### Versions
v0.16.0-beta.2

### What is actually happening ?
we had variables to control the ```navigation-drawer``` width ```$navigation-drawer-width``` and ```$navigation-drawer-mini-variant-width``` but they are gone now,

also the ```main``` element padding right and left according to ```navigation-drawer```'s width are gone too.

**Comment by KaelWD** [comment]
Navigation drawer width is now set in JS, use the `width` and `miniVariantWidth` properties. If you read [the upgrade guide](https://github.com/vuetifyjs/vuetify/wiki/0.16-Release-notes) you'll also notice that `main` should have a `v-content` component that is used to set the width now instead of padding.
