### ISSUE TITLE
[Bug Report][3.5.13] (vAutocomplete/vComboBox): don't allow empty string as model value

### ISSUE THREAD

**Issue by devCodeHub-star** [vuetifyjs/vuetify#19522]
### Environment
**Vuetify Version:** 3.5.13
**Vue Version:** 3.3.8

### Steps to reproduce
1. Autocomplete/Combobox/Select initially treats the empty string as value, input focused and label at top position.

### Expected Behavior
Empty string should be treats as non value like null or undefined

### Actual Behavior
Empty string is a valid value.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrlk0tugzAQhq8yche0UgJKo24iUqlSbxGyMDBIloxNjU3bIO7esZ0HcIUukBl/8/wZTiPrTZV9dF06OGQHlltsO8ktvhcKIB+2FTd1eI+WVpYLhQYa6cQNBGT09928+kqgpz8WbPdasBkMmDurK03F0OIcAQzbVtcoKe7Lofkt2BIfBPXos4ZzTSUvQ+gnNtxJu8aVRG54KdcluRFcWYpzqkYjacR6Gbponwa46QRPPUqsrNCKokfwTcFE48IYjXTg0iFME+TZQtx7qmwpBsGVVERKXeqffy/TTYj5ooVr+dhEsh+rGOl1Z+NK+5u404tCZPaVEZ2FHq3rgq9oO20sjGCwgQkao1tI6D9JPKS0vYUgPRy9x3OSvMRPF1HQ/YpOSaN1soGk5MYfjbhcguniSdSTMyXIs9gHdcCmjXJSbtg+fUt3e3b+A+/XFXc=)

### Other comments
This issue was closed in this PR (https://github.com/vuetifyjs/vuetify/pull/18766) for version 3.4.x. It should update in latest version.

**Comment by yuwu9145** [comment]
Empty string is a legit value, only `null` & `undefined` are real empty.

Your playground should use `null` to achieve empty initial state: [demo](https://play.vuetifyjs.com/#eNrlk0tugzAQhq8yche0UhLULiNSqVJvEbIwMEiWBpsam7ZB3L1jOy+4Qhdgxp/n9TM+TmKwdf7R97vRo9iLwmHXk3T4XmqAYtzW0jbxO1lGO6k0WmjJqyuIyJrvm3k5S8DPcCjF61spHmDE0jtTG06GDh8RwLjtTIPEfl8e7W8plnivuMYQNa5rSrKKrp/YSk9ujWtCaWVF65TSKqkd+3ndoCVusVm6LsrnBq46wdOAhLVTRrP3BKEomLldmJKxGyV5hHmGIl+IewuVL8VguJKKSWUq8/PvZboK8ThocZvuk8j2fRQTvcxsGumwk2Z6kYjNobaqdzCg8308q7reWAcTWGxhhtaaDjK+J1mAHHZwEKWHQzjxrD3RS/p5CUblL/CYtcZkG8gqacPSqvM5mj6tTAM5cYAiT5VwDWLehKjxdfoDFX8XMw==)

**Comment by b-maslennikov** [comment]
@yuwu9145 it's only related to select, autocomplete and combobox I believe?
because label in textfield does not behave like this
see updated [demo](https://play.vuetifyjs.com/#eNrNk99qgzAUxl/lkF24Qau0ZTCKHQz2FrUX0Z5AIBoXE9dVfPedJP1nuwfYhSQn3+fnL+ZkO7DOVNlH26a9Q7ZmucW6Vdzie9EA5P284mYf5rHSjeWyQQNCOXkWgmT096U8eRXQ020KtlgW7EYMMndWV5o+hhahn9d6j4qsXw7NT8FgLYnEvxtGWlC8DIZPFNwpexdIkWdyeOpQYWWlbsg+gA+AkfwwxCLtuXII4wh5NtnuJSqb4pF4B09KqUt9+IfgZ7RHaIsHOxcS1f4P7AdKyG6PMwSr63lTfT3wqJ46IzaOX4mdM0GlsquMbC10aF0bvLJutbEwgEEBIwija0ioGxMvUmxnIUDCxjuek+Ql7ixK4S+fpG0itE5mkJTc+EHI4zGULo6kemVHAXkWOYiAjTO2Sl/TxYr5yVu6ZDPBVYezyd2Ia7tf6jQAZg==)

I do not agree with that btw
empty string = nothing is entered
it should behave like for null and undefined

**Comment by b-maslennikov** [comment]
@yuwu9145 it's only related to select, autocomplete and combobox I believe?
because label in textfield does not behave like this
see updated [demo](https://play.vuetifyjs.com/#eNrNk99qgzAUxl/lkF24Qau0ZTCKHQz2FrUX0Z5AIBoXE9dVfPedJP1nuwfYhSQn3+fnL+ZkO7DOVNlH26a9Q7ZmucW6Vdzie9EA5P284mYf5rHSjeWyQQNCOXkWgmT096U8eRXQ020KtlgW7EYMMndWV5o+hhahn9d6j4qsXw7NT8FgLYnEvxtGWlC8DIZPFNwpexdIkWdyeOpQYWWlbsg+gA+AkfwwxCLtuXII4wh5NtnuJSqb4pF4B09KqUt9+IfgZ7RHaIsHOxcS1f4P7AdKyG6PMwSr63lTfT3wqJ46IzaOX4mdM0GlsquMbC10aF0bvLJutbEwgEEBIwija0ioGxMvUmxnIUDCxjuek+Ql7ixK4S+fpG0itE5mkJTc+EHI4zGULo6kemVHAXkWOYiAjTO2Sl/TxYr5yVu6ZDPBVYezyd2Ia7tf6jQAZg==)

I do not agree with that btw
empty string = nothing is entered
it should have the same behaviour like null and undefined have
