### ISSUE TITLE
[Feature Request] Add props to V-Select to choose show empty string or value when value is missing in items

### ISSUE THREAD

**Issue by williamlinn93** [vuetifyjs/vuetify#19578]
### Problem to solve
can hide the value when it is not in the list.
In my proposed solution, I used the raw data to define whether the value is in list or not.
But I want to get a proper way.
In vuetify2, it handles as showing empty string.

### Proposed solution
[Playground](https://play.vuetifyjs.com/#eNrNUk1PwzAM/StWORSkfbAdqxXEkQOnHddJC50LQWkTJWkn1PW/4yQttBXcubTJe8+O7edDGxmdr5+UWjU1Rkm0s1gqwSw+ZBXArlkypfzRX3JZWcYr1D3kQYMCczsAAJxSLC23AtMsqliJWTQjGyZqRwpm7JhslqU8oyDmjAWrhd371HgeixKXwpBGoVRilHxNRf3Dsr5HRVUNw4WbUB2XFUW0/nnosmikBWhbKKTOcf8uLy/cGF69PTvd9Qr2k14pfNhKswukaQqxfP2glDE8Bty3Csk44+kEXTcqZz0xO0DD4AbTCZi67pCwFJN4uppcc2XBoK3DzvBSSW2hBY0FdFBoWUJMexY7UqD9vb8UrK7RSf6gCyYM8U5BpRkLM1tIQg/e3t/9KIIpRBxCW+3QsFuEBOJNvBgQ534Cm00PdP1/HrGdR2y3k4ijm0+YCM0i6hZVLYT/HL8Ak8sRLQ==)

**Comment by YuWaiLinn** [comment]
Here is my use case.
---
In my old data, the id [5] was saved in the database. 
because there was id [5] in the old options

But now, we remove the option id [5].
At that time, api return the old id, but i don't want to show it to the user.
So I want to hide it in VSelect.
When Vuetify2, it showed as empty string, but now, it showed the value.
So the user can't understand what that number means.


[Playground](https://play.vuetifyjs.com/#eNrNUj1vgzAQ/SsnOtBKSVAidUGhVccOnTKGSHHhaF0ZbNmGqCL8954NNBClexew33t3fvexbwOjs+hFqVVTYxAHW4ulEsziU1oBbJslU8of/SWTlWW8Qj1AHjQoMLMjAMApxdJyKzBJg4qVmAZXZMNE7UieT6lmWcocBeE5FqwWducT40wUuwSGNFJZLitz4SLy9P9c/TaKTI2thbveHCkppPWvQ5cGEy1A20IhdYa7T3l648bw6uPV6c5nsN8KZeHDVpqdIEkSCOX7F6UM4bnHfaUQTzMej9B1EzvRbNQ9NPZtHDkB85k7pF+JWTxdTaa5smDQ1v3G8FJJbaEFjQV0UGhZQkhbFjpSoL1dXwJW1+gkf9AFE4Z4pyBrxsLVXEhCD94/PlwUw1SI2fd1tWPFbhFicuVGvw4XI8zzGNbDrRv+N2M285jNLObgmtS3hRoSdIuqFsJ/Dj/TwxMC)

**Comment by williamlinn93** [comment]
Here is my use case.
---
In my old data, the id [5] was saved in the database. 
because there was id [5] in the old options

But now, we remove the option id [5].
At that time, api return the old id, but i don't want to show it to the user.
So I want to hide it in VSelect.
When Vuetify2, it showed as empty string, but now, it showed the value.
So the user can't understand what that number means.


[Playground](https://play.vuetifyjs.com/#eNrNUj1vgzAQ/SsnOtBKSVAidUGhVccOnTKGSHHhaF0ZbNmGqCL8954NNBClexew33t3fvexbwOjs+hFqVVTYxAHW4ulEsziU1oBbJslU8of/SWTlWW8Qj1AHjQoMLMjAMApxdJyKzBJg4qVmAZXZMNE7UieT6lmWcocBeE5FqwWducT40wUuwSGNFJZLitz4SLy9P9c/TaKTI2thbveHCkppPWvQ5cGEy1A20IhdYa7T3l648bw6uPV6c5nsN8KZeHDVpqdIEkSCOX7F6UM4bnHfaUQTzMej9B1EzvRbNQ9NPZtHDkB85k7pF+JWTxdTaa5smDQ1v3G8FJJbaEFjQV0UGhZQkhbFjpSoL1dXwJW1+gkf9AFE4Z4pyBrxsLVXEhCD94/PlwUw1SI2fd1tWPFbhFicuVGvw4XI8zzGNbDrRv+N2M285jNLObgmtS3hRoSdIuqFsJ/Dj/TwxMC)
