### ISSUE TITLE
[Bug Report][3.5.15] v-badge inline left prop not working

### ISSUE THREAD

**Issue by pedrito-96** [vuetifyjs/vuetify#19613]
### Environment
**Vuetify Version:** 3.5.15
**Vue Version:** 3.4.21
**Browsers:** Chrome 123.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Add inline prop --> add left prop

### Expected Behavior
Badge should go left

### Actual Behavior
Badge stays in right position

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj8sOwiAQRX+FTFxaG7cGm/gd4gLL0JDgSCg0PuK/O1CfmwlzOMm9s7/DGPt2F8JqyggbkAlPweuEnSIh5NToEOqzLv2ZknaE8YUqPGozoHDk+UMUAyltFawVCI82fdQqOxZEGWwsODI5e2VxdDdkcmm8jgMq6GQ7u98gBjXp3Yb3/zqFzG1l+3NFJoOWJaMIHkvK3tdxeAJsklGR)

### Other comments
Doc of inline prop: Moves the badge to be inline with the wrapping element. Supports the usage of the left prop.

**Comment by KaelWD** [comment]
There is no left prop in v3, but `location="left"` doesn't work here either.

**Comment by bbedyukh** [comment]
I have the same problem here, in Vuetify v3.5.8.

**Comment by J-Sek** [comment]
It seems that in order to close this issue we only need to update `inline` description in docs. It could say "_inline badge is always on the right and ignores location prop, use `location="left"` to put badge centered left_"

However, I wish to take this opportunity to ask whether current implementation is "optimal". In my [big-ass example](https://play.vuetifyjs.com/#eNrdWFFv0zAQ/itWeQTTDQZC06gEb5NASIw3yoObuK2pY0e203Qg+O07p04aO0mTbu3D+lI19vl8933nu7N//h1pFY0/penrdUZH16MbQ5OUE0MnU4HQzRqTNEVmSRP6cTqKiVpNR8VMOYdnRCHDDLfzGP1HuBIoRGZGIG1ItKJxNbydIPGCokhyqWAlVUqq6QjF0iAmOBMUcTo3tSXFIhZJgewPLElihgXNdUpSqvCaKEaEwTIzdjWoGtf3G7sNa2O3xTaVqVbCiCeazmVEDCvMs+bXoOhwIJUapHpt/eL0nthaJOdzTQ3eWC4vL/rNj4iKMYkimQH0MTWEcX0ABd+K7dqdsl8uvnYBJ8iaLQqbcaxIThUC7hMiqNiFCohxpsE7sEGDnSaXniNuHjOI9Cpyb8VMbsBinc3KoZjOScYtKqBp5SNRHhK0xppLc50qmlJRB74V/FSxhKh7UAkQGjAaxt4HKHcgzayBmAB7OY5lLgJ0uxC2o96J3olWIPjYxGzNYgDW424gZEyUzJ8AMpcWzho59BLN2YbqoyDIibbxn3AsLlGisADAzhJXB0RhoTNOw/d+EF8U0PeFX7MuTe5ANfoKme4A77yNS9onW4XPHI5GpEBBFlXwpQpD7NkIhKCqIWeFHh8s++Asj9DTYS2FdwO7TaEy+UfPMRAWzDayAroqqDh+28ZRL0vtZx4Af0SL4vTN6pquQOZzoZ6JbQ5DNv/cjGdNQ1o57Gaxg46h0O3Hqj0/tqEFuRGcHNgjNZNcq29DaJvtcHXGdiB7IvxqofcBPCuL0Xe6yDi09VbGRWSjlfMPRmielWj0ajC3p5GrAa3YYmmRPl1vV252mk6lxZXz7FpKRyHnbm8OR8AzxKYBbyjQRDuU8G41b5rzHjn+5LNvhAinyuCIqYj39OWHdwD998cQvcldSpIKjD1QH1D2E6Y1Ewtr0dEB3QdXZxgX8VGvLe9sl72jxCiil3B1bgZKl9c1k/C2ANcyN2g/ImmgrUHaD2vwMNYalnY7UhIY+pJLtSIKXhRiX11F+HHTWuFccPMHmNwR7zkyA0tDiX9LYQjBtxwNSTrdQXS6bBPU/a4i79YnhHkPVDbLwhBoLAlfQo64QDGec7pBvzNt2PweR5CJQYZwthDuwy/xYFelwa21PzhXJEULYpvoMOjImhjoZzT7Y+mFTQE092AI3+69Ci5IXTzWXiQrTlXLgvY3Mpnb8NrufWW3HspXafix3WmmgLN0KixGz9nLlqDvPCEdt5x0s71f7ie/4eGjgQGT+0HxxaxIlSZqWaZKJe5RGP572Wz075XIOC9+fj0A6C5BEw==) you can notice following problems exposed:

- top toolbar
  - location-left needs offset
    - of course it depends on use case, but I suspect it might be needed more often than not
- center content
  - without `inline` icon stays centered
   - easy to workaround but maybe an inconvenience compared to `inline left` from v2
- left drawer
  - inline requires spacing tweaks and I cannot use `offset`
- left drawer bottom slot
  - both use cases seem OK, but I think prepend looks cleaner
    - I wish docs could include/suggest this example
- right drawer
  - uses location and seems much cleaner, until I want the left badge on the title
    - I don't think there is area for improvement on these examples, included just for reference

**Suggestions**:

- restore `left` for `inline` or a new `inline-left` prop
- include more examples in docs to guide developers towards `location` when their first idea might be to use `inline`

**Comment by KaelWD** [comment]
There is also `floating` which applies a 12px offset or 8px with `dot`.

I think the intention with `inline` was to use it standalone *next to* something instead of having the icon inside it, this would explain the 4px margin `.v-badge--inline .v-badge__wrapper` has.

**Comment by J-Sek** [comment]
> There is also `floating` which applies a 12px offset or 8px with `dot`.

It would be nice if it would add a bit more when location is effectively centered as it would eliminate the need for `offset-x` in this case:

![image](https://github.com/user-attachments/assets/06668205-6eea-44f7-b03c-354547ec7258)

**Comment by KaelWD** [comment]
I don't think we should have a separate way of positioning it just for this, inline should only be used without anything inside:

https://play.vuetifyjs.com/#eNpVjs0KwjAQhF8lLB6txavEgs9hPMRmWwJxDWlS/MF3dxMjtJdld+ZbZs5vmELfnrzfzQnhADLizTsdsVMkhJwb7X1Zy9HfKWpLGKpUxKs2IwpLjg2RCaR4VLBX0Mm22kveMiPyYGjDqdEOTwVisi9k5dE4HUaszxn7x/O5zs/Kr55sF7UTGRwYMorgs6XkXBmXL0iGTfw=

**Comment by J-Sek** [comment]
> _**inline** should only be used without anything inside_

I have never noticed this :) Thanks for pointing it out.

For anyone using it as a wrapper, you can leave `left` (assuming IDE does not complaint) and reorder stuff with CSS:

```
.v-badge--inline[left] .v-badge__badge {
  order: -1;
}
```
