### ISSUE TITLE
[Bug Report][3.5.16] v-btn does not show icon when using v-tooltip

### ISSUE THREAD

**Issue by alanscordoba** [vuetifyjs/vuetify#19651]
### Environment
**Vuetify Version:** 3.5.16
**Vue Version:** 3.4.23
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 10

### Steps to reproduce
See the example

### Expected Behavior
Show icon

### Actual Behavior
Does not show the icon

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj0uuwjAMRbfil0kfEtA5KkjM2AEDyiAUgyLlYzluJ4i946Z8J1F8c3Suc7iZzF29JVoOPZqVaQQDeSu4aSNAMywsUbmWoUtRrIvIz6iEJ4ng9GXdmnB2C/J9bs0bKIik5MUR2E7cYCWxsmQZoygpmKWp39BHrZm6X+06/daPybRdU39trWPu2JFARuknnQuUWOAGjBe4w4VTgEo/XI04gHqzQMhXWI/Ef7VD7xPsE/vzXzUbCyalysx9Hnvvy3F8ABGZafM=)

### Other comments
If v-tooltip is removed it works fine.

**Comment by SonTT19** [comment]
Not sure if it's expected behavior but you can show the icon by adding `v-icon` inside `v-btn`
https://play.vuetifyjs.com/#eNpVULtuwzAM/BVWi1ugqffCCdCtf5AhzqA4TCBAD4KivQT591Cy81oE8u50d9LuYjIP7R/RzzSi+TWdYCBvBTd9BOimlSWqY12GFMW6iLxAFTxIBKfMujfh6Fbkx9ybh6BKCr3p2mV4oyQlL47ADuImK4nVhixjFDURzFKuLaJnqmIaey+m23uzgszFu/blQbrmgR0JZJRxtnOBEgtcgPEEVzhxCtDoXzRFDqC+WSDkM6yL4rP5R+8TbBP740fzVQJmSzUz1+84el+P/Q054XF4

**Comment by alanscordoba** [comment]
Ok thanks, that worked. It's strange that you have to add <v-icon> without properties. I don't know if it's what's expected.

**Comment by mirocklez** [comment]
In the docs, the [default template](https://dev.vuetifyjs.com/en/components/tooltips/#usage) is:
```
<v-tooltip text="Tooltip">
  <template v-slot:activator="{ props }">
    <v-btn v-bind="props" icon="mdi-plus">test</v-btn>
  </template>
</v-tooltip>
```

and it is working like this.

**Comment by alanscordoba** [comment]
Is there any way to avoid having to emit the click event manually?
`<template>
    <v-tooltip text="Tooltip">
        <template v-slot:activator="{ props }">
            <v-btn v-bind="props" icon="mdi-plus" @click="$emit('click')"></v-btn>
        </template>
    </v-tooltip>
</template>
`

**Comment by ESP-Marc** [comment]
This is because the value of `icon` is rendered in the `#default` slots fallback content but you are consuming the default slot with a tooltip thus overriding the fallback content.

Us the `v-tooltip` directive are place the tooltip an alternate slot.

Here are those two working examples:

```vue
      <v-btn icon="mdi-plus" v-tooltip="'Plus'" />

      <v-btn icon="mdi-minus">
        <template #append>
          <v-tooltip activator="parent">Minus</v-tooltip>
        </template>
      </v-btn>
```

https://play.vuetifyjs.com/#eNp1kD1PAzEMhv+KCUNA4rgdXZHYWJDYGDiGcJeiSPmwHN8tVf87TtJWvaFLFL+2H/v190Flmvo3xOd1sepFDWwDesP2dYwAw9oZxPqtwZQiGxctnaQq/nIEJ5ndqMLsOvRLHhWsHafk2aHI+lM0LWIvfbc7g4ul9cKWmvM2cC972Dhf5SrhNAPMxG41nEhQaMhGFs5H4Q39peoa3G98NqkudDYr0dZtUdoxNs0S5okcMmTLS5vhAiZiOADZPRxhTymAlvvq5l64mSHkP9iVigf9br1P8JXIz3f6sQxoSIGp41NcvK/Pzz8qcIs7

**Comment by alanscordoba** [comment]
The first way works:
` <v-btn icon="mdi-plus" v-tooltip="'Plus'" />`
Thank you so much!
