### ISSUE TITLE
[Bug Report][3.5.17] Error when rendering tooltip with an icon as activator inside of a loop

### ISSUE THREAD

**Issue by AndronKarp** [vuetifyjs/vuetify#19685]
### Environment
**Vuetify Version:** 3.5.17
**Vue Version:** 3.4.21
**Browsers:** Firefox 125.0
**OS:** Ubuntu 22.04.4

### Steps to reproduce
Start development server and open the application in a browser (warning: huge memory leak, your computer might freeze).

### Expected Behavior
Tooltips render without any errors.

### Actual Behavior
Rendering of tooltips causes application crash.

### Reproduction Link
[https://github.com/AndronKarp/vuetify-tooltip-bug](https://github.com/AndronKarp/vuetify-tooltip-bug)

**Comment by BenShelton** [comment]
Something to do with binding the props to `v-icon` is breaking here, I believe it's the `target` that's the problem. We're seeing similar errors in 3.5.16, but I think it's actually the Vue version that's the problem here as even downgrading Vuetify causes similar console warnings to appear.

A possible workaround is wrapping the `v-icon` in a div, and then doing `v-bind="props"` on the div instead. Though this can cause the tooltip to appear in the wrong place.

Example (cloned from repro link and adjusted): https://replit.com/@BenShelton/vuetify-tooltip-bug

**Comment by markusheiden** [comment]
A `span(v-bind="props")` wrapper is sufficient to avoid the problem.
