### ISSUE TITLE
[Feature Request] VNumberInput dynamic step size

### ISSUE THREAD

**Issue by lukasberbuer** [vuetifyjs/vuetify#19779]
### Problem to solve
The `step` prop currently only takes a number. This works well for linear scaled numbers.
I would like to use a dynamic step size (for a logarithmic scaled value):
- increment: multiply value by 2
- decrement: divide value by 2

### Proposed solution
The prop could take a callable which returns the computed step size, e.g.:
```ts
enum StepDirection {
  Up = 1,
  Down = -1,
}
type StepFunc = (value: number, direction: StepDirection) => number;

const logStep = (value: number, direction: StepDirection) => {
  switch (direction) {
  case StepDirection.Up:
    return value;
  case StepDirection.Down:
    return -0.5 * value;
  }
};
```

**Comment by J-Sek** [comment]
Title is a bit misleading. You do not ask for dynamic step, but for straight override of the up/down behavior.

In the current state it is not possible to achieve with VNumberInput. While we can override slots, implementation contains `preventDefault` after detecting `ArrowUp` and `ArrowDown` preventing parent component from detecting such interactions. I was able to implement this with VTextField [[Demo]](https://play.vuetifyjs.com/#eNqtU8Fu2zAM/RXCGxBnmO10uw3J2g65DDtvl7oHRaYxoTIlSLKbLci/j7KTLPbWokV7EaTHJ5J6erzZJd7J4travGsx+ZQsAzZWi4CfSwJYdpmwtt/2B2koCEXoDlAPBtyGrFaoK+iEU4LCqkxMGzQTqzKBLmtMhZrBTugWGbm6w1+VuafIo2/DvkxOOTnrsQt4w/WRqkzRedWe8+NLoHMAoOYrYyQojWNEauE9F/6ZXSwWsDGuQpf5MhmzSDTIpAqlwwYpZBuuNeEoVoM5b3FrBfFDx1GvfscMvhFaT2NBbBRVuOV4djENXkmt5B2HZOuDadaxBeFZtnNa8ZpSNC6jj/AkQRQ9QRBptBZ22vLrSfI1NvGoJMtiZOMBOnfq0dIMjj0dkcHyoxx89NIpG8BjaIeJUI01LsAOHNawh9qZBmY8RbNIZ3UN+cATwZaHVeSk1Go9H4J1SzIoQzB+UTqH3dBZfy8fbl9ermDxL/xuBR8iuv9vyqNvnpWyeCDlaUpTPKVTNaQ3s2vnzP2aI7PbnM2h2wp9ijkP+PzEBMDcOuzYNmusRatDyjIcPDhp9og7ltkdPM3dTAp+ty8q91fuB8vxsiyGL+fPTvbv4+f1y+0fMCeM8w==).

I wish I could understand this use case a bit more. In what scenario user would expect this kind of behavior instead of adding or removing defined `step` value? I am curious because I felt a bit confused when interacting with the example implementation.

**Comment by lukasberbuer** [comment]
Awesome solution @J-Sek, thank you 👍
