### ISSUE TITLE
[Documentation] VList example is incomplete

### ISSUE THREAD

**Issue by PaulCombal** [vuetifyjs/vuetify#19829]
### Problem to solve
I want to make a list of checkboxes using lists. Naturally I go to lists. There is an example of how to do so but it's incomplete. 
https://vuetifyjs.com/en/components/lists/#action-and-item-groups

Why do they put a "value" prop on the list-item if it's to never be used? How do I get that value back?

### Proposed solution
The v-list tag in this example should be:

 ```
<v-list lines="three" select-strategy="classic" v-model:selected="slectedSettings">
```

To show that the values are actually stored in selectedSettings.

**Comment by J-Sek** [comment]
It is incorrectly ported from v2 and should actually be hidden in my opinion.
- missing script is the obvious part
- markup does not include `v-list-group` although description says it does
- does not showcase `selection-strategy="classic"` but rather `leaf`
- `isActive` can be replaced with `isSelected` which is confusing

The problem is `v-list-group` no longer emits nor binds any model for selection state. And the [actual example](https://play.vuetifyjs.com/#eNrtVc1u2zAMfhXBG5AWiJYehh2CNFhPwy679BjnoMhKKkyWBIn2Mhh+91Hyv+M1L9CLYZEfyU8fBfJQJd7xzYu1X8pCJNtkByK3ioHYp5qQXUk5cxnhinn/nCY50G8kv1JWgEkTkrMr/SMzeEPX16enNIlBMUxJD82BkExoL+EvgrjJLeOQJp2rpLnJhNp6oQQHkSHGCwCpL34ANU7qwSGvS8wT+Eg+QLbGCh3DD6sf+OeYWh07d8uq50UvzhSWlEwVAiNafM8+IjsZyCfkK0sGxiG0ItYZ60k9AQ+JJYbhnU5SByoRizKBBPW/QrNi1gm8SAiuiPSvrSpr/P+pMwHC5VIjcN1qckOkJcPfBP99Mld6Aj13o1hRc9rdf6gz6DkC412GwhE+obIU872wGbpmdRrKD59FKTQ83sZt5rJsJm9xMI/EHrdsCT5tTEtEG5BnyRlIo8f9+TW1T6v2PSqpVwa2y51aaMiYAg2PyWjigTm417j3+rQPKozBN9rdVp2puKTWTNo7OnpTaOTS6/fanD90u6MbjsyLgPHLe8F5SlmWkd71IeLMGmd2t19aY3dEOfZVhTOx2RykrnebYIsrLHDFHYaHSVk8eu6khRDWZpa5NQ5IRZw4k5qcncnJCvfiKjg5DoUIbmo8B9DD4fgY8jaZMEdSr3WhVPwc/wFr1kcG) for `v-list-group` with `classic` selection has this weird behavior I cannot pinpoint to specific line in the sources...

If I understand the direction of the changes, groups are now only for expand/collapse and it is already pretty clearly presented in the "Sub group" example (if we ignore huge indents and kinda unexpected collapsing.. I wish it had `open-strategy="multiple"` instead of default one).

To be frank I don't understand the "_easily connect actions to your tiles_" even in the v2 version, so I wish I could get an opinion from someone from the core team.
