### ISSUE TITLE
[Bug Report][3.6.11] Cannot Keydown.stop.prevent v-menu 

### ISSUE THREAD

**Issue by kmmerc18** [vuetifyjs/vuetify#20130]
### Environment
**Vuetify Version:** 3.6.11
**Vue Version:** 3.4.27
**Browsers:** Chrome 126.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Try to prevent a v-menu from opening when using up/down arrows while focus is on the v-menu activator

### Expected Behavior
The v-menu dropdown does not open

### Actual Behavior
the v-menu opens

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1UcGOgjAQ/ZUJFzURSPZI1KzZ836BeKgwJF1r27SF1ZD++04LCuzdC/TNvHlvXubUJ9ZU+VHrrGsxKZKdw5sWzOGhlAC7mndQCWbtvkzqtBF4h5/WOt48UqtZhSkzqpV1mUQ6DXTpDWULn1d81OpXZtYpnWmDHUo3coj1NIEutUK5glWOd8wpQzY9aKO0Bf8SHYUvTkKlRCRpw2/MPMqEFC5c1rFEUzQDx6cYBG3Y5XF0Ms8XEUdxwe2036uScuKSRRNN1wFtgezwvqEfBEyWUFBa6sdGgB0TLU6Fme5SOXXcCTz0fVTKIgLvw8b/ObPV5t1ZqkWGAMMhhivmdEZ6LZITtJXhepjAu1bGQY0Na4WDflCpmWMFrDewP8B6rMGQuoDTtFIPcckCVl+CV1f4xhX47Tv78DFnnMeX38SHD1Ff4RK/la0Q8XP+A4fm62s=)

### Other comments
I have a use case where, in a list of options, I have a button that opens up a menu. The list of options is navigated with up and down arrows. When I get to the button, I only want 'enter' to open the menu, instead I want the up and down arrows to navigate to the next or previous list option. Currently, there does not seem to be a way to force that behaviour

**Comment by KaelWD** [comment]
The event is on the button not the menu, and you would have to call stopImmediatePropagation not preventDefault: https://play.vuetifyjs.com/#eNqtUctOwzAQ/JVVLkmkJpU4VgVRwQUhJC6c2h6Ms0EGx7b8CFRR/p2101c4c0k8u+uZ2fF2yJzly40xdR8wW2Vrj52RzOPdTgGsG9EDl8y5213WVK3EH/gMzov2UDnDOFbM6qCaXZbG6UJfdajCERE+0UFfOan9inEveua1JcIBjNXGwXi+fqR49wq4lmnIWNExe9hlcP+Fh0Z/Kypq9YyHRzpTmcaFatIkkc2oADYnOYjqVyLLpHLxuZztffQhhfNzZ7FSCZol2Tb5KyJaAFnAn5J+EDHZgBXZpX5qRNgzGfBSmNm8Zq688BLvhiEx1QnBOEbHf2fm+5y7V1vNdojw/DrrJb0tnWabE3TcCuPBoQ8mDbZBUYhawTn0AksYJkrRQrHNN9bq79jJFzCBN5Pva6G4DA26AmvKoiwBa+e1eeo6bAQJvtKDsQ8WyYsy8o3xw7VyfkoRbmE76QyQNl5B/iAF/4IXzGFc/HcPbk7dfQxmioJCyMaFClKmz/4XZ8MGpA==
#20092 somewhat fixes this, `submenu` will open on right arrow instead of up/down.
