### ISSUE TITLE
[Bug Report][3.6.12] VNavigationDrawer keep visible after upgrade to version after 3.6.0.

### ISSUE THREAD

**Issue by Jayczee** [vuetifyjs/vuetify#20143]
### Environment
**Vuetify Version:** 3.6.12
**Last working version:** 3.5.8
**Vue Version:** 3.4.21
**Browsers:** Chrome 126.0.0.0, Google Chrome
**OS:** Windows 10, Windows, Mac OSX

### Steps to reproduce
Just click the open button.

### Expected Behavior
The drawer come up from right side after the btn is clicked.

### Actual Behavior
The drawer keep partly visible on the right side of the screen.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9U11v0zAU/SsmL22lxU0JAgm6imkg8YaEkHggPHjOTWfh2JbtZJuq/neu7aTxBuKpPffL55x78/NUOMu3N8bQcYDifbH30BvJPBwaRch+LJkx8W8EXCvPhAI7hWLQw6MvOwGyJWPZ6xbkdVP07tgUZJvX3XlFPnIp+G/MawPqk2UPYJvi8BUBaSPab2Ph0scH53Vfpiyx0GFzAt+gy54Ijc/phUhiv99mqhA6boXxxIEfkjjRG209OYX55Ew6q3uyQkNWWfI2Ekmcpwq6zYPBQWwILUjEeYIekOswcr36AlJq8kNb2b5abZaSi5Kp0NsBMB0KukFxL7Qii1XrDTkltZc+OjI5AG118HAdJ5+D4CQRxRVXccMviYZV5zYQydQRrfUO9/FfSz4s7IW7QYojTOQ7Jh1sMP+M/kxtpo6jp7bEHZuD6jgWqYefFjrc4udHox2sT9MEckZ1mTAEL29VsVEcWXh1upf0IpfMOdT2UNZ1U6TYcqkzmzkjNY8jMGXF8d7PcQPWCedB+YTD49oy+5Sgti1Y7Cl3qSH7aJhtLxzuy11VTRZn+cN3QD9v8X5xfjzlEMwue4YB/CXzXyfunyQQx/F4DmhaQOEYzldFTd/Q1zs8i5q+pbu6rOk7WpV34BmtaFX8+gMWBFk/)

### Other comments
I just upgrade the version of vuetify from 3.5.8 to 3.6.12 because i would like to use VEmptyState. Then I came across this bug.

**Comment by Jayczee** [comment]
Besides, if you change version of Vuetify to 3.5.8 then it will run as I expect before.

**Comment by KaelWD** [comment]
c6f65877b33f371c54c571aaea4155394b7debf2 0cd9e54a84249260eb9531a2f972ffd4d363a225 99ea55d2debbab3c7941b9a8b2070258261d8c48

**Comment by johnleider** [comment]
The layout system doesn't officially support width support.

**Comment by johnleider** [comment]
I reverted be8babe because it introduced other issues. The recommended way to do this now is to set **width** to **null**:

https://play.vuetifyjs.com/#eNp9U8tu2zAQ/JWtLrYBS4proIfUMRqkBXorUBTooeqBpVY2UYoUSEpOYPjfuyQli0mDnOzZF2dmV7/OmTW8vO+6Yugxu812DttOMof7SgHshpx1XfgbANfKMaHQjKEQdPjo8kagrGHIW12jvKuy1h6qDMq07o9T8IlLwf9SXneoPht2QlNl+28EoA5oV4bCuY/31uk2j1kw2FBzBN+xSZ7wjc/p+UhkvysTVQQtN6JzYNH1UZxoO20cnP18uEBjdAsLMmSRJB8Ckch5rCjKNOgdpAbfQkSsA/IA7vzI5eIrSqnhpzayfrdYzSVXJWOhMz1S2hc0veJOaAWzVcsVnKPaa18xMNljUWvv4TJMvnjBUSKJy9Zhwy+J+lWnNoBk6kDWOkv7eNOSjzN7Ye+J4oAj+YZJiyvKP6M/UZuo0+ixLXKnZq86jCXq/qfGhrb45bHTFpfncQJcSF0ijMDLW1VsEAfmXx3vJb7IJbOWtJ3y7bbKYmy+1InNlJGahxGUMuJwdFPcP6YNM08RalOjoZp8MxXcnkTtjhRSvZQxmHw5zNRXIsd8c3Mz+pzk9z+QTH2gI0blwj37YHLeE/TgP62v3bl7kgiW0wXtyTmP/EVc1p7hOtsWH4rN++z3P9uKVuQ=
