### ISSUE TITLE
[Bug Report][3.6.11] Installed MDI default icon fonts do not work in offline PWA at Vuetify 3

### ISSUE THREAD

**Issue by carromeu** [vuetifyjs/vuetify#20227]
### Environment
**Vuetify Version:** 3.6.11
**Vue Version:** 3.4.31
**Browsers:** Chrome 127.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
The build PWA is deployed at https://lte.a.agro.rocks/. Put phone ir airplane mode and all MDI icons will disappear. The NPM package "@mdi/font" are installed and in Vuetify plugin, had:
import '@mdi/font/css/materialdesignicons.css'

### Expected Behavior
When PWA is offline (airplane mode) its need to work like online, including show all icons.

### Actual Behavior
All PWA features works well when device is offline, but not icons of MDI package.

### Reproduction Link
[https://github.com/carromeu/lte](https://github.com/carromeu/lte)

### Other comments
I search for solutions in VueJS 3 / Vuetify 3, but on find in older versions.

**Comment by KaelWD** [comment]
https://vite-pwa-org.netlify.app/guide/static-assets#globpatterns

**Comment by leeb-jstrasser** [comment]
This won't actually work because the bundled CSS uses a query parameter but since this file is not exported in the bundle the service worker cannot download it.
  
<img width="1084" height="906" alt="Image" src="https://github.com/user-attachments/assets/f6d4ad3b-8476-4c9f-a83c-3cae08d086a4" />
  
glob pattern:
<img width="434" height="428" alt="Image" src="https://github.com/user-attachments/assets/6786a3b5-1798-41c3-b411-170c73ad6e32" />
  
vuetify.ts:
<img width="473" height="574" alt="Image" src="https://github.com/user-attachments/assets/9f3eaccf-8e81-4780-9d96-76f2af5889ab" />
  
Erroneous bundled CSS:
<img width="586" height="362" alt="Image" src="https://github.com/user-attachments/assets/63b7391d-97aa-429b-b3b6-6211fbc0aeca" />
  
**Solution**
On PowerShell you can use `Get-ChildItem -File -Path "./dist/assets/*.css" | ForEach-Object { $str = Get-Content $_; $str = $str -replace "\?v=\d+\.\d+\.\d+",""; $str | Out-File -Path $_ -Force }` to get rid of the stupid query string.

**Comment by frederikheld** [comment]
@leeb-jstrasser Here's a proper solution:

Add the following to your `VitePWA` config in `vite.config.ts`:

```ts
VitePWA({
  workbox: {
    globPatterns: /* glob string including woff,woff2,ttf,eot */
    ignoreURLParametersMatching: [/^v$/],
    /* other workbox config */
  }
  /* other pwa config */
})
```

@KaelWD: the plugin docs you have linked don't mention this part and I'm also not sure about side effects. Can this approach be used without breaking anything in Vuetify?
