### ISSUE TITLE
FAB button not properly aligned using tooltips

### ISSUE THREAD

**Issue by jmarcelo93** [vuetifyjs/vuetify#2024]
When using v-tooltip the fab button is not able to go to the correct position (probably because of the parent being the tooltip).

### Steps to reproduce
See codepen

### Versions

v0.16.1

### What is expected ?

FAB must be aligned at bottom right.

### What is actually happening ?

FAB not aligned properly.

### Reproduction Link

https://codepen.io/anon/pen/wrpyqP?editors=1010

**Comment by johnleider** [comment]
I'm adding a QoL change to make this easier, but you will have to change how you handle the tooltip in this situation. Mainly because this is a special case in which you will have to manually control the state of the tooltip. For the time being, here is an example of a workaround you can do **now** in 0.16.1:

https://codepen.io/johnjleider/pen/RLxvZG?editors=1011

**Comment by peluprvi** [comment]
In case of use this in too many places, another temporary solution for tooltip usage in absolute FABs is CSS:
https://codepen.io/anon/pen/BJGoPG
