### ISSUE TITLE
[Feature Request] [VNumberInput] Click event support for increment / decrement buttons

### ISSUE THREAD

**Issue by gayanSandamal** [vuetifyjs/vuetify#20342]
### Problem to solve
I tried to used this component to send API requests when on value update by typing and on clicking on the increment and decrement buttons.

According to my use case I wanted to throttle the keyup event separately and emit right after clicking on the increment / decrement buttons.

But as per the current implementation increment / decrement value change fetched under `@update:model-value`

### Proposed solution
I propose to add something like below where we can separately handle the click event on increment / decrement buttons

`@click:increment` / `@click:decrement` or one event for both

**Comment by J-Sek** [comment]
Is it some kind of server-side validation scenario?
Let me know what do you think about [this example](https://play.vuetifyjs.com/#eNp1UU1vqzAQ/Cv7uECkJOSptwii99Q/UFVVL00PLiypK2Nb/iCqEP+9awMBterFsmfGuzuzL31iTZX/13rfeUyOSeGw1YI5PJ0lQNHtmNbxGh+Vko5xiWaCIih9+4Zmx6X2boYBjq2qUew6JjyW58SqFp/D/ZysNEKxmssL8aTjNXP0WAv+eU0gfqul5P07k5dVqXyZRxs89T20aC27IAxDkQdospB/9xCQ0WKRr6zT01aGawcWnR8T4K1WxkEPBhsYoDGqhZRSS4McgOpaks8+oQy67LBZuMXjRDZMWFwJ5qFHNk2JCiSzn7KCxsvKcSVhtp91G+hHX+G7ErgX6pKlqzYSr6Grx2O6hW4qB6tB9pGlhs7QaiLJroy7+POBHHKLmYHyFHJ44i0q7zKzhb+Hw2ETJ6dcGsg6+FOWcHcbCJYgbi26mZps3oiUEgz4AEh5LCV+6B7xAyuH9RbugFuQygETQl2xniv86i9GHViSFPm4W9pqMmylFyIer1+Fuf0C)

**Comment by gayanSandamal** [comment]
> Is it some kind of server-side validation scenario? Let me know what do you think about [this example](https://play.vuetifyjs.com/#eNp1UU1vqzAQ/Cv7uECkJOSptwii99Q/UFVVL00PLiypK2Nb/iCqEP+9awMBterFsmfGuzuzL31iTZX/13rfeUyOSeGw1YI5PJ0lQNHtmNbxGh+Vko5xiWaCIih9+4Zmx6X2boYBjq2qUew6JjyW58SqFp/D/ZysNEKxmssL8aTjNXP0WAv+eU0gfqul5P07k5dVqXyZRxs89T20aC27IAxDkQdospB/9xCQ0WKRr6zT01aGawcWnR8T4K1WxkEPBhsYoDGqhZRSS4McgOpaks8+oQy67LBZuMXjRDZMWFwJ5qFHNk2JCiSzn7KCxsvKcSVhtp91G+hHX+G7ErgX6pKlqzYSr6Grx2O6hW4qB6tB9pGlhs7QaiLJroy7+POBHHKLmYHyFHJ44i0q7zKzhb+Hw2ETJ6dcGsg6+FOWcHcbCJYgbi26mZps3oiUEgz4AEh5LCV+6B7xAyuH9RbugFuQygETQl2xniv86i9GHViSFPm4W9pqMmylFyIer1+Fuf0C)

Hi @J-Sek thanks for picking up this issue and replying. I checked the example you provided and that's really helpful but in my scenario,
1. User needs to press enter or blur the field to update the value (send API request with the newly entered value) after typing.
2. Or user can click increment / decrement buttons send the API request right away with the newly changed value.

That's why I need to handle the increment and decrement button change separately.

@J-Sek Please let me know if you need further clarifications

**Comment by KaelWD** [comment]
You probably want to respond to keyboard up/down too right? Would `watch(count, (a, b) => { if (Math.abs(a - b) === 1) run() })` solve your problem?

**Comment by J-Sek** [comment]
@gayanSandamal OK, so it is not the validation, but a "send to the backend" and you want to handle up/down control clicks without waiting for blur because in the user's mind he is not typing and expects results to be effective immediately.

VNumberInput captures clicks on up/down controls, so there is no way to get this behavior. I needed to swap component with rudimentary implementation for [this example](https://play.vuetifyjs.com/#eNqtVU2P0zAQ/StDODQVTVuEuHTbalfAYQ+LkEBcKAc3nuxaJHbkOFmqkv/O2M5nP4ADl7aeN+OZeTN+/XYMCh0v7vJ8XpUYrIK1wSxPmcHtTgKsq4jlufvpDrGShgmJujGRMTtEssz2qCMh89K0doAqyhTHdLMLCpXhV5aWuAt6eJUqxoV8tDir6McQjFNkmu1T7E23+7TU5Mxxr0oZI//MqtGFt3Eq4h8rF/ovftSKVra8K56LvsdcI5XEioK8MxO92QVbOhnrz11jKzgeYWyCul4vKLAlb3HKnrV4cteLAel0LGItcgMFmtJzL7JcaQMPh4+O6XtLNCRaZTCZL04GYOc4GQQdQWMCdePuQQtTMQXlaEcDG+sXLqc9dtLPuYOfWwMkLC2QQAsnRKcRSkJLbcjceQZZMYWjZyRFA0ZkqEpzz+mSpTeLBMLO3Dk3K/HFAwMHD9f+SxNjWvbpw/l8zvRjnxNGGYng9sJwCpst+Cq7KFfuIAF92C9WHGTcJyEWkMKbDJ6Zyt7eUjuv3O533VXwYrM5Ydf7DOr03HozXWZ0ewPlf2bCgMRn+EQzFQWG2hY/6EbP4PVyuZw2xRPXF5LRrdWVbG6W54373kbPhZy7GVsiZvCW8tqV9ktM6xvMnMRcWNNLcmPwp4kSgSnvXtxeaY56F7SKMvf3EOKJtcBeSE4GF/hOyUSQnLQvr00BL+m5oeT9u6Y44zprV2yYMBqpRsW0YNLYHHTXENHUPUebfTk0C2LLygUXUfyElVYyKvNzHSIXIePevrWyQFVdLfJ/FMLVs7xYCsfrpYxUystXP6y/qBgtoFN6UzRj6cQpVhltA/IZlAXeGaOLkVbdDDePOXjTeYZTgrsn1+wux4Qk9sEuytovCvwCWabpNjxakJWpWcESahvch2NGb6qN/kCHYn2EkIR9Mvq7mExXUCnBod6Gp2JHc7Q64Cvxb+nVqxt3c3h6i39XA508C42iP4T2dQ82nspv2Wz0rFGTRhY7bbH6ZvmbtYZmp6hZUo+UCOCTDnsSHN8j/W+lBeGsNKrH7MmmJCm3TKkkabGaVBKYPLgBOaqHilDP7EDcx/ffLIq/xw==) to work. Please excuse poor debounce.. in real life, you would probably need something better to handle race conditions.

**Comment by gayanSandamal** [comment]
> You probably want to respond to keyboard up/down too right? Would `watch(count, (a, b) => { if (Math.abs(a - b) === 1) run() })` solve your problem?

When I was developing our component I did something similar to what you mentioned above to achieve the expected behaviour

https://github.com/FlowFuse/node-red-dashboard/blob/6015c0f9fadc39bcc79dae28c40dbc538c2a92a5/ui/src/widgets/ui-number-input/UINumberInput.vue#L144

**Comment by gayanSandamal** [comment]
> @gayanSandamal OK, so it is not the validation, but a "send to the backend" and you want to handle up/down control **clicks** (not the keybroad actions) without waiting for blur because in the user's mind he is not typing and expects results to be effective immediately.
> 
> VNumberInput captures clicks on up/down controls, so there is no way to get this behavior. I needed to swap component with rudimentary implementation for [this example](https://play.vuetifyjs.com/#eNqtVU2P0zAQ/StDODQVTVuEuHTbalfAYQ+LkEBcKAc3nuxaJHbkOFmqkv/O2M5nP4ADl7aeN+OZeTN+/XYMCh0v7vJ8XpUYrIK1wSxPmcHtTgKsq4jlufvpDrGShgmJujGRMTtEssz2qCMh89K0doAqyhTHdLMLCpXhV5aWuAt6eJUqxoV8tDir6McQjFNkmu1T7E23+7TU5Mxxr0oZI//MqtGFt3Eq4h8rF/ovftSKVra8K56LvsdcI5XEioK8MxO92QVbOhnrz11jKzgeYWyCul4vKLAlb3HKnrV4cteLAel0LGItcgMFmtJzL7JcaQMPh4+O6XtLNCRaZTCZL04GYOc4GQQdQWMCdePuQQtTMQXlaEcDG+sXLqc9dtLPuYOfWwMkLC2QQAsnRKcRSkJLbcjceQZZMYWjZyRFA0ZkqEpzz+mSpTeLBMLO3Dk3K/HFAwMHD9f+SxNjWvbpw/l8zvRjnxNGGYng9sJwCpst+Cq7KFfuIAF92C9WHGTcJyEWkMKbDJ6Zyt7eUjuv3O533VXwYrM5Ydf7DOr03HozXWZ0ewPlf2bCgMRn+EQzFQWG2hY/6EbP4PVyuZw2xRPXF5LRrdWVbG6W54373kbPhZy7GVsiZvCW8tqV9ktM6xvMnMRcWNNLcmPwp4kSgSnvXtxeaY56F7SKMvf3EOKJtcBeSE4GF/hOyUSQnLQvr00BL+m5oeT9u6Y44zprV2yYMBqpRsW0YNLYHHTXENHUPUebfTk0C2LLygUXUfyElVYyKvNzHSIXIePevrWyQFVdLfJ/FMLVs7xYCsfrpYxUystXP6y/qBgtoFN6UzRj6cQpVhltA/IZlAXeGaOLkVbdDDePOXjTeYZTgrsn1+wux4Qk9sEuytovCvwCWabpNjxakJWpWcESahvch2NGb6qN/kCHYn2EkIR9Mvq7mExXUCnBod6Gp2JHc7Q64Cvxb+nVqxt3c3h6i39XA508C42iP4T2dQ82nspv2Wz0rFGTRhY7bbH6ZvmbtYZmp6hZUo+UCOCTDnsSHN8j/W+lBeGsNKrH7MmmJCm3TKkkabGaVBKYPLgBOaqHilDP7EDcx/ffLIq/xw==) to work. Please excuse poor debounce.. in real life, you would probably need something better to handle race conditions.

Thanks a lot @J-Sek I've achieved the expected behaviour by doing something hackie [here](https://github.com/FlowFuse/node-red-dashboard/blob/6015c0f9fadc39bcc79dae28c40dbc538c2a92a5/ui/src/widgets/ui-number-input/UINumberInput.vue#L144) and it's similar that @KaelWD showed in his comment because I was in a rush to get that done.

I will try with your new example because it's more cleaner than what I've done at the moment.

Also I will close this issue as it's resolved
