### ISSUE TITLE
Infinite scroll with List Component

### ISSUE THREAD

**Issue by jdriesen** [vuetifyjs/vuetify#2037]
### Steps to reproduce
I'm searching for a demo which can point me in the right direction (see explanation below)

### Versions
"vuetify": "^0.15.7",

### What is expected ?
Since a couple of days, I'm searching for an example which combines 'infinite loading' with the ... [Vuetify List Component](https://vuetifyjs.com/components/lists)
I've been searching all over the issues and demo's, but I can't find an example which can point me at least in the right direction.

### What is actually happening ?
Nothing, beside the fact I'm searching for an example.... 

### Reproduction Link
Well, I'm currently 'moving' from Bootstrap to VuetifyJS.
So, I have some examples made in my 'old' environment.
Please take a look at [my test site](http://develop.ireporter.be/)
When clicking on 'teams', you'll see a limited list. (scrollbar is not shown)
When clicking on 'players', you with see a 'longer' list which is dynamically loaded (scroll down in the list  -scrollbar is shown)

I'm searching for a solution to 'reproduce' the same affect using Vuetify ...
On my demo site, I'm using '**vue-infinite-loading**', but I don't know if this is recommended in VuetifyJS... (and I can't make it working either ...)

Any suggestion which can point me in the right direction, is more than welcome.

Thanks in advance for your time.
Regards,
Johnny (Belgium)

**Comment by Webifi** [comment]
Off the top of my head, maybe you could add an item to the end of the list, and use something like this to observe?:
https://github.com/Akryum/vue-observe-visibility

When observer shows visible, add content until you're out of content or the observer is no longer visible, whichever comes first.

Since this doesn't seem to be a feature request or bug report, probably better to move this to discord: https://chat.vuetifyjs.com/

**Comment by nekosaur** [comment]
As @Webifi said, since this is neither a feature request or a bug report, please join us at our discord instead https://chat.vuetifyjs.com.
