### ISSUE TITLE
[Bug Report][3.7.0] Using the v-treeview directory tree to duplicate node and parent node names leads to an endless loop

### ISSUE THREAD

**Issue by zulezhe** [vuetifyjs/vuetify#20389]
### Environment
**Vuetify Version:** 3.7.0
**Vue Version:** 3.3.4
**Browsers:** Edge 128.0.0.0
**OS:** Windows

### Steps to reproduce
I want to use the v-treeview to display my project directory. I also have the src directory under my src directory. When I click src to expand it, I get stuck in a loop

### Expected Behavior
available

### Actual Behavior
not available

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtWs1u4zYQfhXWF7dApJx6MbJbLNDtrVugKHpJcqApyuGaIgWSUmwYfvedkSWFkvVjJ3FsA2sgsTUz/Obj8HdI3W8m1rDbL2ka5hmfzCZ3jieppI5/flCE3OWBM5zngj/jIyEzAXr76WFSfD9MSqlOueIRipVwgkq5/gcklRptg5zKjIOFE07ySkOZEzl1dA6iQoBAgVYBk4ItUVTQACIVLZIHVmo3Sw0HU3S5KfBviLDok2wfJmWZgr5gWkEZEYPlL2gYxgL91zaEbABhV/YPMk0iEcRaRtwEyGVKZr5sSrbbGvx2h97hjUvLPyMu+rL3tdtHKN4ud3fbjDhoq5CDoKGFR8uMSB2x3GVpYS+SVBtHNsTwmGxJbHRCptCUUzQnBPxYRxqtQj6h7a/30zSbQ5Snj7+9GBZ8S4PNjt+TS2QZA0nVIqMLHqDs9+nNzuC7LdVKR/y7fRFrVSoYKAJ8rnRJ1EZMqFlG+rm2SKO4CjxQCuAxmOtVrVULXysSgKh0buV8XaRZlnDlAp05KVRttpIV7cKMrxiXO93Wi0fRy6uA7QqWYQFH2JEBY54JGVWwUPAJHg2HupcFGoX8gsAKfyE7GyaUhakU1r0g4QfJgWmHRti/QPcNQjsjzmTcU269352esfuFgqm6sRrO9hXv4Ev3uGrJ3+wJukZ3BNvygzw9lr8qyV7jG251Zhj3AnZ4BzgHYZjtX0M1oaIemwNl98o3qpt6rkdhOqF8OAieM1pKmJX3UEeRe9EbI5taHrrWWPA/ZVMNmQy0mv/xO/dRHCNYPWGCrUJx6XTjOEn54poI4+pwPXSt0+aq+K4tbo7OybKaMscsBycjoSK+6q3GSBUOoL9PqE27bdE7DWdOyA4ir5+IP77uI4QUd8/aLK+jOfqjN0BzhGLTuU9tdBMFeZXU1NvPvnKtL2oVnbRe1xNUCB0kj+2NyvFRbWze3j5wqYU8smcQvH33xOzAjD0KP+iiueKtIWcN4W/Andfy44YHriZD6173qvKmlRKTBRvavJUVdNRw0Ob8SyXTcGShMOk9Vc/DGv4HZygf0f12Mw0euBzS+UbtLrPvfaP5z1i+Uyz/58YKHMqD/A+p4wXsersy+vcZw5jXXkcyew0Z7KVzHE4hLim3/plQf8zUUt5IDSZwvfpTJJVc5T35zJmyXDySvaYUFy+NevOxbuXpMjK3Tv0z+9elY+X8f7YsdyH1nMpzZ9mndd/dqqPXHFxyBkegKihu5+AcdO33r5JcQ9bDatRDmMMlYQjJWSyaW4GOCBzrQ1lhQ2Wf9kAbsmNRU8qWcGEa+jeyNXJTeCz0v1+//Pn31zDxzo9KXF90LKqzZXhPwLjGxtvrkzp45vNT4K+pUaHUbLmH2xQO4uI7AHe3u5cL4LWCyfZGZVIW/x5/AH8SC+c=)

**Comment by J-Sek** [comment]
I was able to fix it by adding unique ID to every item and using it instead of title for `item-value`. ([Playground](https://play.vuetifyjs.com/#eNrtWs1u2zgQfhWuL05Qi9nLXowkiwLbBfbQLrBY9JLkQEuUw5oiBZFSbLh+987ox6Fs/dhJHNtFDSS2ZobffBxSJIfk3XJgEv/qYxzTLOWD8eDa8iiWzPLbe0XIdebZhPNM8Cd8JGQsQG9u7gf59/2glOqYKx6gWAkrmJSLf0FSqdHWy5hMOVoElZj5VmTMsonkhQBRPK08Xwp/hqKcA7CoOJHMM1LbcZxwMEV/yxx8RIRBh2R1PyjL5NyFrxWUESFY/oaGNBTg7NmGkCUgFGX/JMMoEF6oZcATD7kMydiVDclqtQa/KtAbvHFp+C3ioi9zt3b7AMU3y11f1cMN2ireIKhp4dH4iYgtMdymcW4volgnlixJwkOyImGiIzKEdhyiOSHgx1hSaxJyg7YXd8M4nUCUhw+Xz4Y539JgWfB7tJEsYyCZmqZsyj2U/TEcFQbfTKlWOuDfzLNYq1Lhg8LD50oXBZuIEUtmgX5aW8RBWAUeKHnw6E30fK1VU1crIoCodHZuXV2g/TTiyno6tVKotdlcVrRzMz73uSx0qzweklsimbH/BBCO351QYqevQlhAlYEC18JKDqiTVMigcgQFH+Ex4RCNskCtkFsQeOIv5GtoxHwaS2HsMxJ+kC6YNmiE+Rt0XyDYY2KTlDvKlfO70TN2SCp8tW6+mrNtxRv40i2uNuSv9gSdpTmCm/KdPD2UvyrJVuMn3Og08bkTsN07wDEIw+D/EqoRE+u3taPsVvladWPHdS9MI5QLB8GziZYSxukt1F7kVvTam80Mp3bjXXA/ZVN1mXS0mvtxO/deHAOYT2HIrUJx6nTDMIr59JwI43xxPnSN1clZ8V0YXC4dk2U1ZPZZdg5GQgV83lqNnirsQH+b0CbtTYvWYTi1QjYQeflA/P517yGkuH3Syew8mqM9eh00eyjWnbvUehdRkGlJzZz17Avn+rxWwUHrdT5BhdBBOrm5UNk/qrXF2+tfXGYgs2x5CV6/evJNx4jdC9/poj7jLSCLpfDX4c5p+X7DHWeTrnmveVZ51UyJyYKhJtvIChpq2Glz/KnS17CJoTDpPVTPwxr+D7sq79H9ipEGt2B26Xy9dqfZ976w7Fcs3yiWX3liBL7Knfx3qeMJrHqbMvq3eYcxrz2PZPYcMthT59idQpxSbv0roX6foaU8oOpM4Fr1h0gqucpa8pkjZbm4JXtOKS4eI7XmY83Kw2VkdhG7e/YvS8fK8f9oWe5U6gmTx86yD+u+uVV7jzm45D5sgSovP52DfdCF279KcjVZC6teDzSDQ0IKyVko6kuBhgjs60MZYagyj1ugNdm+qDHzZ3CESt0z2jVyXbgv9H+fPv71+RONnP2jEtcV7YtqTRneAzBeY+N59kEdPPHJIfAXLFFUan+2hVsXduLirYD8fgGed9P85kahpiHcRvjM4os5ubkld0tCKZ2P3LESbjmMUHoxp5WUfP8O8sviqsFPhhFV5cFG4G2BDx+KiwOXYHF9VdzYgLsag9VIpVLm/x5+ACkEcQI=))

I can also just drop `item-value` and it seems to work fine.

Are you sure VTreeView should work normally with incorrect declaration?

**Comment by yuwu9145** [comment]
item-value shouldn't be duplicated. You should either:

- "Adding unique ID to every item" like @J-Sek suggested above
- Or use `return-object` ([demo](https://play.vuetifyjs.com/#eNrtWktv2zgQ/itcX7wLRMppL0baRYFtb22BouglyYGWKIcxRQokpdgw/N87o1coWQ87iWMbqIHE1szwm4/D55C63UyMDq4/JYmfpWwym9xYFieCWvbxThJyk3lWM5Zx9oSPhMw46M2Hu0n+fTcppSphkoUoltxyKsT6O0gqNdp6GRUpAwvLrWCVhgaWZ9TSOYhyAQJ5SnqB4MGyEGlmUw3C+SMLLIpyZsCtYkoyzwhlZ4lmUBpZbHKXV4QbpEG2d5OyTF4jHigJZXgEln+hoR9xpFTbELIBhKLsf2Qah9yLlAiZ9pDelMxc2ZRstzX4dYHe4Y0Jwz4iLvoyt7XbeyjeLndz3WwE0FatAIKGFh5NoHliiYEwJbk9jxOlLdlA5CKyJZFWMZlC607RnBDwYyxpNBT5gLZ/306TdA6Bn97/82yY8y0NNgW/BxuLMgaCykVKF8xD2b/Tq8Lg0ZRqqUL2aJ7FSpaKABQePle6OGwjxlQvQ/VUWyRhVAUeKHnw6M3VqtbKhavlMUBUOruyri5UQRozaT2VWsFlbbYSFe3cjK0CJgrd1olH3vGrgBUFy7CAI+zbgDFPuQgrWCj4AI+aQd3LAo1CbkFghb+QnfFjGviJ4MY+I+EHyYFph4abL6D7BqGdEatT5ii3zu9Oz9j9fB7IurEaznYVb+BL9bhqyV/tCbpGdwTb8r083Ze/KslO42tmVKoD5gRs/w5wCsKwALyEakx5PTYHyu6Ub1Q3cVyPwnRCuXAQPKuVEDAr76COIveiN0Y2Ncy3rbHgfsqmGjIZaDX343bugziGsKDCBFuF4tzpRlGcsMUlEcbV4XLoGqv0RfFdG9wcnZJlNWWOWQ5ORlyGbNVbjZEq7EF/l1CbdtuidxpOLRcdRF4+Eb9/3UcISWaflF5eRnP0R2+A5gjFpnOX2ugmCvIqoaizn33hWp/XKjxqvS4nqBA6SB7bG5XDo9rYvL1+4FIDeWTPIHj97ikwAzP2KPygi+aKt4ac1Ye/AXdOy48b7rmaDK173avKq1ZKTBaMb7JWVtBRw0Gb0y+VgYIjC4lJ77F6HtbwJ5yhvEf3K2YaPHDZp/ON2p1n3/tGsz+xfKNY/mLacBzKg/z3qeMZ7Hq7Mvq3GcOY115GMnsJGey5cxxOIc4pt/6TUL/P1FJeUg0mcL36YySVTGY9+cyJslw8kr2kFBcvjXrzsW7l8TIyu07cM/uXpWPl/H+yLHch1JyKU2fZx3Xf3aqj1xxMwP2xhrvl/HYOzkHXbv8qyTVkPaxGPfgZXBL6kJxFvLkV6IjAoT6k4caX5mEHtCE7FDWhwRIuTH33RrZGbgoPhf7x+dP/Xz/7sXN+VOK6okNRrSnDewTGNTbeXh/VwRObHwN/TbX0hQqWO7hN4SAuvgNwc128XACvFUy2VzIVIv93/xtyIhJ1))

**Comment by J-Sek** [comment]
I have managed to pinpoint specific place where the code get's stuck:

![image](https://github.com/user-attachments/assets/3c08bf7b-128a-4c03-a2d1-9aa69a50bedb)

In theory we could mitigate issue by throwing exception once we detect duplicated ID. Tree view will be unexpectedly unable to expand specific node, but at least end-users browser tab won't have a chance to freeze. I am curious about @yuwu9145 's opinion on it.

**Comment by yuwu9145** [comment]
Adding a warning message would be a good solution, feel free to open a PR
