### ISSUE TITLE
[Bug Report][3.7.3] VDataTable not work with facing-dev/vue-facing-decorator

### ISSUE THREAD

**Issue by mak7an** [vuetifyjs/vuetify#20654]
### Environment
**Vuetify Version:** 3.7.3
**Vue Version:** 3.5.12
**Browsers:** Chrome 129.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
npm run dev

### Expected Behavior
Table with rows

### Actual Behavior
Empty table, only header

### Reproduction Link

```
<template>
  <v-data-table :items="items || items2"
</template>

@Component({ components: [
  VBreadcrumbs,
  VBtn,
  VCard,
  VChip,
  VDataTable,
  VIcon,
  VImg,
  VList,
  VMenu,
  VRating,
  VTab,
  VTabs,
  VTabsWindow,
  VTabsWindowItem,
  VTextField,
] })
export default class App extends Vue {
  items = [{ name: 'Anna', role: 'Manager' }]
  
    @Setup(() => ref([{ name: 'Anna', role: 'Manager' }]))
    public items2 = [{ name: 'Anna', role: 'Manager' }]
}
```
[https://github.com/mak7an/nuxt](https://github.com/mak7an/nuxt)

**Comment by craigrileyuk** [comment]
Class components are not supported or recommended by the Vue team.

If you're having issues using such packages, that's up to the package maintainer to fix.

**Comment by mak7an** [comment]
@craigrileyuk [i do but i think they don't maintain that package](https://github.com/facing-dev/vue-facing-decorator/issues/138) little hope

**Comment by MatthewAry** [comment]
Aside from your code block in the issue the reproduction link makes no reference to the VDataTable component. Also @craigrileyuk makes a good point. Decorator and Class based component design is seldom used by the Vue community, the abstractions they provide could also have unintended consequences. Please be extra sure that your problems are not being caused by the sugar.

Regardless, this issue has an unusable reproduction, a thin issue description and thus will be closed. You may file a new issue, but please be sure to follow the guidelines.
