### ISSUE TITLE
[Feature Request] VDataTableServer persistent pagination settings

### ISSUE THREAD

**Issue by steveatkoan** [vuetifyjs/vuetify#20652]
### Problem to solve
I have a CRUD app that uses a VDataTableServer to display a list of records. The user clicks a View button to view the record, then clicks a left menu item, breadcrumb item, or "cancel" button to go back to the list. The user may customise the list eg by moving to the next page, changing the sort order, or adding a search term. I want to be able to restore that when they go back to the list.

### Proposed solution
Current VDataTableServer calls @update:options with page = 1 when loading the component. If you change the page number to > 1 or try to change the itemsPerPage you get an infinite loop. Fix this so that you can pass in any initial values you want so that user state can be restored

**Comment by MatthewAry** [comment]
This kind of functionality is out of scope for Vuetify, specifically because there are a great many ways to go about managing state persistence, each with different characteristics that are of concern to the developer and not the component authors. For pagination, I would use [VueUse useRouterQuery (assuming you're using Vue Router)](https://vueuse.org/router/useRouteQuery/) to store your pagination state in the URL. This will allow you to use the browser's navigation history to track state.
