### ISSUE TITLE
[Bug Report][3.7.3] VCheckbox - update:modelValue not emitted if modelValue was unchanged on last update

### ISSUE THREAD

**Issue by tobias-rondin** [vuetifyjs/vuetify#20673]
### Environment
**Vuetify Version:** 3.7.3
**Vue Version:** 3.5.12
**Browsers:** Chrome 130.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Click the checkbox
	* updateInfo is set to 'ShouldUpdate'
2. Click the checkbox again
	* Nothing happens
3. Click the checkbox again
	* update:modelValue is emitted and modelValue is updated

### Expected Behavior
update:modelValue is emitted on every click

### Actual Behavior
update:modelValue is only emitted after clicking twice if modelValue was not updated on the last emit

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUjtvgzAQ/isnFhIphR0BapWpS4e+ltLBMUeDYrAFJm1F+e+1jQkJCVXDAPhe38P31jp1Rf07Ibx9g07ghDWtciGhRtkIYKT8iBJH1okTJyVAXgheSWihwmwF8lsgPGIGHWQVL8BVI9yk1IUmtWY53T1/5hTXW6S7Df+CCFqdBqA6gmkAG84ZEtME0IiUSLwvMx6A+7TlDUtfTMiFnyHwwKWN6Z6ux6O8rCXQM8BA8wvPicSKidKwmLLJCKtxNUtmgr08BleODdNfCWtQISz2+uegcQlRPOjPM1ic0/VMgzciQxRFEyeWwwgFPDNgtPlEnMlZcf8SqB9lsPkAKmeuhfY8b67wbx4zJOyNh36/pWon1UFiIZiqNhsa7m+IEObXHNTdSJKXWNlQH7RMRgqMbJCpTR84Js6YCwqeIjN3qiou6LEGH/fc9ppOW6cbMjbEoT+yOjBt2ws2Q2fNMC0n6nSkFx/6R6Y43apsGDOv918MlEzq)

### Other comments
Similar to https://github.com/vuetifyjs/vuetify/issues/19137 but not fixed.
In our case, for certain scenarios we have a confirmation dialog where the user decides if they want to update the value or not after the checkbox is clicked. If they do not, this bug happens.

**Comment by MatthewAry** [comment]
Hey so [I modified your example](https://play.vuetifyjs.com/#eNqNUj1zgzAM/Ss6FuAuLTsHufYydenQr6V0IEY0XAz2gUnbo/z3ygaHABm6gC0/Se896b1zmpoF91Lenlp0QidqWF1IBQ2qVgJPq884cVSTONukAihKKWoFHdSYb0D9SIQnfWKilK3CDHrIa1GCS8XcpNIpBrTjBTu+fBUMdwdkx734hhg6/QzAdASzEPZCcExNEkArs1ThQ5WLENzng2h59mpCLvzawKNQY0zn9EM/JqpG2aLUhZh6ecob9KfXqfgIWBUk8GU5csMSf0t5i5TmnfThzNqHeGsVnTXdGgyBzX94LHLwpv4WEccLlf5UbI2+bgBZAEhC/5M5T1vbd21edsieZ8R6y/nNRG/WY1yyMV19cjoKhqWjFaOLwlJyApqFi043qZTmaC5ET6VFhfUYGoIjRxsC2ts9clpcyz5xprewFBlyM0ZCjKQvAXcD0TluuQFTwjYKJgpnWl13zcTeWE2kdcpMio4MSqPgwgGn31Qt5+bz8Qd+1jlu). Is the double clicking a desired behavior? If not, then I think your problem lies with `:modelValue="clickTwiceCheckbox.checked"` [and the way you're doing assignments to the ref that contains an object.](https://arc.net/l/quote/waxlbcis). I _think_ your reactivity is getting reset because you're basically assigning a new object when you invoke your `setCheckboxValue` function. But admittedly I am not an expert on these interesting use cases.

Either way, I can confidently think of a number of ways to work around your problem and thus conclude this is not a bug.

**Comment by tobias-rondin** [comment]
Hi. [I have modified your modification](https://play.vuetifyjs.com/#eNp1Uk1vgzAM/SsWF0Dqxh1BtamnXXbY12XsQINZUQOJIHSbGP99TiClQHeBxHnPfn72e+c0NQvupbw9teiETtSwupAKGlStBJ5Wn3HiqCZxtkkFUJRS1Ao6qDHfgPqRCE/6xEQpW4UZ9JDXogSXkrlJpSkGtOMFO758FQx3B2THvfiGGDr9DMB0BLMQ9kJwTA0JoJVZqvChykUI7vNBtDx7NSEXfm3gUagxpjn9UI+JqlE2KVUhpV6e8gb96XVKPgJWCQl8mY7csMLfUt4i0byTPpxV+xBvbUdFDt5U4tYAIY7jRSO+xZ89sFAwf/u4TnXdALIAkBqd0v7PnNPW9l2blx2y55lmveX8Zk1s1mNcqjFVfXI6CoaloxWji8JScgKahYtON6mU5mguJE+lRYX1GBqCo0YbAtrbPXJaXKs+caa3sBQZcjNGQoyiLwF3g9A5brkBE2EbBZOEs6yuu2Zib6wm0Zoya0VHhk6j4MIBp99ULefm8/EHiLQ5bg==). Double click is intended behavior. Triple click is not. How do I avoid the triple click and make update:modelValue trigger on every click?
