### ISSUE TITLE
[Bug Report][3.5.10] text-truncate class not working in v-tooltip when used with v-btn

### ISSUE THREAD

**Issue by phibzy** [vuetifyjs/vuetify#20713]
### Environment
**Vuetify Version:** 3.5.10
**Vue Version:** 3.3.6
**Browsers:** Firefox 132.0
**OS:** Windows 10

### Steps to reproduce
1. Create button with tooltip (either with icon or without)
2. Add "text-truncate" class to tooltip with long text

### Expected Behavior
Text in tooltip truncates

### Actual Behavior
Text overflows tooltip and overflowing text is in a grey font

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVUUFuwjAQ/MrWF1qpKVS9VQGpt9574ND0YBxDLK29lr1GVIi/dx2gECmKvDOTmXjn+6hyMvOPGF/2xap31bL1ETXbVRcA2n2jYxyP42AosHbBpgs0ghsOYFDnvOyUx+a1U8CO0co4WESS2cmHle1d48KWktfsKDRUGMWtU/92o2FVr9r55TChmAjZxRsGoA27vWZKEhB1soE7dc+zPbBQX+QtJKsRf6HXPgBS2I0k8KAZ8kAFe9CbTFjYimpjgVMJRpbRy2B0yYIMLoM8yfXOFKSSRVmtpqFeH9au50GC3xaLKXfdVc1urgn3kvHul5veFi2YbPrahUzTMipy7qqd33UoYzbJRbmg5XK2cz5SYjjKOrZwgm0iDzOpf1bl8n8UMoPPO1hWxePss7YIa0rYP8yeasDZUszU6TkUxPH18wfW6L7Q)

### Other comments
Tried and tested in both Chrome and Firefox, seems to happen both with and without icon in button

![image](https://github.com/user-attachments/assets/54d892a2-ff81-4de3-a23e-2f0d148fe244)

**Comment by J-Sek** [comment]
Works with `content-class` instead of `class` ([example](https://play.vuetifyjs.com/#eNpVUsFuwjAM/RWvFzZpHUy7TQVpt9134LDuENJAIzlxlDiICfHvcwIMKlVV/N7rs/Pc72OTop5/hPCyz6Z5bzo2LqBis+o9QLdvVQj1WAtNnpX1Jl6gCm7Yg0aV0rJvHLavfQNsGY2Uo0Ekqa18WNjBttZvKTrFlnxLmVHc+ubfrhoW9aqbXw4TiomQbbhhAEqz3SumKA2CisZz39zzbA4s1Bc5A9EoxF8YlPOA5HeVBB4VQxop4wBqkwgzG1FtDHDMXksYgxRa5STIaBPIE+1gdUbKSZTFatrUqcPaDjxK47fFYsqVEGXK9ppZmaG9drqX1gwuN74FLpgkft2JVNOlFOS8s25+t0spk442yEUN57OddYEiw1Fi2cIJtpEczOQ3mBV5nTMxuLSDZVE8zj7LNmFNEYeH2VNpcLYUs+b07DNiff38AUgNwfg=))

**Comment by phibzy** [comment]
So it does, thanks for that!
