### ISSUE TITLE
[Feature Request] VNumberInput allow Parsing and Fallback for min and max Values in VNumberInput

### ISSUE THREAD

**Issue by 3dyuval** [vuetifyjs/vuetify#20788]
### Problem to solve
The current VNumberInput does not automatically handle non-numeric min and max values, nor does it provide fallback mechanisms for values exceeding JavaScript's safe integer ranges, resulting in possible input errors or unexpected behavior.

### Proposed solution
Implement a parsing mechanism to interpret min and max, and automatically resort to Number.MIN_SAFE_INTEGER or Number.MAX_SAFE_INTEGER when inputs are invalid or exceed safe numeric limits, ensuring robust and predictable component behavior.

[Playground](https://play.vuetifyjs.com/#eNqlVE1vGjEQ/SvTvaRVY7YQyIGQSqiiFYdwSKOqUqkis8xSS7v2yvYSEOK/d9bmY3cFJIQLwm88j/c8j/mzCoyOwn6WNeY5Bt2gZyItMgsGbZ5BwuXsfhxYMw6+jiWASDOlLaxAYwxriLVK4Yoar+7GsqiHITxijBplhAZipcGisULOYM61ULmBicrllOslREpOhRVKmqKRTsbSpSTHJtwX9B9bXz7dFYRPxOCoUr6AF2H/CQmadGGtr7XpG+XpBHXjof/7+Wf/++B5OHoa/Bg8wmdo1ghxESFOC3UFtSOpcd6czZnLjGuDfJJgmbXG2956rFskbycsdmpyhqOqHHbKInEesnh7NmfF4p51M/9vBTWX1o9/N253qTRqavxVQPTrHQrPDuaLLdws8F7o80jpo4PFNEu4RZfF3pzxLHNf3YEILBcS9QYi8ANjXnbEDXbhYTuPyhsDY/uOOZPuHZiQWW63MKlLuDH0TyB9zDczP6Bgf6dLRX/FWSiX5ixVU0yo6iO+r4XO2Wt6/RgNGB4jCGlxhvps3Sq3TMVed0nBTvjxkLdOeCnV3uaFNgtYBeNgKGMhhV2Og4usVMR5J3vmo7Jv3ih7m+8LIkNZOR4ZIf2V1yLTPlfvBBP1ckFgSO6JwDjZx1fGqcB0znWyCwx7b2JqXqqJcVZK1EeF31aFu58O63unQPxa6oWldUVHY5e0ME2kMpy6q436MrneoZWXPwy3NnAtXXv0EEf9IWDlfaRcz6g2UdaqtAutdrZwS3ntNnAhnBQH62uZJ4n7+PsfQz2Tkg==)

**Comment by J-Sek** [comment]
`min` and `max` are already set to `*_SAFE_INTEGER` as default:

```
  min: {
    type: Number,
    default: Number.MIN_SAFE_INTEGER,
  },
  max: {
    type: Number,
    default: Number.MAX_SAFE_INTEGER,
  },
  ```
  
By setting them to `Infinity` and `-Infinity` you would override these defaults and accept numbers outside of range that framework defined as reasonable boundaries for typical use. But that's not the problem here anyways.
  
The problem in the Playground 

![image](https://github.com/user-attachments/assets/542765ad-630a-4f48-a577-597cfdaf4260)

So adding "1" results in the same value. Seems like it is what "_SAFE_" means - once you exceeded safe range, math does not apply.

Workaround `:step='2'`

```html
<v-number-input
  class="max-out-of-range1"
  :max="Number.MAX_SAFE_INTEGER + 2"
  :step="2"
  v-model="value2"
/>

<v-number-input
  class="max-out-of-range2"
  :max="Infinity"
  :step="2"
  v-model="value3"
/>
```
