### ISSUE TITLE
Toolbar partially hiding page content

### ISSUE THREAD

**Issue by akaspick** [vuetifyjs/vuetify#2167]
### Steps to reproduce
On page load, the page content is partially hidden under the toolbar.  From https://codepen.io/anon/pen/RLYoOE, the subheader 'Folders' should be viewable, but it is not.

My original comment on this issue is at https://github.com/vuetifyjs/vuetify/pull/969#issuecomment-336442732

The linked issue provides examples for 'old' and 'new' behavior, but the desired results from the 'new' behavior link don't appear to work in the latest vuetify.

### Versions
Vuetify 0.16.6, Vue 2.4.4

### What is expected ?
The toolbar not to partially hide the initial page content.

### What is actually happening ?
The toolbar is partially hiding the initial page content.

### Reproduction Link
https://codepen.io/anon/pen/RLYoOE

**Comment by jacekkarczmarczyk** [comment]
I've just looked at the codepen - you're missing few things that are required since 0.16
See the corrected codepen: https://codepen.io/anon/pen/boxqwY
I've added `app` prop to the toolbar and `<v-content>` inside the `<main>`
See the release notes for more breaking changes in 0.16: https://github.com/vuetifyjs/vuetify/releases/tag/v0.16.0

**Comment by akaspick** [comment]
@jacekkarczmarczyk Great, thanks. Works perfect now. Apologies for not seeing the upgrade notes.
