### ISSUE TITLE
Button click event is sending the wrong props.index after insert new row in datatable component

### ISSUE THREAD

**Issue by tmmsmoreira** [vuetifyjs/vuetify#2245]
### Steps to reproduce
I have a datatable with some data and each row has a 'view' and a 'delete' button.
I want to be able to add a new row to that table. So, to do that, I created a button that `push` some data to my datatable items array.
After doing that, a new row is added and it is sorted the right way. But when I press the 'view' button of that new row, it shows me the content of previous the row in that same position.

### Versions
0.16.6

### What is expected ?
After pushing new content to datatable items array, the `props.index` that is sent as an argument to the click event button must be the right one.

### What is actually happening ?
The `props.index` is wrong and shows the wrong row data.

### Reproduction Link
https://codepen.io/tmmsmoreira/pen/YrBRBe

**Comment by johnleider** [comment]
The problem is that the index that comes back from the scoped slot does not directly correlate to the index of your locally scoped item array. When the data-table sorts, it doesn't maintain the original array order, and has different indexes for the new sort.

You can observe this behavior by clicking the view button, resorting the table, and clicking the same position. It will display the same item because your local items array has not been mutated in the exact same manner as the table sort.

I'm attaching a different way to handle this, hopefully it can help you.
https://codepen.io/johnjleider/pen/JrzYmE?editors=1111

**Comment by tmmsmoreira** [comment]
Oh.. I understand now. That makes sense!
Thank you so much @johnleider 👍

**Comment by codewp** [comment]
@johnleider 
What should do for items that have many same items? It only returns first matched item!

**Comment by johnleider** [comment]
Would providing an index through the scoped slot (same as data-table) be helpful?

**Comment by codewp** [comment]
@johnleider 

Please look at this code.
```javascript
<template slot="items" slot-scope="props">
              <!-- <tr v-for="(segment, index) in model.segments" :key="index">
                <td class="justify-center">{{ itemName(index, 'dividend') }}</td>
                <td class="justify-center">{{ itemName(index, 'divisor') }}</td>
                <td class="justify-center layout px-0">
                  <v-btn icon class="mx-0" @click="editItem(index)">
                    <v-icon color="teal">edit</v-icon>
                  </v-btn>
                  <v-btn icon class="mx-0" @click="deleteItem(index)">
                    <v-icon color="pink">delete</v-icon>
                  </v-btn>
                </td>
              </tr> -->
              <td class="justify-center">{{ itemName(props.item, 'dividend') }}</td>
              <td class="justify-center">{{ itemName(props.item, 'divisor') }}</td>
              <td class="justify-center layout px-0">
                <v-btn icon class="mx-0" @click="editItem(props.item)">
                  <v-icon color="teal">edit</v-icon>
                </v-btn>
                <v-btn icon class="mx-0" @click="deleteItem(props.item)">
                  <v-icon color="pink">delete</v-icon>
                </v-btn>
              </td>
</template>
```
In the commented codes I provided `index` for each element to find it from original array but when I used this code, when I added second item to `items` data table showed `4 items` instead of `2 items` so I decided to use documentation codes instead of commented code but this way it is not possible to find `item` inside `items` array because maybe there are two same item inside `items`, so we need to provide a unique value for each item to find it like `index` of `item`.

It's possible to add `index` to each item like this `{ 'itemData': itemData, 'index': index }` but this way we should regularly update items index when an element removed or added, and remove this index when we send it to the server because `index` is not right data.

Please let me know your idea to this issue!

Thanks.

**Comment by KaelWD** [comment]
I think the scoped slot already has index available, but it's the displayed index so it's pretty much useless.

**Comment by husayt** [comment]
Yes, indeed seems like current index is both useless and misleading. Would be great to 
a) rename current index to displayIndex
b) add a new index to scope
c) also clearly specify in docs what is each index is for.
