### ISSUE TITLE
SSR: navigation drawer blinks on route changes

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#2266]
It's a quite sparse case then we use custom page component with default slot instead of nuxt built in layout:

```vue
<template>
  <my-page>
    ...
  </my-page>
</template>

<script>
import MyPage from '~/components/MyPage'

export default {
  components: { MyPage }
}
</script>
```
### Steps to reproduce
1. Clone the git@github.com:Darkside73/vuetify-navigation-drawer.git
2. ```yarn && yarn run dev```
3. Navigate to pages via drawer

### Versions
0.16.8

### What is expected ?
Navigation drawer shouldn't appears twice

### What is actually happening ?
![peek 2017-10-20 14-31](https://user-images.githubusercontent.com/339596/31819036-6f16cb3a-b5a3-11e7-82ba-d51d9ef6b273.gif)

### Reproduction Link
git@github.com:Darkside73/vuetify-navigation-drawer.git

**Comment by Darkside73** [comment]
Same issue with initially visible drawer

**Comment by johnleider** [comment]
@KaelWD I'm assigning this to you only because you recently made `v-navigation-drawer` updates. I can take otherwise.

**Comment by KaelWD** [comment]
I'll spin up a simple nuxt project this time I think, I was just using the docs for SSR testing before.

**Comment by KaelWD** [comment]
So this has nothing to do with my recent changes, it's because you're creating an entirely new v-app on each page and setting the nav drawer value from the store. This is not a currently supported setup and you will find that there's more than just the opening animation that doesn't work as expected. You should use nuxt's build-in layout functionality, or come up with some other way of doing this that only involves a single v-app.

**Comment by Darkside73** [comment]
@KaelWD thanks for digging. ```v-navigation-drawer``` should be within nuxt layout as well
