### ISSUE TITLE
I have an existing Vuetify project. But, the customer says he does not want material look. How can I remove Vuetify ?

### ISSUE THREAD

**Issue by Kreaft** [vuetifyjs/vuetify#2290]

**Comment by Kreaft** [comment]
lol @johnleider closed this. You have done a great job and have been using Vuetify since the first day, by default. This time, the customer requested, and unfortunately I had to ask.

Thank you for Vuetify. Made my life easier.

**Comment by johnleider** [comment]
I closed not because of what you asked, but because you asked. The issue board is not for questions, https://chat.vuetifyjs.com is. Normally I have some boilerplate messaging that I post, but I accidentally forgot.
##
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please re-open a new issue with the required information, thank you.

**Comment by Kreaft** [comment]
Pardon.
