### ISSUE TITLE
Very long compiling times with Stylus

### ISSUE THREAD

**Issue by mkhennoussi** [vuetifyjs/vuetify#2294]
### Steps to reproduce
Create a project with vue init. The issue is the same with all the templates webpack, pwa...
### Versions

"vue": "^2.3.3",
    "vue-router": "^2.3.1",
    "vuetify": "^0.16.4"
"stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
### What is expected ?

Quick compiling times when modifying files (.vue, .js or .styl)
### What is actually happening ?

Takes almost 15s to hot reload the page.
### Reproduction Link
Just create a new project with vue-cli and vuetifyjs templates

**Comment by maurop123** [comment]
I just tested the templates and can confirm that there was an issue with the compile time taking too long for any simple edit, like changing some display text. I just fixed this by changing how we import stylus, since that's what was causing the unnecessarily long load times.

@mkhennoussi feel free to try this out again with a new project and share your results.

**Comment by qm3ster** [comment]
@maurop123 can you please link to where you "changed how we import stylus"?

**Comment by maurop123** [comment]
Sure, here's the change in the PWA template: https://github.com/vuetifyjs/pwa/commit/291e255c7d57b2710c1aa8d00d998152e2f75a6a

Specifically, by importing stylus in `main.js` instead of `App.vue`, webpack won't do a full recompile on every little change.

**Comment by mkhennoussi** [comment]
@maurop123 Yes, thank you ! It is better now as webpack won't recompile on each change ! Thank you very much
