### ISSUE TITLE
[Bug] [v-text-field] interpretes negative numbers as NaN 

### ISSUE THREAD

**Issue by myleslee** [vuetifyjs/vuetify#2359]
### Versions and Environment

Vuetify: `v0.17.0-beta1`
Vue: `v2.5.2`
Browsers: `Chrome,Firefox,Safari`
OS: `macOS`

### Expected Behavior
<v-text-field> should allow the entry of negative numbers.

### Actual Behavior

But with v0.17.0-beta.1, as soon as you enter a `minus`, the input will be replaced with a literal string of `NaN`.

### Reproduction Link

https://codepen.io/myleslee/pen/xPxBQY

### Other comments

The issue cannot be reproduced on `v0.16.9` though.

**Comment by KaelWD** [comment]
@azaars fix yo shit

**Comment by azaars** [comment]
Entering '-' as the first character won't cause NaN because it's still a valid number. Entering '-' elsewhere is indeed invalid if the expectation is a number.

I think the real issue here is that users are free to key-in invalid characters into the (number) input field. Because the field is not `mask`ed or formatted in any way, entering garbage should be allowable. https://github.com/azaars/vuetify/commit/c50f47ffd0ab62491524741f7a61d932dc56867b fixes this real issue.
