### ISSUE TITLE
[Bug] Not possible to attach a badge onto a snackbar

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#2392]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.5.2
Browsers: Firefox,Chrome
OS: Mac OSX

### Expected Behavior
That a badge would be on top right corner of the snackbar. Especially when a snackbar uses v-model to be shown and hidden, badge should appear or disappear with it. I expect that to work because in documentation it is written: "The v-badge component can wrap any type of content"

### Actual Behavior
Badge is or not shown or shown somewhere else.

### Reproduction Link
[https://codepen.io/anon/pen/JOdwpv](https://codepen.io/anon/pen/JOdwpv)

**Comment by johnleider** [comment]
This is not possible because of how `v-snackbar` works. It detaches its content and moves it to the base of the application. This causes the badge to appear like it's not in the right spot because it is actually on the snackbar's root element.

At this time, this is not something that we plan to support. Thank you for your report.
