### ISSUE TITLE
[Bug Report] Opening a menu is not aligned as expected

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#2416]
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.5.3
Browsers: Mozilla Firefox
OS: Mac OSX

### Steps to reproduce
Clicking on the avatar in the toolbar open a menu.

### Expected Behavior
Menu should be right aligned to the right edge of the toolbar button.

### Actual Behavior
Menu is not aligned like that.

### Reproduction Link
[https://codepen.io/anon/pen/GOJBzX](https://codepen.io/anon/pen/GOJBzX)

### Other comments
This is a followup to https://github.com/vuetifyjs/vuetify/issues/2383, where I tried to get it to be aligned for the long menu entry, but then I realized that the issue is with a short entry. In short, I am trying to get this to work for different sizes of menu entries, and it seems no combination of props make it work. It seems that by documentation, the issue is in fact with the short version which I am reporting here.

**Comment by KaelWD** [comment]
I'll add that triple-clicking opens it centered for some reason.

**Comment by johnleider** [comment]
It was working when you clicked fast because the measurements taking from **menuable** use getBoundingClientRect. The content when first rendered is only 71px, but due to a later **calculatedMinWidth** in `v-menu` was setting the minimum width to be 110px. When you clicked fast, it still had the 110px width from the DOM declared min-width.
