### ISSUE TITLE
[Feature Request] Grayed-out disabled floating action buttons

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#2426]
### New Functionality
It seems that currently when you disable a floating action button, the button disappears. I would prefer that it gets grayed-out and inactive. The reason is that I want to disable it just after the click while server is processing the call, to prevent double click. But hiding might confuse users.

### Improvements
Currently there is no simple way to disable a button without hiding through existing API.

### Bugs or Edge Cases it Helps Avoid
It avoids confusing users what is happening.

**Comment by johnleider** [comment]
This sounds like you are adding the **dark** prop to a `v-btn` with the **fab** prop in order to achieve white text within the button. This may still also be lingering in the documentation. It is **NOT** the correct way to implement a `v-btn` as a **dark** variant is expected to be on a contrasting background. It seems like it is disappearing, but it is really just changing its background color to display properly on a darker background.

Use **class="white--text"** instead. If my assumption is wrong, please provide a minimal reproduction of what this request would fix.

**Comment by mitar** [comment]
No,  am setting `disabled` property on the fab button.

**Comment by johnleider** [comment]
Then I need to see a reproduction of the issue you are wanting to fix.

**Comment by mitar** [comment]
Here: https://codepen.io/anon/pen/KymRoN

**Comment by johnleider** [comment]
As I stated above, you are adding the **dark** prop. Stop it..It's not on a dark background.

https://codepen.io/johnjleider/pen/LOymdg

**Comment by mitar** [comment]
Ohhhh. How I missed that. Sorry for the noise.

**Comment by mitar** [comment]
And thank you for the patience.

**Comment by mitar** [comment]
I figured out why I used `dark`, because in 0.16.9 if you use a primary color, it leaves the icon black. In latest version (in codepens above) behavior is correct and you get a white color of the icon.

See here: https://codepen.io/anon/pen/KymRoN

**Comment by mitar** [comment]
Semi-followup: https://github.com/vuetifyjs/vuetify/issues/2488
