### ISSUE TITLE
[Bug Report] Incorrect right margin size for right most toolbar action button

### ISSUE THREAD

**Issue by joshas** [vuetifyjs/vuetify#2448]
### Versions and Environment
**Vuetify:** 0.16.9
**Vue:** 2.5.3
**Browsers:** Firefox 56.0
**OS:** Windows 7

### Steps to reproduce
Setup toolbar with sample code from example # 2. Switch to mobile viewport size.

### Expected Behavior
Margin between "more" action menu item and right screen edge is 16px measuring from icon, as defined in Material Design specification.
![image](https://user-images.githubusercontent.com/79141/32571701-0c5a09d4-c4d1-11e7-8237-45173bafe054.png)

### Actual Behavior
Action button "more" has 17px right margin and additional padding from button width.
![image](https://user-images.githubusercontent.com/79141/32571733-27cc64dc-c4d1-11e7-82f4-f40d2fc87ee2.png)

### Reproduction Link
[https://codepen.io/anon/pen/WXoPjY](https://codepen.io/anon/pen/WXoPjY)

**Comment by johnleider** [comment]
The icons are sized that way because they are actionable buttons. In order to best support the spec, what we do is ensure that amount of spacing from the hover effect of the corresponding icon.

I went ahead and looked at a bunch of other Material Frameworks from Vue, React, and Angular. None of their implementations match this particular portion of the spec, and in fact, most are not even close.

This will have to be a caveat to the rule unfortunately.
