### ISSUE TITLE
[Bug Report] Logic to set 'exact' prop for home routerlink does not work

### ISSUE THREAD

**Issue by atorkhov** [vuetifyjs/vuetify#2485]
### Versions and Environment
**Vuetify:** 0.17.0-beta.3
**Vue:** 2.5.3
**Browsers:** Firefox 56.0
**OS:** Linux

### Steps to reproduce
Vuetify has logic to set router link `exact` prop to true when `to` points to `/`:
https://github.com/vuetifyjs/vuetify/blob/b2b1a4a96bf87d938c415ffbc8197131e67b276f/src/mixins/routable.js#L44
But it does not work.
Just create some link with `to` set to `/` and go to different page.

### Expected Behavior
Router link to home deactivates.

### Actual Behavior
Router link to home stills active.

### Reproduction Link
[https://codepen.io/anon/pen/jamygP](https://codepen.io/anon/pen/jamygP)

**Comment by jacekkarczmarczyk** [comment]
Link to home doesn't deactivate, because by default `exact` is false. If you don't want it to be active add `exact` prop
I'm not closing this issue only because probably the mentioned line should be removed at all, it's executed only if `exact === undefined` which happens only when you explicitely provided `undefined` as a `exact` value. It looks like a workaround for something, introduced in e5dc4f4e5eea86a788dbc036b4f5cdc17b171c63, but have no idea what it was supposed to do. @nekosaur ?

**Comment by atorkhov** [comment]
Then, probably, it should be returned to previous logic:
https://github.com/vuetifyjs/vuetify/blob/c168def381d6a904ec5531b182fffb8de7f44678/src/mixins/route-link.js#L32

or even this:
https://github.com/vuetifyjs/vuetify/blob/36fa5c7006616aadc4e3f11d2637bd27af62c059/src/mixins/route-link.js#L7

**Comment by johnleider** [comment]
I believe that Vue changed how it handles Boolean declared props with no definition. At one point it left them as undefined, as you can see per the code. However, it appears they now typecast it. Is there a scenario where a developer would **NOT** want exact to be true on '/'? If so, we cannot do this.
