### ISSUE TITLE
[Bug Report] v-toolbar-side-icon When on the right, wrapped in a menu has incorrect margin

### ISSUE THREAD

**Issue by garfonzo** [vuetifyjs/vuetify#2489]
### Versions and Environment
**Vuetify:** 0.16.9
**Vue:** 2.5.3
**Browsers:** Chrome 61.0.3163.100
**OS:** Mac OS 10.13.1

### Steps to reproduce
The v-toolbar-side-icon needs to be pushed to the right edge of the toolbar. 

### Expected Behavior
The spacing against the right edge should be the same as when the toolbar-side-icon is on the left side

### Actual Behavior
The menu icon is right against the right edge of the toolbar

### Reproduction Link
[https://codepen.io/anon/pen/wPdYqd?editors=1010#0](https://codepen.io/anon/pen/wPdYqd?editors=1010#0)

### Other comments
Note that the CSS is specifically overridden to make the margin=0. See code: https://github.com/vuetifyjs/vuetify/blob/24dcd8180224c202ffdac221a221fb69dc4b0b15/src/stylus/components/_menus.styl#L24

**Comment by slippyC** [comment]
This is a problem with a multitude of things.  Basically, from what I can tell, it checks to see what type of component you are putting on the right side.  If you were to have a dialog attached to a button on the right side you will get the same effect, the v-button is wrapped inside that dialog.  If you have a tooltip set on a button, which makes it become wrapped again, same effect.

There is an easy way around the dialog issue, just use the button not wrapped and then on @click event you can toggle your value that's tied to the dialog(basically it toggles it's visibility).  On the tooltip situation, I'm going to have to find work around or have to fork and redo the styles myself.  I would prefer not to do this, since I would like to pull the most current version of vuetify.

But yes, there is a 16px right margin put on pretty much everything but buttons of some type.

**Comment by KaelWD** [comment]
All the keylines are incorrect anyway, the desktop and mobile dimensions are the wrong way around.
