### ISSUE TITLE
[Bug Report] It is possible to tab outside a modal dialog (using the tab key)

### ISSUE THREAD

**Issue by nborko** [vuetifyjs/vuetify#2538]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.4
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 10

### Steps to reproduce
In the Codepen, open a modal dialog. Press the tab key past the last control in the dialog until the activator button is active, and press enter. The dialog will be closed.

### Expected Behavior
Nothing should be accessible via keyboard outside a modal dialog.

### Actual Behavior
You can activate any control under a modal dialog by tabbing to it, including the modal activator itself thereby closing the modal.

### Reproduction Link
[https://codepen.io/nborko/pen/EbbKYZ](https://codepen.io/nborko/pen/EbbKYZ)

### Other comments
This is mentioned in issue #2261, but the fix only addresses initial focus and not the fact that non-modal content is accessible via the tab key.

**Comment by KaelWD** [comment]
I don't think this is possible to do without setting `tabindex="-1"` on every focusable element on the page.

**Comment by jingzheshan** [comment]
When you blur the last element on the dialog, target it back to the first one in the dialog.

**Comment by stratosgear** [comment]
The last element on the dialog is more likely a button so utilizing a blur event to set the focus on the first, let's say input field, works fine.  So  tabbing through rotates all elements in the dialog.

But trying to catch SHIFT-TAB is tricky, because of the ambiguity of blurring the first input field (is the user moving to next element or previous?), that does not allow you to easily shift focus on the last dialog element (your button more likely)

**Comment by dmcknight26** [comment]
Stumbling across this issue now myself, and from an accessibility standpoint this is really needed (along with #2261).

Bootstrap seems to be handling this is an elegant way, even accounting for the SHIFT+TAB scenario -- perhaps it can be reverse engineered?  

https://getbootstrap.com/docs/4.0/components/modal/#live-demo

**Comment by KaelWD** [comment]
https://github.com/twbs/bootstrap/blob/a79b8aa16ab5fa5c71a91425d8464f0bdcd3fe37/js/src/modal.js#L275-L285

**Comment by stratosgear** [comment]
Tiny, picky note:
Still the bootstrap example does not properly catch the SHIFT-TAB cycling.  TABing infinitely cycles through all elements, but SHIFT-TABing is not.

**Comment by firepick1** [comment]
Like dmcknight26 I'm using Vue for an accessible download alert. I ended up using <v-dialog> with an onblur() that re-established the focus within the v-dialog with $nextTick(...). Since the only tabbable control in the v-dialog is the close <v-btn>, this solution is workable, but overall we need better support for accessibility. As it is, I'm having to avoid most of the cool Vue stuff (e.g., dropdowns and menus) simply because they are not accessible. I also understand that accessibility is hard and takes time to do right.

**Comment by joshmenden** [comment]
We are also seeing this issue. It's a detriment to our user experience.
