### ISSUE TITLE
[Bug] ripple directive sets/unsets position

### ISSUE THREAD

**Issue by DedDorito** [vuetifyjs/vuetify#2573]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.6
**Browsers:** Firefox 57.0
**OS:** Windows, Linux

### Steps to reproduce
1. Add ripple directive to v-card
2. Inspect element on the `v-card` element
3. Click on and off the card

### Expected Behavior
The `position` style attribute to remain unchanged.

### Actual Behavior
The `position` style attribute is set to `relative` and then unset.

### Reproduction Link
[https://codepen.io/anon/pen/Ebozdm](https://codepen.io/anon/pen/Ebozdm)

### Other comments
I probably don't understand the full scope or context of why it is doing this (perhaps this is necessary for some other functionality or application of the directive).  This breaks certain things like using masonry.js for instance, as the position of the cards must remain `absolute`.  Blocking this functionality doesn't appear to have any negative effects on the ripple directive working on the `v-card` element.

**Comment by nkovacs** [comment]
It's because of https://github.com/vuetifyjs/vuetify/issues/1014.
My guess is that the element that has a ripple directive has to be positioned so that it becomes the offsetParent of the ripple. The check is wrong though, it should be `computed.position === 'static'` (since anything other than static makes an element positioned).

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

**Comment by nkovacs** [comment]
This isn't a feature request, it's a bug. The condition has since been changed to `(computed.position !== 'absolute' && computed.position !== 'fixed')` (https://github.com/vuetifyjs/vuetify/blob/dev/src/directives/ripple.ts#L66) to fix this bug for fixed elements, but like I said, it should be `computed.position === 'static'` (the current code still breaks position:sticky, for example).
