### ISSUE TITLE
[Bug Report] Icon documentation insufficient/Icons not appearing

### ISSUE THREAD

**Issue by Craz1k0ek** [vuetifyjs/vuetify#2599]
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.8
**Browsers:** Safari 11.0
**OS:** Mac OS 10.12.6

### Steps to reproduce
Try to create a v-icon with mdi or fa. Icons will not appear. (Not locally or in codepen)

### Expected Behavior
I'd like to see a codepen link where the icons are showing, or updated documentation.

### Actual Behavior
Icons do not appear.

### Reproduction Link
[https://codepen.io/anon/pen/LOddqJ, https://codepen.io/pen/?&editors=100](https://codepen.io/anon/pen/LOddqJ, https://codepen.io/pen/?&editors=100)

**Comment by pdcamilleri** [comment]
The documentation could be improved in this area. Usually the trick is to use underscores instead of dashes when referencing the icons, e.g.

`<v-icon>mdi_watch</v-icon>`

**Comment by KaelWD** [comment]
> Please note that you still need to include the MDI icons in your project.

The way the codepens are generated means that it is not currently possible for us to include other libraries, but if you set up your project correctly then it should work fine.

**Comment by Craz1k0ek** [comment]
Material icons are clearly imported in codepen (take a look at the css links); you can tell it is working by adding `<i class="material-icons">wb_cloudy</i>` In codepen the icon now appears. The underscore does work for some icons, yet the existing ones remain the same.

**Comment by jacekkarczmarczyk** [comment]
MDI is Material Design Icons, it's not same as Material Icons. And there is `xbox_controller` icon:
![image](https://user-images.githubusercontent.com/15625235/33123335-8155b810-cfac-11e7-847c-9143eb8cca85.png)

**Comment by KaelWD** [comment]
The default icon set is google's own [Material Icons](https://material.io/icons/), it uses font ligatures and does not require a prefix. 

[Material Design Icons (MDI)](https://materialdesignicons.com/) are a third-party icon font that uses classes instead of ligatures. They should be prefixed with `mdi-` in vuetify. 

`v-icon` looks for that prefix to determine if it should use a css class-based or ligature-based font. Using the wrong prefix will try to render the default ligature font, resulting in unwanted whitespace if you have extra characters such as `mdi_`. 

To use anything other than google's icons in codepen, you have to link it yourself.

**Comment by neoricalex** [comment]
For clarity [here](https://cdn.materialdesignicons.com/1.1.34/) is the list of icons using mdi-*
