### ISSUE TITLE
[Bug Report] Snackbar is absolute positioned inside a Dialog if you close the Dialog

### ISSUE THREAD

**Issue by sqram** [vuetifyjs/vuetify#2766]
### Versions and Environment
**Vuetify:** 0.17.4
**Vue:** 2.5.9
**Browsers:** Chrome 63.0.3239.84
**OS:** Linux x86_64

### Steps to reproduce
1. Click "Open Dialog" button in reproduction link.
2. Click "Agree" inside the opened Dialog

### Expected Behavior
Snackbar to be shown at the top of the body, not parent container (Dialog)

### Actual Behavior
Snackbar is being absolute positioned inside the parent container, v-dialog

### Reproduction Link
[https://codepen.io/sqram/pen/zpOYNX?editors=1010](https://codepen.io/sqram/pen/zpOYNX?editors=1010)

### Other comments
If one does not close the Dialog, the Snackbar is shown in the expected place.
Ie, commenting out line #14 in the reproduction link (`this.dialog = false`), will cause the Snackbar to show up in the expected place. (top of body)

**Comment by johnleider** [comment]
This is because you are putting the `v-snackbar` into the `v-dialog`. When dialog closes, it is using a translate, which is creating a new rendering layer, which is capturing the position of `v-snackbar` (it's actually a hack used sometimes). You can verify this by removing the transition from `v-dialog`.

https://codepen.io/anon/pen/BJBejg?editors=1010
