### ISSUE TITLE
[Bug Report] VSelect input not focusable after pressing backspace or arrow left

### ISSUE THREAD

**Issue by samschl** [vuetifyjs/vuetify#2834]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.3
**Vue:** 2.5.11
**Browsers:** Safari 11.0.1
**OS:** Mac OS 10.13.1

### Steps to reproduce
* Select a few items
* Press backspace or arrow left
* Try to type something or click into the input field

### Expected Behavior
The input field should be focused again, when clicking on it (and preferable when start typing again)

### Actual Behavior
Focusing the input field again, can only be achieved by pressing arrow right or clicking outside of the input and then the input again.

### Reproduction Link
[https://codepen.io/anon/pen/zpqzZq](https://codepen.io/anon/pen/zpqzZq)

**Comment by KaelWD** [comment]
Codepen is empty

**Comment by samschl** [comment]
I updated the link

**Comment by jacekkarczmarczyk** [comment]
And if you select the chip with mouse then you can focus the input but arrow keys don't work

**Comment by KaelWD** [comment]
There seems to be a disconnect between keyboard and mouse interaction. Clicking the chip instead of using the arrow keys works fine, and you can highlight two chips by scrolling to one and clicking the other
![image](https://user-images.githubusercontent.com/16421948/34163118-f93d8f64-e529-11e7-8ded-b45d8521ecd6.png)

**Comment by samschl** [comment]
Hi,

I am currently trying to fix this issue, but I can't find the click listener on the selected chips. Maybe someone can point me in the right direction?
