### ISSUE TITLE
[Bug Report] Vuetify.js flex elements doesn't work as expected

### ISSUE THREAD

**Issue by AlexAlabyev** [vuetifyjs/vuetify#2884]
### Versions and Environment
**Vuetify:** 0.17.16
**Vue**: 2.5.2
**Browsers**: Chrome 63.0.3239.108
**OS**: Win10 x64

### Steps to reproduce
```
 <v-container>
    <v-layout row justify-space-between>
        <v-flex>
            <div class="pa-3">
                <h3>Element 1</h3> 
            </div>
        </v-flex>

        <v-flex>
            <div class="pa-3">
                <h3>Element 2</h3> 
            </div>
        </v-flex>                       
    </v-layout>
</v-container>

<v-divider></v-divider>

<v-container style="display:flex; justify-content:space-between;">
    <div class="pa-3">
        <h3>Element 1</h3> 
    </div>

    <div class="pa-3">
        <h3>Element 2</h3> 
    </div>
</v-container>

```
### Expected Behavior
To behave as the CSS flex box (the bottom one):

![Image](https://i.stack.imgur.com/pjH9R.png)

### Actual Behavior
The elements are not on the opposite sides of the parent element

### Reproduction Link:
[https://codepen.io/anon/pen/baqxov](https://codepen.io/anon/pen/baqxov)

**Comment by scottmontminy** [comment]
The `.flex` class defaults to `flex: 1 1 auto` ([source](https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/components/_grid.styl#L83)), so the first example is the behavior you should be getting from the `<v-flex>` component. Note that the first value `1` is for `flex-grow` and this should make the child elements consume all the horizontal space.

I think the distinction here would be that the `<v-flex>` component is designed for working the Vuetify grid system. In your case, I see you're trying to use flexbox, but not necessarily a grid system, so I suggest that you simply remove the <v-flex> elements to get the expected behavior you're seeking:

https://codepen.io/anon/pen/GyWzEX

The <v-layout> component is set to display as a flex element, so you don't need to set the child elements as flex elements unless you want to apply grid widths grid attributes like `xs6`.

**Comment by AlexAlabyev** [comment]
@scottmontminy thank you for explaining and the example!
