### ISSUE TITLE
[Bug Report] hidden-xs-only and hidden-sm-and-up are ignored on printing

### ISSUE THREAD

**Issue by husayt** [vuetifyjs/vuetify#2908]
### Versions and Environment
**Vuetify:** 1.0.0-alpha.3
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.24
**OS:** Windows 10

### Steps to reproduce
```
<h5 class="hidden-xs-only">
   <nuxt-link :to="`/q/${item.url}`"  v-html="item.content"/>
 </h5>
 <h6 class="hidden-sm-and-up">
     <nuxt-link :to="`/q/${item.url}`"     v-html="item.content"/>
  </h6>
```

### Expected Behavior
when printing only one of them needs to be displayed

### Actual Behavior
both printed

### Reproduction Link
[https://codepen.io/](https://codepen.io/)
https://www.sozler.im/#/authors/sedi-sirazi

**Comment by Leespiker** [comment]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps To Reproduce
1. Open reproduction link.
2. Resize preview panel to 599px.

```
<div class="hidden-xs-only">
    hidden-xs-only
</div>
<div class="hidden-sm-and-up">
    hidden-sm-and-up
</div>
```

### Expected Behavior
Only hidden-xs-only should be displayed.

### Actual Behavior
Both hidden-xs-only and hidden-sm-and-up are displayed.

### Reproduction Link
https://jsfiddle.net/9L3v7jqr/

### Notes
It happens on one of my monitors, but not the other. I tried to find differences between the two and ended up using this site: https://bjango.com/articles/min-device-pixel-ratio/

#### The monitor that only displays hidden xs-only:
![working](https://user-images.githubusercontent.com/1329447/52184783-a49bdb00-27cc-11e9-82a5-33afd9796a33.png)

#### The monitor that displays both hidden-xs-only and hidden-sm-and-up:
![broken](https://user-images.githubusercontent.com/1329447/52184791-cac17b00-27cc-11e9-866b-6d14c012b579.png)

**Comment by johnleider** [comment]
I can't reproduce this and at this point is probably not relevant.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
