### ISSUE TITLE
[Feature Request] Evaluate base value of a color directly

### ISSUE THREAD

**Issue by parzh** [vuetifyjs/vuetify#2919]
### New Functionality
This feature will allow developers to get base color value without evaluating `.base` property (preserving it though).

```js
import colors from 'vuetify/es5/util/colors'

const red = colors.red; // '#F44336'
red === colors.red.base; // true
const darkred = colors.red.darken1; // '#E53935'
```

### Improvements
Turn a color into String-derived class `class Color extends String {}`

### Bugs or Edge Cases it Helps Avoid
That feature provides encapsulation

**Comment by parzh** [comment]
I am not very familiar to pull requests, so I'll leave the code here for now:

```js
class VuetifyColor extends String {
  constructor(base, shades = {}) {
    super(base)

    return Object.freeze(Object.assign(this, shades, { base }))
  }
}

const red = new VuetifyColor('#F44336', {
  lighten5: '#FFEBEE',
  lighten4: '#FFCDD2',
  // other shades...
  accent4: '#D50000'
})

// other colors...

export default Object.freeze({
  // all defined colors
})
```

**Comment by KaelWD** [comment]
I already tried something similar, and it isn't very practical. `extends String` is *not* the same as an actual string, it's just like any other object, and the same thing happens if you try to add properties to a string literal. This change would mean having to cast all colors to strings before being able to use them.

Also:
> `red === colors.red.base; // true`

is not true, `red` is an object and `red.base` is a string.
