### ISSUE TITLE
[Bug Report] Input doesn't update correctly

### ISSUE THREAD

**Issue by auringon** [vuetifyjs/vuetify#2931]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.84
**OS:** Windows 8.1

### Steps to reproduce
Open the reproduction link
Type letters in the input
Type numbers in the input

### Expected Behavior
Do not allow letters

### Actual Behavior
Text field value only changes after typing numbers

### Reproduction Link
[https://codepen.io/auringon/pen/wpqVYo](https://codepen.io/auringon/pen/wpqVYo)

### Other comments
This used to work in Vuetify v0.15.5
https://codepen.io/richcorbs/pen/zExNGe

**Comment by KaelWD** [comment]
This is caused by a couple of `nextTick()` calls that were added in #2099, I'm not sure why they're there. You can put the assignment to `newUser.phone` inside a nextTick to fix this until we figure out if it's actually needed here. 

https://github.com/vuetifyjs/vuetify/pull/2099#discussion_r159641467

**Comment by johnleider** [comment]
I'm going to declassify this as a bug. When mutating a value that is bound by a model, you should _always_ wait until the next tick to manipulate that data.
