### ISSUE TITLE
[Feature Request] Change v-tooltip from component to directive

### ISSUE THREAD

**Issue by devistar** [vuetifyjs/vuetify#2961]
### New Functionality
We would be able to add a tooltip on every elements (html or vuetify) easily.
Just like this :
```html
<div v-tooltip.top="This is a tooltip on top"></div>
<v-icon v-tooltip.right="This is a left tooltip for a person icon">person</v-icon>
```

### Improvements
It should work everywhere. Currently there is some components like navigation drawer where tooltip do not work.

### Bugs or Edge Cases it Helps Avoid
...

**Comment by jacekkarczmarczyk** [comment]
Tooltips were directives in the older versions of Vuetify, now it's a component and it allowes having html or other components displayed in the tooltip, see the docs https://vuetifyjs.com/components/tooltips
If you think it doesn't work somewhere then create a bug report and provide reproduction link

**Comment by garyo** [comment]
The current tooltips work, but are super complicated to use (I'm not sure what the "on" variable is or why it needs to be referenced within my component, for instance). A simple directive-based alternative like in this ticket would be so much simpler for common cases. Why not allow both?
Right now I'm using an external v-tooltip lib because of ease of use.

**Comment by PetrPy** [comment]
Guys, current tooltips make no sense from the design logic perspective. Even though a tooltip is just a small helper related to a component, you now have to wrap the component in a tooltip as if tooltip was the important, parent element, and not the other way round.

What we do? We **add a tooltip** to an existing component. It should be as easy as adding a directive tooltip='ABC'. Yes, let us have a separate component for cases that are more complicated, but 99% of time we need a simple solution, not the currently implemented hell of tags.

I think that these are the exact decisions that, when coupled together, can sink an otherwise decent project. Please reconsider, ease of use is a key.

**Comment by nekosaur** [comment]
We are taking another look at how tooltips work for 2.0

**Comment by builder7777** [comment]
judging by the 2.0 documentation, nothing's changed. tooltips are still bulky useless components
