### ISSUE TITLE
[Bug Report] <v-select>  debounce-search prop is redundant

### ISSUE THREAD

**Issue by ecmel** [vuetifyjs/vuetify#2978]
### Versions and Environment
**Vuetify:** 1.0.0-beta.2
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Use debounce-search prop on `<v-select>`

### Expected Behavior
Debounce should be handled by developer just like vue https://vuejs.org/v2/guide/migration.html#debounce-Param-Attribute-for-v-model-removed

### Actual Behavior
Debounce is tied to veutify

### Reproduction Link
[https://github.com/vuetifyjs/vuetify/issues/1735](https://github.com/vuetifyjs/vuetify/issues/1735)

### Other comments
This is discussed for `<v-textfield>` as well and debounce is not part of `<v-textfield>`

https://github.com/vuetifyjs/vuetify/issues/1735

**Comment by pbastowski** [comment]
Is there an example available of how to easily debounce `v-select` input?

This was a useful feature that certainly belongs in a great framework like Vuetify. Pity it is gone. VueJs may have left it out, because it is a generic tool that can be used to create frameworks like Vuetify, which implement more abstract functionality, such as debounce, to make our life easier.

Congrats on the 1.0 release 👍

**Comment by nekosaur** [comment]
Debounce it just like any other input, using either homegrown solution or libraries like lodash/underscore
