### ISSUE TITLE
Flash of unstyled content on page load

### ISSUE THREAD

**Issue by cschweda** [vuetifyjs/vuetify#3]
I noticed there's a flash of unstyled content (on the latest Chrome Canary, at least) when first loaded.

Is there a workaround for this? Is this a known issue?

**Comment by johnleider** [comment]
This is due to how assets are lazy loaded. I had a method for inlining critical styles so this is avoided (webpack-ssr is configured for pagespeed), but ultimately was not happy with the way it operated and removed it before launch.

A simple work around is to open up src/index.template.html and move the styles that are generated inside of the noscript tag into the head.

**Comment by cschweda** [comment]
Sounds great. Thank you!

Will install the webpack (non-SSR) version later today. Will post if I encounter any issues.

**Comment by johnleider** [comment]
No problem, ty.
