### ISSUE TITLE
[Bug Report] Chips component with `v-select` with `solo`, `rules` and `chips` properties has no error display integration

### ISSUE THREAD

**Issue by KevinNTH** [vuetifyjs/vuetify#3000]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Linux x86_64

### Steps to reproduce
Setup a `v-select` component with `chips`, `solo` and `rules` properties. 

### Expected Behavior
Errors from `rules` property should be displayed somewhere

### Actual Behavior
Errors from `rules` are not integrated to the component.

### Reproduction Link
[https://codepen.io/KevinNTH/pen/eyKprV?editors=1011](https://codepen.io/KevinNTH/pen/eyKprV?editors=1011)

**Comment by johnleider** [comment]
Rules are currently not integrated into the **solo** prop because it is not defined in spec. It's main purpose is to mimic the functionality you might see on google for example. There are currently no plans to change this.

With that being said, there will be more tools available to developers after 1.1 in regards to form components. This should allow you to create this functionality should you want to.
