### ISSUE TITLE
[Bug Report] dialog activator is bigger than the actual button (caused by margin of button)

### ISSUE THREAD

**Issue by BennyAlex** [vuetifyjs/vuetify#3033]
### Versions and Environment
**Vuetify:** 1.0.0-beta.4
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 7

### Steps to reproduce
Click at the side of the button and you can open the dialog
![unbenannt1](https://user-images.githubusercontent.com/17402724/35040714-81b13da0-fb82-11e7-9b4a-fe6d8d0d8ae7.PNG)

### Expected Behavior
Don't open the dialog

### Actual Behavior
Opens the dialog

### Reproduction Link
Look the demo: https://next.vuetifyjs.com/components/dialogs#example-modal

### Other comments
This can be seen in the demo page of vuetify. Please allow reproduction link of vuetifyjs.com when submitting with https://issues.vuetifyjs.com
-> https://next.vuetifyjs.com/components/dialogs#example-modal

**Comment by johnleider** [comment]
This is part of Material Design spec under accessibility: https://material.io/guidelines/components/buttons.html#buttons-usage

**Comment by BennyAlex** [comment]
@johnleider okay, but on PC its a bad behavior, because you see exactly where the mouse is pointing to. And when using the dialog without activator-slot, the touchable area is only as big as the button

**Comment by johnleider** [comment]
Unfortunately at this point, that would be a massive breaking change that would take a very serious concerted effort to ensure was working properly when we are about to release v1.0. Because of that, anything in regards to this functionality would not arrive until 2.0, which I do not plan on skipping our planned minor versions this year to accomplish that.
