### ISSUE TITLE
[Bug Report] v-select does not close itself when blurred with a click outsite the `v-app` element

### ISSUE THREAD

**Issue by AlexandreBonneau** [vuetifyjs/vuetify#3144]
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Firefox 59.0
**OS:** Linux x86_64

### Steps to reproduce
1. Click on the `<v-select>` element
2. Blur it by clicking on the red background (outside the `v-app`)

### Expected Behavior
The `v-select` should close itself

### Actual Behavior
The `v-select` stays open

### Reproduction Link
[https://codepen.io/AnotherLinuxUser/pen/aqzaqy](https://codepen.io/AnotherLinuxUser/pen/aqzaqy)

### Other comments
In some cases, it's not possible to add the `v-app` to the top level element of the page.
Perhaps Vuetify could add a 'click' listener to `body` and check the `event.target` if it's that `v-select`.
If it's not, close it?

**Comment by KaelWD** [comment]
> Perhaps Vuetify could add a 'click' listener to `body`

Nope, that doesn't work on iOS. It might be possible to listen for a blur event on the v-select instead, but that obviously wouldn't work for regular menus, navigation drawers, or non-autocomplete selects.

**Comment by AlexandreBonneau** [comment]
So you're saying there is no way to fix that bug consistently?
Couldn't that be fixed only for `v-select`? No need to interact with `v-menu` isn't?

If I were to implement this myself, what's the attribute attached to `<v-select>` that controls the shown/hidden state?

**Comment by KaelWD** [comment]
> there is no way to fix that bug consistently

There is, adding the click handler to an actual element instead of the `<body>`. We created v-app for that purpose. 

> Couldn't that be fixed only for v-select? No need to interact with v-menu

v-select renders a v-menu internally. It *could* be fixed for autocomplete selects only, which isn't something we're likely to do. 

> controls the shown/hidden state

It's internal data, not a prop - `menuIsActive`

Like I said, you can mostly fix this just by changing where the click handler is applied, here I've also added `class="theme--light"` to fix the menu background color: https://codepen.io/anon/pen/oEXGPO

**Comment by AlexandreBonneau** [comment]
Thanks
