### ISSUE TITLE
[Bug Report] v-menu and v-dialog Scrolling z-index

### ISSUE THREAD

**Issue by RGFanker** [vuetifyjs/vuetify#3202]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.3
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 7

### Steps to reproduce
> Click on icon
> Reduce the browser size vertically until the scroll bars appear
> Scroll and you will see the content behind the popover and dialog

### Expected Behavior
The element on top should have the higher z-index (not be transparent)

### Actual Behavior
The element is transparent when you scroll to a certain point.

### Reproduction Link
[https://codepen.io/kfanker/full/opqMQg/](https://codepen.io/kfanker/full/opqMQg/)

@johnleider

**Comment by johnleider** [comment]
This is also present in current beta.

**Comment by sorinsarca** [comment]
> The element on top should have the higher z-index (not be transparent)

It does have the higher z-index.

> The element is transparent when you scroll to a certain point.

It is not transparent. Well, it looks like it is but another thing is happening here when you are scrolling: 
```js
<v-menu>
  <v-card style="height: 300px">
    <v-card-text> ... contents ... </v-card-text>
  </v-card>
</v-menu>
```
the container is `v-menu` and because `v-card` has a height of 300px it won't show all the contents from `v-card-text`.
So, in order to fix this behaviour you just need to add `overflow-y: auto` to `v-card`, see this pen: https://codepen.io/sorins/full/eVBVro/

I don't think this is related to vuetify, and it is definitely not z-index problem (at least not in your case).

**Comment by KaelWD** [comment]
Not a bug with vuetify, to limit menu height you should use the `max-height` prop: https://codepen.io/kfanker/pen/opqMQg?editors=1010
