### ISSUE TITLE
[Bug Report] The content-props for the v-data-iterator component does not work

### ISSUE THREAD

**Issue by Aps05** [vuetifyjs/vuetify#3239]
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Create a `v-data-iterator` component with the following props:
- `content-tag`
- `content-props`

### Expected Behavior
The value in the `content-props` prop should be added as props to the underlying `content-tag` component.

### Actual Behavior
The props do not get added to the `content-tag` component.

### Reproduction Link
[https://codepen.io/anon/pen/VQpwWp?editors=1010](https://codepen.io/anon/pen/VQpwWp?editors=1010)

### Other comments
In my reproduction link I have the `row` and `wrap` props on a `v-layout` element with `v-flex xs12`  inside the iterator. The props are not applied to the `v-layout` component so the `v-flex` components do not break to a new line.

**Comment by SnekInDisguise** [comment]
As a work around you can just put them as attributes in the v-data-iterator tag

**Comment by nekosaur** [comment]
Not sure how to fix this (or if we should). `content-props` does not work in this case because the `content-tag` is `v-layout`, which does not actually have any props defined but uses attributes put on the component to dynamically set classes.

The solution is to simply put the props directly on the `v-data-iterator` as we pass any props not defined on it as attributes to the `content-tag`. See https://codepen.io/anon/pen/MGyzoa?editors=1010

@vuetifyjs/dev-team ?

**Comment by adjenks** [comment]
How would you workaround applying 'justify-content' to a v-layout content-tag to center the items?

**Comment by nekosaur** [comment]
`content-props` and `content-tag` props have been removed in 2.0. Use `body` slot instead.
