### ISSUE TITLE
[Feature Request] Smooth Slide Navigation Drawer (see quasar)

### ISSUE THREAD

**Issue by jpgilchrist** [vuetifyjs/vuetify#3262]
### New Functionality
On mobile (cordova) I want the navigation drawer to feel more native. See quasar (http://quasar-framework.org/quasar-play/android/index.html#/showcase/layout/play-with-layout) in mobile emulation mode. As you drag your finger from either edge the navigation drawer follows your finger. Whereas, with vuetify, it pops out when the gesture is finished. 

This is borderline necessary in order for me to pursue vuetify as my component framework in a cordova application. 

### Improvements
NavigationDrawer gesture/animation

### Bugs or Edge Cases it Helps Avoid
n/a

**Comment by jpgilchrist** [comment]
Specifically the touch-pan directive: 
https://github.com/quasarframework/quasar/blob/dev/src/directives/touch-pan.js

as used in:
https://github.com/quasarframework/quasar/blob/dev/src/components/layout/QLayoutDrawer.js

**Comment by phoenix741** [comment]
I use the vuetify and i love this framework, but i look to go to quasar or other framework because on the mobile application i develop, the gesture not working as expected.

The drawer is slow and not responsive.

It will be great if the framework implements mobile gesture and if the framework is optmized to be run on mobile device.

**Comment by pudjamansyurin** [comment]
same with me, when I use vuetify on desktop, it run smoothly. but when i accessed it from mobile, there was delay about 1 sec, when i clicked something

**Comment by Tajnymag** [comment]
Having around 2 second delay too after clicking hamburger icon on Oneplus One (Chromium 70)

Neither VueMaterial or Quasar have this issue.

**Comment by JamesDeegan** [comment]
I would just like to add my voice to this discussion. Living in a mobile first world today I would also like to see the mobile side of vuetify kicking it up a notch to feel more native. Actual draggable nav drawers is top of my request list. 

I too considered Quasar just because of touch support and better native mobile experience but i can see the Vuetify devs just have to add a few small things and there will be no question vuetify is better in every of SPA's/PWA's for mobile and desktop. When deciding between React and Vuejs a year and a half ago i could see Vue was gaining traction and chose a framework based not on the now but the future.. Same thing here. Vuetify will become the defacto in my opinion, Quasar is really missing so many components. Vuetify just needs to add native draggable drawers, some kind of recyclable scroller (seems people prefer this built in than having to look for something like vue-scroller and install it seperately) and better touch support and Quasar is toast :) Remember, We living in a mobile first world today. So a bit more focus there please devs. Otherwise absolutely great framework

**Comment by johnleider** [comment]
This did not make the cut for v2.0 release. It is something that we still plan to implement. Thank you for your patience.

**Comment by MIhailsPopovs** [comment]
Hello, i too have this issue. Are there any updates coming soon? Should we expect an update on this when the version reaches 3.x.x ?

**Comment by doubleyhun** [comment]
Is this problem solved?
I'm seriously considering going to quasar

**Comment by MIhailsPopovs** [comment]
@doubleyhun You could use an external package..
