### ISSUE TITLE
[Bug Report] Toolbar looses app prop after switching views

### ISSUE THREAD

**Issue by joshas** [vuetifyjs/vuetify#3274]
### Versions and Environment
**Vuetify:** 1.0.0
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Windows 7

### Steps to reproduce
1. Note "Page 1" text on first page.
2. Switch to "Page 2" using bottom navigation and then to "Page 1"
3. Note missing "Page 1" text on first page.

### Expected Behavior
This setup was working correctly with vuetify 0.17.7 . Content text on both pages should be visible after page switch.

### Actual Behavior
Page content text hides under toolbar, as if toolbar is missing its "app" prop.

### Reproduction Link
[https://codepen.io/anon/pen/yvoVZg?editors=1010](https://codepen.io/anon/pen/yvoVZg?editors=1010)

### Other comments
Might be not a bug, but I couldn't find any info on how to correctly implement different toolbars for different views.

**Comment by johnleider** [comment]
This is happening because the incoming toolbar is created before the old is destroyed. When an application component is destroyed, it resets its corresponding value in the **$vuetify.application** object. There are a few ways that you could get around this.

1. Use one toolbar and dynamically change its content per view
2. Add a ref to the toolbar and call `this.$refs.refName.callUpdate()` (where refName is the name you assign to ref)

After going through the code a bit, I'm not sure if at this time that is something we can explicitly support, but simply provide these workarounds.

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.

**Comment by KaelWD** [comment]
Fixed by #3295
