### ISSUE TITLE
[Bug Report] Tabs with grow option move left when selecting second tab (on smaller screen)

### ISSUE THREAD

**Issue by sebastianbarfurth** [vuetifyjs/vuetify#3294]
### Versions and Environment
**Vuetify:** 1.0.0
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.119
**OS:** Windows 10

### Steps to reproduce
1. Open the pen
2. Select the second tab
3. Resize the window to make it less wide
4. Make window smaller until tab bar shifts left

### Expected Behavior
The tab bar should stay in place

### Actual Behavior
The tab bar receives a CSS style: "transform: translateX(...);" and moves left

### Reproduction Link
[https://codepen.io/anon/pen/eVGxRN](https://codepen.io/anon/pen/eVGxRN)

### Other comments
In the pen this issue is only triggered by resizing the window, when running a collapsible sidebar menu it is triggered on page load once the tab is switched.

**Comment by KaelWD** [comment]
Can you provide a screenshot? I don't see any problem in that pen.

**Comment by sebastianbarfurth** [comment]
@KaelWD My corporate network doesn't seem to allow image uploads. It basically shifts the tabs over. I've resorted to removing "grow" for now.

**Comment by smiller171** [comment]
@KaelWD I have the same issue, caused by the transform on the `tabs__container`. Screenshots attached.

You can see this live at https://5ac628c50b79b71bca89fc43--millergeek.netlify.com/contact/


![screenshot 2018-04-05 at 9 57 14 am](https://user-images.githubusercontent.com/3587913/38370354-ef851b04-38b7-11e8-98f6-335211f801dc.png)
![screenshot 2018-04-05 at 9 57 31 am](https://user-images.githubusercontent.com/3587913/38370353-ef747bfa-38b7-11e8-9304-a7b9ab4b73c9.png)

**Comment by smiller171** [comment]
You can see my code at this point in time at https://github.com/smiller171/www.millergeek.xyz/tree/c93a70eea4a2e9775dee1d9c8d567b756d3e811d

**Comment by smiller171** [comment]
I've created [a minimal codepen example](https://codepen.io/smiller171/pen/eMPOqQ). You may need to reduce the viewport width to make the issue appear, so I suggest positioning the editors on the side to play with the width.

![screenshot 2018-04-05 at 10 26 00 am](https://user-images.githubusercontent.com/3587913/38372005-d5891e0e-38bb-11e8-8987-02152dac69e1.png)

**Comment by smiller171** [comment]
As I dig into this further I'm realizing the issue is in the scrolling behavior.
1. It does not seem to be calculating correctly whether it needs to scroll
2. When it decides to scroll, it's scrolling past the selected tab even if that's the rightmost tab.

**Comment by johnleider** [comment]
If you want to pop into the community we can debug together :) https://community.vuetifyjs.com #bugs

**Comment by KaelWD** [comment]
I had trouble reproducing this because of the vague directions, but here it is:

Narrow window, click the last tab:
![image](https://user-images.githubusercontent.com/16421948/38779573-a93c9ce0-410d-11e8-83af-302517bb07f3.png)
Increase width, but keep below 1264px (default mobile-breakpoint value):
![image](https://user-images.githubusercontent.com/16421948/38779582-c77e180a-410d-11e8-8059-fdff6c53ee7a.png)
If you go *past* 1264px, it works fine:
![image](https://user-images.githubusercontent.com/16421948/38779588-e11bd734-410d-11e8-9faf-cb7d7a62c55a.png)
