### ISSUE TITLE
[Bug Report] v-speed-dial getting lost behind v-card

### ISSUE THREAD

**Issue by EvanZ** [vuetifyjs/vuetify#3414]
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Mac OS 10.12.4

### Steps to reproduce
Put a bunch of v-cards on a page with a speed-dial.

### Expected Behavior
Speed-dial fixed should always stay on top of other elements.

### Actual Behavior
Speed-dial is getting placed behind other elements.

### Reproduction Link
[https://codepen.io/ezamir/pen/NyebVJ](https://codepen.io/ezamir/pen/NyebVJ)

### Other comments
Discussed this in bugs forum on discord.

**Comment by KaelWD** [comment]
They're both positioned, so it works if you put the speed-dial *after* the cards in your markup: https://codepen.io/anon/pen/rJbjdN?editors=1010

Speaking of, why do cards need `position: relative` again?

**Comment by johnleider** [comment]
That style is very old and probably not needed anymore.

**Comment by KaelWD** [comment]
Should I take this one? I've already tried removing that rule before, maybe I'll have better luck this time.

**Comment by johnleider** [comment]
Yea

On Mar 3, 2018 7:47 AM, "Kael" <notifications@github.com> wrote:

Should I take this one? I've already tried removing that rule before, maybe
I'll have better luck this time.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/vuetifyjs/vuetify/issues/3414#issuecomment-370145146>,
or mute the thread

**Comment by KaelWD** [comment]
K. Won't get to it tonight, but I'll have a go tomorrow if you don't beat me to it.
