### ISSUE TITLE
[Bug Report] Vuetify icons self hosted not working properly

### ISSUE THREAD

**Issue by Tabrizian** [vuetifyjs/vuetify#3462]
### Versions and Environment
**Vuetify:** 1.0.0
**Vue:** 2.5.0
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
If you simply run the file it contains a ```v-icon``` with icons not aligned properly

### Expected Behavior
Plus icon to be adjusted in the center.

### Actual Behavior
Plus icon is stuck to the top.

### Reproduction Link
[https://github.com/Tabrizian/vuetify-selfhosted-icons](https://github.com/Tabrizian/vuetify-selfhosted-icons)

![vuetify selfhosted icons](https://user-images.githubusercontent.com/10105175/36946066-71b69b7a-1fcc-11e8-8eac-673f5f885210.png)

**Comment by preeteshjain** [comment]
This is happening with me as well. Although I am importing icons directly in my main Vue template, like this:

```vue
<template>
  ...
</template>

<script>
  ...
</script>

<style>
    @import 'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons';
</style>
```

**Comment by KaelWD** [comment]
The icon font needs to be loaded **above** the rest of vuetify's CSS or the overrides won't work properly.

**Comment by zzAutumn** [comment]
@preeteshjain I import  icons in my main Vue ,I use vue-cli ,that is in App.vue, and it works

**Comment by zzAutumn** [comment]
![image](https://user-images.githubusercontent.com/30762123/40277053-114282d4-5c4b-11e8-937b-bf2b008a48ca.png)

**Comment by Djaler** [comment]
@KaelWD I think we need to reopen this. Cause I have this bug even with correct ordering of imports.
Maybe the source of the problem is that I have many vendors chunks?
Anyway, `inline-flex !important;` in `.v-icon` can solve the issue 
![screenshot_20181031_093510](https://user-images.githubusercontent.com/7964583/47770514-bdd64c80-dcf0-11e8-9c68-4cf02bc0ff3a.png)
![screenshot_20181031_093541](https://user-images.githubusercontent.com/7964583/47770515-bdd64c80-dcf0-11e8-9bcc-c4c3cdfc1a9b.png)
![screenshot_20181031_093826](https://user-images.githubusercontent.com/7964583/47770516-be6ee300-dcf0-11e8-9841-e2f379574199.png)

**Comment by NegativeDearc** [comment]
> The icon font needs to be loaded **above** the rest of vuetify's CSS or the overrides won't work properly.

that works

**Comment by PeterKnight** [comment]
Note that `display: inline-flex !important;` also overrides `display: none;`, which is how `v-show` toggles visibility on elements.
