### ISSUE TITLE
Vuetify & vuex

### ISSUE THREAD

**Issue by maartendraijer** [vuetifyjs/vuetify#347]
First of all, thanks for this awesome package!

A question I'm having is: what is the proper way to use Vuetify in combination with Vuex? For example, how to use `v-model` (alerts or snackbars) with data received from a vuex store?

Because when closing an alert, or when a toast times out, it tries to directly modify the object received from the vuex store, and this is not allowed (vuex strict mode): `Error: [vuex] Do not mutate vuex store state outside mutation handlers.`

Also, when I try to do something like this: `v-model="toast"`, where toast is an object like this in the store: `{ msg: 'This is the toast', timeout: 1000}`, I'm getting the following error: `Invalid prop: type check failed for prop "value"`. My workaround for how is to add an extra property `show: true` to the toast object. But perhaps there is a better way.

Any tips?

**Comment by johnleider** [comment]
The first error is not Vuetify, you must use a proxy in order to communicate state change from the Vuex store.

Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.
