### ISSUE TITLE
[Feature Request] Add color prop to v-app

### ISSUE THREAD

**Issue by coxta** [vuetifyjs/vuetify#3590]
### Problem to solve
Would like to give the `v-app` parent a `color` prop, rather than being limited to just `light` and `dark` themes.  This would help solve the contrast issues that exist, for example, with lists having a white background but contrasting with the *light grey* background inherited from a default `light` theme.  Looking for a consistent flat look, one might want to just set the `v-app` prop `color="white"` to remediate the anomaly.  While its *very easy* to simply use inline styling, such as `<v-app style="background: white">`, it would be preferable to avoid inline styles and maintain consistency.

### Proposed solution
Enable the `color` prop for `v-app`

**Comment by AlexSHoffman** [comment]
@coxta there's a lot of elements that don't support this prop. There's a very straightforward workaround for this - you can use `class="white"` instead of `color="white"` for all the elements that do not support `color` prop.

To change the background color:
`<div class="grey darken-2">change background color</div>`

To change the text color:
`<div class="blue--text text--darken-2">change text color</div>`

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

**Comment by coxta** [comment]
Ahh, seems pretty straightforward now, can't beleive I didn't try that first.  Sorry to waste your time, keep up the great work!
