### ISSUE TITLE
[Bug Report] Cannot navigate using arrows keys in dropdown containing a textfield

### ISSUE THREAD

**Issue by marya314** [vuetifyjs/vuetify#3674]
### Versions and Environment
**Vuetify:** 1.0.0
**Vue:** 2.5.2
**Browsers:** Chrome 65.0.3325.181
**OS:** Mac OS 10.13.3

### Steps to reproduce
In the code pen, type a search query in the text field. The up/down keyboard arrows no longer work. 
Then, when you click on an option in the dropdown, they up/down keys don't navigate to all the options. Maybe depending on what's viewable in the viewport?

### Expected Behavior
Users should be able to search then use arrow keys to select dropdown options. 

### Actual Behavior
Users must use mouse to select dropdown option after searching.

### Reproduction Link
[https://codepen.io/johnjleider/pen/pLWmyN](https://codepen.io/johnjleider/pen/pLWmyN)

### Other comments
In addition, the open-on-hover prop on v-menu makes the whole menu scroll with the page, which I believe is a known Vuetify issue. I couldn't reproduce in this codepen but I see it in my larger project.

**Comment by chewy94** [comment]
I do not think this is an issue here. You are clicking on the text field which causes the list to lose focus and the arrow keys are within the scope of the text field.

@vuetifyjs/dev-team Any other thoughts on this?

**Comment by uzirthapa** [comment]
Any update on this. I am trying to make an accessible menu so that people do not need to use the mouse to select an option. Currently there isnt a way to select the items inside the menu with the arrow keys. When I open the menu and try to tab into it, the menu closes.

**Comment by johnleider** [comment]
Not yet. We are currently in the process of alpha testing 1.1, which is a big form update. I'll tag this

**Comment by johnleider** [comment]
After careful consideration, this is something that should be solved in user land. You are essentially creating a new component with functionality combined from a few different sources. Because of this, you are going to have to handle keydown actions yourself in order to adjust the `v-menu`'s list index, similar to what we do for v-select.

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.
