### ISSUE TITLE
[Bug Report] DataTable's current page reset to 1 when totalItems change

### ISSUE THREAD

**Issue by petr-k** [vuetifyjs/vuetify#3766]
### Versions and Environment
**Vuetify:** 1.0.11
**Vue:** 2.5.13
**Browsers:** Chrome 65.0.3325.162
**OS:** Linux x86_64

### Steps to reproduce
* Change `total-items` property of a `DataTable`

### Expected Behavior
`page` on the bound `pagination` is not changed

### Actual Behavior
`page` on the bound `pagination` is reset to `1`

### Reproduction Link
[https://codepen.io/anon/pen/Wzgbzr](https://codepen.io/anon/pen/Wzgbzr)

### Other comments
While using server-side paging and sorting, users typically browse through the pages. It is quite common that while they are doing this, the total number of items might change, because new rows might appear e.g. in the remote database. Current behavior unexpectedly resets the view to the first page, which is confusing.

**Comment by nekosaur** [comment]
This was a conscious decision on our part. The motivation was that, if the data changes then the current view (page) of the data is no longer valid.

Say you have the following pagination and current page
```
1 [2] 3 4
```
If the data changes such that all items are prepended to list
```
1 [2] 3 4 (6) 7 8
```
Then if page stays at 2 it will be a completely different view of the data, `()` being the old page.

However with that said, I do see how this should probably be a toggleable behaviour

**Comment by KaelWD** [comment]
True, but if items are just *appended*, then resetting the page makes no sense. I'd say leave it up to the consumer if they want to change pages or not.

**Comment by nekosaur** [comment]
Yeah I'm leaning towards this being entirely up to the user

**Comment by shwetasahuit** [comment]
How can I set the config to change the pagination to first page on dataload

**Comment by nekosaur** [comment]
Use `pagination` prop

**Comment by Flamenco** [comment]
If I have 5 pages of data, and the user scrolls to the last page, and then applies a filter to her data set, the DataTable displays `no data` and shows a completely messed up page number, even though there is data.  The use can still page back to the first page and see the data.  There is no way it can be justified that this behavior is correct under any circumstance.

So the issue is not resetting when `totalItems` changes per OP, but when first visible row >= totalItems.

**What Needs To Be Fixed**
The component should ALWAYS reset to first page if the current page start is beyond the available rows.

<img width="713" alt="screen shot 2018-10-12 at 7 53 27 am" src="https://user-images.githubusercontent.com/819940/46867938-af34fd80-cdf4-11e8-96a5-09335effbf5e.png">

**Comment by jacekkarczmarczyk** [comment]
@Flamenco please do not comment closed issues, if you encouter a bug please create a new issue and provided a reproduction boiled down to minimal

**Comment by Flamenco** [comment]
@jacekkarczmarczyk This issue should be re-opened then, as the comments and discussion are all relative to the issue.

**Comment by jacekkarczmarczyk** [comment]
No, this issue is solved (see the reproduction link in the issue description)

**Comment by Flamenco** [comment]
OK. I will post a new issue.
