### ISSUE TITLE
Replace hex color values with rgba values

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#383]
As per [Material Design specs](https://material.io/guidelines/style/color.html#color-usability), text and icons should use opacity values (rgba) instead of solid colors (hex codes) to make text more eligible when used on different backgrounds. For example, primary text should have an opacity of 87% black (`rgba(0, 0, 0, .87)`) instead of `#424242`, which currently is used in Vuetify. Please consider updating the base color scheme to use rgba values where appropriate for better conformance with the spec.

**Comment by johnleider** [comment]
Please keep in mind, the spec for color was literally updated last week.

**Comment by DivinoAG** [comment]
@johnleider I'm sorry to disagree, but the specs defined colors for fonts and icons through transparency since they were first announced. You can see [on archive.org](https://web.archive.org/web/20161227131244/https://material.io/guidelines/style/color.html#color-text-background-colors) that since their first snapshot the page already included this information. 

It's not a big deal, but I thought you'd like to be aware of it.

**Comment by johnleider** [comment]
Ok

**Comment by johnleider** [comment]
This has been merged into dev.
