### ISSUE TITLE
[Feature Request] Focus / Outline Indicator for Buttons

### ISSUE THREAD

**Issue by dmcknight26** [vuetifyjs/vuetify#3923]
### Problem to solve
Currently when tabbing through a group of buttons it can be extremely difficult (if not impossible) to tell which one is currently focused. Especially for normal and icon buttons that have a color applied to them. Generally browsers will apply a blue outline around the focused element to indicate to the user that is the currently focused element.

### Proposed solution
Support (or re-enable) the default blue outline that's applied to focused elements, perhaps making that a configuration option for the element. Failing that Google Play Music has an interesting take on icon buttons which applies an outer grayish circle on focused icon buttons that have a color assigned to them. You can see an example here which shows the pause button currently being focused: https://imgur.com/a/nCTJdsc.  This could be a nice alternative...

**Comment by johnleider** [comment]
Going to move this to `help wanted` as we have met MD2 spec for v2 and this did not make the cut.

**Comment by renoirb** [comment]
For reference, here is the WCAG success criterion this issue is about.

For the issue regarding button focus visibility 

It's WCAG 2.4.7, [`w3.org/WAI/WCAG21/quickref`][quickref-focus-visible], some more notes are in [`w3.org/WAI/WCAG21/Understanding` section][understanding-focus-visible-2]

> The bigger the visible change the easier it is for someone to see, authors are encouraged to make the change as large as possible. For example, a thick outline around the element. 

![The bigger the visible change the easier it is for someone to see][wcag21-focus-visible-enhanced-size-of-indicator]

[wcag21-focus-visible-enhanced-size-of-indicator]: https://user-images.githubusercontent.com/296940/98851800-c657d680-2424-11eb-9e78-0f1d1a91a901.png
[quickref-focus-visible]: https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=324%2C331%2C332%2C335%2C412%2C247#focus-visible
[understanding-focus-visible-2]: https://www.w3.org/WAI/WCAG21/Understanding/focus-visible-enhanced#size-of-indicator

**Comment by KaelWD** [comment]
My current implementation uses a more opaque overlay on buttons with dark backgrounds:

![image](https://user-images.githubusercontent.com/16421948/108190309-e1de2600-7165-11eb-95c5-364169f3b203.png)
![image](https://user-images.githubusercontent.com/16421948/108190320-e4d91680-7165-11eb-8883-686b6e953787.png)

This is still only 1.45 contrast against unfocused buttons, but you can customise it per colour with `--v-theme-<color>-overlay-multiplier` (here it's 4):
![image](https://user-images.githubusercontent.com/16421948/108191525-54033a80-7167-11eb-8614-c29178bc85d0.png)


Another solution would be a lighter ring overlaid only on keyboard focus like material-ui: 
![image](https://user-images.githubusercontent.com/16421948/108191134-ea832c00-7166-11eb-8d1f-8a52367efa92.png)

One problem is if it's too opaque it can make the text unreadable.

**Comment by wiseadme** [comment]
I would like to take a task

**Comment by msftedad** [comment]
Hi Team, Issue is still repro'ing in Vuetify 3.7.x version as well.
