### ISSUE TITLE
[Feature Request] Ability to separate Stepper header from content

### ISSUE THREAD

**Issue by shinynet** [vuetifyjs/vuetify#3941]
### Problem to solve
In a nutshell, I wish this worked more like the Tab component, in that I can have the actual tabs defined separately from the tab content. For example, I can render the tabs in the toolbar, and render the tab content below in the page. This doesn't appear possible with the Stepper

### Proposed solution
Model the Stepper component similar to the Tabs component. Allow the v-stepper-content component take a v-model property, so it can be defined, by itself, anywhere.

**Comment by johnleider** [comment]
Stepper will be converted to use the new `v-item-group` component in v1.3

**Comment by johnleider** [comment]
All `v-stepper` updates are being moved to v2.0 due to backwards compatibility issues.

**Comment by johnleider** [comment]
Due to time constraints all stepper changes are being moved to a future minor release in v2.x . Thank you for your patience.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by johnleider** [comment]
The design of stepper caused this to be an issue. It's being completely rebuilt into separate components for vertical and horizontal, which will in turn alleviate this issue. Due to that, I'm not going to track this as a related issue for a new component.

Please watch for v3 to see the new components in action!

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
