### ISSUE TITLE
[Bug Report] v-slider not working as expected with v-model

### ISSUE THREAD

**Issue by kdholt34** [vuetifyjs/vuetify#4105]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.6
**Vue:** 2.5.15
**Browsers:** Chrome 66.0.3359.181
**OS:** Mac OS 10.12.6

### Steps to reproduce
Move slider outside the provided validation values.

### Expected Behavior
Slider should always match the v-model.

### Actual Behavior
Slider displays a different value than what the v-model holds.

### Reproduction Link
[https://codepen.io/kdholt34/pen/LmgLNj?editors=1010](https://codepen.io/kdholt34/pen/LmgLNj?editors=1010)

### Other comments
Same code worked prior to 1.1.0

You'll probably wonder why I'm not just using the provided min/max props... We have multiple related fields using the sliders and want them all to be the same "width" but limit actual selection based on ranges previously set per field.

**Comment by johnleider** [comment]
My advice would be to use the scoped slot and manually define the displayed value. You have a defined max of 80. The slider will obey your model up until the point you stop updating it. Once it hits 45, the internalValue continues to update lazyValue, which them emits the change, which due to your logic is never persisted. Either set a dynamic max or you can use this as a template:

https://codepen.io/johnjleider/pen/BxbNXp?editors=1010
