### ISSUE TITLE
[Bug Report] Select All doesn't seem to work with pagination

### ISSUE THREAD

**Issue by marcovc** [vuetifyjs/vuetify#4166]
### Versions and Environment
**Vuetify:** 1.0.13
**Vue:** 2.5.13
**Browsers:** Chrome 66.0.3359.117
**OS:** Linux x86_64

### Steps to reproduce
1. Create a datatable with "select-all" and pagination.
2. On the first page click on the header select all checkbox.
3. Navigate to second page.

### Expected Behavior
The rows in the second page should be automatically selected.

### Actual Behavior
Only the rows in the first page are selected.

### Reproduction Link
[https://codepen.io/anon/pen/oygbKO](https://codepen.io/anon/pen/oygbKO)

### Other comments
Although I think that the current reasoning of not adding all rows to the selected object is rational (otherwise it would have to pull all pages from the server at once, thus breaking the pagination promise), I think it should still do it lazily - whenever the user transitions to a new page, if the select all checkbox is on, then add all rows in that page to the selected object. If the user then clears the select all checkbox, the object is cleared at once.

**Comment by KaelWD** [comment]
This is intentional, take Gmail as an example:

![image](https://user-images.githubusercontent.com/16421948/40717499-e1d85d68-644f-11e8-8e15-422c38b05f4a.png)

![image](https://user-images.githubusercontent.com/16421948/40717544-151c5152-6450-11e8-90fc-6e4bc514f749.png)

If you switch pages it retains the original selection, but there is a link to select **everything** if you really want. You can do this pretty easily just by adding all the items to the `selected` array: https://codepen.io/anon/pen/vrEGpG?editors=1010

**Comment by marcovc** [comment]
@KaelWD, 

Thanks.

I didn't know the semantics of select all was "select all in current page". Sorry for the noise.

Can you point me to the easiest way to make the header select-all checkbox behave as the "select everything" button you just added below?

**Comment by KaelWD** [comment]
Something like this should do it: https://codepen.io/anon/pen/pKvbEB?editors=1010

Most of that's taken from https://vuetifyjs.com/en/components/data-tables#example-headers

**Comment by marcovc** [comment]
Thanks a lot @Kael!
