### ISSUE TITLE
[Bug Report] Beta.1 - Required property not working for a-la-carte fields

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#4211]
### Versions and Environment
**Vuetify:** 1.1.0-beta.1
**Vue:** 2.5.3
**Browsers:** Firefox 60.0, Google Chrome
**OS:** Ubuntu undefined

### Steps to reproduce
Check that repo out.  
Yarn install
Yarn Dev
Notice the input on the page doesn't have the "required" * next to the label.

### Expected Behavior
If you downgrade to the latest stable version of vuetify, it shows correctly.

### Actual Behavior
No star is showing

### Reproduction Link
[https://github.com/GreywallSoftware/vuetify-a-la-carte-bug](https://github.com/GreywallSoftware/vuetify-a-la-carte-bug)

**Comment by KaelWD** [comment]
That was intentionally changed in 1.1, you have to add it to the label manually now.

**Comment by gabaum10** [comment]
So there is no "required" prop anymore?  Just want to clarify.

**Comment by gabaum10** [comment]
I suppose that makes sense, it wasn't doing a whole lot.

**Comment by KaelWD** [comment]
That's literally all it was doing as far as vuetify goes. You can image how that would be annoying if you want to use the *actual* `required` attribute without having the `*`.

**Comment by gabaum10** [comment]
Rock on.  Sounds good.

**Comment by clementmas** [comment]
Actually, it was doing something when used within a `<form>` tag:

With _Vuetify 1.0.19_, this form would trigger the HTML5 validation:
https://codepen.io/anon/pen/XYjNKW

Same form here with _Vuetify 1.1.0-beta.2_. Looks like it strips off the `required` attribute:
https://codepen.io/anon/pen/VdKmjp

Is this an intentional change as well?

I know there are many ways to do validation with the `<v-form>` component but for simple forms HTML5 validation is quite useful. Otherwise, we have to re-implement this feature and add i18n when it's already there.
If it's a simple fix, I think it's worth keeping the required attribute on the input.

I can post a separate issue if this is an "issue".

**Comment by jacekkarczmarczyk** [comment]
Yes, that looks like a bug

**Comment by clementmas** [comment]
Ok, I created a new issue:
https://github.com/vuetifyjs/vuetify/issues/4223
