### ISSUE TITLE
[Bug Report] v-autocomplete cause builtin chrome autocomplete(autofill) break

### ISSUE THREAD

**Issue by aldarund** [vuetifyjs/vuetify#4214]
### Versions and Environment
**Vuetify:** 1.1.0-beta.2
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.62
**OS:** Windows 10

### Steps to reproduce
Put cursor in any field and let chrome autocomplete popup appear ( need to have data in chrome autocomplete from other froms - https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill )
Click any item from the list.
Nothing happens.
If delete v-autocomplete - all works fine.
If enclose with v-form - all works fine.
In firefox seems to be working fine without any additional steps.

### Expected Behavior
Form data filled

### Actual Behavior
Nothing happens

### Reproduction Link
[https://codepen.io/aldarund/pen/rKLxpg](https://codepen.io/aldarund/pen/rKLxpg)

**Comment by AGPDev** [comment]
Same here

**Comment by johnleider** [comment]
TLDL: [Change **autocomplete** on `v-autocomplete` to **browser-autocomplete**](https://codepen.io/johnjleider/pen/MXbjXG)

The reason this happens:

On `v-text-field`, the **autocomplete** attribute gets propagated to the _input_ field. On `v-autocomplete`, that property has no mean. The reason is that before it was abstracted, `v-select` had an **autocomplete** prop. In order to provide the dev with a way to change the actual input autocomplete settings, we added **browser-autocomplete**. Now that we have `v-autocomplete` as a standalone component we can safely deprecate this prop, but not until v1.2 after we have deprecated the **autocomplete** prop itself.

**Comment by aldarund** [comment]
@johnleider hm, but why adding property that has no mean break other fields? I would expect it just not working for autocomplete, not to break other fields completely.

**Comment by johnleider** [comment]
Agreed, it is bad, but mistakes were made. We're trying to resolve it.

**Comment by aldarund** [comment]
@johnleider maybe at least print some warning to user similar to deprecation warning?

**Comment by johnleider** [comment]
It is very easy from a macro position to say "Hey, it's easy just do this", but that happens about 100 times a day. Maintaining the documentation is a herculean task and as an open source project. This means we have to triage what gets attention and not everything shares the same level of importance.

Basically, if there is something you feel should be somewhere, it's infinitely better to reach out and see if we agree, and then PR the changes. Otherwise, we will get to it as soon as we can.
