### ISSUE TITLE
[Bug Report] Min and max props regression

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#4221]
### Versions and Environment
**Vuetify:** 1.1.0-beta.2
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Compare the counter of:
https://codepen.io/anon/pen/vrXKZb?&editors=101
https://codepen.io/anon/pen/YvGWQd?&editors=101

### Expected Behavior
Same behavior

### Actual Behavior
Looks different

### Reproduction Link
[https://codepen.io/anon/pen/YvGWQd?&editors=101](https://codepen.io/anon/pen/YvGWQd?&editors=101)

**Comment by jacekkarczmarczyk** [comment]
That's because the arbitrary default counter value of 25 has been removed (and I think I did it), so now you need to do `counter="25"` or `maxlength="25"` to get the same result
It is a breaking change but imho it's unlikely to break anything as I guess that people using counters will provide their own max length
This look more like the issue with docs where the counter value should be provided in the example

**Comment by jacekkarczmarczyk** [comment]
Closing after discussion in #team, docs will be updated

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetifyjs.com/commit/9a6733a07a6c4662445b0fb89ac51226fe0ba13b
