### ISSUE TITLE
Ability to specify placeholder for text inputs and selects

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#436]
Some times it is nice to be able to specify a placeholder text for input control that are different from the label (e.g. a short explanatory text). I know we already have the `hint` prop, but a placeholder fills a slightly different purpose. It is also part of the HTML spec.

Vue-material already have this. Have a look at the second example to see what I mean:
https://vuematerial.github.io/#/components/input

What do you think?

**Comment by mfferreira** [comment]
@sindrepm You can do this by defining the `label` prop.

**Comment by sindrepm** [comment]
@mfferreira I think maybe I did not explain myself clear. I am talking about a `placeholder` prop in addition to the current `label` prop. As I said, there are times where it is preferable to have a placeholder that is **different** from the label. The placeholder should show in the text field only when it is empty, whereas the label keep the current behavior. Did you look at the example from vue-material?

**Comment by mfferreira** [comment]
@sindrepm Yes I did. And I see what the issue is now.
Check my example: https://codepen.io/mfferreira/pen/VbmBLe

You can achieve the placeholder by using both `label` and `single-line` props on the `v-text-field`.
That also means you won't be able to have a "placeholder" and a label floating above the input at the same time.

Room from improvement. Thanks for pointing this out.

**Comment by sindrepm** [comment]
@mfferreira thanks for adding this on the roadmap., I think it will be a nice feature to have both the floating label and a placeholder.
