### ISSUE TITLE
Best way for validation on form inputs?

### ISSUE THREAD

**Issue by sirchas** [vuetifyjs/vuetify#44]

**Comment by johnleider** [comment]
Wrap the component in your own, then using the validate property. https://vuejs.org/v2/guide/components.html#Prop-Validation
Do the validation in whatever component or system that is managing your applications state.

**Comment by dohomi** [comment]
@johnleider it would be great to see some form validation inside of the form section. Some basic field input error handling would be awesome

**Comment by wdews** [comment]
+1 on this; would be great to see some sort of Form component that houses all of the form's errors so that it can be evaluated easily before submitting a form, for example. I love this library, thanks @johnleider

**Comment by johnleider** [comment]
This may be something that is done after the Vuetify core is finished. No
promises though.

On May 8, 2017 8:27 AM, "Wes Dews" <notifications@github.com> wrote:

+1 on this; would be great to see some sort of Form component that houses
all of the form's errors so that it can be evaluated easily before
submitting a form, for example. I love this library, thanks @johnleider
<https://github.com/johnleider>

—

You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/vuetifyjs/vuetify/issues/44#issuecomment-299853119>,
or mute
the thread

**Comment by jofftiquez** [comment]
+1

**Comment by nekosaur** [comment]
This is also not very hard to do yourself. Here's one that I've used before. 

https://gist.github.com/nekosaur/1da5fed1abcd7ccbf077e86d33e94183

**Comment by dohomi** [comment]
@nekosaur nice example!
