### ISSUE TITLE
[Bug Report] Class "input-group--focused" isn't working anymore

### ISSUE THREAD

**Issue by Mairtrus** [vuetifyjs/vuetify#4470]
### Versions and Environment
**Vuetify:** 1.1.1
**Last working version:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 7

### Steps to reproduce
1. Create a **v-text-field** component
2. Add to it the class "input-group--focused"

### Expected Behavior
The  **v-text-field** should always stays in a focused state, even if it's really focused or not

### Actual Behavior
The  **v-text-field** only is in focus state when gains the focus

### Reproduction Link
[https://codepen.io/anon/pen/KeYzWo](https://codepen.io/anon/pen/KeYzWo)

### Other comments
The class "input-group--focused" seems missing in the css file.

**Comment by johnleider** [comment]
Classes got scoped for v1.1, The new class is `v-input--is-focused`. Although you will need to add a text color as well:

https://codepen.io/johnjleider/pen/LrvZJz

This won't get it exactly the same as before as most of the internals are now controlled pro-grammatically instead of through cascaded css selectors.
