### ISSUE TITLE
v-dialog's v-model gets set twice without the activator slot (and on close)

### ISSUE THREAD

**Issue by maartendraijer** [vuetifyjs/vuetify#451]
Not really an issue perhaps, but just noticed that the `set()`'s method gets called twice when opening/closing the `v-dialog`. It doesn't do this when the trigger is contained within the `activator` slot though.

https://codepen.io/anon/pen/ZKLvLY?editors=1111

By the way: the reason I need the computed property is that I'm setting the state to a vuex store.

**Comment by abelovic** [comment]
@johnleider - It doesn't seem like this is fixed (the codepen above points to latest and doesn't work) :( 

I also need to be able to control the dialog in the same way because I am trying to reuse a dialog in the parent (called from child) to get around this: https://github.com/vuetifyjs/vuetify/issues/620

In addition, I have headers and footers in my layout and want the dialog to go full screen and not just the full height and width of component which is why I am trying to use one dialog in the parent.

**Comment by johnleider** [comment]
https://codepen.io/johnjleider/pen/YVmPyP?editors=1111

**Comment by abelovic** [comment]
@johnleider  - Thank you!!!

For those who run into the same issue, the difference between the two examples (besides the fix that is in version 0.12.2) is that the button event handler needs to have the "stop"

i.e. @click.native.stop
