### ISSUE TITLE
[Feature Request] v-text-field add `align-text` prop

### ISSUE THREAD

**Issue by lowerends** [vuetifyjs/vuetify#4552]
### Problem to solve
Currently (version 1.1.1), when using v-text-field with the `reverse` property, the `prefix` and `suffix` properties are also reversed in that sense that the prefix becomes a suffix and vice versa. There should be at least an option to disable this behaviour, or this behaviour should be modified permanently. This was discussed in issue #1782 .

### Proposed solution
The proposed solutions is (1) to not swap the `prefix` and `suffix` properties or (2) to provide a property that disables the swapping of the `prefix` and `suffix` properties if desired.

**Comment by lowerends** [comment]
To add to this, this is currently causing a bug when using `prefix` in combination with `reverse`, as the prefix is not positioned correctly (i.e. within the text field). It jumps out of the text field. An example of this behaviour is implemented in this codepen: https://codepen.io/anon/pen/oPaXJo

**Comment by jacekkarczmarczyk** [comment]
The prefix thing looks like https://github.com/vuetifyjs/vuetify/issues/3485 @lowerends

**Comment by graham-sportsmgmt** [comment]
The codepen doesn't seem to be working.  Here's an image with the error:

![annotation](https://user-images.githubusercontent.com/16939733/47160554-0af40080-d2a5-11e8-9151-2a58743a2205.png)

This was the pug used to generate that output:

`v-text-field(v-model='value' prefix='pounds' reverse)`

I also tried this suggestion from the originating issue with the same result:

`v-text-field(v-model='value' style="text-align:right" prefix='pounds' reverse)`

**Comment by jacekkarczmarczyk** [comment]
@marc398 this is not related to this issue, also it should be already fixed https://github.com/vuetifyjs/vuetify/pull/5476

**Comment by MatthewAry** [comment]
It seems several issues have been closed regarding this and have been consolidated into this one.
I initially started looking through the issue tracker because I was trying to figure out how to right align the text in components that are VTextField or extend off of VTextField. What I've learned thus far is that there is no clear breakdown of the different requests relating to alignment and I would like to list what I think the different requests have been so far regarding this issue and what my particular need for this is.

This issue has been submitted in the following ways:

- Need to be able Align input text and label to the right
- Need to be able to align just the input text to the right but not the label
- Need to support right-to-left behavior for rtl languages, which means swapping prefix with postfix and aligning everything generally to the right.
- Need to be able to align just the label to the right

These various requests are similar but are functionally different. Right now there is no good way to get granular control over text alignment over labels or the input text. This is something that I think needs to be exposed.

In my situation, I am trying to align the input text to the right as numbers are better presented when aligned to the right. In order for me to do this, I have to use deep selectors if I am using scoped css and/or i need to be very explicit with my CSS Selectors to modify the desired input field. This is not ideal. Vuetify has no obligation to maintain their current css class names as they are right now, so any styling that I do for this will be brittle.

So, I think that the high level solution here is to make VTextField type input components have more style related properties which can ultimately address these needs.

**Comment by wiseadme** [comment]
I would like to take a task

**Comment by KaelWD** [comment]
`reverse` no longer swaps the affixes in v3

**Comment by emreseyit** [comment]
I can't use or find added feature neither in v2 nor v3. I checked the [documentation](https://vuetifyjs.com/en/api/v-text-field) and it does not include `align-text` prop. Can someone help about the usage or inform about latest status of the feature?
