### ISSUE TITLE
Menu position calculation incorrect when attached to custom element

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#4578]
I have a fullscreen dialog with some selects and other elements which use detachable components, e.g. v-menu. When the dialog needs to scroll it cause problem because the menu is attached to the root by default so it does not scroll with the select list. I tried to set the `attach` property on `v-select` to the `.v-dialog` element but in this case the position of the menu is not calculated correctly (it always gets top/left: 0).

### Versions and Environment
Vuetify: Latest
Vue: Latest stable
Browsers: Chrome latest
OS: Win7

### Steps to reproduce
Click on Open Dialog and then open the select menu.

### Expected Behavior
The menu should appear in the correct position.

### Actual Behavior
The menu always appears in the top left corner.

### Reproduction Link
Go to https://codepen.io/anon/pen/PBwpZz

---

### Additional Comments:

If I set the attach prop to some non-existing element it sort of works because it seems then that the menu content is attached to the immediate parent, but still the position is not correct and this is an ugly workaround.

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/anon/pen/MBYoOm

**Comment by sindrepm** [comment]
@jacekkarczmarczyk cool! I wasn't aware that you could use the `attach` prop that way with a boolean. Is this documented?

**Comment by jacekkarczmarczyk** [comment]
Not really, just mentioned in the props list (with wrong type description). This case deserves an example, you can create an issue in docs repo

**Comment by sebzap** [comment]
@jacekkarczmarczyk your fix works nicely for this particular issue, but IMHO the documented bug still exists.

I have a use case where i similarly want to attach the menu somewhere else, like in the original codepen here, however i cannot use attach like you because the parent of my <v-select> is small with `overflow: hidden`, like this: https://codepen.io/anon/pen/rgZZMy

**Comment by Tofandel** [comment]
IMO the calculation for the position of the dropdown is invalid and buggy.. It should find the first parent of the element to which it is attached and calculate it's position relative to that element..
Right now it wrongly assumes the v-app should be at a position of 0,0 on the page at all time, so if the v-app is contained in something it will calculate the position relative to the document instead of the v-app, so you will have a double offset effect and the dropdown will be far far away from where it should be..

**Comment by dstearle** [comment]
@Tofandel so if I understoof your post correctly then that might be related to my current problem.

I created a calendar plugin using Vue and Vuetify, when implemented into the wordpress site everything except the v-menu popup works fine. I have it so that when you click on an event a popup should open below it to give more details. This works fine in the dev environment for the plugin itself but in the dev environment for the wordpress site the popups appear way below where the calendar is and I believe it is because it is getting the position of the calendar before it is rendered on the screen. So am I assuming there is no way to fix this currently?

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/issues/7703
