### ISSUE TITLE
[Feature Request] Expose the click-outside directive as a public API

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#4654]
### Problem to solve
The click-outside directive allows us to detect when a user has clicked outside a specified element. By detecting this, we can trigger important events. Vuetify has several components that use the click-outside directive including v-dialog, v-select, v-speed-dial, v-menu, v-slider and v-navigation-drawer. However this directive is not available as part of Vuetify's API. There are third-party directives such as ndelvalle's popular v-click-outside directive which can get the job done, but it's recently been discovered that using it with Vuetify creates a conflict which can break Vuetify's own built-in click-outside directive.

### Proposed solution
By exposing the built-in click-outside directive as a public API, users can create custom components with this directive without having to roll-their-own or use a third-party directive to achieve the same result.

**Comment by Kasheftin** [comment]
I would like this to be implemented. There're external solutions like vue-click-outside but they do not work in some particular cases. Usually they bind click listener to the root document, and this does not work when some intermediate container has click listener with stopPropagation. 

For example, I have custom select component (my own, not v-select) that has to collapse on click outside. If I place it into v-dialog, it stops working because the last uses stopPropagation. 

The click-outside directive from vuetify works differently. It binds click on the capture phase and uses getBoundingClientRect to determine if the click was outside of the target element. Probably it's not so fast, but it works well with stopPropagation. I have not met this approach before, was it you idea, @johnleider ?

**Comment by KaelWD** [comment]
> I have not met this approach before, was it you idea

#1932

**Comment by Kasheftin** [comment]
I've read the code and got some understanding about why click-outside directive was not exported. It calls some expensive methods, that's why there're some conditional optimizations inside. That's why if we just import the directive itself from the source and call it like `<div v-click-outside="someAction">`, it will not work. 

I created a simple wrapper with the v-select component as an example:

    export default {
      props: {
        focused: Boolean
      },
      render (createElement) {
        return createElement('div', {
          directives: this.directives,
          attrs: this.$attrs,
          props: this.$props,
          on: this.$listeners
        }, this.$slots.default)
      },
      computed: {
        directives () {
          return this.focused ? [{
            name: 'click-outside',
            value: this.blur,
            args: {
              closeConditional: this.closeConditional
            }
          }] : undefined
        }
      },
      methods: {
        closeConditional (e) {
          return (
            !!this.$el &&
            !this.$el.contains(e.target) &&
            e.target !== this.$el
          )
        },
        blur () {
          this.$emit('click-outside')
        }
      }
    }

Assume there's some component that wants to use click outside, and it has some `focused` flag (it might be an opened menu, modal or whatever). Then we can wrap the component like this:

    <click-outside :focused="focused" @click-outside="handler">...</click-outside>

This is not perfect, it creates a div wrapper, and it's not tested, but it seems to work in my case.

**Comment by johnleider** [comment]
If you would be willing to champion the change, come msg me in the community. https://community.vuetifyjs.com

**Comment by fjoalland** [comment]
Did you implement a new feature for this issue? It is a problem when we manipulate props.

**Comment by KaelWD** [comment]
It should be possible with Vue 2.6 if you implement closeConditional but the directive is using `binding.args` instead of `binding.arg` so it still only works with render functions: https://codepen.io/kaelwd/pen/oNXdwYV?editors=1010

**Comment by johnleider** [comment]
resolved in #4654

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
