### ISSUE TITLE
Does data table support transition -group ?

### ISSUE THREAD

**Issue by ouraios** [vuetifyjs/vuetify#468]
All is in my title, does data table support transitio-group effect ?
If yes how can i do it ?

**Comment by johnleider** [comment]
It does not. During development it was a bit jarring so I opted to not support it.

**Comment by andrepuggelli** [comment]
Is implementation expected for this issue?

**Comment by andrepuggelli** [comment]
How can i add animation adding items to a data table?

**Comment by inad9300** [comment]
Please, add support for transitions when data rows are added/moved/removed. In my case, the data table is updated based on WebSocket messages, and it is quite important from a UX perspective to see the new entries coming and going rather than having all the values changed at once. Currently, one has to redefined the whole table body for this, losing an awful lot of the benefits offered by the data table.

**Comment by impowski** [comment]
Please, implement this one, it would be very useful for us too. I support @inad9300 on this issue, right now adding elements at the top of table looks very clunky. @johnleider if it's possible to reopen this one it would be really nice.
