### ISSUE TITLE
[Bug Report] vee-validate "changed" flag not working correctly on v-text-field

### ISSUE THREAD

**Issue by bragma** [vuetifyjs/vuetify#4704]
### Versions and Environment
**Vuetify:** 1.1.8
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
The codepen shows a v-text-field and standard html input field. Change the value on both, as an example with the up key and look at the "changed" vee-validate field shown below. Then set the original value back with the down key and look again at the "changed" value

### Expected Behavior
Changed should show "true" on key up, then "false" on key down. In general, it should show changed as true if the value if edited to something different than the original value.

### Actual Behavior
On the v-text-field, it stays "false" on first edit, then changes to "true" (see the steps suggested above). Both are incorrect. In general, the changed field value is incorrect.

### Reproduction Link
[https://codepen.io/bragma/pen/OwgNgO](https://codepen.io/bragma/pen/OwgNgO)

### Other comments
Tested with vee-validate 2.0.9 and 2.1.0-beta6

**Comment by bragma** [comment]
Hi, I'm not sure how to help here. Do you think it's a vuetify or a vee-validate issue?

**Comment by nekosaur** [comment]
I think we'll have to call this as a not-bug. The issue is that the initial value of `value1` is a number, which means that for vee-validate, it's internal `initialValue` will be a number. But since vue does not support v-model modifiers on custom components (so we can't use `.number` as on the vanilla input), that means any future update to the v-model will be a string. So when vee-validate does the changed check (`initialValue !== value`) it will always return true because one is a number and one is a string.

One workaround is to set the initial value of the v-model variable to a string (https://codepen.io/anon/pen/OebMBJ).

**Comment by KaelWD** [comment]
> vue does not support v-model modifiers on custom components

Incorrect. Vue does not support `.lazy` or custom modifiers, but `.number` works fine and the behaviour here is identical to the native input.
