### ISSUE TITLE
[Bug Report] v-tabs in a v-stepper has no pagination buttons

### ISSUE THREAD

**Issue by napnapnapnap** [vuetifyjs/vuetify#4710]
**Versions and Environment**

Vuetify: 1.1.10
Vue: 2.5.16
Browsers: Google Chrome 68.0.3440.68, Firefox 61.0.1
OS: Windows 10 1803

**Previously worked in:**

Maybe never

**Steps to reproduce**

I am attaching a CodePen.

- Create a stepper with atleast two steps
- Place a VTabs that should have pagination buttons in the second step
- Switch to the second step and you will see no buttons on the paginated VTabs.

**Expected Behavior**

We should see the pagination buttons right away when we switch to the second step

**Actual Behavior**

The buttons won't appear when you go to Step 2 unlesss the VTabs is on the first step

**Reproduction Link**

https://codepen.io/anon/pen/qyjgOe?editors=1011

**Additional Comments:**

The pagination buttons will apear if the VTabs is on the first step or if you resize the browser window.

**Comment by johnleider** [comment]
You will need to conditionally render your tabs in order to achieve this. Show arrows will ultimately only work if the container is overflowing. When it's initially rendered, it is hidden, and has no dimensions and doesn't think it is overflowed. Once you select the next step, it renders but there is no way for us to know when this takes place and when to trigger another check.

You can solve this in a few ways, the easiest being assigning a **key** to `v-tabs` that changes with the index model, or with **v-if="index === '2'"**.
