### ISSUE TITLE
[Bug Report] V-divider in production mode

### ISSUE THREAD

**Issue by kyusupov33** [vuetifyjs/vuetify#4744]
### Versions and Environment
Vuetify: 1.0.19
Vue: 2.5.16
Browsers: Chrome
OS: MacOs, Windows

### Additional Comments:
In production mode v-divider have border: none
![image](https://user-images.githubusercontent.com/29026701/43367606-62818ad4-9358-11e8-954e-b9b7f9134de0.png)

**Comment by AlexSHoffman** [comment]
@kyusupov33 where did you find this code? If you go to the [docs page](https://vuetifyjs.com/en/components/dividers#example-vertical) and inspect a `v-divider` element you will see the following code:

```
.v-divider {
    display: block;
    flex: 1 1 0px;
    max-width: 100%;
    height: 0px;
    max-height: 0px;
    border: solid;
    border-width: thin 0 0 0;
}
```

**Comment by kyusupov33** [comment]
I did not quite understand how this happens, but as I wrote, the problem appears in the production mode. Everything is fine in the developer.

**Comment by AlexSHoffman** [comment]
@kyusupov33 well, I have no idea what the "production mode" is because in "production" (on the official website) it has the code above

**Comment by gtalarico** [comment]
I don't have enough info to create the issue/repro yet but I am having what might be a similar problem. 
I will leave this additional info here in case someone else runs into a similar, but otherwise not action necessary.

I don't know the cause or if this is the issue at all, but:
`v-divider` shows fine in development production on Windows + Chrome OS, 
but it's invisible on my Mac OS + Chrome/Safari

I have cleared cache and deployed multiple versions, 
and the issue persists every time (v-divider is invisible on Mac).

Mac Os + Chrome Screenshot:
![image](https://user-images.githubusercontent.com/9513968/43530453-9a699840-957b-11e8-8df7-4bbecd75f2e1.png)

On Windows:
![image](https://user-images.githubusercontent.com/9513968/43530813-7176ab7a-957c-11e8-957c-c6892f38d882.png)

Here is the link. Curious if others can see the v-divider or not.
http://apidocs.co/#/apps/revit/2019/d4648875-d41a-783b-d5f4-638df39ee413.htm

**Comment by KaelWD** [comment]
Probably something to do with cssnano, not vuetify. This is what's distributed with 1.0.8:
![image](https://user-images.githubusercontent.com/16421948/43533442-26960908-95f8-11e8-804a-c65119cdac47.png)

**Comment by AlexSHoffman** [comment]
@gtalarico try this, in your main component in `<style>` add the following rule:

```
.v-divider {
    display: block !important;
    flex: 1 1 0px !important;
    max-width: 100% !important;
    border: solid !important;
    border-width: thin 0 0 0 !important;
}

```

**Comment by gtalarico** [comment]
Note the results on this screenshot, the exact same deployment side by side in development and production:

![image](https://user-images.githubusercontent.com/9513968/43618506-ca13d1ca-9696-11e8-843f-9774ebba1c53.png)

# Proposed Solution

Your code made the `v-divider` but as thick black line. 
This line only fixes for me:
```
.v-divider
    border-style: solid !important
```

### PS

If `border-style: solid !important is removed` the border `v-divider` goes away.
![image](https://user-images.githubusercontent.com/9513968/43618535-e87033e8-9696-11e8-9fe7-c25377e3d8d0.png)

**Comment by weeuwee** [comment]
For some reason, i am getting the exact same problem.
