### ISSUE TITLE
[Feature Request] Create Rate Component

### ISSUE THREAD

**Issue by marciojalber** [vuetifyjs/vuetify#4766]
### Problem to solve
Choose a value from a scale of values

### Proposed solution
Simplify evaluation value information

**Comment by AlexSHoffman** [comment]
@marciojalber another component just for a few lines of code? You can easily create it yourself using the existing Vuetify components:

Here'a an example for you: 
https://codepen.io/anon/pen/NByzyW?editors=1010

**Comment by AlexSHoffman** [comment]
@marciojalber another component just for a few lines of code? It's literally 5 lines of code.

 I don't think anyone will bother creating it because it's not a universal component and it's really easy to create it yourself out of the existing universal components like `v-radio`.

Here'a an example for you:
https://codepen.io/anon/pen/NByzyW?editors=1010

**Comment by KaelWD** [comment]
Duplicate of #3665
