### ISSUE TITLE
[Bug Report] Transitions on v-tab-item are not working properly

### ISSUE THREAD

**Issue by jlynde** [vuetifyjs/vuetify#4782]
### Versions and Environment
**Vuetify:** 1.1.9
**Vue:** 2.5.17
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 7

### Steps to reproduce
Open the reproduction link provided and switch between tabs.  Notice the behavior is not what is expected.

### Expected Behavior
Code says to use scale-transition when switching between tabs.

### Actual Behavior
When switching to a tab to the right the scale-transition does not work as expected.  When switching to a tab to the left the default transition is executed (not the scale-transition).

### Reproduction Link
[https://codesandbox.io/s/vy7xx7m287](https://codesandbox.io/s/vy7xx7m287)

**Comment by KaelWD** [comment]
- `transition` only controls one direction, you need `reverse-transition` too
 - `scale-transition` is not set up to be used with this mode, you need to add `position: absolute`
 - your custom css wasn't being applied because you spelled a class wrong, an weren't using deep selectors

https://codesandbox.io/s/w0r9po19kw
