### ISSUE TITLE
[Bug Report] FAB Icons Lost Center Alignment Following #7abf1aa

### ISSUE THREAD

**Issue by hdimmig16** [vuetifyjs/vuetify#4825]
### Versions and Environment
**Vuetify:** 1.1.10
**Last working version:** 1.1.9
**Vue:** 2.5.16
**Browsers:** Chrome 70.0.3508.0
**OS:** Mac OS 10.13.6

### Steps to reproduce
See [this](https://vuetifyjs.com/en/components/floating-action-buttons#example-speed-dial) and other FAB examples from the docs. 

### Expected Behavior
FAB icons to be centered within the button

### Actual Behavior
Icons are at the bottom

### Reproduction Link
[https://codepen.io/anon/pen/pZQbbO](https://codepen.io/anon/pen/pZQbbO)

### Other comments
Commit [#7abf1aa](https://github.com/vuetifyjs/vuetify/commit/7abf1aa1cea8dad76543f3d554c1d702e81f70cf) removed `height: inherit` from button styling, which previously centered them.

**Comment by praveenpuglia** [comment]
Working on this bug has led me to discover a quirk in CSS. 
https://codepen.io/praveenpuglia/pen/jpXrKp

Buttons are special elements in which even if the button has `display: flex` it still creates a block formatting context instead of a flex one. To put it simply, it just ignores that `display: flex`.

More on this here - https://twitter.com/praveenpuglia/status/1027721484871979008
