### ISSUE TITLE
[Bug Report] Input components (like v-checkbox, v-switch, ...) don't stay in sync when using v-model

### ISSUE THREAD

**Issue by lukas-tr** [vuetifyjs/vuetify#4829]
### Versions and Environment
Vuetify: 1.1.10
Vue: 2.5.17
Browsers: Chrome 68.0.3440.84 (Official Build) (64-bit)
OS: Windows 10 Home 10.0.17134 Build 17134

### Previously worked in:
Vuetify: /
Vue: /

### Steps to reproduce

Click on every checkbox a few times.

### Expected Behavior

I expect both checkboxes to have the same state after every click (since both receive the same value from v-model).

### Actual Behavior

The state of the second checkbox changes even though `computedCheckbox` doesn't change. Other input components have this bug too.

### Reproduction Link

https://codepen.io/lukas-tr/pen/BPGEoO?editors=1010

---

### Additional Comments:
In case some people want the checkbox or other input components to be independent, add a `lazy` prop.

**Comment by praveenpuglia** [comment]
Because they don't actually change the value of `checkbox` property. Place `{{checkbox}}` in your code.. say after `<v-container>` to print its value.

### Why? 
Because the setter does absolutely nothing with the updated value. If you had somehow did something like 
```js
 set(val){
       this.checkbox = val;
 }
```
It would then keep all of them in sync.

In general, you shouldn't be changing data properties inside computed values. That just leads to confusion.
