### ISSUE TITLE
Text-field hint trigger transition when changed dynamically

### ISSUE THREAD

**Issue by Kleemer** [vuetifyjs/vuetify#4880]
### Versions and Environment
Vuetify: 1.1.12
https://codepen.io/Kleemer/pen/wxLavr

### Previously worked in:
Vuetify: 1.0.18
https://codepen.io/Kleemer/pen/qyzdRO

### Steps to reproduce

Just type in the text field.

### Expected Behavior

The hint is dynamically changing, but the transition is triggered at every change, the hint is "dancing".

### Actual Behavior

The transition probably shouldn't be triggered here.

**Comment by travbus** [comment]
I'm getting this same issue in version 1.4.. Thats using code copied and pasted from the docs website. Going to try purging my current project of everything but Vuetify and see if problem still exists  
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18337819/52300570-6970e780-2945-11e9-8c00-ad551b91bf7c.gif)

**Comment by Tower450** [comment]
i hit the same issue here.

**Comment by travbus** [comment]
It is upgrade to 1.4.8

**Comment by Tower450** [comment]
still got the issue maybe it's on my side i'll let you know.

**Comment by benzittlau** [comment]
Also still seeing this issue, I don't believe this is resolved.

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.

**Comment by benzittlau** [comment]
Understand that policy, but would like to add a quick additinal comment as we were able to resolve it.  

We were continuing to see the issue, but were able to resolve it by upgrading *Vue* from 2.5.18 to 2.5.22.  I'm not sure what the issue was that was resolved by that update, but it appears that there might be some couplings between certain Vuetify and Vue versions that will show the issue, but on the most recent versions of each the issue appears to be resolved.
