### ISSUE TITLE
Datepicker scroll broken on Firefox 

### ISSUE THREAD

**Issue by leonardoarroyo** [vuetifyjs/vuetify#492]
### Steps to reproduce
Scroll up or down in datepicker window(inside menu or dialog).

### Versions
Vuetify: v0.11.1(tested inside vuetify docs)
Firefox: 50.0.2

### What is expected ?
Months should slide backward and forward depending on direction scrolled.

### What is actually happening ?
Months always slide backward in time, never forward.

### Reproduction Link
Can be reproduced at Vuetify docs.
https://vuetifyjs.com/components/pickers

**Comment by smares** [comment]
Is it supposed to scroll backwards in time when you scroll down, and in the future when you scroll up? Seems counter-intuitive to me.

**Comment by johnleider** [comment]
Could you elaborate as to why you find it counter intuitive?

**Comment by smares** [comment]
Because I am used to reading content top to bottom and for me, things that happen now are written at the bottom of the page, thus, if you want to go back in time, you scroll up. I never understood the concept of that natural scrolling direction for mice and touchpads Apple introduced to mimic the movement you do on a smartphone or tablet.

**Comment by johnleider** [comment]
That is an interesting point of view. I personally do not share the same
opinion but I would be interested in hearing from others on the matter.

**Comment by smares** [comment]
One more thing. :) If you click on the year, a standard list with years is displayed with the previous years top and the next years bottom. Since that list uses the default system scrolling, which in my case is "use the mousewheel to scroll the bar" and not the natural scrolling "use the mousewheel to scroll the content", I have to scroll up to get to the previous years. Then back in the month view, I have to scroll down to get to the previous months.

**Comment by johnleider** [comment]
I agree on the year points and is something I will do.
