### ISSUE TITLE
[Feature Request] v-select filter with sorting

### ISSUE THREAD

**Issue by 0vvland** [vuetifyjs/vuetify#4936]
### Problem to solve
It's allowing sort items based on filter's data.

### Proposed solution
v-select filter property function return -1 or index. -1 for exclude item, index for sorting.
It's possible to made in "user land" over computed, but here it'll be better.

**Comment by johnleider** [comment]
Can you provide some additional information, maybe an example showing how you are getting around this not being in Vuetify.

**Comment by 0vvland** [comment]
Well, I have a list of languages and search trough them by input. And will be good to sort items by index of found letters in values. Like input "en" and English will be on the first place, because of "English".indexOf("en")===1
I cannot getting around this in Vuetify. I can make items is computed. But this exclude custom sorting in input. It was better for me to left it not sorted.

**Comment by KaelWD** [comment]
> But this exclude custom filter in input

Use `:search-input.sync` and `no-filter` to do the filtering and sorting manually. 

@jacekkarczmarczyk data table's filter is different, `custom-filter` iterates over all the items then calls `filter` on each matching header. We've talked about removing that complexity anyway as it's pretty unclear how it all ties together.

**Comment by andywgarcia** [comment]
> Use `:search-input.sync` and `no-filter` to do the filtering and sorting manually.


@KaelWD I came across this, and I am having issues with using this technique when using `cache-items` in order to simply just sort the items in the dropdown. I am wanting to fuzzy sort the items so that the closest match is on the top of the dropdown. It doesn't look like all of the items are getting sorted, particularly after they get cached

I see that `v-select` has a `value-comparator` prop, and it seems like that is involved with sorting, but I can't figure out how to use it even after looking at the code in the `moreInfo` section. Is this what I need in order to sort the dropdown items?

**Comment by andywgarcia** [comment]
After doing some more investigation, it looks like the internal cache of the items always appears first in the list, so there is no sorting algorithm that can be applied to this other than the one that is defaulted in the v-select. If we could give a sorting algorithm to be used post filtering on all items in the list (event the cached items) that would be ideal.

If the value-comparator prop is what is supposed to be used for this (and I guess even if it is not), can we get some more docs on what it is and how to use it?

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
