### ISSUE TITLE
[Bug Report] IE11 error on build: Symbol is not defined

### ISSUE THREAD

**Issue by ziaxdk** [vuetifyjs/vuetify#4997]
### Versions and Environment
**Vuetify:** 1.2.1
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Windows 10

### Steps to reproduce
npm run build
serve the dist folder

### Expected Behavior
To work according to doc

### Actual Behavior
Symbol is not defined

### Reproduction Link
[https://github.com/ziaxdk/ie11-vuetify](https://github.com/ziaxdk/ie11-vuetify)

### Other comments
Scaffolded a new vue project with vue cli service (@vue/cli v3.01)

**Comment by jacekkarczmarczyk** [comment]
You need to choose to use babel/polyfill during scaffolding
`? Use babel/polyfill? (Y/n)`

If you didn't do this you need to add polyfill manually https://vuetifyjs.com/en/getting-started/quick-start#ie11-support
If you did but polyfill wasn't installed then that's the bug with vuetify plugin and it should be reported in the [plugin repository](https://github.com/vuetifyjs/vue-cli-plugin-vuetify)

**Comment by ziaxdk** [comment]
But according to documentation it should be taken care of when using vue
cli service 3?

Kenneth

**Comment by KaelWD** [comment]
Only if you follow the rest of the guide, it looks like you've just installed vuetify on a base vue-cli project.

**Comment by ziaxdk** [comment]
OK, thats it. Thanks.

Great product

**Comment by Aymkdn** [comment]
Hi.

Adding my 2 cents here, because it looks like a bug (or an error in documentation).

I tried to install a fresh new Vue app : 
```
vue create tests-vuetify
cd tests-vuetify
vue add vuetify
```

I used the "custom" prompt from the Vuetify plugin, but I left all options by default.

Then I built the project (`npm run build`) without changing anything and when I try to open it in IE11 I got the `Symbol is not defined` error.

The document is confusing because it says : 
> If you are using vue-cli-3, this is done automatically for you. Otherwise [...]

I'm using vue-cli-3. It's a brand-new untouched project. So why IE11 doesn't not work ? What is missing ?

**Comment by johnleider** [comment]
You should post a bug on that repository @Aymkdn https://github.com/vuetifyjs/vue-cli-plugin-vuetify

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
