### ISSUE TITLE
Firefox: progress linear / circular cpu hog

### ISSUE THREAD

**Issue by ellis2323** [vuetifyjs/vuetify#5190]
When i use progress component, one core jumps at 70%. I have the same behaviour on mac os x or on linux.

OS X 10.13.6: firefox 62.0.2
Linux ubuntu 18.04 / Firefox 62.0.2 (64 bits)

To reproduce just go with Firefox
[Official doc](https://vuetifyjs.com/en/components/progress)

On chrome, the cpu usage is not that high.

**Comment by ellis2323** [comment]
It seems a firefox problem with css animations.

Same problem on this page: https://projects.lukehaas.me/css-loaders/

**Comment by johnleider** [comment]
You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).
In order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 7 days before being closed.

Thank you for your contribution and interest in improving Vuetify.
