### ISSUE TITLE
[Feature Request] custom vertical & horizontal scrollbars

### ISSUE THREAD

**Issue by musasoftlabx** [vuetifyjs/vuetify#5196]
### Problem to solve
- Does away with the native browser scrollbars which take up some container space and do not match the site's theme.
- Prevents the need to import 3rd party plugins

### Proposed solution
- Should have an option to change colors to match the current theme
- Should have a watch in order to re-initialize when content in the container changes.

**Comment by JojoMig** [comment]
Hi, for general use I've replaced the native scrollbar with the package **[Vuebar](https://github.com/DominikSerafin/vuebar)**  from **[Dominik Serafin](https://github.com/DominikSerafin)**, which uses a  Vue directive to wrap the content you want to scroll, pretty neat for most Vuetify components were you can add your own literals string templates as content like v-dialog etc... 

Some Vuetify components tho can't have the native scrollbar themed like the v-combobox or v-select for instance due to theirs DOM element hierarchy..

Its a theoretical very rough idea, but since **[Vuebar has some Customization Options](http://github.serafin.io/vuebar/#options)**, its would be nice to implement a very similar concept for instance on the v-combobox return of the list of items generator were either the genlist return would be a wrap of the **[Vuebar Markup Wrapper](http://github.serafin.io/vuebar/#usage)**, or to Wrap the genlist return.. 

Cheers

**Comment by fnoop** [comment]
Will this work to wrap a v-card (or specifically a v-list/v-list-group within a v-card)?  I can't for the life of me get it to work.  Some sample markup here would be really helpful :)

**Comment by karambaq** [comment]
Any updates on this?

**Comment by James-Hudson3010** [comment]
Another similar implementation which may help guide development of this is https://quasar.dev/vue-components/scroll-area

**Comment by KaelWD** [comment]
> change colors to match the current theme

#14039
