### ISSUE TITLE
[Bug Report] v-pagination trigger v-form submit

### ISSUE THREAD

**Issue by materight** [vuetifyjs/vuetify#5212]
### Versions and Environment
Vuetify: 1.2.6
Vue: 2.5.17
Browsers: Chrome69
OS: Windows 10

### Steps to reproduce

Use the v-pagination component inside a v-form or form and change page

### Expected Behavior

It should not trigger form submit

### Reproduction Link

https://codepen.io/materight/pen/YJwgZy

**Comment by SnakeyHips** [comment]
Okay so after some digging, the buttons used for the pagination component use the standard HTML <button> tag rather than <v-btn>. The standard HTML button object's event defaults to submit "default for all browsers, except Internet Explorer" [(from w3schools)](https://www.w3schools.com/jsref/prop_pushbutton_type.asp) and so that's the case for the buttons used within the pagination component since their type isn't defined [as seen here.](https://i.imgur.com/wXZWXYf.jpg) You can test this by putting a standard button within a form without a type or click function attached to it and it'll submit the form which is the same as your issue. 

I still think you'd be able to achieve what you want with the pagination component outside of the form but for now it seems the buttons within will keep firing off the default submit event unless you're able to somehow override this. Maybe this can get looked into by the dev team and maybe they can change the type for these buttons to "button" instead?

**Comment by Materight** [comment]
You are right, thank you! I'll try to fix this and make a pull request.

**Comment by KaelWD** [comment]
Fixed in v1.3.3 with #5229
