### ISSUE TITLE
Dialog close if click inside button 

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#522]
### Steps to reproduce
1. Create Dialog with dynamic list inside
2. Delete one element

### What is actually happening ?
When I modify list array then dialog close itself. 

### Reproduction Link
https://jsfiddle.net/kozack/13cczxct/3/

The exception does not occur if
* Add `persistent` to `v-dialog` (https://jsfiddle.net/kozack/13cczxct/5/)
* Not modify list on click (https://jsfiddle.net/kozack/13cczxct/4/)

**Comment by johnleider** [comment]
So after extensive testing, I have determined that this is not a bug.

One of the checks that is performed when a click in the body happens is the click-outside directive.  The element checks to see if the click originated from an element inside of it. If it finds one, it stops propagation. In the example provided, you have a computed property bound to a v-for. This computed property is reactive and is watching the array of toDeletePages. When the button is clicked, the array is changed which causes the v-for loop to re-evaluate and display the results. The issue however, is when the re-evaluation occurs, Vue is re-rendering the components, which is removed them from the ```.contains``` check. Since the button is being rendered conditionally, it leaves the DOM before the check if it exists within the dialog occurs.

I can confirm this by not being able to verify the elements location anywhere within the body from within Vue's virtual dom. If this same logic is checked within the console, it works properly.

You can verify this within your codepen by wrapping your push into ```toDeletePages``` in a setTimeout(.., 0). This will give the click to propagate before the comparison checks happen, leaving the dialog open as expected.
