### ISSUE TITLE
Wrong v-date-picker width in menu with full-width

### ISSUE THREAD

**Issue by fotonmoton** [vuetifyjs/vuetify#5220]
### Versions and Environment
Vuetify: 1.2.1
Vue: 2.5.17
Browsers: Google Chrome 68.0.3440.106
OS: Mac OS 10.13.3 (17D47)

### Steps to reproduce

put v-date-picker inside v-menu with full width

### Expected Behavior

v-date-picker should take minimum required space or expand to parent width.
### Actual Behavior

v-date-picker has weird shadow 
### Reproduction Link

https://codepen.io/Fotonmoton/pen/wYWBWy
---

**Comment by jacekkarczmarczyk** [comment]
If you want v-date-picker to expand to parent width you need to apply `full-width` prop to v-date-picker. However if you do it the menu width gets bigger so you need to add max-width prop to v-menu to constraint it: https://codepen.io/anon/pen/MPeoLB
Maybe setting the max width should be done automatically by v-menu? @vuetifyjs/dev-team thoughts?

**Comment by fotonmoton** [comment]
@jacekkarczmarczyk thanks for solution! I went another way and add min-width constraint to menu as documentation [suggest](https://vuetifyjs.com/en/components/date-pickers#examples) (date picker in dialog menu). But I don't understand why this is working. When I specify `full-width` prop for `v-menu` element why menu doesn't expand to parent width but occupy more width than parent `v-flex` element? And why `min-width` but not `max-width` prop solve this issue? I'm little bit confused and didn't find explanation in docs.

**Comment by jacekkarczmarczyk** [comment]
I'm of the opinion that picker should behave differently when placed in menu, they should be independent components, so the workaround above closes the issue.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by shanna** [comment]
Wasn't sure if I should bump this old ticket or open a new one but this doesn't solve the v-date-picker full-width issue if the v-menu itself has a full-width or the date-picker is inside a v-dialog.

Something like `v-dialog > v-card > ... > v-menu > v-date-picker` for example the date picker will ignore all the ancestor component widths including v-menu and v-dialog.

**Comment by tylerjames** [comment]
It seems like this `min-width` (apparently max-width` works too) workaround shouldn't really close the issue. Showing a date picker with a menu seems to be standard behaviour, but should we really have to hardcode a width value to make it work properly? 

What happens when they change the standard width of the date picker? Update the hardcoded values?

**Comment by jacekkarczmarczyk** [comment]
> What happens when they change the standard width of the date picker? Update the hardcoded values?

That's a valid point, not sure atm what would be the proper fix, but here is workaround (note that this codepen uses vuetify 2.0, but it should be same for 1.X)

https://codepen.io/anon/pen/EzGaQg?editors=1100

> And why min-width but not max-width prop solve this issue?

Because menu content by default gets inline style `min-width: WIDTH_OF_THE_ACTIVATOR_OR_SOMETHING`, and `min-width` prop changes it

**Comment by jacekkarczmarczyk** [comment]
lol bot doesn't like the issue

**Comment by jacekkarczmarczyk** [comment]
v1.5 reached end of life on July 31st, 2020 and is no longer actively maintained
