### ISSUE TITLE
DataTable should reset to first page if the first visible item is >= total items after data changes.

### ISSUE THREAD

**Issue by Flamenco** [vuetifyjs/vuetify#5312]
If I have 5 pages of data, and the user scrolls to the last page, and then applies a filter to her data set, the DataTable displays no data and shows a completely messed up page number, even though there is data. The use can still page back to the first page and see the data. There is no way it can be justified that this behavior is correct under any circumstance.

**What Needs To Be Fixed**
The component should ALWAYS reset to first page if the current page start item is beyond the available rows.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/819940/46868637-00de8780-cdf7-11e8-8f08-0ac24a0f485f.png">

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by Flamenco** [comment]
Please just fix the issue. I don’t have time to jump through your hoops, and you should be thanking me for finding problems with your product.

**Comment by bryanjglass** [comment]
+1  I'm experiencing the same issue as @Flamenco and when searching through the issues I keep stumbling upon closed issues because they don't meet the guidelines :/

**Comment by nekosaur** [comment]
Not to be flippant, because we do appreciate anyone reporting issues, but

1. It really doesn't take very long to create an issue using the available template, or https://issues.vuetifyjs.com
2. If previous issues have been closed due to insufficient information, then perhaps that's a clue that you should try to follow the guidelines?

I understand that your time is valuable, but so is _ours_. Which is why we've tried to make creating an issue as easy and painless as possible, while giving us all the necessary information we might need.

That being said, I just created https://github.com/vuetifyjs/vuetify/issues/5426 with a reproduction of part of your issue. In mine the `x of x` text is not incorrect, only the page next/prev buttons. But since you did not provide a reproduction I've no idea the exact conditions in which that happens.

**Comment by Flamenco** [comment]
@nekosaur perhaps your time is valuable, but then again, perhaps you get paid for it.  Perhaps my time is way more valuable than you give me credit for   I work with hundreds of open source projects every week;  I have spent entire seasons donating my time to some of them.  Others I don't bother contributing to at all.

In the case of Vuetify, I have issues with your company's arrogance, stubbornness, and general culture;  I wouldn't follow your nitpicky guidelines even if you paid me.  Furthermore,  If I took the time to report all the bugs and aesthetic issues I have with Vuetify, the Vuetify website, and the way you treat your community, It would take me weeks to report, and even more if I followed your guidelines.  In the case of Vuetify, we have 100+ patches/adapter classes to solve bugs and crappy API that we would never even consider submitting to your team.  We would rather merge them after every release in than lock horns at GitHub while trying to share them with you and others.

So post rant, let me state specifically what I find insulting:  It should not have taken 13 days for a response.  You should have thanked me for reporting the bug, and taking the time to describe it and submit a screenshot.  You should never have _closed_ this issue.  There should have been a discussion if this was a regression or not.  Also a discussion about the expected behavior.  Then add a discussion about the best ways to technically solve it. Separately, someone with time on their hands could have posted a working example after you marked this issue as `needs reproduction`.  And the community could have acted as a team, instead of your company expecting us to do the work for you.

This thread actually makes me want to puke when I think about how Vuetify treats developers.   IMO you should not expect the contributing community to behave like an employee.

**Comment by johnleider** [comment]
> perhaps your time is valuable, but then again, perhaps you get paid for it. Perhaps my time is way more valuable than you give me credit for I work with hundreds of open source projects every week; I have spent entire seasons donating my time to some of them. Others I don't bother contributing to at all.

If this is how you contribute to them, I don't think I would want your help.

> In the case of Vuetify, I have issues with your company's arrogance, stubbornness, and general culture;

I am the only employee of Vuetify. But if you are referencing specifically to the people who have titles, the only stubborn person is @KaelWD and we try to keep him away from people

> It should not have taken 13 days for a response

Out of everything you said, oddly enough, this is the most shocking. No one owes you anything and this is the worst attitude anyone could have towards something that is free, seriously..

> You should never have closed this issue

A large majority of the time the issue resides within that developer's application. The reason why we ask for a reproduction is that it verifies that bug persists outside of your specific environment.

> And the community could have acted as a team, instead of your company expecting us to do the work for you.

I'll remind you again that this is OSS, we are not a company with a product. We try our absolute best to observe what other successful OSS projects do in order to maximize our effectiveness of clearing out bugs and adding new features.

The _only_ way that this works is if we **do** rely on the community to report bugs and help with resolution.

> This thread actually makes me want to puke when I think about how Vuetify treats developers. IMO you should not expect the contributing community to behave like an employee.

This is basically covered by the above, but no one is expecting anyone to behave like an employee. We are expecting people to follow the guidelines we have put in place so that this process goes as smooth as possible.

I carry the belief that we are all passionate developers and that we get heated when things don't work as expected. Our goal is always to make the best possible experience for users. People sacrifice their personal time to improve something that provides an immense benefit for developers all around the world and you should be more respectful of that.

With all that being said, this has to be the most entitled post I think I have ever seen, and I've seen a lot. This is not criticism or an effort to help improve a process, it is simply a bitch fest for you that ultimately insults the hard work of everyone before you and serves absolutely no purpose.

I will take time today to review our language and process for developers reporting issues, requesting new features and receiving help.

**Comment by Flamenco** [comment]
@johnleider Thank you for responding.  FYI I really like working with Vuetify, but I think you have some issues that are holding back the project.  I assumed that with your merchandise sales, patreons, ad-clicks, themes, etc., you would be able to dish out some $$$ to other developers to support and maintain your project; That is who I referred to as `employees`.

> If this is how you contribute to them, I don't think I would want your help

Regardless of how much of an AHOLE I am or may seem, a bug is a bug, and it would be INSANE to ignore help for that reason...

I feel that with many open source projects, the project managers expect way too much from contributors.  This can range from asking to write code to reproduce the problem when it is very easy to describe in a short text paragraph, to insisting on detailed documentation for PRs, to requiring test cases that require the submitter to learn a silly amount of extra infrastructure.

Please forgive me for appearing _entitled_, but given my abilities and accomplishments, I will take:
> With all that being said, this has to be the most entitled post I think I have ever seen

as a sentiment to my confidence and passion :)  

**IMO, it is having too many restrictions for contributions that is `acting entitled`.**

With that being said, please take my comments as a `tree shaking`.  I am not trying to insult you or have a `bitch fest`; I am being very direct as to how I feel, for I selfishly want Vuetify to be better and more agile;  I hope my unrestrained opinion will make you a bit more sensitive on the way you interact on GitHub.  I do respect many of the talented contributors involved, and I actually _want to send you a big fat check_ in support, but my experiences thus far have pushed me away.

So in closing, I hope you are still willing to accept my bug reports and feature requests, and can find a way overlook my snobby, arrogant, and self-entitled tone, while simply take it as `constructive criticism`.

**Comment by johnleider** [comment]
We do receive funds from the above mentioned areas, but the honest truth is it barely covers the cost of a junior dev (by avg salary in the US). I tried to cover devs out of pocket for almost a year and could not afford it anymore. We are working on ways to alleviate this, but we aren't there yet.

**Comment by cb109** [comment]
Quick, before he changes his mind about those sweet dollars :money_with_wings: ! 

My 2 cents: For me it's simply about where to spend time on: Dealing with crap like this or with actual helpful feedback. This behaviour is pure cancer and in no way justified and it drains too much time and energy.

**Comment by johnleider** [comment]
I feel we have come to a moderate conclusion to this conversation and will be locking to avoid any further potential kerfuffles. Please follow https://github.com/vuetifyjs/vuetify/issues/5426 for any additional updates to this issue.
