### ISSUE TITLE
[Bug Report] v-treeview : Expand icon displayed for empty children array  

### ISSUE THREAD

**Issue by mgiraud** [vuetifyjs/vuetify#5357]
### Versions and Environment
Vuetify: 1.3.0
Vue: 2.5.17
Browsers: Firefox
OS: Mac

### Steps to reproduce
Create a tree with categories which children exist but is an empty array 

### Expected Behavior
The expand icon should not be generated

### Actual Behavior
The expand icon is generated

### Possible fix:

File: VTreeviewNode.ts L221
```
      if (this.children) children.unshift(this.genToggle())
```
```
      if (this.children && this.children.length > 0) children.unshift(this.genToggle())
```

**Comment by jacekkarczmarczyk** [comment]
Please provide runnable minimal reproduction

**Comment by nekosaur** [comment]
Items with a children property that is an empty array can be expanded and get children with the `load-children` prop. So checking children length won't work. We could possibly do `this.children && this.loadChildren` so that toggle is only rendered if one has supplied a load-function callback.

**Comment by nekosaur** [comment]
Items with a children property that is an empty array can be expanded and get children with the `load-children` prop. So checking only children length won't work. We could possibly do `this.children && (this.children.length || this.loadChildren)` so that toggle is only rendered if one has supplied a load-function callback.

**Comment by mgiraud** [comment]
Minimal reproduction on codepen : https://codepen.io/anon/pen/pxVVJE
