### ISSUE TITLE
Icons, cache and offline mode

### ISSUE THREAD

**Issue by mailok** [vuetifyjs/vuetify#5414]
### Versions and Environment
Browsers: Chrome
OS: Windows

### Steps to reproduce
Recently I had problems with running vuetify offline, and I found what was the cause,
**every time I stopped and put it to run it did not work unless I deleted the folders generated in the address** : ```vuetifyjs.com-dev\node_modules\.cache\hard-source ```

Another thing that I saw was that I could not see the icons that are used throughout the application,
and I solved it in the following way:

1. I deleted inside the file **index.template.html**: 

``` 
<link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Inconsolata:300|Material+Icons' rel="stylesheet" type="text/css">
```

2.I installed the dependency **material-design-icons-iconfont**

3.I added to the file **entry-client.js**:
``` 
import 'material-design-icons-iconfont/dist/material-design-icons.css';
```

4.And it's ready

The images of the problems it gives, if the generated folders are not deleted, are attached.
![a](https://user-images.githubusercontent.com/3769277/47430329-fc0ac380-d766-11e8-9481-61bcbaa2516d.PNG)

![b](https://user-images.githubusercontent.com/3769277/47430331-fd3bf080-d766-11e8-86f1-7a69344e1095.PNG)

![captura](https://user-images.githubusercontent.com/3769277/47430334-fdd48700-d766-11e8-97e5-e0dc49cab003.PNG)

![folders](https://user-images.githubusercontent.com/3769277/47430561-c0bcc480-d767-11e8-901e-259ff2b93598.PNG)

**Comment by KaelWD** [comment]
- hard-source is to improve build speed for development, it will be removed when we update to webpack 5
- we haven't seen any problems like that with hard-source, sounds like something in your system is broken (probably windows)
- the project is an actual live website, we won't be changing anything to make it run without a fully-connected server behind it
- if you haven't modified anything, use `yarn build` and `yarn start` instead of running it in dev mode
- this is the wrong repo for documentation problems, they should be reported on https://github.com/vuetifyjs/vuetifyjs.com
- there is already a request for proper offline support - https://github.com/vuetifyjs/vuetifyjs.com/issues/249
