### ISSUE TITLE
[Bug Report] v-menu not showing in v-toolbar

### ISSUE THREAD

**Issue by douglassllc** [vuetifyjs/vuetify#5518]
### Versions and Environment
**Vuetify:** 1.3.5
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Mac OS 10.13.6

### Steps to reproduce
Copy and Pasted the example code from the here and wrapped it in a v-toolbar.  I am using electron-webpack to serve up my development environment.  However, it does not work in the production build either.

```
<template>
  <v-toolbar>
    <v-menu offset-y>
      <v-btn
        slot="activator"
        color="primary"
        dark
      >
        Dropdown
      </v-btn>
      <v-list>
        <v-list-tile
          v-for="(item, index) in items"
          :key="index"
          @click=""
        >
          <v-list-tile-title>{{ item.title }}</v-list-tile-title>
        </v-list-tile>
      </v-list>
    </v-menu>
  </v-toolbar>
</template>
```

### Expected Behavior
button to show on v-toolbar.  clicking button shows dropdown menu

### Actual Behavior
button does not show at all on window.  However, I do see the menu in vue-devtools.

### Reproduction Link
<a href="https://codepen.io/anon/pen/XyWdvZ#anon-signup" target="_blank">https://codepen.io/anon/pen/XyWdvZ#anon-signup</a>

### Other comments
The same code works in codepen

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 7 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by douglassllc** [comment]
This seems to be related to #4068.  As suggested in this thread I add a whiteListedModules.  However, most referred to adding this to webpack.config.js like so
`
let whiteListedModules = ['vue', 'vuetify'];
module.exports = {
  externals: [
    ...Object.keys(dependencies || {}).filter(d => !whiteListedModules.includes(d))
  ]
}
`
This did not work for me.  I was able to add the following to my package.json and it now works.

`
  "electronWebpack": {
    "whiteListedModules": [
      "vue",
      "vuetify"
    ]
  },
`
I am using electron-webpack in my compile and build processes within package.json

Hope this helps others.
