### ISSUE TITLE
TreeView - load async

### ISSUE THREAD

**Issue by hhertogh** [vuetifyjs/vuetify#5543]
Hello,
I'm trying to use the TreeView component and the load async method on expanding an empty children item. Children are loaded successfully but I get the following error when expanding/closing item:

vue.runtime.esm.js?2b0e:587 [Vue warn]: Error in created hook: "TypeError: Cannot set property 'vnode' of undefined"

found in

---> <VTreeviewNode>... (2 recursive calls)
       <VTreeview>
         <ViewConnectionsComponent> at src/components/ViewConnectionsComponent.vue
           <VCard>

I don't know why I'm getting this error.

**Comment by nekosaur** [comment]
You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com/). In order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 14 days before being closed.

The best way forward is for you to use the [issue creator](https://issues.vuetifyjs.com/) and edit the issue with the generated information. Don't forget to create a reproduction using codepen or a similar service.

Thank you for your contribution and interest in improving Vuetify.

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
