### ISSUE TITLE
[Feature Request] Allow for vuetifyjs.com reproduction links in the vuetify issue tool

### ISSUE THREAD

**Issue by bviala** [vuetifyjs/vuetify#5548]
### Problem to solve
The vuetify issue tool (https://issues.vuetifyjs.com/) does not allow vuetifyjs.com url for reproduction links.
- Sometime the doc examples are enough to reproduce an issue.  There is no need to create a codepen.
- If you want to open an issue concerning vuetifyjs.com, eg a broken link, you don't need a reproduction link, you need the actual link where the problem is.

### Proposed solution
Allow vuetifyjs.com urls, or make the reproduction link optional

**Comment by nekosaur** [comment]
There is a codepen icon on every example in the docs that will generate a pen with that example.

**Comment by bviala** [comment]
@nekosaur 
Yes, a pen that you then have to save in order to get an URL.  
There is strictly no point duplicating code from the documentation in order to demonstrate an issue.
A codepen can be whatever code, whereas a vuetifyjs.com gives the information that there really is an issue with vuetify code.

Also, you completely eluded my second point. How exactly do you reproduce a broken link in a codepen ?

**Comment by nekosaur** [comment]
I would suggest that using a codepen actually _does_ demonstrate that the problem exists with vuetify (or not), since in this case it isolates it from the rest of the docs. 

I apologize for not addressing your second point. I agree that it does not make much sense to provide a reproduction if it's a bug or problem with the docs themselves, such as a problem link. We are working on updating the reporting process to make this more clear, since we've recently switched to a monorepo.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify-issue-helper/commits/specified-repos
