### ISSUE TITLE
[Bug Report] v-list-tile-tile content is not ending with dots, but rather trying to fill non-existing space

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5581]
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 7

### Steps to reproduce
Follow first reproduction link:
https://codepen.io/anon/pen/yQydpX

### Expected Behavior
last line finished with dots

### Actual Behavior
trying to fill not existing space

### Reproduction Link
<a href="https://codepen.io/anon/pen/yQydpX" target="_blank">https://codepen.io/anon/pen/yQydpX</a>

### Other comments
implement vue line clamp https://github.com/Frondor/vue-line-clamp or develop any other simply own solution

**Comment by MajesticPotatoe** [comment]
Don't think v-list-tile-tile is a thing.

**Comment by jacekkarczmarczyk** [comment]
First of all you have `v-list-tile-tile` instead of `v-list-tile-title`, after fixing you still need to add `style="width: 100%"` to `v-tooltip` to make it look better (yeah, that's a workaround, @Kael started working on this in https://github.com/vuetifyjs/vuetify/pull/3206)
Second thing is that only `three-lines` uses line-clamp, for `two-lines` you need to add `v-list-tile-title` and `v-list-tile-sub-title`, it still doesn't work as expected but again it's #3206

https://codepen.io/anon/pen/VVKOBO?editors=1000

So as @MajesticPotatoe said looks more like a feature request

**Comment by gileneusz** [comment]
sure, so it could be closed, if there is no need to fix the v-tooltip width as default

**Comment by johnleider** [comment]
The tooltip width is handled by kael's #3206 so closing this.
