### ISSUE TITLE
v-autocomplete active even if parent has pointer-events: none

### ISSUE THREAD

**Issue by alex-knyazev** [vuetifyjs/vuetify#5615]
When we use v-autocomplete inside div with pointer-events: nonde we still can click on it

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 7 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by alex-knyazev** [comment]
@jacekkarczmarczyk 
I did reproduction
https://codepen.io/anon/pen/dQWgpN

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/blob/9aa40bf9ce8f33db400b99003cfa5b709bea0790/packages/vuetify/src/stylus/components/_autocompletes.styl#L20
