### ISSUE TITLE
[Bug Report] Navigation drawer hidden with permanent

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#5617]
### Versions and Environment
**Vuetify:** 1.3.8
**Last working version:** 1.2.4
**Vue:** 2.5.16
**Browsers:** Chrome 70.0.3538.77
**OS:** Mac OS 10.14.0

### Steps to reproduce
Put a navigation drawer inside of a dialog with `permanent` property.

### Expected Behavior
Nav drawer to be always visible.

### Actual Behavior
When closing the dialog and re-open it, the nav-drawer is hidden.

### Reproduction Link
<a href="https://codepen.io/blaydator/pen/RqVeVj" target="_blank">https://codepen.io/blaydator/pen/RqVeVj</a>

### Other comments
Workaround : 

```
<v-navigation-drawer
  style="transform: translateX(0) !important;"
  permanent>
```

**Comment by johnleider** [comment]
The supplied codepen does not work.

**Comment by blalan05** [comment]
https://codepen.io/anon/pen/MRpvoj?editors=1010
I found this the other day as well.
Kael mentioned dependant mixin as the issue: https://discordapp.com/channels/340160225338195969/342461135343321108/565519421758767119

**Comment by ThomasKientz** [comment]
@johnleider https://codepen.io/thomaskientz/pen/gyvjNJ?&editable=true&editors=101

**Comment by tday0501** [comment]
@ThomasKientz did  style="transform: translateX(0) !important;" work for you? It's not working for me.

**Comment by JulienAramino** [comment]
style="transform: translateX(0) !important;visibility: visible !important;" is working

**Comment by chema-dw** [comment]
work for me! thanks

**Comment by crThiago** [comment]
The same bug happens when there is a navigation drawer nested within another navigation drawer, but `style = "transform: translateX (0)! Important; visibility: visible! Important;"` solve!

https://codepen.io/crthiago/pen/LYWbBXp

**Comment by ahmed71032** [comment]
Hi , I tried "transform: translateX (0)! Important; visibility: visible! Important;" and it worked as of now. Need to follow up till when it will be fixed .

**Comment by johnleider** [comment]
This is fixed in Vuetify 3:  https://play.vuetifyjs.com/#eNqFVMlu2zAQ/RVGPbgFQqltmhYQnKBBL733GOfAiIzMmhvIkZzC8L93SNkSJXe5SJzlzfJmyMdDEXxTPThX9p0o6mINQjvFQNxvDCHrnjLniOR3m0Ka4KQXmyJZks2wXrYMpDWUe7YXnsBWaIHOnPndpiCeSZU+dC85bNFw+xnVTnjNjDBwCpWCKRmASkxPGsVCQF/3Sj+O6U5eUrcEK0brFsCFuqo8M9zqLghfalExJytnPWBSCNXeamGqL7flT9di3mrKV2UJUZvVwWUvObYSnRflES5MkPALszdWO9YABkUS5iVOjfT0xfpIXRSkIfEfEFLvRIwRxRIkqInUU5DzEMgb54UThs/MAxGNNfeHQ4pZRoEcj7GrpJ8Fq7KRzgxZqTSVMcZL0ing0ifrdUHiXHteExQv9uRfK9RTbblQcYmSIuMG/b3dj/vxIpWiWyHbbZqDpW0HIHy4HMcIaRG/JPtPE1PS7OLE4j+bWBRRir/LiSyIwlggXmFCTdv3d/Iu6BsUWPV/6BwJxftKn9mZ4VwVcWk9yNdGyWY3MkzuyNWZ6+Xag7UqYofZ4zuByJQ6FjI3TgVONYxlaSantVxfUUoIpRlktJ/weF4s7jo0XrqBF/Ea7zhexxfWKSCHIQ5nwN6+O0uEeAGdN5OMHqnLmphOqetJne5lTR7z+RxI6qomq+/4iKyuSWQOJc0l7aXYU87C9tkyz1fkmMXKkQ/PtoM5FNer03PEU3ZO+4aVnJOuvlkD+M6EeP4hAKRpwypHaGlkTcB3YlQeh8OQA4V1NVJXHK+Lm/JT+eGmOB3eF0+/AUHy2ms=

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
