### ISSUE TITLE
[Bug Report] Avatar in chip is not align to the left side

### ISSUE THREAD

**Issue by knagyorg** [vuetifyjs/vuetify#5619]
v-avatar within v-chip has space from left side of chip.

![image](https://user-images.githubusercontent.com/10117488/48559621-40176100-e8ec-11e8-90e1-b2f5c96c7ee2.png)

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 7 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by knagyorg** [comment]
Reproduction Link
https://codepen.io/anon/pen/PxjQvd?editors=1111

**Comment by KaelWD** [comment]
The space seems intentional judging by the 1px transparent border, but that was never in the guidelines: https://material.io/archive/guidelines/assets/0Bx4BSt6jniD7MmdUUVdtcW9SVWM/components-chips-contact-keyline1.png

If it *is* intentional then the bug is that small chips are 24px instead of 26, not leaving space for the top/bottom borders.

**Comment by blenderskool** [comment]
From the design guidelines, I think the transparent border should not be present. Space exists only when there is no icon.

Can I work on it?

**Comment by johnleider** [comment]
@blenderskool Trying to avoid as many stylistic changes as possible since after 1.4 (this month) we are full swing into md2 conversion. If you are interested in helping I'd love to chat, swing by the community, https://community.vuetifyjs.com

**Comment by blenderskool** [comment]
@johnleider Oh, I would love to contribute for the design upgrade :slightly_smiling_face: :heart:
