### ISSUE TITLE
[Feature Request] Treeview search

### ISSUE THREAD

**Issue by ahmadnchami** [vuetifyjs/vuetify#5621]
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Windows 10

### Steps to reproduce
Check any node and search for another node

### Expected Behavior
The selected items should not be changed

### Actual Behavior
The selected items will removed if not found in the search results

### Reproduction Link
<a href="https://codepen.io/anec/pen/YRVged?&editors=101" target="_blank">https://codepen.io/anec/pen/YRVged?&editors=101</a>

**Comment by cb109** [comment]
To clarify: While the nodes retain their "selected" status __visually__, their keys are removed from the `selected` `v-model`. So visual representation and actual selection are out of sync.

**Comment by nekosaur** [comment]
This is a tricky one. Because the expected behavior that you describe is not what will happen when this bug is fixed. Since the filtering is happening outside of the component, it has no way of knowing that previously selected items that are filtered out are supposed to 'stay' in the selected set, and return when you reset the filter.

All it knows is that it is given a new set of items, and it creates the tree from that, resetting state in the process.

I do get what you're trying to achieve, but I don't see an immediate easy solution, other than internalizing a filter function in the component..

**Comment by ahmadnchami** [comment]
I might have a solution in mind, not sure if this helps or not.
I suggest to have a scoped slot where a node can be hidden (not removed) based on on an item property. However, this does create a problem, what if the node hidden is a parent node, in this case the node children should be hidden as well.
Just an idea I suppose.
