### ISSUE TITLE
v-select defaultText is not selectable

### ISSUE THREAD

**Issue by mfferreira** [vuetifyjs/vuetify#57]
There should be an option for `v-select` to enable the selection of `defaultText`.

Either that or an option to default to one of the items in `:options`.

**Comment by johnleider** [comment]
After experimenting with ways to handle this, I'm currently at the conclusion of in order to solve this, I would need to place a slot that you can manually iterate through options for.  Here's why:

With v-model, I'm able to notify the parent of changes made to the value property within the child. Let's say I only pass an options array-

```
options: [{ text: 'Value 1', value: 1},{ text: 'Value 2', value: 2, selected: true}]
```

and I use the selected property to determine what is selected. How do I notify the parent of the change? Do I keep a shallow copy in the component and only update that if the instance isn't bound by a v-model? I can do that, which would be an alternative to the slot, but is there a compelling use-case?

As far as to enable the selection of the defaultText, it's technically not an option that is bound for selection, it is only there to represent an empty state.

**Comment by mfferreira** [comment]
The use case would be for editing data. When selecting an object, you'd want to fill the form with object (selected) properties.

**Comment by mfferreira** [comment]
Here's a bit more argument for this.

On my specific use case, I have objects that reference other objects. For example, a `User` as a property `roleId` referencing a `Role` object. But this property is not required, which means that `roleId` can be left undefined/null.
From a UX perspective, on the `select` input I have two options:
- either I set a `label` to it and have the first select option for `None`, to be able to not have a Role selected for this User. Problem: I'm not able to select "None" if I have another option selected.
![image](https://cloud.githubusercontent.com/assets/882713/21580382/949727e4-cfd8-11e6-8358-5f5a9c06e824.png)
![image](https://cloud.githubusercontent.com/assets/882713/21580383/9b2e9588-cfd8-11e6-97f9-bff038aa6a7e.png)

- or I don't set a `label` and have the first select option as the "label". Problem: Looks weird, specially cause all the other inputs have labels set.
![image](https://cloud.githubusercontent.com/assets/882713/21580385/a66c7064-cfd8-11e6-9c31-9909550a8917.png)
![image](https://cloud.githubusercontent.com/assets/882713/21580387/aa9cea56-cfd8-11e6-8818-172720976de5.png)
 

Hope that shines some light about the (UX) issue.

**Comment by johnleider** [comment]
This sounds reasonable, I'll prep this for v0.8.4

**Comment by johnleider** [comment]
Added ability to enable default option. 7ffb6e013eddacd160fa62722040f8ecb99d8a24

**Comment by bombicode** [comment]
Hello, please tell me why there is no property defaultDisabled in the latest version 0.17? Thanks in advance
