### ISSUE TITLE
light and dark are switched

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [vuetifyjs/vuetify#575]
### Steps to reproduce
Just run the codepen
### Versions

The last one
### What is expected ?

The one described in the doc:
https://vuetifyjs.com/components/buttons
### Reproduction Link

https://codepen.io/anon/pen/GmPpRO

Best Regards,

Francesco Saverio Zuppichini

**Comment by johnleider** [comment]
So it's understood that some properties may seem backwards from MD spec. It was described in the release notes we are aware of this and it is intentional. It was confusing depending on the component you were using to what color you would get. We decided to make light theme always refer to #fff and dark to #000.
