### ISSUE TITLE
[Bug Report] Clearing a Text Field with Clearable Option Does Not Trigger Changed Event

### ISSUE THREAD

**Issue by dfmiller** [vuetifyjs/vuetify#5797]
### Versions and Environment
**Vuetify:** 1.3.11
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Mac OS 10.14.1

### Steps to reproduce
From a text field with the clearble option and a change handler, click the X.  The change event is not triggered.

### Expected Behavior
Change event triggered when X is clicked.

### Actual Behavior
Event is not triggered.

### Reproduction Link
<a href="https://codepen.io/darinfmiller/pen/QJoROw" target="_blank">https://codepen.io/darinfmiller/pen/QJoROw</a>

**Comment by johnleider** [comment]
Use `@click:clear="yourMethod"` to hook into this. An **input** event is already emitted.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by dfmiller** [comment]
The issue here is not whether I can track the change but that it does not correctly trigger the change event.

Still a bug.

**Comment by WhatFreshHellIsThis** [comment]
This is a bug and should not have been closed, I just came here to report this same bug.

**Comment by genechuah** [comment]
Ditto! This is a valid bug. Why is it closed? I'm going to try opening a new Issue.

**Comment by jacekkarczmarczyk** [comment]
It behaves same as native input which also doesn't emit `change` event

https://codepen.io/anon/pen/VoLJjj?editors=1100

**Comment by WhatFreshHellIsThis** [comment]
@jacekkarczmarczyk and your point is?  Not sure how that's relevant to this bug.

**Comment by jacekkarczmarczyk** [comment]
Do you consider native inputs as buggy?
Actually there is a small bug related to `clearable and `@change` event but it's not the same issue as described here

**Comment by WhatFreshHellIsThis** [comment]
I consider that I have a job to do here in the real world and this is a bug.

**Comment by jacekkarczmarczyk** [comment]
Bug is something that works differently than intended, which is not the case here. 
Emitting `@change` event when the clear button is clicked would be a new feature, you can open a new issue for this, although I can't guarantee that it won't be closed as `won't implement`

**Comment by WhatFreshHellIsThis** [comment]
@jacekkarczmarczyk I'm sorry but you are not making any sense here: the whole component is literally a **replacement** and **improvement** for the native input.  Why in the world would you want to make all these improvements for ease of use over the native component but draw the line at such an obviously serious flaw?  Do you consider the component input text to **not** be changed when it's cleared?  That's unrealistic at best isn't it?  Please re-open this case immediately or make some kind of objective and logical explanation as to why you won't.

**Comment by MajesticPotatoe** [comment]
@WhatFreshHellIsThis to clarify what @jacekkarczmarczyk is saying is that the input components were create to mimic the functionality of a native component, and apply CSS so that it follows MD Spec. This issue is not considered a bug because the component is working as intended. What you are requesting is a Feature to be added to the component.
You are also welcome to open a Feature Request as mentioned, but its not guaranteed to be implemented, as you can see earlier in this issue a PR was made and declined by John.
Additionally, if you are in high need of said feature I do believe it can easily be obtained with use of a watcher in vue or `@click:clear` as mentioned above also provides a listener for when it is cleared (which you should be able to reuse your `@change` function.

I am locking this convo as it seems to be getting a little too heated. If you would like to continue this feel free to reach out to us in our [Discord community](https://community.vuetifyjs.com). 

Thank you for your contribution and interest in improving Vuetify.
