### ISSUE TITLE
[Feature Request] Menu should be added at the end of body

### ISSUE THREAD

**Issue by deraw** [vuetifyjs/vuetify#5866]
### Problem to solve
If you have a title, like `h2` in a menu, it will be added at the top of `<body>`, so the first heading is not a `h1`, even if you have one in your `App.vue` for example.

### Proposed solution
Inject menus at the bottom of `<body>`. A workaround is to put the `<h1>` outside of the element where your app is rendered, and update it with JS, but it will be nice to don't have to do that!

**Comment by Deraw-** [comment]
Of course, here it is! https://codepen.io/dylan-broussard/pen/LMVadY?&editable=true&editors=101
Look at the image:
![oie_rvvrzrjjrlmp](https://user-images.githubusercontent.com/10298932/49858404-1ff89600-fdf5-11e8-94af-33b9a9d3de9e.png)
The `<h1>` is **after** the `<h2>` in the generated DOM, which is an accessibility issue because first title should always be a `<h1>`

**Comment by bkosborne** [comment]
Or have a "jump to main" link in your app to skip to the main content

**Comment by johnleider** [comment]
This is changing in v3 with the new Vue 3 portal system.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
