### ISSUE TITLE
[Bug Report] Browser autofill doesn't work with v-select

### ISSUE THREAD

**Issue by albernhagen** [vuetifyjs/vuetify#5936]
### Versions and Environment
**Vuetify:** 1.3.15
**Vue:** 2.5.21
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
Check out the codepen to see a working example.  My specific problem is that, when I have a dropdown for a user's state in their address, the autocomplete doesn't work.  I don't want the user to be able to type in the box -- I just want them to use a select box directly.  Despite that, I tried this with a v-autocomplete, and while the value fills, the v-menu stays open and the value doesn't save if the user clicks away.  I'm hoping I'm missing something simple that I can do to make this work correctly.  Note that I'm using Typescript in my local project, not that that matters.

### Expected Behavior
Chrome's autofill/autocomplete should automatically select the state.

### Actual Behavior
Nothing happens to the state dropdown.  I tried adding hooks for the input/change events but they never fire.

### Reproduction Link
<a href="https://codepen.io/albernhagen/pen/ebBmjM" target="_blank">https://codepen.io/albernhagen/pen/ebBmjM</a>

**Comment by albernhagen** [comment]
If I use the v-autocomplete instead (which almost works, though I'd prefer to force the user to use a select dropdown), is there a way to automatically select the option when autofill attempts to complete this field?  right now, if it fills the state as `CO`, then the dropdown stays open after form completion and clicking outside of it does not choose the option for the user.

**Comment by albernhagen** [comment]
@johnleider Let me know if there's anything I can do to assist.

**Comment by RileyDavidson-Evans** [comment]
I'm also having the same issue with my country and state / province dropdowns. 

@albernhagen have you found any fixes for this ?

**Comment by RileyDavidson-Evans** [comment]
So in order to solve this problem I had to introduce some custom functionality but now the desired auto fill works as requested !

`<template>
  <div>
    <v-select
      class="blw-control blw-select"
      @input="$emit('input', $event)"
      v-bind="{ ...$props, ...$attrs }"
      v-on="$listeners"
    >
      <template v-for="(_, slot) of $scopedSlots" v-slot:[slot]="scope"
        ><slot :name="slot" v-bind="scope"
      /></template>
    </v-select>
    <input class="select-auto-fill-input" v-model="autoCompleteValue" :name="name" />
  </div>
</template>

<script>
import { find as _find } from 'lodash';

export default {
  name: 'BlwSelect',
  props: ['items', 'name'],
  data() {
    return {
      autoCompleteValue: '',
    };
  },
  watch: {
    autoCompleteValue(value) {
      this.autoCompleteHandler(value);
    },
  },
  methods: {
    autoCompleteHandler(value) {
      const autocompletedMatchedItem =
        _find(this.items, { text: value }) || _find(this.items, { value });
      autocompletedMatchedItem && this.$emit('input', autocompletedMatchedItem.value);
    },
  },
};
</script>

<style lang="scss">
.blw-select {
  .v-select__slot {
    cursor: pointer;
  }
}
// can't use display none for the desired functionality, hide the input off the screen
.select-auto-fill-input {
  position: fixed;
  top: 150%;
  left: 150%;
}

// Item Hover (global overlay, CSS can't be nested)
.theme--light.v-list .v-list__tile--link {
  &:hover,
  &.v-list__tile--highlighted {
    color: white !important;
    background: $blue !important;
  }
}
</style>
`

**Comment by flyingL123** [comment]
Anything happening with this? I'm having the same issue. I don't want to use v-autocomplete because it seems to be a mess trying to stop the browser from showing it's own autofill suggestions. V-autocomplete is also not great because when the field is autofilled, it just filters the list down to one result, but doesn't actually select it, so the user still has to manually click the option themselves.

I would rather use a v-select but want it to work with autofilling, which it currently doesn't. The only solution I can come up with is something similar to what @RileyDavidson-Evans is suggesting above, but this seems like a lot of extra work that shouldn't be necessary.

Is this a major issue with the component or am I missing something?

**Comment by flyingL123** [comment]
@RileyDavidson-Evans I was able to get autocomplete working as well. I think my way is a bit simpler. The strategy is to make the `readonly` input that comes within the v-select not readonly, and then style it so it's offscreen. From what I can tell, the result is browser autocomplete working.

So, first I add these styles in my component that is using v-select:

```
>>> .v-select__selections input {
  position: absolute !important;
  left: -999999px !important;
}
```

I also store a `ref` to the v-select and remove its `readonly` attribute in the `mounted` hook:

```
mounted() {
  const input = this.$refs.stateSelect.$el.querySelector('.v-select__selections input');
  input.removeAttribute('readonly');
}
```

So far this seems to be working.
