### ISSUE TITLE
vue-router on v-breadcrumbs-item

### ISSUE THREAD

**Issue by chiu0602** [vuetifyjs/vuetify#6023]
v-breadcrumbs supports only "href" as link, "to" is also suggested as parameter so as to support vue-router

**Comment by MajesticPotatoe** [comment]
You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).
In order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 14 days before being closed.

Thank you for your contribution and interest in improving Vuetify.

**Comment by MajesticPotatoe** [comment]
`v-breadcrumbs-item` supports `to`
https://next.vuetifyjs.com/en/components/breadcrumbs
