### ISSUE TITLE
Textarea instead of Textfield in Combobox

### ISSUE THREAD

**Issue by tasoskn** [vuetifyjs/vuetify#6053]
Hello.
I was wondering if it's possible to have a v-textarea instead of v-text-field inside v- combobox.
I tried changing the files inside the es5/components, but nothing seems to work.
I even ended up manipulating the v-textfield files. Inside the index.js i set `textarea:true` instead of `textarea:boolean` and even changed `([0, _console.deprecate)('<v-text-field textarea>', '<v-textarea outline>', wrapper, parent)` to`([0, _console.deprecate)('<v-text-field>', '<v-textarea outline>', wrapper, parent)`

No luck. I always get a text field instead of v-textarea.

Thank you.

**Comment by sh7dm** [comment]
You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).
In order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 14 days before being closed.

Thank you for your contribution and interest in improving Vuetify.

**Comment by sh7dm** [comment]
@tasoskn please create a new issue using generator.
