### ISSUE TITLE
v-data-table pageText not page-text

### ISSUE THREAD

**Issue by Rouche** [vuetifyjs/vuetify#6081]
Hi,

The documentation says page-text as option. But the real option is pageText.

Is it a bug, or a documentation bug? Documentation i guess sadly, because fixing this would be a breaking change, unless supporting both slot name.

**Comment by sh7dm** [comment]
@Rouche You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).
In order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 14 days before being closed.

Thank you for your contribution and interest in improving Vuetify.
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by sh7dm** [comment]
But I see that this is a docs issue

**Comment by Rouche** [comment]
I was trying to find the doc repo for PR but without success, Ill create a doc bug with issue cxreator then.

**Comment by MajesticPotatoe** [comment]
@Rouche i got it take care of, changes will be up shortly. just in the future please use issue creator

**Comment by Rouche** [comment]
Yes sir! sorry.
