### ISSUE TITLE
[Bug Report] responsive scaling issues with chartjs since 1.4

### ISSUE THREAD

**Issue by Helmi** [vuetifyjs/vuetify#6083]
### Versions and Environment
**Vuetify:** 1.4.1
**Last working version:** 1.3.16
**Vue:** 2.5.21
**Browsers:** Chrome 72.0.3626.28
**OS:** Mac OS 10.14.2

### Steps to reproduce
resize the browser window on the codesandbox to see the problem. The top left box doesn't scale down correctly while the right one does. The right one does not have d-flex set on the v-flex while the top left one has. We use d-flex to get the boxes to equal heights.

### Expected Behavior
Should scale down with the browser

### Actual Behavior
Does scale up fine but not scale down anymore when d-flex is set.

### Reproduction Link
<a href="https://codesandbox.io/s/74l0v3ylzj" target="_blank">https://codesandbox.io/s/74l0v3ylzj</a>

**Comment by MajesticPotatoe** [comment]
Heres a codepen repo too 
https://codepen.io/anon/pen/REmEpx

**Comment by VadimOsovsky** [comment]
@Helmi, https://codepen.io/anon/pen/BErMdR
here's a crutch, that would solve specificaly your situation

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity. If this is still happening in the latest version, please open a new issue with a reproduction.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
