### ISSUE TITLE
[Feature Request] Content Loader

### ISSUE THREAD

**Issue by nrmv** [vuetifyjs/vuetify#6121]
### Problem to solve
Component to create placeholder loading

### Proposed solution
![Image](https://user-images.githubusercontent.com/4838076/34308760-ec55df82-e735-11e7-843b-2e311fa7b7d0.gif)

**Comment by PeteAndersen** [comment]
I would also love this feature. To expand more, there are some material guidelines on the subject: https://material.io/design/communication/launch-screen.html#placeholder-ui

It might be possible to bake this into existing components so that instead of rendering their content (which might not exist yet) they display something the same shape/size as shown above, allowing a seamless transition to actual content without changing layout. 

Potential candidates for supporting this would include anything displaying non-editable text or images. Avatars, card media/content, and list header, subheader, and text are very good candidates. Handling vertical sizing with a placeholder might be a challenge but generally I think horizontal sizing should be simple.

**Comment by MajesticPotatoe** [comment]
@PeteAndersen we have plans to implement this at some point, but most likely wont be till after 2.0

**Comment by aggarwaldev** [comment]
Closed via #9037

**Comment by bdeo** [comment]
Closed by https://github.com/vuetifyjs/vuetify/pull/9037
