### ISSUE TITLE
UI issue with date picker

### ISSUE THREAD

**Issue by jawahar273** [vuetifyjs/vuetify#6151]
Issue with the date picker's UI displaying but the UX work fine. I am using [`materialdesignicons`](https://materialdesignicons.com) 

```js
<v-date-picker
   v-model="millContent.lastDeliverDate"
   header-color="green"
    color="green darken-1"
    prev-icon="mdi-arrow-left"
    next-icon="mdi-arrow-right"
    scrollable
    :reactive="true"
     :light="true"
>

```

# What I got.
![image](https://user-images.githubusercontent.com/7668497/51163410-93436b00-18bf-11e9-947f-4294cb817a94.png)

# What I would love get.
![image](https://user-images.githubusercontent.com/7668497/51163762-c1757a80-18c0-11e9-8beb-17e6916170cb.png)

```json
    "vuetify": "^1.2.5"
    "vue": "^2.5.17",

```

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by jawahar273** [comment]
On sand box the `date picker` works fine so, I believe that it might be other factor affecting the UI. I will try to look into the issue
