### ISSUE TITLE
[Feature Request] Swipeable bottom nav

### ISSUE THREAD

**Issue by akandeBolaji** [vuetifyjs/vuetify#6186]

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).
In order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 14 days before being closed.

Thank you for your contribution and interest in improving Vuetify.

**Comment by MajesticPotatoe** [comment]
This issue is being closed due to:

- [x] Requested information not provided (inactivity for 14 days)
