### ISSUE TITLE
[Bug Report] VTooltip open-on-hover prop does not work

### ISSUE THREAD

**Issue by spuy767** [vuetifyjs/vuetify#6188]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Google Chrome, Mozilla Firefox, Safari, Microsoft Edge
**OS:** Mac OS 10.13.6, Windows, Linux

### Steps to reproduce
Hover over a v-input which is the activator slot for a v-tooltip which has the open-on-hover prop set to false.

### Expected Behavior
The tooltip should not show.

### Actual Behavior
The tooltip shows.

### Reproduction Link
<a href="https://codepen.io/anon/pen/pqmrYg" target="_blank">https://codepen.io/anon/pen/pqmrYg</a>

### Other comments
This may be a documentation issue rather than a code issue, in which case this should be converted to an NFR.

**Comment by MajesticPotatoe** [comment]
there is no `open-on-hover` prop for tooltip. If you are looking for this functionality use `disabled`

**Comment by spuy767** [comment]
Thanks for the tip with disabled, that does what I wanted, but just so you know, the docs reference the prop I referred to.  

![docs](https://user-images.githubusercontent.com/43174736/51633871-b229a900-1f20-11e9-9ae1-44191a6ff0f0.png)

**Comment by MajesticPotatoe** [comment]
@spuy767 that references the prop because the close-delay is inherited from v-hover, and its the description assigned to that prop. For tooltip, open-on-hover defaults to true in the background (kinda the point of the tooltip, is that it opens on hover). the actual prop itself is not exposed thus why it doesn't show up as settable prop.
