### ISSUE TITLE
using V-data-table, we need  in-line Editing for multiple rows and saving on button click  Vuetify Js (No popups. Required Editable Grid).

### ISSUE THREAD

**Issue by Raviteja369** [vuetifyjs/vuetify#6200]
Hello Team, 

I am looking for in-line editable rows using vuetify js. When I click on Save button which is placed outside the grid,need save the edited data in database. 

Please help out with sample code so that we can implement them.

Thanks in advance for your kind support.

Regards, 
Raviteja.

**Comment by sh7dm** [comment]
@Raviteja369 You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).
In order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 14 days before being closed.

Thank you for your contribution and interest in improving Vuetify.
