### ISSUE TITLE
please make more document to introduce vuetify.

### ISSUE THREAD

**Issue by kealuya** [vuetifyjs/vuetify#6209]
Please write more documents to introduce vuetify. There are too few documents. 
For example, this.$vuetify all the methods and so on.

**Comment by MajesticPotatoe** [comment]
You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).
In order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 14 days before being closed.

Thank you for your contribution and interest in improving Vuetify.

**Comment by MajesticPotatoe** [comment]
This issue is being closed due to:
- [x] Requested information not provided (inactivity for 14 days)
