### ISSUE TITLE
[Bug Report] Wrong menu positioning

### ISSUE THREAD

**Issue by evgencode** [vuetifyjs/vuetify#6223]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Wrap v-app and v-menu into custom scroll library

### Expected Behavior
In some cases, it flies away. 

### Actual Behavior
Menu is positioned relative to the button

### Reproduction Link
![image](https://user-images.githubusercontent.com/2129431/51478463-909fb480-1d9c-11e9-9280-6fda016781a2.png)

### Other comments
Why is the menu position not calculated relative to the parent? 
In some cases, it flies away. 
Can make the position of the menu relative to the parent?

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by buzzzzer** [comment]
The same issue on 1.4.3
1.4.2 as well

here example: 
https://codepen.io/Buzzzzer/pen/BMyEmK

**Comment by pauldaiko** [comment]
I am having the same issue where using the left prop on a menu in a toolbar that has a layout that is centered. Here is an example : https://codepen.io/slinkz/pen/zevxXa

**Comment by z0mbie42** [comment]
same issue as @blalan05 since 1.4.3 (1.4.2) is fine for me.

**Comment by zeljic** [comment]
One more example, in v-data-table.
Also, issue in 1.4.3 (1.4.2 works fine)
https://codepen.io/anon/pen/GzZJpb?editors=1010

**Comment by z0mbie42** [comment]
Work in progress in #6294

**Comment by jacekkarczmarczyk** [comment]
This doesn't look like #6294 (examples in comments do, but the original issue doesn't)

**Comment by z0mbie42** [comment]
Acknowledged, my bad. So the issue still needs reproduction ? As the comments above seems to reproduce #6294 and the @zeljic seems not buggy for me.

**Comment by jacekkarczmarczyk** [comment]
Yes, seems that `bug` label was added because of the comments, not the original issue

@evgencode

**Comment by johnleider** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
