### ISSUE TITLE
v-expansion-panel custom icon should not turn

### ISSUE THREAD

**Issue by Ed-ouard** [vuetifyjs/vuetify#6284]
https://vuetifyjs.com/en/components/expansion-panels

Can we have an option, especially for custom icon slot, to keep the icon fixed, because when we use it (also in the example) the icon make a 180 degrees. Good for an arrow, but not for a custom icon (error, success..)

Thank you.

**Comment by sh7dm** [comment]
You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).
In order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 14 days before being closed.

Thank you for your contribution and interest in improving Vuetify.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by antontsvil** [comment]
you can disable the turning pretty easily :

template:
```
<v-expansion-panel-content class="keep-icon-upright" expand-icon="some-icon">...</v-expansion-panel-content>
```

css:
```
.keep-icon-upright i{
        transform: unset!important;
}
```
