### ISSUE TITLE
Default sorting in v-datatable doesn't work in Safari 12.03

### ISSUE THREAD

**Issue by rykr** [vuetifyjs/vuetify#6287]
Specifying :pagination.sync="obj"  on my data table

and then having obj: {'sortBy': 'priority', 'descending': true} where priority is the value of the column I want sorted.

This works fine in chrome but doesn't work at all in Safari 12.03 in Mac Mojave.

**Comment by MajesticPotatoe** [comment]
You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).
In order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 14 days before being closed.

Thank you for your contribution and interest in improving Vuetify.

**Comment by rykr** [comment]
no longer an issue with vuetify 1.4.4
