### ISSUE TITLE
[Bug Report] v-btn-toggle active-class prop doesn't apply to child v-btn

### ISSUE THREAD

**Issue by 06b** [vuetifyjs/vuetify#6378]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.2
**Browsers:** Chrome 72.0.3626.81
**OS:** Windows 10

### Steps to reproduce
Create a `v-btn-toggle` with `v-btn` children that has the prop active-class.
Click or set any of the `v-btn` children to be active.

### Expected Behavior
I would expect that `v-btn` would pick up the active-class from the `v-btn-toggle`.

What I would expect to happen from the repo link code:
![image](https://user-images.githubusercontent.com/1302542/52308735-1a8a7880-296c-11e9-9176-3b6f989e37ab.png)

### Actual Behavior
`v-btn` doesn't pick up the active-class prop from `v-btn-toggle`.

What I actually happens from the repo link code:
![image](https://user-images.githubusercontent.com/1302542/52308765-342bc000-296c-11e9-980e-1ca4d9ca9494.png)

### Reproduction Link
<a href="https://codepen.io/anon/pen/xMXgwN" target="_blank">https://codepen.io/anon/pen/xMXgwN</a>

**Comment by KaelWD** [comment]
The groupable mixin has handling for this but it gets overridden by v-btn. It wouldn't work properly anyway because it's only using a prop default and there's nothing consuming `groupClasses`

**Comment by heidricklevi** [comment]
@KaelWD - We could do something like `[ this.btnToggle ? this.btnToggle.$options.propsData.activeClass : this.activeClass ]: this.isActive,` inside of the computed classes for v-btn. But not sure if this is desirable since it effectively bypasses using props. Do you possibly have a more elegant suggested approach? I struggled to pinpoint where the activeClass in groupable is going wrong when I add in groupClasses to v-btn because it is just taking the default from v-btn I think rather than the activeClass of the namespace (btnToggle).

**Comment by johnleider** [comment]
As far as I can tell, this is the current behavior as of v2.3.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
