### ISSUE TITLE
Choose date using tabulator in v-date-picker is not working

### ISSUE THREAD

**Issue by KarianneKariak** [vuetifyjs/vuetify#6419]
When using this example: https://codepen.io/pen/?&editable=true&editors=101 it is not possible to tab/navigate using in the datepicker using the keyboard. We are using Vue.js for our frontend and datepicker will be used. Is there any way to fix this?

**Comment by blalan05** [comment]
You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).

Your linked codepen is blank, in order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 14 days before being closed.

Thank you for your contribution and interest in improving Vuetify.

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5629
