### ISSUE TITLE
[Bug Report] text-truncate cuts off bottom part of title

### ISSUE THREAD

**Issue by WIStudent** [vuetifyjs/vuetify#6488]
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Firefox 65.0
**OS:** Windows 10

### Steps to reproduce
Create a div with classes "title" and "text-truncate"
```html
<div class=title text-truncate">
gggyyy
</div>
```

### Expected Behavior
Bottom of text should not be cut off:

### Actual Behavior
Bottom of text is being cut off
![grafik](https://user-images.githubusercontent.com/2707930/52716311-c7817880-2f9e-11e9-81f5-7d9b6a0ae3ba.png)

### Reproduction Link
<a href="https://codepen.io/wistudent/pen/xMJPQq" target="_blank">https://codepen.io/wistudent/pen/xMJPQq</a>

**Comment by blalan05** [comment]
Simple fix, add a little padding: class="py-1". Text-truncate class only adds: overflow: hidden; text-overflow: ellipsis;

**Comment by 06b** [comment]
However due to `.title` having a `line-height:1 !important;` when the `.text-truncate` is added the `overflow:hidden;` will cause the issue of cutting off descenders on letters.

Changing the line-height to 1.1 would fix the issue in this case or it could be switched to normal which is the default line-height & would then be up to the user agent to use a "reasonable" value based on the font of the element according to the [spec ](https://www.w3.org/TR/CSS2/visudet.html#propdef-line-height)at least.
