### ISSUE TITLE
[Bug Report] Autocomplete menu icon doesn't close menu

### ISSUE THREAD

**Issue by Flip535** [vuetifyjs/vuetify#6564]
### Versions and Environment
**Vuetify:** 1.5.2
**Last working version:** 1.0.19
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.109
**OS:** Windows 10

### Steps to reproduce
type something into the autocomplete to populate the dropdown list. try to click the menu icon on the right of the control to close the menu. be sure that the browser is tall enough so that the menu does not cover up the menu icon

### Expected Behavior
menu icon clicks should open and close the menu

### Actual Behavior
Menu doesnt close

### Reproduction Link
<a href="https://codepen.io/anon/pen/omRZba?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/omRZba?&editable=true&editors=101</a>

**Comment by GarrettGeorge** [comment]
I'm interested in making a PR for this, any discussion to be had? 

Currently `v-menu` has `closeOnClick` which closes when `click-outside` is triggered, but this is for any outside click instead of just the `append-inner` slot.

Currently you can you also have a custom prop for `append-inner` for `v-combobox` and then handle it manually, but it doesn't make sense (to me at least) that this shouldn't be default.

**Comment by thexperiments** [comment]
Also hitting this bug. Is there a workaround available?

**Comment by simonmaass** [comment]
same issue here - any news here?

**Comment by pauldaiko** [comment]
I have been using a workaround for this for a while. it should also work for select components as well.
Here is a pen of the original link with the fix:

https://codepen.io/slinkz/pen/rXzoWa
