### ISSUE TITLE
Using v-model in v-stepper can clear data

### ISSUE THREAD

**Issue by jijoel** [vuetifyjs/vuetify#661]
When using a v-model attribute in a v-stepper, some of the properties in my data get cleared. This does not happen if I don't set the v-model attribute. 

I am dynamically generating components via a proxy so the specific fields can be passed in from a database. Questions are split into sections, which are then shown in each step of the v-stepper.

Please see https://codepen.io/jijoel/pen/XgrpOz. When the stepper's v-model is not set, it shows the expected behavior from the form. We can switch from one step to another, and see questions associated with each step. When the v-model is set, the question data is cleared, so questions do not appear.

### Versions
Tested with Vue v2.3.3; Vuetify 0.12.0 - 0.12.5, Chrome on Mac

### What is expected ?
v-stepper shows the questions for each step. Moving from step to step will show new questions.

### What is actually happening ?
v-stepper shows questions for the initial step, but the data for steps has been cleared. Switching to any other step (or even clicking on the title of the first step) shows no questions.

### Reproduction Link
https://codepen.io/jijoel/pen/XgrpOz

See line 24 of the Javascript. When commented out, things work as expected. When enabled, data is cleared. Click any section header to see that in action.

**Comment by johnleider** [comment]
This is quite a weird one. Still looking into it.

**Comment by johnleider** [comment]
Finally figured this one out. In your proxy component, you are binding ```attrs``` to ```this.props```. This is creating a reference between the attrs on whatever component is rendered, in this case ```v-text-field```. This is the reason why only when you use a model does the issue show because when the model changes, it forces a re-render of the component and its children. When this happens, Vue breaks down each component and in this case, breaks down the binded ```attrs```, removing them from your proxy component.
Beyond that, I assume that this is caused because of the broken down `attrs`.

You can circumvent this by replacing your render function of the proxy component with this:
```
return createElem(this.type, { attrs: Object.assign({}, this.props) });
```
