### ISSUE TITLE
[Bug Report] v-dialog with tabs hides the tabs slider until you click any of the tabs

### ISSUE THREAD

**Issue by mrodal** [vuetifyjs/vuetify#6626]
### Versions and Environment
**Vuetify:** 1.5.3
**Vue:** 2.6.7
**Browsers:** Chrome 72.0.3626.109
**OS:** Windows 10

### Steps to reproduce
* Create a v-dialog with tabs inside
* Open the dialog

### Expected Behavior
The tabs slider showing on the active tab.

### Actual Behavior
The tabs slider is hidden until you click on any tab other than the initial.

### Reproduction Link
<a href="https://codepen.io/mrodal/pen/PLqWOP" target="_blank">https://codepen.io/mrodal/pen/PLqWOP</a>

### Other comments
This is a duplicate of https://github.com/vuetifyjs/vuetify/issues/1978, that the royal sweet potato suggested me to do since you guys usually don't respond on closed issues.

I copy my comment on that issue, which is a possible solution:
>Have you considered something like [this](http://marcj.github.io/css-element-queries/) instead of the window resize event for example? I made a quick test adding that on the resize directive and it fixes this.

>Im not sure how it might affect the rest of the codebase, but they even claim that it performs better than the window resize event that is used currently on the resize directive, so it might improve the whole vuetify performance!

As you can see in the original bug, there's a lot of duplicates, and I think its an annoying bug that shouldn't exist on a library as good as this. I'm not too familiar with the codebase to say if it breaks things or not, but I think its worth considering, and if you want I can make a PR since its a simple change.

**Comment by X1machinemaker1X** [comment]
Happens to me as well

**Comment by cn-xufei** [comment]
Tab pagination controls not appear in expansion panel.
https://codepen.io/cn-xufei/pen/EzJXQQ

**Comment by johnleider** [comment]
This is part of a larger issue with components that have internal elements that rely on a DOM element's dimensions. When a component like `v-tabs` is inside of a `v-menu`, or a `v-dialog` or a `v-expansion-panel`, it is unable to determine its slider position because its parent is hidden. This is also something we experience with inputs that use **autofocus**.

It is a larger issue that needs a more framework wide solution and the only workaround for now is to either use the **lazy** prop, or add a **$ref** to the `v-tabs` component and manually call `this.$refs.tabs.callSlider()` when the model of the `v-expansion-panel` changes.

**Comment by johnleider** [comment]
This was resolved in v2 with the introduction of the [intersectable]() mixin. https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/mixins/intersectable/index.ts

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
