### ISSUE TITLE
[Bug Report] Menu in multiple <v-app/> instance do not close

### ISSUE THREAD

**Issue by dirtymurdoc** [vuetifyjs/vuetify#6722]
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.6.8
**Browsers:** Firefox 67.0
**OS:** Mac OS 10.14

### Steps to reproduce
Click on more button on first card, menu will open.
Click on the first card outside the menu, menu will close.

Click on more button on second card, menu will open.
Click on the second card outside the menu, menu will NOT close.

### Expected Behavior
Click on the second card outside the menu, menu should close.

### Actual Behavior
Click on the second card outside the menu, menu will NOT close.

### Reproduction Link
<a href="https://codepen.io/anon/pen/EMbJMR" target="_blank">https://codepen.io/anon/pen/EMbJMR</a>

**Comment by KaelWD** [comment]
Having more than one v-app is not currently supported.

**Comment by nscozzaro** [comment]
I'm in a situation where I'm developing an extension (for JupyterLab) which can have multiple instances open at the same time, but I don't have the ability to wrap all of the instances in one `v-app` because I don't have access. This is causing a bunch of weird issues like clicking a button in one instance triggers the modal opening in the other instance. 
What can I do in a situation like mine?
