### ISSUE TITLE
v-card-text has a padding top of 0px in dialogs

### ISSUE THREAD

**Issue by mornir** [vuetifyjs/vuetify#675]
### What is expected ?
Inside a dialog component, v-card-text should have some padding on top.

### What is actually happening ?
Inside a dialog component, v-card-text has a padding-top of 0px. When v-card-title has a background-color, it doesn't look good because the content of v-card-text is too close to the color.

### Reproduction Link
https://codepen.io/mornir0/pen/KqKPrE

In this codepen, we can see the difference in terms of padding-top between a card component placed inside and outside a dialog component.

In material design specs, the padding between title and body text must be 20dp. Currently, there is a padding-bottom of 20px on v-card-title inside a dialog. I suggest having a padding-bottom of 10px on v-card-title and a padding-top of 10px on v-card-text.

**Comment by sindrepm** [comment]
In my opinion the v-dialog (or any other component) should not change the default styling of another component just because it is assumed it can be used in a certain way. It is important that the styling of components are consistent regardless of where it is placed. Otherwise it becomes very difficult to create consistent UI and developers have to add ugly hacks to work around the default styles.

It is not assumed from the spec that you are supposed to add a card inside a dialog to get the appropriate spacing. If a developer choose to add a card inside a dialog they should get a card inside a dialog (with the default styling, nothing more/less), and not a dialog with special styling just because it can be convenient to re-use the card styles.

**Comment by mornir** [comment]
@sindrepm Yes, I agree. The card component should look the same inside a dialog as it does outside. Currently, this is not the case. I think this is the CSS rule that overrides the default behavior of v-card-text.
```
.dialog>.card .card__text {
    padding: 0 24px 24px;
}
```

**Comment by johnleider** [comment]
One of the difficulties we had with this component was how differently the spacing is inside it while still (visibly at least) appearing to use a card. I went back and forth with @marco with this one and I agree with your sentiment.

The problem is coming up with something that satisfies both ends.
