### ISSUE TITLE
[Bug Report] Expand all panel of Expansion Panel

### ISSUE THREAD

**Issue by thibaultchazal** [vuetifyjs/vuetify#6752]
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.5.21
**Browsers:** Chrome 72.0.3626.121
**OS:** Mac OS 10.14.0

### Steps to reproduce
I added a 'value=true' to v-expansion-panel

### Expected Behavior
I expect all the panel to be opened

### Actual Behavior
All are opened exept the last one

### Reproduction Link
<a href="https://codepen.io/thibaultchazal/pen/drKwEN?&editable=true&editors=101" target="_blank">https://codepen.io/thibaultchazal/pen/drKwEN?&editable=true&editors=101</a>

**Comment by DanielStout5** [comment]
The problem is you have `value=true` which seems to be interpreted as an array with 4 non-falsy elements, so only the first 4 panels are opened.

See the console warning:

`[Vue warn]: Invalid prop: type check failed for prop 'value'. Expected Number, Array, got String with value 'true'.`

You should have an array with as many `true` as there are panels, so something like this:

```
<v-expansion-panel
      :value="Array(5).fill(true)"
      expand
>
```
