### ISSUE TITLE
Timepicker in 24h mode not according to material design

### ISSUE THREAD

**Issue by duebbert** [vuetifyjs/vuetify#676]
### Steps to reproduce
Include a `timepicker` component with `format="24h"`.

### Versions

0.12.5

### What is expected ?

A timepicker like in Material Design should appear with 2 circles of hours and minutes.
Here is an example of what it should look like (and what it looks like on Android): http://www.materialdoc.com/time-pickers/

### What is actually happening ?

Just one circle of hours and minutes is shown, also the time at top is right aligned instead of centred.

### Reproduction Link

https://codepen.io/anon/pen/YQzPvK

**Comment by johnleider** [comment]
The link you provided links to the actual documentation for the spec, which displays the picker as Vuetify does, https://material.io/guidelines/components/pickers.html#pickers-time-pickers.

**Comment by duebbert** [comment]
Not in 24h, does it?

**Comment by johnleider** [comment]
The MD spec has no visual aid on the site for what 24hr mode looks like. It had to be assumed to use the same style as 12h.

**Comment by duebbert** [comment]
Yes, I thought that but the actual material android design for 24h is like
in the link I sent. It's in two circles.

**Comment by johnleider** [comment]
Unfortunately, there are many designs that exist in many places of google that are different. The most surefire thing that I can do is mimic what is on the official spec page (which is updated). Otherwise, it becomes difficult to explain why some components are what they are.

Imagine I make this change, someone comes along, looks at the official spec, and notices that 24hr is different than 12hr and they make a thread like this saying I'm not in spec. It's slippery slope.

**Comment by duebbert** [comment]
Sure, that's fair enough. But does the official specs page show an example
for 24h? Because I'm using stock android and it's definitely like the
example link I've provided and that's consistent. I've never once had the
24h one ring that vuetify does at the moment.

**Comment by johnleider** [comment]
No, the spec does not have an official example. I've spoke with some of the team and I don't have an issue doing this, but it will be low priority for now.

**Comment by duebbert** [comment]
This here is useful to see the native Android 24h time picker. From React-Native: https://facebook.github.io/react-native/docs/timepickerandroid.html

To see the native Android Material time picker:
1. Click "Run this example" and wait a few minutes as it takes a while to start.
2. Search for "TimePicker"
3. Click on "TimePickerAndroid"
4. Click on "Time picker with 24 hours format"

Then it shows the native 24h time picker like this:
![image](https://cloud.githubusercontent.com/assets/2813849/26823793/d5fe97d2-4aa6-11e7-9c20-a1c463a7db44.png)


(This might actually also be useful to check other Material Design aspects that are not clearly spelt out in the spec.)

**Comment by keystorm** [comment]
Aside from there not being a clear consensus about whether stock android should be considered default canon, that approach is much clearer.

The current implementation is quite counter-intuitive for our less technical users, since 24h clocks don't look anything like that, but they aren't quite used to the AM/PM approach either.

So here's my +1 to this enhancement.

**Comment by johnleider** [comment]
Fixed with #880
