### ISSUE TITLE
[Bug Report] 'expand' does not work v-data-iterator

### ISSUE THREAD

**Issue by BudZZEman** [vuetifyjs/vuetify#6760]
The 'expand' on data-table works perfect, but I can't get it to work with data-iterator. The docs say it should work.
I'm not sure if it is a bug or it has to be used in another way as in the table. 
If someone has a working sample with data-iterator, please let me know

**Comment by MajesticPotatoe** [comment]
You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).
In order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 14 days before being closed.

Thank you for your contribution and interest in improving Vuetify.

**Comment by MajesticPotatoe** [comment]
eg: https://codepen.io/anon/pen/BbOyoz per discord.
Will be added to docs.
