### ISSUE TITLE
range slider with negative step value - left value higher than right

### ISSUE THREAD

**Issue by sureshvv** [vuetifyjs/vuetify#6762]
Can this be implemented? I can help with some guidance.

**Comment by MajesticPotatoe** [comment]
You've submitted an issue that appears to have not been created from our [issue creator](https://issues.vuetifyjs.com).
In order to effectively disposition this, we need additional information. This issue will be tagged as `missing information` for the next 14 days before being closed.

Thank you for your contribution and interest in improving Vuetify.
