### ISSUE TITLE
[Feature Request] doc lacks info on v-model functionality

### ISSUE THREAD

**Issue by YuqiaoS** [vuetifyjs/vuetify#6823]
### Problem to solve
Currently the v-model prop on the component doesn't appear to be explained anywhere on the doc but just put in the examples on certain components like navigration-drawer or snackbar. How would we know which components can use this?

### Proposed solution
Could you add to the doc on the usage of v-model prop?

**Comment by MajesticPotatoe** [comment]
It is not documented as it is not a function that originates from Vuetify. In order to use Vuetify effectively you should have at least a basic knowledge of the underlying technology Vue. `v-model` is simply syntactical sugar for `v-bind:value`. You can read more about `v-model` [>HERE<](https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components) and [>HERE<](https://vuejs.org/v2/guide/forms.html)

**Comment by YuqiaoS** [comment]
And yet where is it explained in Vue or anywhere that :value means hidden or display?

**Comment by jacekkarczmarczyk** [comment]
It's not explained in the Vue, because it's up to lib authors what the model is responsible for, but you can see the description of `value` prop in different components in the API section, for example https://vuetifyjs.com/en/components/alerts:

![image](https://user-images.githubusercontent.com/15625235/54972932-5e8b1880-4fc0-11e9-96a7-dd3cdf0eea79.png)

**Comment by YuqiaoS** [comment]
Ok. I guess that's a miss on my part.

What about the 'activator' slot logic in the examples? ([Others seem to have struggled on finding doc on  it as well](https://stackoverflow.com/questions/49079936/how-does-slot-activator-work-in-vuetify). I suppose that the examples on the doc now are different now with the v-slot attribute update since Vue 2.6.0, but its even more confusing? Where is the `on` variable from??

https://vuetifyjs.com/en/components/tooltips#usage

<v-tooltip bottom>
      <template v-slot:activator="{ on }">
        <v-icon color="primary" dark v-on="on">home</v-icon>
      </template>
      <span>Tooltip</span>
</v-tooltip>

**Comment by YuqiaoS** [comment]
Hello? Should I open as new issue for this?
