### ISSUE TITLE
[Bug Report] v-dialog width auto doesn't work

### ISSUE THREAD

**Issue by romprzy** [vuetifyjs/vuetify#6919]
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.6
**Browsers:** Chrome 73.0.3683.86
**OS:** Windows 7

### Steps to reproduce
Use v-dialog without specifying width or set width to auto

### Expected Behavior
v-dialog width should be auto by default,
setting manually width="auto" should change width to auto

### Actual Behavior
v-dialog width is set to 100% by default,
setting manually width="auto" doesn't work

### Reproduction Link
<a href="https://codepen.io/romprzy/pen/LvGMGp?&editable=true&editors=101" target="_blank">https://codepen.io/romprzy/pen/LvGMGp?&editable=true&editors=101</a>

### Other comments
There is workaround - setting manually width="auto " (with extra space)

**Comment by KaelWD** [comment]
Broken by #2185

**Comment by bufferUnderrun** [comment]
@romprzy @KaelWD 

That's **a breaking change** and the release-note should have a upgrade guide about this.

Because v-dialog were 100% width, i only set max-width in my template.

Now, to get the same visual result in v2.6.0, i have to add the prop width='100%'

Can you update the release-note. Thanks

**Comment by KeterSCP** [comment]
This also changed default width style for the `v-bottom-sheet` component as it extends `v-dialog`.  Now we should explicitly set width=100% to make bottom sheet look like previously.

**Comment by KaelWD** [comment]
I love how it's in beta for over a month and then four people somehow manage to notice it at the same time like a week after release.

**Comment by bufferUnderrun** [comment]
@KaelWD due to lack of time, devs and finals users can't test every beta of lib or app they use. Many issues and regressions are found few hours after release. That's why you should consider a release is a beta for someone else

**Comment by oelerpearler** [comment]
Thanks @bufferUnderrun for the hint! Just upgraded the library and was wondering why all my dialogs (which also solely used max-width) were visually altered.

Vuetify is great, and as far as I know, such breaking changes rarely happened in the past, but still it would have been really nice to have such things described in the changelog, since (I assume) this is the ting Devs to in case they face issues with a minor update of a dependency.

**Comment by KaelWD** [comment]
> such breaking changes rarely happened in the past

More than you'd think, they're probably just fixed before you notice. 

> nice to have such things described in the changelog

It was: `VDialog: default to auto width`. I didn't know it would break things or it wouldn't have been there at all.

**Comment by bufferUnderrun** [comment]
@KaelWD vuetify is a beautiful project : the more i use it, the more i love it. You do a great job like other team member. Thanks !
