### ISSUE TITLE
[Feature Request] [Docs] Card API documentation lists v-card-media and not v-img. Warning says "use v-responsive", but Card docs make no mention of v-responsive

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#7032]
### Problem to solve
Documentation inconsistencies. https://vuetifyjs.com/en/components/cards

* API Lists `v-card-media` but not `v-img` despite `v-card-media` being deprecated.
* Warning when using `v-card-media` says `use 'v-responsive' instead`, but the card API docs do not have `v-responsive` listed.

Searching for `v-responsive` also doesn't produce results:

![image](https://user-images.githubusercontent.com/1400380/56461031-0944eb80-6361-11e9-9cd3-2c39187fbdc0.png)

Related to https://github.com/vuetifyjs/vuetify/issues/5002

### Proposed solution
Change docs API to include v-img and `v-responsive`

**Comment by MajesticPotatoe** [comment]
`v-card-media` in 2.0 has been fully deprecated all together and the card docs does have an alert in 1.5 stating its been deprecated and to using `v-img`

`v-responsive` does exist in docs under [Aspect Ratios](https://next.vuetifyjs.com/en/framework/aspect-ratios). Unfortunately we don't have much control over what algolia provides as search results.

**Comment by douglasg14b** [comment]
@MajesticPotatoe Will the docs be updated in 2.0 to not be conflicting/confusing in this area? If that has not be explicitly planned for `v-card`, then shouldn't this be marked 2.0 and docs?

Similarly, why does the warning say to use v-responsive if that can't be found under v-card, which is a reasonable place for a user to look for it given the context?

I strongly feel like this is a valid documentation issue, as it's ambiguous, conflicting, and difficult to find. Which is a primary source of user frustration, and is often hand-waved away until it reaches critical mass.

**Comment by MajesticPotatoe** [comment]
@douglasg14b in 2.0 there shouldn't be any confusion as that warning and `v-media-card` do not exist and will be noted in upgrade paths. As for `v-responsive`, this component is not exclusive to `v-card` which is why it does not exist under it. Chances are when `v-media-card` that was what was being suggested as a suitable replacement. Additionally we are not accepting issues related to 2.0 until beta, as for alpha is like hitting a moving target with many moving pieces.

If you strongly feel this is still an issue, you are welcome to PR a solution you see would resolve this confusion to our next branch and will review it.

**Comment by douglasg14b** [comment]
@MajesticPotatoe 

I guess what I'm having a hard time with is that there are documentation deficiencies, **deficiencies that are well known in the development world to be anti-patterns**. Vuetify maintainers state on social media that the team is always looking to improve it's documentation and user experience, but when attention is brought to these deficiencies and anti-patterns they are brushed aside...

It's disenfranchising to be encouraged in other forums to make documentation related issues for Vuetify.  Just to have them closed. Especially when the state of the documentation, and some of the over-arching issues it has, have already been recognized.

PRs take investment. Not only into the PR itself, but also appealing to the style and patterns already cemented into the team. Having well known fundamental problems brushed aside and closed doesn't bode well for any work someone might put into PRs to solve existing documentation anti-patterns. 

Why work on PRs that will probably get closed?

**Comment by MajesticPotatoe** [comment]
@douglasg14b thank you for your input. I understand your frustration and am aware of such deficiencies. The most I can say is that I am working on bettering the way these are handled in the future, however most of that will not be seen until 2.0 is released.

I agree that PR's are an investment, whatever size they may be (and in most cases, docs related ones that are submitted are relatively small). Since I've started on this project rarely have I seen a PR related to docs closed and tossed aside without at least a reason so. Generally if something doesn't fit or is inaccurate, we will provide feedback for such. Most of the ones that are closed usually involve a period of inactivity from the submitter, and some are closed because they are manually added by a team member.

Aside of the docs as a whole though, I still stand by my decision listed above on this particular issue.  If you would like discuss this more, feel free to hit me up in discord.
