### ISSUE TITLE
[Feature Request] Option of disabling the "theme---light" classes

### ISSUE THREAD

**Issue by crotanite** [vuetifyjs/vuetify#7097]
### Problem to solve
Building a completely custom theme on top of vuetify, but would like to remove the unneeded "theme--light" classes from every item. It would be nice to disable this via a prop on the main app.

### Proposed solution
```javascript
<v-app :dark="false" :light="false">
  ...
</v-app>
```

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by dragontheory** [comment]
`theme: { disable: true}` doesn't get rid of the `theme--light` class - which assigns styles INLINE? I have my own styles to apply. How do you propose coding around this? Thanks.

**Comment by tryforceful** [comment]
Can we get an answer at least for @dragontheory's question? I have the same complaint. `theme--light` classes force `!important` styles all across the DOM, forcing me to override with `!important!` myself... It's not a good practice. Being able to remove `theme--light` would be ideal.

**Comment by Maximus1000** [comment]
Plus one, Vuetify's JS features are incredible.  Its forced theming styles are a big problem for users who want to make use of other CSS utility libraries like Tailwind.  The theme--light class overrides just about any attempt I make especially for dynamic content like an active radio button.  Too difficult to turn it off.

**Comment by Taras-od-ua** [comment]
simple feature. but would be so useful for many. Why it's so hard to add?

**Comment by AlissonRS** [comment]
@johnleider can we get an answer? This would be very useful. I have a specific page that I want to use vuetify components, but don't want to use the theme, and disabling the theme doesn't seem to remove the inline styles, which seems to be a bug.

**Comment by Svenmarim** [comment]
+1 on this question. It has been almost one year now that @dragontheory has asked this...

**Comment by viennv1709** [comment]
@johnleider  It should reopen the issue. I can't change color and background color with css classes

**Comment by flytedan** [comment]
+1 on this. I love vuetify, but the theming is absolutely horrible to deal with. If you want to write a custom theme, it is damn near impossible to get around all the theme--light styling. There really needs to be a way to diable the theme--light class. 

Also on a side note, what was the reasoning to apply this class on literally every component? Why not just a top level theme--light on the v-app and call it a day? Isn't that the whole point of cascading style sheets, so you don't have to apply the same class on literally every component, you can just apply one time globally / wherever needed?

**Comment by johnleider** [comment]
> Can we get an answer at least for @dragontheory's question? I have the same complaint. theme--light classes force !important styles all across the DOM, forcing me to override with !important! myself... It's not a good practice. Being able to remove theme--light would be ideal.

There are very few, if any, places left where !important is used in conjunction with theme styling. This is a non issue as far as I'm concerned.

> +1 on this. I love vuetify, but the theming is absolutely horrible to deal with. If you want to write a custom theme, it is damn near impossible to get around all the theme--light styling. There really needs to be a way to diable the theme--light class.

This is not even close to true. We have 1000's of variables that alter the styling of the application. If you're making changes via overwriting classes, you're doing it wrong.

> Also on a side note, what was the reasoning to apply this class on literally every component? Why not just a top level theme--light on the v-app and call it a day? Isn't that the whole point of cascading style sheets, so you don't have to apply the same class on literally every component, you can just apply one time globally / wherever needed?

It is the foundation for cascading dark and light theme styling when nesting components. Applying a global class doesn't work when components can exist in 2 states, light or dark.

---

While there have been numerous changes made to improve our styling structure and process, I agree there is still room for improvement but the general basis is by design. We utilize ITCSS & BEM concepts for building our stylesheets and utility classes are meant to have important.

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
