### ISSUE TITLE
[Feature Request] How to improve lighthouse score with Vuetify

### ISSUE THREAD

**Issue by husayt** [vuetifyjs/vuetify#7265]
### Problem to solve
We have a number of web sites with Vuetify and Nuxt. Vuetify works great for us, only concern is performance. As soon as we add vuetify Lighthouse score tumbles down. Most probably we don't follow best practices.

Here you can see lighthouse scores:
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.sozler.im
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fkoran.center

### Proposed solution
Would be great to have a realistic example (not a hello world) with a few components which would score high on LightHouse and which can be a point of reference. Maybe you will discover, indeed there is a performance issue with adding Vuetify to your website and no realistic app would score high with Vuetify on LightHouse. That will allow to identify issues and resolve them.

Meanwhile, some tips and performance guidelines for Vuetify would be appreciated by everyone here.

Thanks

**Comment by darylteo** [comment]
Just adding to this.

We have just noticed that Vuetify's implementation of buttons don't conform to Material Design/Google Accessibility Guidelines as reported by Lighthouse.

Touch Targets have to be 48dp by 48dp, but the default v-btn are only 40x40.

**Comment by johnleider** [comment]
We will look into the lighthouse issues. As far as the touch target, I'm not really sure what we can do about the buttons.

**Comment by KaelWD** [comment]
I'm guessing it would have to be something like this: https://codepen.io/anon/pen/EqZMvZ

**Comment by bengineer19** [comment]
Has there been any progress on strategies to improve Lighthouse score?
If there are ways to use Vuetify which don't significantly negatively impact performance scores in Lighthouse then it would be really useful to have some examples or a short mention in the docs.

Otherwise, it seems virtually impossible to use Vuetify in any reasonable application without dragging a lighthouse score down from green into orange or red.

**Comment by Sshuichi** [comment]
Any progress on this?
I can't make it past 80 (Without tracking nor ads..)

**Comment by johnleider** [comment]
Are any of your implementations available that I can see?

**Comment by Sshuichi** [comment]
Absolutely! 
I'll try to set it up today. But on the other hand, could you show us a site that is performing +90 on lighthouse using Vuetify?

**Comment by bengineer19** [comment]
Just running  `vue create my-app` then `vue add vuetify` as in the quickstart guide results in a demo page which when built has weirdly high FCP and TTI.

**Comment by Sshuichi** [comment]
@johnleider, I could reproduce the performance issues with the quickstart as @bengineer19 mentioned

**Comment by husayt** [comment]
That is probably the best place to start from. Then we can try to look into
problems with real websites, like for instance https://www.sozler.im/ or
https://koran.center. Google is heavily penalising these websites due to
performance issues.

>

**Comment by bengineer19** [comment]
Yep. I'm currently working on a new site with Vuetify to replace a legacy site with millions of users anually. Our biggest worry about changeover is that our Google rankings will take a dive because of the lighthouse hit incurred by Vuetify.

**Comment by tschut** [comment]
I'm the developer for wammes-gifts.nl, and according to https://developers.google.com/speed/pagespeed/insights/ the score for desktop is fine, but on mobile it's not.

@johnleider if it helps I can probably get you access to the repo for that, at least temporary?

**Comment by micardona96** [comment]
the performance scoring is only affected in the test by running on mobile, 

![image](https://user-images.githubusercontent.com/37484798/82556341-27b28300-9b2f-11ea-91c1-77c967718599.png)


How could I solve this, I emphasize that it is just the simple sample app, with:

` >> vue add vuetify`

https://api-springboard.web.app/#/

**Comment by syskin** [comment]
After some test with vuetify on a nuxtjs application, it seems to be that bad performances come from default icons load and fonts load.

If you try to remove default values, and import your own icons and fonts, your app you can easily get 95+ lighthouse score.

**Comment by Tajnymag** [comment]
@syskin Could you please share with us, what combination of fonts/icons fares well on Lighthouse? I've tried self hosting several roboto and icon fonts and it didn't lead to much better results.

**Comment by DRoet** [comment]
I think its also good to note that the lighthouse score heavily depends on the specs of the machine its being run on, for example on a slower machine I might get around a ~80, while on a fast machine I consistently get 96-97 using the same website

**Comment by Sshuichi** [comment]
@DRoet, That's for field Data, not lab data. Lab data should be consistent as it's simulating the same shitty device for all websites.

**Comment by syskin** [comment]
> @syskin Could you please share with us, what combination of fonts/icons fares well on Lighthouse? I've tried self hosting several roboto and icon fonts and it didn't lead to much better results. 

I follow the doc recommendation for production deployment, I import mdi/js (https://vuetifyjs.com/fr-FR/customization/icons/#installer-les-icones-material-design-js-svg)  and I override @fontface property in CSS file as it is said.

But I used the nuxtjs/vuetify module, so I don't know how you can override that properties in a classic vuetify app.

**Comment by yohane55** [comment]
I too have 38%  performance for my site. But the official vuetify site also have 41%.

<img width="1440" alt="Screen Shot 2020-06-15 at 7 59 18 PM" src="https://user-images.githubusercontent.com/9741727/84685551-295f4300-af43-11ea-81c7-b574dd8d62d9.png">

**Comment by Radiergummi** [comment]
To chime in here; I'm working on a new greenfield project and settled on Nuxt.js, Vuetify and TypeScript. We have Lighthouse results around 80 on desktop and 36 on mobile.  
What I found to be the hardest thing during development was creating a production setup. Almost all resources online seem to assume some kind of prototype or dev environment, not an actual performance-optimized production application. The Vuetify documentation doesn't help too much here, either: There's no section dedicated to production setup or optimization. Getting icons right, for example, requires digging deep into the docs until you find the relevant snippet:
> Use the SVG paths as designated in @mdi/js. This is the recommended installation when optimizing your application for production. You **ONLY** need to include this if you plan on using more than the default icons.

I understand this makes kind of sense given that not every application requires icons outside of Vuetify components, but it's really not obvious until you actively search for solutions to performance problems.  
Is there any guide for production setups somewhere? Could we, as a community, get together and create one, to be featured in the Vuetify documentation?

**Comment by husayt** [comment]
This is the single biggest problem with Vuetify and I still found no good solution to this. My websites are being heavily penalised by search engines for that, to the point that I have already migrated some of them away and some are in process. Currently my recomendation is unfortunately, if SEF&SEO are any concern Vuetify will not be the right choice. It's a shame, it has so many good features, but here we are.

**Comment by maartenvn** [comment]
You can easily remove unused CSS from @mdi/font by using PurgeCSS.
I am using this configuration with Vuetify and it stripped around 200kbs of the CSS bundle. Only the mdi icons used in the application are included in the actual bundle.

```sh
npm i @fullhuman/postcss-purgecss @fullhuman/vue-cli-plugin-purgecss
```

postcss.config.js

```js
const purgeCSS = require("@fullhuman/postcss-purgecss");

const PRODUCTION = process.env.NODE_ENV === "production";

module.exports = {
    plugins: [
        PRODUCTION &&
            purgeCSS({
                content: [
                    `./public/**/*.html`,
                    `./src/**/*.vue`,
                    `./node_modules/vuetify/src/**/*.ts`,
                    `./node_modules/vuetify/dist/vuetify.css`
                ],
                safelist: [
                    /-(leave|enter|appear)(|-(to|from|active))$/,
                    /^(?!(|.*?:)cursor-move).+-move$/,
                    /^router-link(|-exact)-active$/,
                    /data-v-.*/
                ]
            })
    ]
};
```

You could even `./node_modules/vuetify/dist/vuetify.css` if you whitelist the CSS classes that are injected at runtime and shave it down by almost 400kb in total (in my case).

You could even remove `

**Comment by Radiergummi** [comment]
@maartenvn Nice! I'm absolutely going to steal this snippet 😉 

On a serious note, though, that's exactly what I was talking about. Maybe we can collect stuff like this into a comprehensive guide for Vuetify production setups?

**Comment by Tajnymag** [comment]
@Radiergummi Why stop there? The snippet of @maartenvn could even be included in the official vuetify vue-cli plugin, thus everyone would get this optimization by default.

**Comment by Sshuichi** [comment]
PurgeCSS never worked out for me. But I will test this snippet hoping that it's working today.

**Comment by maartenvn** [comment]
I ended up switching to @mdi/js anyways, because the full webfont is still included with @mdi/font.

Unfortunately performance is still terrible. 

![image](https://user-images.githubusercontent.com/6013068/97777795-dfce6800-1b72-11eb-88e4-e2f511384190.png)

**Comment by husayt** [comment]
If you look in detail at LighouseLogs for what is causing performance issues, it's not css.
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.sozler.im

Purgecss is good step, but not the solution to the problem.

**Comment by Velikolay** [comment]
I'm also experiencing major performance issues on mobile, especially mid / low tier devices. Loading and changing between pages is painfully slow. Understandably the Lighthouse / Page Insights score is also low - can't make it past **50** on the google test for a static home page with very little content on it. It was my intention to use vuetify for the app's blog in order to reuse some of the layout and individual components, but that's unthinkable with this score and ux. 

It's a the javascript evaluation and execution that's slow, the **main-thread is busy for tool long**. Did some profiling on a **x4 slowdown** to replicate mobile.


Static page with a header / footer and minimal content: **2s execution**

![profiler-home](https://user-images.githubusercontent.com/4264791/103899327-e93df880-50fe-11eb-8412-80fb59b8a1e7.png)


Larger dynamic page with more components and API data: **5s execution**

![profiler-search](https://user-images.githubusercontent.com/4264791/103899337-ee02ac80-50fe-11eb-8811-8e4d023cf798.png)

After optimising everything there is, i'm stuck with these numbers. Tips are welcome.

**P.S.** I can confirm @husayt 's observation that css is not the main issue, yet it's a huge file and it can be an issue on a slow network. I tested the app without css (yes, ugly unstyled page) => was still just as slow.

**Comment by hagemann** [comment]
> But I used the nuxtjs/vuetify module, so I don't know how you can override that properties in a classic vuetify app.

To those who are also using nuxtjs/vuetify and are not making use of Vuetify fonts or icons, set `defaultAssets` to `false`. This helped me get the scores up from 42/91 (mobile/desktop) to 75/98.

I retained other render-blocking resources like polyfill and FontAwesome Kit which could give another boost if removed, but I’m happy enough for the time being. With that said, I think Vuetify is quite usable for production.

Source: https://github.com/nuxt-community/vuetify-module#defaultassets

**Comment by KaelWD** [comment]
You can eliminate the polyfills too with modern builds: https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-modern/

**Comment by maartenvn** [comment]
For those using Nuxt.JS in SSR mode, there is a way to drastically improve the lighthouse score using the package: [@luxdamore/nuxt-prune-html](https://www.npmjs.com/package/@luxdamore/nuxt-prune-html)

This package will strip unnecessary Javascript when a bot User-Agent is detected. Since the bad lighthouse score is mostly coming from the First Contentful Paint, this will drasticly improve the score.

**Note: this will not fix the performance issues with the framework itself for regular users. The main benefit here is that the search engine ranking will not be penalized due to bad performance.**

This is my performance on mobile, coming from a 34/100 score before:

![image](https://user-images.githubusercontent.com/6013068/106908797-ecc59f00-66ff-11eb-9f71-a6dd277da94f.png)

**Comment by Sshuichi** [comment]
> For those using Nuxt.JS in SSR mode, there is a way to drastically improve the lighthouse score using the package: [@luxdamore/nuxt-prune-html](https://www.npmjs.com/package/@luxdamore/nuxt-prune-html)
> 
> This package will strip unnecessary Javascript when a bot User-Agent is detected. Since the bad lighthouse score is mostly coming from the First Contentful Paint, this will drasticly improve the score.
> 
> **Note: this will not fix the performance issues with the framework itself for regular users. The main benefit here is that the search engine ranking will not be penalized due to bad performance.**
> 
> This is my performance on mobile, coming from a 34/100 score before:
> 
> ![image](https://user-images.githubusercontent.com/6013068/106908797-ecc59f00-66ff-11eb-9f71-a6dd277da94f.png)

**WRONG!** 
Search Engines consider the field data i.e what users experience with your site. IF you're using nuxt-prune, you're fooling only yourself or the manager who asked for a better performance. The speed report on search console and CrUX are the only source of truth about the signals search engines consider as ranking factor.

**Comment by maartenvn** [comment]
> > For those using Nuxt.JS in SSR mode, there is a way to drastically improve the lighthouse score using the package: [@luxdamore/nuxt-prune-html](https://www.npmjs.com/package/@luxdamore/nuxt-prune-html)
> > This package will strip unnecessary Javascript when a bot User-Agent is detected. Since the bad lighthouse score is mostly coming from the First Contentful Paint, this will drasticly improve the score.
> > **Note: this will not fix the performance issues with the framework itself for regular users. The main benefit here is that the search engine ranking will not be penalized due to bad performance.**
> > This is my performance on mobile, coming from a 34/100 score before:
> > ![image](https://user-images.githubusercontent.com/6013068/106908797-ecc59f00-66ff-11eb-9f71-a6dd277da94f.png)
> 
> **WRONG!**
> Search Engines consider the field data i.e what users experience with your site. IF you're using nuxt-prune, you're fooling only yourself or the manager who asked for a better performance. The speed report on search console and CrUX are the only source of truth about the signals search engines consider as ranking factor.

I wasn't aware of this. Do you have a source on that? Thanks

**Comment by KaelWD** [comment]
https://developers.google.com/search/docs/advanced/guidelines/cloaking

**Comment by Sshuichi** [comment]
https://blog.searchmetrics.com/us/core-web-vitals/

**Comment by Sshuichi** [comment]
> https://developers.google.com/search/docs/advanced/guidelines/cloaking

This is unrelated because the content from SSR is likely the same as the one with JS, only there is no hydration

**Comment by husayt** [comment]
Anyone here claiming to have fantastic lighthouse scores with Vuetify, please, also provide a link. Without seeing the complexity of website lighthouse score alone, even if it is achieved doesn't mean much.

**Comment by Sshuichi** [comment]
No need to provide a link. Lab data is bullshit. Talk to me field data ;) 
![image](https://user-images.githubusercontent.com/5939429/106927861-e0970d00-6712-11eb-85fd-3003d68e1692.png)

**Comment by husayt** [comment]
> No need to provide a link. Lab data is bullshit. Talk to me field data ;)
> ![image](https://user-images.githubusercontent.com/5939429/106927861-e0970d00-6712-11eb-85fd-3003d68e1692.png)

@Sshuichi, you can take that screenshot from anywhere. So that doesn't mean anything, as well as previous screenshots you provided

**Comment by Sshuichi** [comment]
hehehehe I didn't provide any screenshot before but whatever makes you sleep at night :)

**Comment by husayt** [comment]
> hehehehe I didn't provide any screenshot before but whatever makes you sleep at night :)

Sorry, saw your name under previous screenshot. Didn't realise that you were replying.

**Comment by Sshuichi** [comment]
But hey, Vuetify does come with some heavy ass components that can be optimized heavily. 
For example the Skeletons, they're using the main thread to animate the loaders which is crazily expensive. The right way is to use GPU. 
I tweeted about this in the past but I don't know if it's been taken care of. 
https://twitter.com/aysennoussi/status/1290176046696816640

**Comment by Tofandel** [comment]
I got my score at 80 using prerendering, some preloading and lazy loading. But yeah it looks like most of the performance issue (The last 20%) comes down from the core and could be see a few optimizations to get the performance we deserve :100:

**Comment by johnleider** [comment]
> I tweeted about this in the past but I don't know if it's been taken care of.
> [twitter.com/aysennoussi/status/1290176046696816640](https://twitter.com/aysennoussi/status/1290176046696816640)

I did not see this, we'll look into it. Thank you

**Comment by johnleider** [comment]
Working with the Vuetify preset, these are my results for local and web.dev:

[deployed-lighthouse-incognito](https://gist.github.com/johnleider/ea458124215c9a2984e4c2bce8972d0d)
[deployed-lighthouse-webdev](https://gist.github.com/johnleider/c3cebb9ed257125bc626483a6ebc41b4)

Not sure how to reconcile this.

**Comment by Sshuichi** [comment]
That's actually consistent. Because all the measurements are tightly related to the FCP. The higher the FCP, the higher everything else because everything else starts calculating after FCP, so if FCP takes 5 secs, everything else will be +5s. 

I'm saying it's consistent because the difference between TTI or Speed index from the FCP is closely the same on both web.dev and Lighthouse. 

Now why does it have 5s FCP? Lots of reasons but mainly related to the server, not the Vuetify.

**Comment by mcoolidge** [comment]
> Anyone here claiming to have fantastic lighthouse scores with Vuetify, please, also provide a link. Without seeing the complexity of website lighthouse score alone, even if it is achieved doesn't mean much.

Very simple example here: https://www.orbitalhealth.co/

Didn't do much to optimize yet.

![image](https://user-images.githubusercontent.com/986728/116884064-4e5cb300-abf4-11eb-86b3-039148407799.png)

**Comment by maartenvn** [comment]
> Didn't do much to optimize yet.
> 
> ![image](https://user-images.githubusercontent.com/986728/116884064-4e5cb300-abf4-11eb-86b3-039148407799.png)

PageSpeed Insights says otherwise:

![image](https://user-images.githubusercontent.com/6013068/116884878-89c4a500-ac27-11eb-9b65-435881c1a3ac.png)

https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fwww.orbitalhealth.co%2FPlatform

---

At VueConf US John Leider said Vuetify v3 will have major performance improvements. So it looks like the future is bright in terms of performance :slightly_smiling_face:

**Comment by mcoolidge** [comment]
Thx for the heads up. Love how easy and consistent lighthouse tools are 😉

**Comment by ManasMadrecha** [comment]
I use **Nuxt + Content + Tailwind + Vuetify**. I was able to improve the **score for Mobile to 87** and **for Desktop to 94**. 😃

![image](https://user-images.githubusercontent.com/65993481/121843565-1fac1f00-cd00-11eb-830e-470540e3549d.png)

![image](https://user-images.githubusercontent.com/65993481/121843626-3fdbde00-cd00-11eb-906f-14a3a31d6f51.png)

### Things I did

1. Tailwind has the great JIT feature. So, I can use its utility classes like margin, padding, colors, etc endlessly. So I don't need Vuetify's colors and all. I only use Vuetify for the javascript stuff. Whenever I need to color some button or icon, I can simply use `tw-text-blue-700`, etc. So, I have **disabled all the colors and utility classes of Vuetify**. This itself had the biggest improvement with the `view-source page` reducing from 30k lines to half.

```sass
$color-pack: false 
// https://vuetifyjs.com/en/styles/colors/#sass-color-pack

@import '~vuetify/src/styles/styles.sass'

@each $name, $value in $utilities  
  $utilities: map-merge($utilities, ($name: false))

```

2. Next, I have set the `defaultAssets` to false inside the Nuxt Vuetify module.
3. Next, instead of using cdn's mdi fonts, I have installed `mdi/js`, so that I can import only a couple of dozens font I will ever use either in `.vue` files or in `Content`'s markdown files.
4. And, of course `treeshake` has been set to true in Nuxt Vuetify module.


### Pending issues with Vuetify

1. I use a sidebar menu with `v-navigation-drawer`, which is toggleable from a button placed on `v-app-bar`. But it causes huge Cumulative Layout Shift on Desktop because it opens up later. Maybe it is because of this: 

> While the $vuetify object supports SSR (Server-Side Rendering) including platforms such as NUXT, the breakpoint service detects the height and width values as 0. This sets the initial breakpoint size to xs and in some cases can cause the layout to snap in place when the client side is hydrated in NUXT.

However, this is not an issue on Mobile, and on for Desktop, other parameters can compensate for this one issue.

2. Also, the `v-breadcrumbs` again cause huge CLF.

3. Vuetify still loads so much CSS, even for the components I haven't used anywhere like v-alert, ripple etc. So, it again can seek inspiration from Tailwind's JIT.

But compared to when I first used Vuetify with no changes made, this is remarkable improvement in score. So, no major complaints against this amazing library. 💛

**Comment by johnleider** [comment]
@ManasMadrecha If you'd be interested in helping us beef up our performance documentation, please reach out to me in Discord community, https://community.vuetifyjs.com.

**Comment by johnleider** [comment]
I believe that this issue has been adequately discussed and worked on over the years. The core team is focused on Vuetify 3 and I don't anticipate us revisiting anything performance-related outside of a community pull request.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by black2002** [comment]
Recently completed a [website](https://znizhki.by/otzyv/belarus/filmy/dom-guchchi-1642347243?t=1) on Laravel + Vuetify. About a year was spent on improving the performance.
Now everything is OK.
Desctop
![gucci_desctop](https://user-images.githubusercontent.com/24980488/149910271-af5a14bc-8c8f-4175-bf3e-8b5ad6a3021f.JPG)
Mobile
![gucci_mobile](https://user-images.githubusercontent.com/24980488/149910295-33634a94-2b0e-4c66-8c9e-7370175bfb38.JPG)
I will share my experience.
1. in production, a really fast server, the best of its kind, not just average in speed, but fast one with minimal ping
2. don't make the whole page Vue component <component/> , it loads abruptly after some delay, which is especially noticeable on a mobile device, I mean <body><component/></body>
3. loading :prop={{json_encode($var)}} is an error, this is a slow function, the bigger $var, the more delay. If $var is a static value, import it in app.js ( now:  :prop="prop").
4. Image optimisation and etc. 
5. lazy v-tab:  <v-tabs-items v-model="tab"> <v-tab-item value="tab-1" key="1" **v-if="tab=='tab-1'"**>

**Comment by johnleider** [comment]
> I also had problems getting a good lighthouse score. I found out that using v-footer is causing a significant layout shift. Wrapping v-footer in a v-lazy solved that issue and increased my score significantly.

In v2 or v3?

**Comment by chrfritsch** [comment]
> > I also had problems getting a good lighthouse score. I found out that using v-footer is causing a significant layout shift. Wrapping v-footer in a v-lazy solved that issue and increased my score significantly.
> 
> 
> 
> In v2 or v3?

In v3

**Comment by johnleider** [comment]
Could you provide me with some markup to reproduce this?
