### ISSUE TITLE
[Bug Report] Combobox onblur called after onclick on a button

### ISSUE THREAD

**Issue by robertotrapletti** [vuetifyjs/vuetify#7329]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
Click of button update is execued before onblur of the combobox. (new values)
1.type 'C' in the combobox
2.click on button "update" -> nothing happens
3.click oone more time -> the updatedCategory variable is updated with 'C'

### Expected Behavior
before onblur and then click of button

### Actual Behavior
before click and then onblur

### Reproduction Link
<a href="https://codepen.io/robertotrapletti/pen/MdqLar" target="_blank">https://codepen.io/robertotrapletti/pen/MdqLar</a>

**Comment by tcourtqtm** [comment]
+1 

In our app we are experiencing this scenario:

1. User types something _very important_ into a VComboBox on a form
2. User clicks the form submit button
3. Form is submitted **without the value that the user typed** because the button click is happening after the ComboBox emits the user-typed value

This is actually a very serious problem for us because there is _no indication to the user at all_ that what they filled into the box isn't what is being submitted.

**Comment by tcourtqtm** [comment]
Here is a pen that demonstrates the problem: https://codepen.io/tctimmeh/pen/XWbNgrx

- Type something into the combox and hit submit without clicking outside the combobox. The button click handler doesn't see the latest value. 
- Type something different and hit submit, again without clicking outside the combobox. The button click handler sees the _previous_ value.

**Comment by AntonLugtenburg** [comment]
Hello :),

 any news on this ? Can't use a form made out of comboboxes when somebody is using mouse to submit without trickery, 
 Will this be fixed in Vuetify v3 ?

**Comment by KaelWD** [comment]
You can just wait one tick with `setTimeout()` before submitting the form. This would have been fixed by the fix for #11989 but it caused #12586
