### ISSUE TITLE
[Bug Report] Missing docs about slots for v-radio

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#7331]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
If you search for **v-radio** API documentation

https://vuetifyjs.com/en/components/selection-controls

 there is written nothing about available slots. However, I noticed that **v-radio** has i.e. "label" slot.

### Expected Behavior
Docs should mention about slots for **v-radio**

### Actual Behavior
Docs are incomplete

### Reproduction Link
<a href="https://codepen.io/ sorry I have to paste sth to bypass validation" target="_blank">https://codepen.io/ sorry I have to paste sth to bypass validation</a>

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/en/components/selection-controls#label-slot

and 

![image](https://user-images.githubusercontent.com/15625235/58574542-5e322680-826a-11e9-9ab4-0deb3955d3e6.png)

**Comment by Mikilll94** [comment]
Hey. I said that that documentation is missing for **v-radio** component. Not **v-radio-group**

**Comment by MajesticPotatoe** [comment]
Wont likely be updated in v1.5 of docs, until at least after next docs are released as api-gen have undergone some changes that would cause merge conflicts, and this slot hasn't changed since then. Almost all (and I say that because human error is always a factor) missing api props/slots/events will be resolved by then as its part of a greater update outlined in #7047.
