### ISSUE TITLE
[Bug Report] Strange behavior on Iphone 7

### ISSUE THREAD

**Issue by Airhune** [vuetifyjs/vuetify#7492]
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.5.21
**Browsers:** Google Chrome, Safari
**OS:** iOS

I've replaced images for text but there is no any difference.
It can be tested too in the testing environment: https://odour.100x100.net/

### Steps to reproduce
It is almost impossible to reproduce. In most mobile devices, the application looks correct. But I have a bug with an iphone 7: the icons in the top menu are not shown, showing only the blank bar. I can not debug it because the device belongs to a user and I do not have more information. I would be very grateful if you could give me any idea why this happens.

### Expected Behavior
The menu is displayed correctly (buttons on both corners and the logo in the middle)

### Actual Behavior
On some iOs devices the icons and logo are not shown, only the white bar appears

### Reproduction Link
<a href="https://codepen.io/airhune/pen/YoPdge" target="_blank">https://codepen.io/airhune/pen/YoPdge</a>

**Comment by johnleider** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
