### ISSUE TITLE
[enhancement] - make v-select recieve default value onload like v-btn-dropdown do

### ISSUE THREAD

**Issue by jofftiquez** [vuetifyjs/vuetify#766]
### What is expected ?

I understand that `v-btn` was made to work with `v-app-bar`. But wouldn't it be nice if it `v-select` could receive a default value via `v-model` like `v-btn` do?

When model is explicitly declared from the `data()` function, it should reflect to the `v-select` in the DOM.

### What is actually happening ?

It just stays blank onload of the component.

### Reproduction Link

https://jsfiddle.net/greenfoxx/gpcykkeb/3/

**Comment by johnleider** [comment]
This is happening because you are not specifying the value of your select items. By default, the select looks for 2 fields, text and value for objects, or if supplied with a string, it considers the string to be the value and the text.

If you do not supply a value when providing options to the select, you must tell it where to look for it. If you add the prop ```item-value="text"``` to your select everything will work as expected.

**Comment by jofftiquez** [comment]
As always thanks @johnleider
