### ISSUE TITLE
[Bug Report] Tabs not overflowing correctly when inside a tool or app-bar

### ISSUE THREAD

**Issue by restofever** [vuetifyjs/vuetify#7720]
### Versions and Environment
**Vuetify:** 2.0.0-beta.4
**Vue:** 2.6.10
**Browsers:** Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer
**OS:** iOS, Windows, Android, Mac OSX

### Steps to reproduce
Discovered this issue when trying to use VTabs inside of VToolbars and VAppBars.  

### Expected Behavior
Expecting tabs to overflow inside the toolbar container like they do inside of [cards](https://codepen.io/restofever/pen/MMVVjP)

### Actual Behavior
Tabs overflow outside of the wrapping toolbar container

### Reproduction Link
<a href="https://codepen.io/restofever/pen/NZYYPa" target="_blank">https://codepen.io/restofever/pen/NZYYPa</a>

**Comment by MajesticPotatoe** [comment]
seems to be due to `.v-toolbar__content, .v-toolbar__extension` using `display: flex;` whereas v-card uses `display: block;`
simple workaround would be to add 
`.v-toolbar__extension {
  display: block !important;  
}` i think explicitly setting in source though breaks the nature of v-toolbar though.
