### ISSUE TITLE
[Bug Report] v-card-title long text bug

### ISSUE THREAD

**Issue by menthos984** [vuetifyjs/vuetify#7730]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
add long 1 word text like Supercalifragilisticexpialidocious

### Expected Behavior
Long texts should be automatically put to a newline

### Actual Behavior
Long texts triggers an overflow of text out the card

### Reproduction Link
<a href="https://codepen.io/menthos984/pen/bPMmbP?&editable=true&editors=101" target="_blank">https://codepen.io/menthos984/pen/bPMmbP?&editable=true&editors=101</a>

**Comment by Mikilll94** [comment]
Looks bad only on small screen size.

**Comment by jacekkarczmarczyk** [comment]
workaround: add `style="word-break: break-all"` to `v-card-title`

**Comment by sh7dm** [comment]
![image](https://user-images.githubusercontent.com/19504461/60964165-4e067000-a31b-11e9-8b5c-41eb4c4a7152.png)
![image](https://user-images.githubusercontent.com/19504461/60964179-5494e780-a31b-11e9-8904-3ae37321f957.png)
just `max-width: 100%` on internal div

**Comment by gregveres** [comment]
@avengerweb  I really don't think this is a good approach to the fix. There is a trade off. I was just about to create a defect saying that by default v-card-title breaks lines mid-word, which is, in my opinion, is way worse than the example in this bug. 

I am using v-card in a dialog and with a long dailog title on small screens, I am seeing a title like this:

Select the membership T
ype

When I would have expected it to be:

Select the membership
Type

It seems like an odd default to use break-all instead of break-word.

**Comment by avengerweb** [comment]
@gregveres yes I think about it, and I think u are right we should rollback this part, coz long words rare case compare to long title that looks very bad. @johnleider
