### ISSUE TITLE
[Bug Report] The data property "rules" is already declared as a prop. Use prop default value instead.

### ISSUE THREAD

**Issue by prashanth4** [vuetifyjs/vuetify#7771]
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
On extending v-auto-complete, i am getting warning that data property "rules" is already declared as a prop. Use prop default value instead.

### Expected Behavior
No warnings

### Actual Behavior
getting warnings

**Comment by jacekkarczmarczyk** [comment]
Probably you're declaring data property "rules" which is already declared as a prop. Hard to say anything without reproduction

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by elirehema** [comment]
I have been struggling to resolve the same issue in my NuxtJs project. And I discovered that giving the mixins property the same name as a prop was the problem. 
E.g If I have this value in mixing ``` rules: [(v) => !!v || 'Field is required']``` and used it in the text-field as ```:rules="rules"``` was the source of error I just renamed the mixing rules from ```rules:[(v) => !!v || 'Field is required']``` to ```fieldrequiredrules:[(v) => !!v || 'Field is required']``` And the warning dismissed. 

 I had two properties warning the same message and all had the same name as a prop and all fixed by renaming with other name
