### ISSUE TITLE
[Bug Report] Wrong caret behavior with 3rd party masking libs

### ISSUE THREAD

**Issue by 1001v** [vuetifyjs/vuetify#7784]
### Versions and Environment
**Vuetify:** 2.0.0-beta.5
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
Open the [vue-the-mask example](https://next.vuetifyjs.com/ru/components/text-fields#masks-using-vue-the-mask) and insert smth into the center of the input

### Expected Behavior
The caret should stay at it's last position, as it happens [here](https://vuejs-tips.github.io/vue-the-mask/)

### Actual Behavior
The caret jumps to the end of the line

### Reproduction Link
<a href="https://codepen.io/anon/pen/jjXmOG?editors=1011" target="_blank">https://codepen.io/anon/pen/jjXmOG?editors=1011</a>

### Other comments
This happens with other masking libraries as well, such as this: https://www.npmjs.com/package/di-vue-mask

**Comment by 1001v** [comment]
This issue presents in vuetify 1.5 as well.

**Comment by diazemiliano** [comment]
@1001v  A workaround i'm doing using `vue-the-mask` is to reset the selection on a setter:
``` javascript 
customComputed: {
  get(){
    ...
  },
  set(){
  this.$nextTick(() => {
    this.$refs.theInput.setSelectionRange(
      this.$refs.theInput.selectionStart(),
      this.$refs.theInput.selectionEnd()
    );
  });
  }
}
```

**Comment by YipingRuan** [comment]
The link https://next.vuetifyjs.com/ru/components/text-fields#masks-using-vue-the-mask is not longer valid..

**Comment by johnleider** [comment]
We've since removed our example of vue-the-mask. I did reach out to the author to see if they would be interested in updating the plugin. It hasn't been updated in awhile and as we plan to bring back masking. I'm going to close this as resolved.

This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
