### ISSUE TITLE
v-select hidden behind v-edit-dialog

### ISSUE THREAD

**Issue by german970814** [vuetifyjs/vuetify#779]
### Steps to reproduce
(see code pen below)

### Versions

0.12.7

### What is expected ?

v-select should appear on top off v-edit-dialog

### What is actually happening ?

v-edit-dialog is hidden behind v-select

### Reproduction Link

https://codepen.io/anon/pen/ZyLQmR

**Comment by amitailanciano** [comment]
I think this is basically the same issue as #771 , maybe whatever is done to fix this could apply to 771

**Comment by johnleider** [comment]
You are correct. Small dialog was just forgot. Poor guy!

**Comment by johnleider** [comment]
After testing multiple implementations of this, it's a side effect of having the items appended. Since in Vue, component children are processed before the parent, the elements will always line up in a way that makes the child not show. The best way to handle this may be the custom class declaration unless anyone else has  a suggestion.

**Comment by Gostwow** [comment]
I believe this can be easily solved by giving a higher `z-index` to the dialog's children.
