### ISSUE TITLE
[Bug Report] Error when using a RegExp in group property of v-list-group

### ISSUE THREAD

**Issue by garcianavalon** [vuetifyjs/vuetify#7812]
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
https://codepen.io/anon/pen/WqWxvE?editors=1111

### Expected Behavior
group property in v-list-groups accepts RegExp, as stated in the docs.

### Actual Behavior
Invalid prop: type check failed for prop "group". Expected String with value "/foo/g", got RegExp

### Reproduction Link
<a href="https://codepen.io/anon/pen/WqWxvE?editors=1111" target="_blank">https://codepen.io/anon/pen/WqWxvE?editors=1111</a>

### Other comments
This used to work, but I can't figure out in which Vuetify version

**Comment by hugoazevedosoares** [comment]
I don't have a lot of experience with the code base, but do you guys think that if we update the group prop on the VListGroup.ts file it will fix this? Now it takes a String and my proposal is to change it to receibe both Strings and RegExp.

![image](https://user-images.githubusercontent.com/23644433/61303139-66640800-a7bd-11e9-933b-6c6e1d3286dc.png)

Already checked where the 'group' prop is used and seems to be on a single validation in the 'matchRoute' method of the same file. Since it is matching the route to the group prop, I think it will do the same job if it was a RegExp.

**Comment by jacekkarczmarczyk** [comment]
Yeah, I looked at it before and I think that this is valid solution

**Comment by hugoazevedosoares** [comment]
Nice. I'll make a PR

**Comment by hugoazevedosoares** [comment]
I'm having a problem here. When I changed the group prop from `group: String` to whats on the first image, my editor is pointing this errors on the second image.

![image](https://user-images.githubusercontent.com/23644433/61337313-4bb88000-a80b-11e9-99a7-de49825e5ede.png)

![image](https://user-images.githubusercontent.com/23644433/61337364-7571a700-a80b-11e9-96f8-16a74d13ef1a.png)

Already runned all the test and linting suites, and everything was fine. Can someone explain this to me? Should I commit this anyway because it's just a bug with my VSCode?

**Comment by hugoazevedosoares** [comment]
@jacekkarczmarczyk do you have any clues about this?

**Comment by jacekkarczmarczyk** [comment]
not really, it's working for me (both in vscode 1.36.1 and in yarn lint)

**Comment by hpo14** [comment]
why this hasnt fixed ?

**Comment by KaelWD** [comment]
That description was added in 54038a7ad3b6e8df61dd13c6198b19d937bc8aa7. The group prop hasn't been touched since b8801e45df657e70edebe0cf9744025c09dba0bc.
