### ISSUE TITLE
[Feature Request] Prepend icon for calendar event v2.x

### ISSUE THREAD

**Issue by trongtran178** [vuetifyjs/vuetify#7874]
### Problem to solve
This will describe the meaning of the event in detail for calendar component.
This is codepen illustrate the issue: https://codepen.io/trongtn178/pen/PMwNXO

### Proposed solution
Have an event-icon props like event-name, event-text-color, ... props

**Comment by ClickerMonkey** [comment]
The code example you shared used 1.5.6, this is an updated example with 2.0.3 which uses the new event-name prop to pass a function which is given an event and you return HTML you want to display in the event DIV.

https://codepen.io/anon/pen/PMmpZV

Since there are so many potential things you could add in there, I'm not sure yet if we'll add this feature.

**Comment by nekosaur** [comment]
@ClickerMonkey Your solution is not really idiomatic Vue though. You won't be able to use Vue components in the html string. Is there no slot for this?

**Comment by KaelWD** [comment]
If you're returning html it's just a scoped slot with less features.

**Comment by trongtran178** [comment]
> The code example you shared used 1.5.6, this is an updated example with 2.0.3 which uses the new event-name prop to pass a function which is given an event and you return HTML you want to display in the event DIV.
> 
> https://codepen.io/anon/pen/PMmpZV
> 
> Since there are so many potential things you could add in there, I'm not sure yet if we'll add this feature.


Thanks so much for your solution.

**Comment by ClickerMonkey** [comment]
You're right @KaelWD & @nekosaur, I have a slot for that and forgot about it:

https://codepen.io/anon/pen/PMmpZV
