### ISSUE TITLE
[Bug Report] vuetify slide-groups/simple/carousel.vue doesn't work

### ISSUE THREAD

**Issue by alexlai5128** [vuetifyjs/vuetify#7967]
### Environment
**Vuetify Version:** 2.0.0
**Last working version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
from this link: https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/slide-groups/simple/carousel.vue

vuetify slide-groups/simple/carousel.vue doesn't work, it shows a blank to me...

### Expected Behavior
https://user-images.githubusercontent.com/30002046/61802786-a719ec00-ae63-11e9-871f-af1d0d2e61ef.png

### Actual Behavior
https://user-images.githubusercontent.com/30002046/61802745-92d5ef00-ae63-11e9-8d9a-37faa29dfcaf.png

### Reproduction Link
<a href="https://github.com/alexlai5128" target="_blank">https://github.com/alexlai5128</a>

**Comment by MajesticPotatoe** [comment]
Repo link does provide an actual reproduction. Will need a little more info about your environment, as The example works fine in codepen. https://codepen.io/anon/pen/JgXVjj

**Comment by johnleider** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by johnleider** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
