### ISSUE TITLE
[Bug Report] Class text-xs-center does not center text anymore

### ISSUE THREAD

**Issue by VincentMarrec** [vuetifyjs/vuetify#8003]
### Environment
**Vuetify Version:** 2.0.0
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Linux x86_64

### Steps to reproduce
Use a container like a v-card
Add in it a \<p\> that has takes all the width with some text
Add the "text-xs-center" class

### Expected Behavior
The text should be centered on any viewport

### Actual Behavior
The text is not centered on any viewport

### Reproduction Link
<a href="https://codepen.io/anon/pen/jgrxvQ?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/jgrxvQ?&editable=true&editors=101</a>

### Other comments
In Chrome DevTools the class "text-xs-center" is applied to to \<p\> but doesn't seem to exist in css.
If you add to the \<p\> element : 
text-align: center;
il will work as expected (without the viewport considered)

**Comment by KaelWD** [comment]
Please read the [upgrade guide](https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0#user-content-upgrade-guide)

**Comment by gvonderau** [comment]
I read it.  No mention of it.

**Comment by danleyb2** [comment]
it's here https://vuetifyjs.com/en/getting-started/releases-and-migrations/

**Comment by gregveres** [comment]
In case anybody stumbles upon this issue and wonders what "unless overridden" means in the migration guide, here is the answer. 
When I first read the migration guide I had no idea what "unless overridden" means. It turns out that there are text-{bp}-left and text-{bp}-right classes that can be used to pull the contents of the div left or right on bigger screens. 

So if you want to have an item that is centered on a xs,sm screens and left justified on md and larger screens, use the following classes: 
class="text-center text-md-left"

The text-md-left overrides the text-center once the screen size gets to md or larger.
