### ISSUE TITLE
[Bug Report] I'm facing issue on cluttering the screen of every page of layout using Vuetify UI component

### ISSUE THREAD

**Issue by akash58** [vuetifyjs/vuetify#8038]
### Environment
**Vuetify Version:** 1.5.14
**Last working version:** 1.2.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142, Google Chrome, Mozilla Firefox, Opera, Internet Explorer, Microsoft Edge, Other, Safari
**OS:** Linux x86_64, Windows, Mac OSX, Linux, iOS

### Steps to reproduce
Vuetify version 1.5.14
1) Removed app.styl in nuxt.config.js 
2) Included in vuetify.js
3) I don't get the css duplicate issue in pagesVuetify version 1.5.14

### Expected Behavior
I'm expecting don't clutter the screen after refresh the page

### Actual Behavior
Vuetify version 1.2.10
1) Added app.styl in nuxt.config.js 
2) not include in vuetify.js
3) But i get the css duplicate issue in pagesVuetify version 1.2.10

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

### Other comments
I'm facing the issue of clutter the screen layout on reload the every page. Currently i'm using the Vuetify version - '1.5.14', Nuxt version - '2.7.1'. I removed the app.styl from nuxt.config.js because of css code repeat in every page and added the directly in plugin vuetify.js as "import 'vuetify/src/stylus/app.styl';". I don't know what is exactly issue Please help someone about this issue.

import 'vuetify/src/stylus/app.styl';
added directly in vuetify.js

**Comment by akash58** [comment]
`
![Screenshot_2019-07-26-13-06-26-62](https://user-images.githubusercontent.com/25900706/61940880-f40cd800-afb3-11e9-9f8d-d8f8017f815b.png)
`

**Comment by johnleider** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by johnleider** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
