### ISSUE TITLE
[Bug Report] vtextfield outlined solo not work height

### ISSUE THREAD

**Issue by lpj145** [vuetifyjs/vuetify#8051]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
```html
<v-text-field
  placeholder="Username"
  id="id"
  solo-inverted
  outlined
  flat
  height="10"
  class="mt-1"
></v-text-field>
```

### Expected Behavior
Expected minor height from default height.

### Actual Behavior
...

### Reproduction Link
<a href="https://codepen.io/anon/pen/MNjxJb" target="_blank">https://codepen.io/anon/pen/MNjxJb</a>

**Comment by lpj145** [comment]
step to fix: https://codepen.io/anon/pen/wVzZwz

**Comment by johnleider** [comment]
This field actually isn't hooked up, just unfortunately added to the api because of how its structured. The reason it doesn't work is css defines a min-height for the field and height doesn't override that.

I think since it never did anything, I might end up removing this prop and supporting regular / dense inputs as to not have to account for a myriad of potential custom height issues.

**Comment by lpj145** [comment]
maybe make sense, but with little css i can work as expected, but, my idea is use vtextfield so simple normal field. :)

![image](https://user-images.githubusercontent.com/11980109/61980950-976ae680-afce-11e9-9531-39c49be4ed52.png)

**Comment by lpj145** [comment]
the pen solved issue with select, textfield, textarea.
