### ISSUE TITLE
[Bug Report] App Bars，Some content will not be displayed

### ISSUE THREAD

**Issue by JokerLoLgrey** [vuetifyjs/vuetify#8117]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
none

### Expected Behavior
none

### Actual Behavior
none

### Reproduction Link
<a href="https://codepen.io/JokerYM/pen/Jgbzmv" target="_blank">https://codepen.io/JokerYM/pen/Jgbzmv</a>

### Other comments
none

**Comment by jacekkarczmarczyk** [comment]
You're missing v-content (which is used to calculating the content size when using app bar with `app` prop) and there's a lot of console errors in your codepen, please fix them first

**Comment by JokerLoLgrey** [comment]
> You're missing v-content (which is used to calculating the content size when using app bar with `app` prop) and there's a lot of console errors in your codepen, please fix them first

the mistake is not  'material-design-icons-iconfont/dist/material-design-icons.css'

**Comment by johnleider** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by stact** [comment]
related to #8364 ?

**Comment by johnleider** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
