### ISSUE TITLE
[Bug Report] v-list-item misalignment

### ISSUE THREAD

**Issue by Namchee** [vuetifyjs/vuetify#8118]
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Just toggle the menu

### Expected Behavior
Perfectly vertically-aligned `v-list-item` contents

### Actual Behavior
The icon part is misaligned. Inserting only 2 childs is fine though.

### Reproduction Link
[Codepen link](https://codepen.io/anon/pen/pMPaOV)

### Other comments
This issue can be solved with `align-self: center` in the `v-list-icon` but, maybe it doesn't meant to be vertically-centered at all?

Note: `v-list-icon` is undocumented in [v-list documentation](https://vuetifyjs.com/en/components/lists), but the documentation used it in one of the example.

**Comment by jacekkarczmarczyk** [comment]
That's too much for a repro, please use codepen with only relevant code
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by Namchee** [comment]
I'm sorry about that, [here you go](https://codepen.io/anon/pen/gVLJwx).

Basically, I used non-standard font-size on `v-list-item-title`. Using some non-Roboto-like fonts also breaks this.

Note: I don't get why some icon doesn't work correctly, it's unrelated to this issue but, I want to post a separate issue.

**Comment by johnleider** [comment]
I honestly don't see what is wrong here. If you are using non-standard fonts/font-sizes, you need to reproduce this in the codepen.

You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by Namchee** [comment]
I've updated my repro link both on the first post and my last comment. Plus, I've added some images to explain the issue. As you can see in the below image, the icon is not vertically centered if a content has a non-standard size.

![Sample Image](https://i.ibb.co/sVg8VJ4/v-list-bug.png)

**Comment by nekosaur** [comment]
This is caused by `.v-list-item__icon` having `align-self: flex-start`

**Comment by johnleider** [comment]
I'm not sure how to approach this because the spec gives mixed feedback.

Here is the spec definition for 2 line (also applies to 3 line):

![image](https://user-images.githubusercontent.com/9064066/62470315-cf58f300-b75f-11e9-9733-58373a741f38.png)


And here is one of the examples on the same specification page:

![image](https://user-images.githubusercontent.com/9064066/62470347-dbdd4b80-b75f-11e9-8d11-88bdbd883eed.png)

I'm not sure which one to interpret, and of course the MWC implementation doesn't even display the use-case: https://material-components.github.io/material-components-web-catalog/#/component/list

Here is the list spec for reference: https://material.io/design/components/lists.html

Thoughts on how we should approach this @vuetifyjs/core-team ?

**Comment by nekosaur** [comment]
I'd imagine centering things would be the ideal/expected result in _most_ cases

**Comment by johnleider** [comment]
This is the default behavior in v3 for `v-list` and only aligns to the top when using **lines="three"**. In addition, the recommended way to do this within a card is using the new props or through the default slot.

https://codepen.io/johnjleider/pen/bGqjraR

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
