### ISSUE TITLE
[Bug Report] base-card sizing problem

### ISSUE THREAD

**Issue by alexlai5128** [vuetifyjs/vuetify#8151]
### Environment
**Vuetify Version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
blob:https://pasteboard.co/IqeVuE2.jpg

### Expected Behavior
The max-width: 1300px;  Not 1000px as default setting

### Actual Behavior
It's default fixed at 1000px in a hidden child div

### Reproduction Link
<a href="https://github.com/likw00/letbebest_first_draft" target="_blank">https://github.com/likw00/letbebest_first_draft</a>

**Comment by johnleider** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by alexlai5128** [comment]
> You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.
> 
> You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).
> 
> Services to create a reproduction:
> 
> * [Codepen](https://template.vuetifyjs.com)
> * [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
> * [Codesandbox](https://codesandbox.io)
> * [JSFiddle](https://jsfiddle.net/)
> * A small reproduction repository
> 
> Thank you for your contribution and interest in improving Vuetify.

I'm sorry that Idk how to use codepen with your vuetify...   
But here is my code of the problemed page: [](https://github.com/likw00/letbebest_first_draft/blob/master/website/src/components/home/Contents.vue)

And it's my website, you can see the contents in the middle are fixed only by max-width="1000px";
However, I want to let out to 100%....
I can override it on google chrome editor, how seems it's hidden on your code.

### Current problem of fixed max-width="1000px"
**![image](https://user-images.githubusercontent.com/30002046/62224909-0048c900-b3ea-11e9-922b-b405f46a6f4f.png)**


**### Expected result that can override by chrome editor**
![image](https://user-images.githubusercontent.com/30002046/62224663-9e885f00-b3e9-11e9-90b4-628bb0bcf5ee.png)

**Comment by johnleider** [comment]
I'm still nowhere closer to understanding what your issue is.

**Comment by alexlai5128** [comment]
> I'm still nowhere closer to understanding what your issue is.

Sorry, here is the story..

I used your template "Landing", which is from Vuetify version 1.5.  Inside this template, there is a file home.vue that has a component call <base-card>, it has a hidden child <div> inside this <base-card>, this <div> max-width defaulted at 1000px, and nowhere to find at the editor code...

I want to set the max-width more than 1000px....  How can I do that?

**Comment by KaelWD** [comment]
You have something like `<v-card max-width="1000">`, just change that.
