### ISSUE TITLE
[Feature Request] v-expansion-panels flat style request

### ISSUE THREAD

**Issue by ksbgenius** [vuetifyjs/vuetify#8204]
### Problem to solve
not problem
just request

### Proposed solution
request v-expansion-panels flat style

ex)like.. none box-shadow and border 1px solid grey?

request flat style

**Comment by johnleider** [comment]
Due to how expansion-panels work, this does not actually look good with anything else except the **accordion** prop, in which case, I believe it can/should be handled in userland.

https://codepen.io/johnjleider/pen/oKwwaB

Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
