### ISSUE TITLE
[Bug Report] deletable-chips not work in selects

### ISSUE THREAD

**Issue by MrVokia** [vuetifyjs/vuetify#8218]
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.2

### Steps to reproduce
Remove `template`component

### Expected Behavior
Shown avatar and deletable chips in select item

### Actual Behavior
Deletable chips and v-slot:selection conflict, deletable chips not work

### Reproduction Link
<a href="https://codepen.io/mrvokia/pen/KOmbGg?editors=101" target="_blank">https://codepen.io/mrvokia/pen/KOmbGg?editors=101</a>

**Comment by MajesticPotatoe** [comment]
If you are defining the selection slot, you are responsible for also defining its functionality, as it overrides any defaults that would be provided by props (just as if you were to deleted the chips prop you would still have chips because you are defining them).

you can achieve this by adding close prop to the chips and defining the click event:
https://codepen.io/anon/pen/jgmdQZ
