### ISSUE TITLE
[Feature Request] Data table: max-height property

### ISSUE THREAD

**Issue by vschimpf** [vuetifyjs/vuetify#8243]
### Problem to solve
I'm using the properties "fixed-header" and "height" for the data table component, they work fine. But for the cases where there a just a few items on the table it takes the height set anyways having bigger space than the one needed. 

### Proposed solution
I think it would be really useful to have a "max-heigth" property, so the table can be smaller depending on the amount of items and grow up to certain height value showing the scroll if it is bigger.
It would be very helpful if this can receive a different value depending on the resolution (xs, lg, etc)

**Comment by mtx-z** [comment]
Indeed, it would be great. Thanks.

**Comment by nyszilard** [comment]
Alternative solution:
`<div style="max-height:25vh; overflow:auto">
<v-data-table>...</v-data-table>
</div>`

**Comment by ghyath5** [comment]
@nyszilard 
What about "fixed-header"?
If we use your solution we will break "fixed-header"  feature

**Comment by edrichhans** [comment]
Any updates?

**Comment by nyszilard** [comment]
This feature would be good, because I can only solve this problem with a hack right now: https://codepen.io/szili303/pen/vYGjOxb 
This solution doesn't work if I set the fixed-header property. Although I think it can be solved based on this codepen.

**Comment by courageon** [comment]
For those who come looking for the solution, this worked for me:
https://medium.com/untitled-factory/sticky-table-header-in-vuetify-js-fab39988dc3
Basically:

```css
.table{
	max-width: calc(100% - 48px);
	max-height: calc(100vh - 170px);
}
.v-data-table {
	overflow: auto;
}
.v-data-table /deep/ .v-data-table__wrapper {
	overflow: unset;
}
```
Where you set your table's class to "table" and set max-height to whatever magic numbers make it work for your view. Hope this helps!

**Comment by m4st3rm4tz3** [comment]
I agree that this would be a good feature. I am using another workaround and wanted to share the solution that worked best for me:

Because the table header and table row height is fixed (by default `48px`, see [documentation](https://vuetifyjs.com/en/api/v-data-table/#sass)) you can easily calculate the necessary height attribute.

```vue
<v-data-table
  :headers="headers"
  :items="items"
  :items-per-page.sync="itemsPerPage"
  fixed-header
  :height="itemsPerPage === -1 && items.length > 10
    ? 48 * 11 - 1
    : undefined
  "
></v-data-table>
```

This example makes the table scrollable if `itemsPerPage` is set to `all` and there are more than 10 items to show. If there are for example only 5 items the table will only use the necessary space.

You could take your own `max-height` value and only set the height attribute only if header and all rows to display are bigger than that value.

**Comment by MennoB** [comment]
Was this ever implemented, or are there any plans to implement this in Vuetify 3?
