### ISSUE TITLE
Date picker formatted value changes on "cancel()"

### ISSUE THREAD

**Issue by Bentfield** [vuetifyjs/vuetify#831]
### Steps to reproduce
Can be reproduced by clicking
Edit Week -> July 8 -> Save -> Edit Week -> July 15 -> Save -> Edit Week -> Cancel
in the supplied CodePen below

### Versions

Vue 2.3.4, Vuetify 0.12.7, Chrome v58

### What is expected ?

The formatted date stays the same when you click cancel.

### What is actually happening ?

The formatted date goes to the date before the expected date; however, the non-formatted date is correct.

### Reproduction Link

https://codepen.io/anon/pen/LLOeob

**Comment by johnleider** [comment]
After spending some time with this, the issue is actually not a bug. You are using new Date().toDateString() which converts it to local. You can see this by having the date format return .toISOString(). The values are always correct. This is a flaw with the Date object and part of the reason why dates are hard.

If you want to use the Date object, I suggest using ISOStrings or update your date-format.
