### ISSUE TITLE
[Bug Report] VDataTable expand slot will resize whole table

### ISSUE THREAD

**Issue by OysterD3** [vuetifyjs/vuetify#8334]
### Environment
**Vuetify Version:** 2.0.4
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Using v-slot:expanded-item="props"

### Expected Behavior
https://codepen.io/OysterD3/pen/dxJrYK

In v1.5.16, the table won't resize due to the high resolution of images and will fit 6 of the images into the expand slot

### Actual Behavior
Resizing table and user will have to scroll horizontally.

### Reproduction Link
<a href="https://codepen.io/OysterD3/pen/dxJKbO" target="_blank">https://codepen.io/OysterD3/pen/dxJKbO</a>

### Other comments
Is there any other workaround? My previous ticket has been closed which my problem hasn't been solved

**Comment by nekosaur** [comment]
This is caused by `v-responsive__content` element in `v-img` having `width: 1600px` as style.

**Comment by johnleider** [comment]
A change was made to natural width that would use the images naturalWidth in the absence of a defined one. This change was also made to bring `v-img` in line with what the expected behavior for a regular `img` element would be.

https://github.com/vuetifyjs/vuetify/pull/5788

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
