### ISSUE TITLE
[Bug Report] VDataTable mobile overflow

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#8411]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 7

### Steps to reproduce
View it in mobile to see the "test" column spill into the next row

### Expected Behavior
Overflow to be hidden or expand row

### Actual Behavior
Overflows into the next row

### Reproduction Link
<a href="https://codepen.io/teellcory/pen/oKdKEa" target="_blank">https://codepen.io/teellcory/pen/oKdKEa</a>

**Comment by ivanvorona** [comment]
Hi Guys, to workaround the issue within this thread i am trying to hide certain fields using class, it doesn't look like works for me, see code below. am i doing something wrong?
      headers: [
        {
          text: "Drill Name",
          align: "left",
          sortable: true,
          value: "node.drillName"
          
        },
        { text: "Drill Desc", value: "node.drillDesc",  **class: ["hidden-lg-only"] }**, // class doesn't work - to fix in future.
        { text: "DrillPurpose", value: "node.drillPurpose", **class: ['.d-md-flex'] },**

**Comment by ocBruno** [comment]
I was attempting to solve this issue but failed to reproduce it in the playground. I'm not sure why but I suspect the problem might be either specific to a certain mobile config or happening because of how codepen renders the sandbox.  

Although while troubleshooting I did notice the data cells could possibly use a mininum padding for these situations. Not sure if anyone is working on this but if so give me a heads up!
