### ISSUE TITLE
[Bug Report] v-timeline not proper small dots position when align-top

### ISSUE THREAD

**Issue by abdumuslim** [vuetifyjs/vuetify#8437]
![Screenshot (1)](https://user-images.githubusercontent.com/29736771/62796368-c1013300-bae1-11e9-9570-17f1d23d2d81.png)
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Using small dots with align-top in v-timeline.

### Expected Behavior
Center aligned small dots to the card arrow.

### Actual Behavior
Not center aligned small dots to the card arrow.

### Reproduction Link
<a href="https://codepen.io/abdumuslim/pen/oKPPXY" target="_blank">https://codepen.io/abdumuslim/pen/oKPPXY</a>

**Comment by sh7dm** [comment]
Same thing with large: https://codepen.io/sh7dm/pen/qeJEbN
![image](https://user-images.githubusercontent.com/19504461/62803108-412f9480-baf2-11e9-933a-027aba0e1c12.png)

**Comment by sh7dm** [comment]
Reverted by 3d5dcdf

**Comment by dappiu** [comment]
> Reverted by [3d5dcdf](https://github.com/vuetifyjs/vuetify/commit/3d5dcdfa634e3fac703f4a39028da19290477e33)

Having reverted the commit has removed `position: absolute`, but `.v-timeline-item__dot--{size}` has a "left" positioning that generates a warning:
(firefox)  _left has no effect on this element since it’s not a positioned element_

I think is safe and required having `position: absolute` on `.v-timeline-item__dot`
