### ISSUE TITLE
[Bug Report] VDataTable Sort on contents / bound prop

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#8484]
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 7

### Steps to reproduce
Preface: I'm using a c# backend and thus modeled data is camel case. 

Sorting uses the value binding of the header and tries to find that in the data. To use a template with it, it has to be lowercase. So my setup ends up looking like: header.value = "something" real data prop is "Something" and template says
` <template v-slot:item.something>{{item.Something}}</template>`

That works. What doesn't work is trying to sort. Because the sort only cares about the header's value, which item.something does not truly exist. I would like the option to bind the data to sort through in the header to another prop or for an option to sort by the contents of the template. If the latter case was done, that would also allow for calculations to take place in a column and to sort by the result.

### Expected Behavior
Sorting

### Actual Behavior
Not sorting

### Reproduction Link
<a href="https://codepen.io/teellcory/pen/JjPdoNQ" target="_blank">https://codepen.io/teellcory/pen/JjPdoNQ</a>

**Comment by shubhranshu** [comment]
It may be a bug with data tables but the the property and example given above is in PascalCase not camelCase. Most web libraries willl not cater to pascal case, it should be easy enough to adjust your seraliser to output proper camelCase.

**Comment by MajesticPotatoe** [comment]
Your best bet is to apply a middleware between your backend and frontend to standardize casing. Due to the nature of slot, their names can only be lowercase or kebab case (even snake case i think may work), which inherently means the object properties should follow suit if you would like to use their slots. I'm not sure it that should or can be done internally to handle this case as its a byproduct of vue and can be handled in userland.

**Comment by Teellcory** [comment]
I've since given up on this and done that, so I'll close it.
