### ISSUE TITLE
[Bug Report] Pagination Bug

### ISSUE THREAD

**Issue by oixan** [vuetifyjs/vuetify#8558]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
1) Click the tab 2, the pagination look ok. 
2) Click the tab 3, then click again the page 2 the pagination is totaly wrong

### Expected Behavior
Pagination should show only one page

### Actual Behavior
show 2 page separated by '...'

### Reproduction Link
<a href="https://codepen.io/oixan/pen/mdbPjRB?editors=1010" target="_blank">https://codepen.io/oixan/pen/mdbPjRB?editors=1010</a>

**Comment by Tomdanizer** [comment]
I was able to investigate this a little bit.
The issue reveals itself when the pagination control is **hidden**. This causes VPagination.ts **onResize** function to set a negative number for **maxButtons.**

Which in turn causes the following to fail because maxLength gets set to the negative number and proceeds to the logic that adds in the `return [1, '...', ...this.range(start, end), '...', this.length]`
```
 items (): (string | number)[] {
const totalVisible = parseInt(this.totalVisible, 10)
const maxLength = totalVisible > this.maxButtons
        ? this.maxButtons
        : totalVisible || this.maxButtons
      if (this.length <= maxLength) {
        return this.range(1, this.length)
      }
```

Here is my repro link:
[https://codepen.io/tomdanizer/pen/XWrjvqK?editors=1010](https://codepen.io/tomdanizer/pen/XWrjvqK?editors=1010)
Clicking the yellow button will display the control in the broken state. Resizing the window when it is visible will cause it to recalculate/fix itself.
Hiding it again and then resizing will cause it to insert the double dots again.

**Comment by isimonov** [comment]
I reproduced this bug in my project. He was also associated with pagination in the tab...
