### ISSUE TITLE
[Bug Report] v-col no longer supports xs viewports - order-xs and xs don't exist

### ISSUE THREAD

**Issue by adamrabbit** [vuetifyjs/vuetify#8597]
### Environment
**Vuetify Version:** 2.0.7
**Last working version:** 2.0.6
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Mac OS 10.14

### Steps to reproduce
1 use order-xs and xs in v-col
2 shrink the browser window

### Expected Behavior
layout change for extra small viewports

### Actual Behavior
no layout change occurs

### Reproduction Link
<a href="https://codepen.io/adamrabbit/pen/qBWNXqP" target="_blank">https://codepen.io/adamrabbit/pen/qBWNXqP</a>

### Other comments
xs still seems to be a valid breakpoint

**Comment by jacekkarczmarczyk** [comment]
Use `cols` prop
https://codepen.io/jkarczm/pen/VwZjzpX

**Comment by Thrainsa** [comment]
@jacekkarczmarczyk 
I understand that you can use cols instead of xs but it doesn't feel intuitive. 
Like @adamrabbit I thought this was a bug ;)

**Comment by sionzeecz** [comment]
Hey! 

I was also trying to use `xs` today. I had to ask on Vuetify discord server if this is a bug. They have told me that this is not bug but old documentation. 

I would like to see some note about `cols` and `xs` at [Grids](https://vuetifyjs.com/en/components/grids) page. Because the page tells us that, the existing are xs, sm, md, lg and xl.
