### ISSUE TITLE
[Bug Report] Text wrapping in chips

### ISSUE THREAD

**Issue by funkybg** [vuetifyjs/vuetify#8642]
### Environment
**Vuetify Version:** 2.0.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Create an autocomplete
2. Select an item with long name and spaces

Alternatively use the code below
<v-chip close style="width: 70px;">First name</v-chip>

### Expected Behavior
Text should not wrap inside the chip.
Close button should be visible and in the expected position

### Actual Behavior
Text wraps inside the chip. A particular example is autocomplete with chips. On larger screens we can allocate more space and hope for the best, but on small screens there is almost nothing that can be done.

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-1268u" target="_blank">https://codesandbox.io/s/vue-template-1268u</a>

**Comment by funkybg** [comment]
nowarap solves the issue in some cases, but when you have limited width of the input and a close prop, the close button is pushed off the visible part. The request is not for chip wrapping, there should be a way to solve the bug and still respect the spec.

**Comment by sploders101** [comment]
I know nowrap isn't always a solution, as I said in my response.

I'm not sure there is a way to keep all text, without wrapping, and without growing the chip past its bounds. The text wrapping isn't described in the spec, so I don't think it would be in violation, but I *can* see the argument that it might. The only other solution I can think of though, would be shrinking the font size. However, I'm not sure that would be very useful, because in the case of your codesandbox, the text would become so small it's almost unreadable.
Maybe I'm misunderstanding something, but what you're asking for sounds like trying to stuff in elephant in your trunk. If you can't split it up, and you can't shrink it, it's not going to work (tardis excluded).
Technically, you could add a scrollbar, but that would end up taking even more space that we don't have. I don't really like my wrapping idea either, but it's the best idea I could come up with.

I also don't think it's a bug. I think they should at least discourage use of long strings in chips, because given that chips should be short summaries of what they represent, it seems as though long strings defeat the purpose. You can have an abbreviation or ellipses, and open a v-menu when they click it to give more information using the item slot.

You could maybe have a scrollbar on the input element, but not the chip itself.

**Comment by funkybg** [comment]
i'm asking for the contributors to examine the example and propose a solution that fits for them or shut it down. I already know the workaround in my case 😅
