### ISSUE TITLE
[Bug Report] hide-on-scroll direction of v-bottom-navigation is reverse 

### ISSUE THREAD

**Issue by jjangga0214** [vuetifyjs/vuetify#8706]
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Ubuntu undefined

### Steps to reproduce
Please visit the repro link.

### Expected Behavior
v-bottom-navigation should be hidden when scrolling down, shown when scrolling up.

### Actual Behavior
The opposite from the expected.

### Reproduction Link
<a href="https://codepen.io/jjangga0214/pen/VwZPxxp" target="_blank">https://codepen.io/jjangga0214/pen/VwZPxxp</a>

### Other comments
possibly similar to #8337.

**Comment by mayank-shaan** [comment]
+1

**Comment by johnleider** [comment]
Docs: ![image](https://user-images.githubusercontent.com/9064066/69441339-26370800-0d10-11ea-8e83-d39d1f1a2ddb.png)
Spec: https://material.io/components/bottom-navigation/#behavior

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Ruudje87** [comment]
I have Vuetify version vuetify@2.2.12 and scrolling downwards reveals the bar instead of hiding it. So exactly what the Vuetify documentation says. But in material.io its says: 

Scrolling
Upon scroll, the bottom navigation bar can appear or disappear:
Scrolling downward hides the bar
Scrolling upward reveals it

So scrolling UP reveals. 

The v-app-bar with bottom has correct behaviour.
