### ISSUE TITLE
[Bug Report] Sandbox example not behaving same as code

### ISSUE THREAD

**Issue by Zyles** [vuetifyjs/vuetify#8726]
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
I am trying to copy the exact sandbox example seen here:

https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/layouts/sandbox.vue

On your website here:

https://vuetifyjs.com/en/examples/layouts/sandbox

But it is not behaving the same way.

Is the code not up2date or what is wrong?

### Expected Behavior
Drawer should not go above header/footer.

### Actual Behavior
The drawer goes above the app bar and the footer.

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-playground-itqsd" target="_blank">https://codesandbox.io/s/vuetify-playground-itqsd</a>

**Comment by Bbansjkl** [comment]
modal Navigation-Drawers displaying above the header and footer seem to be part of Material Design spec: https://material.io/components/navigation-drawer/#modal-drawer

**Comment by Zyles** [comment]
I still don't want my app to behave like that.

And the docs say the clipped props should behave differently but nothing happens when using it.

"Description
A clipped drawer rests under the application toolbar"

**Comment by Bbansjkl** [comment]
So temporary and clipped should also rest under the app bar?  
Yeah, that should probably be fixed, either by fixing the style or by correcting the docs. No idea what would be the correct course of action here.

Until it's fixed, you can apply the following CSS to your drawer to get it the way I think you want:

```css
.v-navigation-drawer--temporary.v-navigation-drawer--clipped {
    z-index: 5;
    top: 64px !important;
}
```
[Example](https://codesandbox.io/embed/vuetify-playground-gbs9o)  
I dislike using `!important`, but for some reason the top-attribute is added directly to element's style by Vuetify and since you can't get more specific than that (to my knowledge), you have to use `!important` if you want to override that. You may need to modify the value, since it's based off the height of the app-bar. Maybe consider calculating that via the `:style="..."` attribute.

**Comment by johnleider** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
