### ISSUE TITLE
[Documentation] VContainer-Documentation missing prop "fill-height"

### ISSUE THREAD

**Issue by Bbansjkl** [vuetifyjs/vuetify#8744]
### Environment

**Browsers:** Firefox 68.0
**OS:** Windows 7

### Steps to reproduce
Open the API-Explorer of v-container

### Expected Behavior
`fill-height` should be included in the API-Explorer of `v-container`, explained what it does and possibly also have an example.

### Actual Behavior
The `fill-height`-prop is only mentioned in the FAQ: https://vuetifyjs.com/en/getting-started/frequently-asked-questions#how-to-center-vertically

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/grids" target="_blank">https://vuetifyjs.com/en/components/grids</a>

**Comment by Bbansjkl** [comment]
Ah, that's good to know!  
What is the distinction between helper classes and props to users of the framework (other than that they're usable globally)? Is there an overview somewhere?  
Searching for `helper class` in the documentation only has one result, the FAQ entry linked in the issue.

**Comment by Bbansjkl** [comment]
I'm aware of what Vue props and CSS classes are, was just wondering why the helper-classes are applied by adding them like a prop instead of written in the class-attribute. Looking at the source mostly only explains how something works and not often why, and from the perspective of a user of the Vuetify-framework component props and helper classes work similarly.

**Comment by avinoamsn** [comment]
@MajesticPotatoe adding onto @Bbansjkl's comments above, is there a place in the documentation that explains the rationale behind "overloading" the prop syntax like this, and/or a page that lists all of the available helper classes? I created the dup issue https://github.com/vuetifyjs/vuetify/issues/13753 precisely because I wasn't aware of this nuance, and just like @Bbansjkl, I haven't had much luck in finding a comprehensive lists of all of the available helper classes.

**Comment by MajesticPotatoe** [comment]
https://vuetifyjs.com/en/components/grids/#v-container
As for a comprehensive list of helper classes, there isn't so much a single page with all of them, but they are all sectioned out amongst their applicable pages in the "Styles and animations" section of the docs (helper classes aren't really found anywhere outside of that section)
