### ISSUE TITLE
[Documentation] missing document for v-layout v-flex components

### ISSUE THREAD

**Issue by ShaneXie** [vuetifyjs/vuetify#8784]
### Problem to solve
i saw there two components in the page create by the nuxt cli. however i can not find any information about them in the document. but i can see the components in the source code. 
and they confused me with v-row v-col etc. grid components

### Proposed solution
add document for these components and explain when grid component when use theme

**Comment by MajesticPotatoe** [comment]
v-layout and v-flex are 1.x grid components, They have been removed from the docs in lieu of 2.x grid documentation ( v-row / v-col ). The grids page does have a link to 1.5 docs in the header which would contain your documentation for v-layout/v-flex. May want to post an issue on nuxt-cli to have them update their 2.0 code to use v-row/v-col. I'll add some support info to the alert for a little more clarity.

**Comment by ShaneXie** [comment]
thanks! maybe also output some deprecated message when someone trying to use it in current version, since this component indeed still available in the package.

**Comment by morficus** [comment]
@MajesticPotatoe  - if you go to the "API Explorer" page in the 2.0 docs (https://vuetifyjs.com/en/components/api-explorer) v-layout still appears when doing a search and doesn't have any indication that it applies to 1.x only.

**Comment by MajesticPotatoe** [comment]
@morficus - API is generated from source code, thus doesn't distinguish between deprecation in versions as they are not yet removed. This will resolve itself when it is actually remove from source (or if we decide to extract deprecation logic out of docs and into api-gen)

@ShaneXie probably a good idea, I thought it already did originally, but i think that's only if you have the eslint plugin installed.

**Comment by Webifi** [comment]
There needs to be clarification here.

In [releases and migrations](https://vuetifyjs.com/en/getting-started/releases-and-migrations/), it says "The grid has been rebuilt modeled after bootstrap. **The existing grid still works and needs some slight modifications**."

After reading that, rather than moving my existing code to v-row/v-col, I just fixed the existing v-layout and v-flex worked.

Had I known v-layout was slated for removal, I would have just moved to v-row/col then. But that is not clear in the releases and migrations notes!

When will support for v-layout/v-flex be removed from Vuetify?

**Comment by MajesticPotatoe** [comment]
![123123](https://user-images.githubusercontent.com/27827979/80724216-96bc2f00-8acf-11ea-87bc-4519638762d3.png)

**Comment by Webifi** [comment]
The 1.5 docs don't contain information on what shouldn't be used in 2.x.  Also that doesn't answer the main question:  When will v-layout / v-flex be removed?

The release and migration notes to not strongly encourage move to v-row / v-col -- quite the opposite.

**Comment by MajesticPotatoe** [comment]
It has not been determined officially when it will be removed. Likely with the release of v3. AFAIK there isn't anything that was removed from v-layout or v-flex just changes to things like v-container and spacing, which is outlined in the migration guide and the associated comparison gist, though @KaelWD was the one that worked on the 2.0 upgrade so he would likely know better if something was removed.

Its also been discussed about making v1.5 grids as an optional add on package which is why there is no strong encouragement to push people one way or another (and why we haven't flooded everyone's projects with deprecation notices yet - and the PR was stashed for when we are ready)

**Comment by KaelWD** [comment]
> if something was removed

`<v-layout row>` used to do nothing, and now adds some probably-unwanted padding. Other than that it should all work the same as before.

**Comment by danieldanielecki** [comment]
> It has not been determined officially when it will be removed. Likely with the release of v3. AFAIK there isn't anything that was removed from v-layout or v-flex just changes to things like v-container and spacing, which is outlined in the migration guide and the associated comparison gist, though @KaelWD was the one that worked on the 2.0 upgrade so he would likely know better if something was removed.
> 
> Its also been discussed about making v1.5 grids as an optional add on package which is why there is no strong encouragement to push people one way or another (and why we haven't flooded everyone's projects with deprecation notices yet - and the PR was stashed for when we are ready)

I think it was removed in `Vuetify3`, now I can't render anymore `v-flex`.
