### ISSUE TITLE
[Bug Report] VCheckbox color not applied when false-value is set to true

### ISSUE THREAD

**Issue by pawel-marciniak** [vuetifyjs/vuetify#8798]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Set false-value to true and true-value to false and some color:
```
<v-checkbox
    :false-value="true"
    :true-value="false"
    color="primary"
>
</v-checkbox>
```

### Expected Behavior
Checkbox has selected color.

### Actual Behavior
Checkbox is grey.

### Reproduction Link
<a href="https://codepen.io/pawlox/pen/WNeEvNX" target="_blank">https://codepen.io/pawlox/pen/WNeEvNX</a>

**Comment by EkinOf** [comment]
I got the same issue but with null value instead of false value

### Environment
Vuetify Version: 2.3.1
Vue Version: 2.6.11
Browsers: Firefox 82
OS: Windows 10

### Steps to reproduce
```javascript
<v-switch
    :false-value="true"
    :true-value="null"
    color="primary"
    v-model="switchValue"
    label="Switch button">
</v-switch>
```

### Expected Behavior
Switch should be colored with primary color

### Actual Behavior
Switch is grey.

### Reproduction Link
[https://codepen.io/EkinOf/pen/bGeELVX](https://codepen.io/EkinOf/pen/bGeELVX)

**Comment by nekosaur** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).
