### ISSUE TITLE
[Bug Report] I can't have two navigation drawer

### ISSUE THREAD

**Issue by frbuceta** [vuetifyjs/vuetify#8852]
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.15.1

### Steps to reproduce
I want to put two `v-navigation-drawer`, one with` v-app-bar` and one with `v-toolbar`

But the two are always fixed to the v-app-bar

### Expected Behavior
I hope one is with the `v-app-bar` and another with the` v-toolbar`

### Actual Behavior
the two `v-navigation-drawer` are set to the `v-app-bar`

### Reproduction Link

https://codepen.io/frbuceta/pen/XWrzPbd

### Other comments
```
<v-app>
    <v-navigation-drawer clipped app>
        Test app bar
    </v-navigation-drawer>
    <v-app-bar>
        AppBar
    </v-app-bar>
    <v-content>
        <v-navigation-drawer clipped app>
            Test toolbar
        </v-navigation-drawer>
        <v-toolbar>
            Toolbar
        </v-toolbar>
    </v-content>
</v-app>
```

**Comment by sh7dm** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by frbuceta** [comment]
https://codepen.io/frbuceta/pen/XWrzPbd

**Comment by frbuceta** [comment]
something new?

**Comment by sh7dm** [comment]
@frbuceta this issue is good now, it has reproduction and it'll be fixed as soon as possible

**Comment by frbuceta** [comment]
thanks

**Comment by frbuceta** [comment]
something new?

**Comment by frbuceta** [comment]
something new?

**Comment by KaelWD** [comment]
This is not currently supported, you cannot have two `app` components of the same type on the same side. May change in v3 but the markup won't look like that.
