### ISSUE TITLE
[Bug Report] v-data-table select all does not trigger item-selected event

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#8879]
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Windows 7

### Steps to reproduce
Create a v-data-table with show-select and item-selected like so:

     <v-data-table show-select @item-selected="myMethod()" />

Create a method that shows a console message

     myMethod() {
       console.log('Clicked');
     }

### Expected Behavior
I expect myMethod to be called when each checkbox is clicked, or when the 'select all' checkbox is clicked

### Actual Behavior
myMethod is NOT called when the 'select all' checkbox is clicked

### Reproduction Link
<a href="https://codepen.io/uglyhobbitfeet/pen/ExYQBpM?editors=1010" target="_blank">https://codepen.io/uglyhobbitfeet/pen/ExYQBpM?editors=1010</a>

**Comment by sh7dm** [comment]
@UglyHobbitFeet You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by UglyHobbitFeet** [comment]
Unfortunately both codepen and jsfiddle do not work with even a basic bare bones of the latest vuetify and data table.  Examples of that are
here: 
https://codepen.io/uglyhobbitfeet/pen/KKPQLYa?editors=1010
and here:
https://jsfiddle.net/uglyhobbitfeet/eruz09tp/22/

The only working jsfiddle/codepen examples out there use outdated vuetify versions (0.x). Something must have changed as the newest ones do not load correctly.

The details in the original post still stand and are in fact an issue

**Comment by mjzarrin** [comment]
Check if you declare `item-key` attribute.
I had the same problem with that.

**Comment by nekosaur** [comment]
This is working as intended. If you need to know when select-all is clicked, use `toggle-select-all` event
