### ISSUE TITLE
[Bug Report] Fontawesome Icon Loading Performance

### ISSUE THREAD

**Issue by adarshmadrecha** [vuetifyjs/vuetify#8885]
### Environment
**Vuetify Version:** 2.0.15
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
Add more than 10 font awesome icons to a v-card. Using v-for create 100+ Cards.
The performance is very bad.
> The Reproduction link is not added. Instead, have added a screenshot of the production environment. 

![image](https://user-images.githubusercontent.com/11911938/64472863-53006800-d182-11e9-9af0-abd4e3c9fc8e.png)

### Expected Behavior
v-icons should not take so much time to load

### Actual Behavior
v-icons takes very high time to load

### Reproduction Link
<a href="https://codesandbox.io/s/new" target="_blank">https://codesandbox.io/s/new</a>

**Comment by adarshmadrecha** [comment]
The v-icon component count is very high, even though the total number of icons which are loaded is less than 100.

![image](https://user-images.githubusercontent.com/11911938/64472886-c1452a80-d182-11e9-92d2-19868c5ce801.png)

**Comment by sh7dm** [comment]
@adarshmadrecha screenshot can't provide enough information to our team, we can't debug it or try fixes on it. Please provide a reproduction!

You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by adarshmadrecha** [comment]
Thanks for creating an awesome library. I upgraded to vuetify 2.1.0 and this issue is solved.
To further improve the performance, I implemented https://github.com/Akryum/vue-virtual-scroller
