### ISSUE TITLE
[Documentation] Migration Guide

### ISSUE THREAD

**Issue by SumNeuron** [vuetifyjs/vuetify#8888]
### Problem to solve
Many of the staple conventions for structuring apps have been re-works and in some cases, higher level "magic-esque" properties have been removed (e.g. gridlist)

### Proposed solution
A migration guide showing the old documentation grid and gridlist pages examples in the new framework e.g. v-flex to v-row / v-col / div.d-flex

**Comment by sh7dm** [comment]
@MajesticPotatoe @KaelWD when you start working on this I can help with grid migration guide if you want.

**Comment by johnleider** [comment]
We currently have a migration guide to v2 https://vuetifyjs.com/en/getting-started/upgrade-guide/#upgrading-from-v15x-to-v20x

This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
