### ISSUE TITLE
[Bug Report] vertical tabs always showing arrows in <v-tabs>

### ISSUE THREAD

**Issue by vincentauger** [vuetifyjs/vuetify#8981]
### Environment
**Vuetify Version:** 2.0.17
**Last working version:** 2.0.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.6

### Steps to reproduce
Simply go to another tab, arrows now show where they didn't before. This can also be replicated using example in documentation. https://vuetifyjs.com/en/components/tabs#vertical-tabs

### Expected Behavior
No arrows should show in vertical mode.

### Actual Behavior
Arrows show in vertical mode

### Reproduction Link
<a href="https://codepen.io/vincentauger/pen/pozZXEo?&editable=true&editors=101" target="_blank">https://codepen.io/vincentauger/pen/pozZXEo?&editable=true&editors=101</a>

**Comment by MajesticPotatoe** [comment]
Seems to be caused when the `v-tab-item` context exceeds the height of the tabs container

**Comment by vincentauger** [comment]
Yes, good observation, it does appear to be the case.

**Comment by MajesticPotatoe** [comment]
Will have to dig a little deeper, but the only 2 changes i see that were introduced were
b45b67c and 5329514, just gotta see which one it is. should be relatively easy fix.

**Comment by vincentauger** [comment]
Thanks! That is some seriously fast response time :).

**Comment by Aaronm14** [comment]
Also ran into this just now, happy to see not only an existing issue but a quick response by @MajesticPotatoe  so thanks for the update.  I'd guess it has to do with the https://github.com/vuetifyjs/vuetify/commit/b45b67cd055c3fb3299fbf9fe974e0fa78e0e880 commit you linked because I do see that class when the arrows are showing at max screen size (when they shouldn't be).

I have confirmed that the arrow issue is not there in our application running on v2.0.15.  Can provide a screenshot if desired
