### ISSUE TITLE
[Bug Report] Datatables options -> sortDesc property does not allow a single boolean value, only an array

### ISSUE THREAD

**Issue by mju516** [vuetifyjs/vuetify#8982]
### Environment
**Vuetify Version:** 2.0.17
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Firefox 60.0
**OS:** Linux i686

### Steps to reproduce
Open the console log for the attached codepen

### Expected Behavior
The v-data-table should have it's header rendered

### Actual Behavior
The header does not render, and the console contains errors. This is related to the sortDesc property. Previously, it accepted a single boolean (which is indicated in the docs)

It appears that now an array of boolean(s) must be passed

### Reproduction Link
<a href="https://codepen.io/mju516/pen/JjPaGKB" target="_blank">https://codepen.io/mju516/pen/JjPaGKB</a>

**Comment by Teellcory** [comment]
If you look at the definition of "options" it doesn't claim to allow either (you were looking at the main props, although I agree it should work identically). The "sortBy" being a string instead of an array is what is really breaking the header. The sortDesc as a boolean works for ordering the data, but it breaks the functionality of clicking on the header to sort (but it does not cause it to not appear).

The main prop sort-desc does allow it to be a single boolean, just as sort-by allows it to be a single string.

**Comment by nekosaur** [comment]
as @Teellcory mentions, both `sortBy` and `sortdesc` need to be arrays in the `options` prop.

**Comment by escapedcat** [comment]
@nekosaur is it possible to get this info from the current documentation?

@Teellcory 
> ([...] although I agree it should work identically)  

I totally agree. This is confusing.
