### ISSUE TITLE
[Bug Report] Alert doesn't properly show on data-table if v-slot:body="{ items }" is used.

### ISSUE THREAD

**Issue by taylanwhite** [vuetifyjs/vuetify#8988]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
Override data table slot with v-slot:body
### Expected Behavior
v-alert should appear in datatable if corresponding datatable is given empty array

### Actual Behavior
datatable shows no rows, and alert does not pop up. 

### Reproduction Link
<a href="https://codepen.io/taws/pen/GRKXeqQ?#anon-login" target="_blank">https://codepen.io/taws/pen/GRKXeqQ?#anon-login</a>

**Comment by esynaps** [comment]
I do not think it's a bug. The no-data slot is included in the body slot. In your case, maybe the solution is  to use the item slot instead of body.

**Comment by nekosaur** [comment]
@esynaps is correct. the body slot overrides all internal rendering of content, including the no-data slot. It should _only_ be used if you need access to the `tbody` element, and if so you will need to implement your own functionality for no-data etc.

Otherwise use the `item` slot, or the `item.<name>` column slots.
