### ISSUE TITLE
[Bug Report] v-toolbar does not correctly adjust height when child has padding

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#9029]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Windows 7

### Steps to reproduce
Go to the codepen and look at the outcome.  You can see that the extension slot does not move down to compensate for large paddings.  

Change the toolbar components padding from 210px to 0px and you can see it looks correct

### Expected Behavior
I expect the extension slot to move down to compensate for a toolbar child with padding.
I expect the toolbar to allow the child to have the padding without it spilling over outside the toolbar component

### Actual Behavior
The extension slot does not move down to accommodate the padding
The child component of the toolbar spills outside of the toolbar container

### Reproduction Link
<a href="https://codepen.io/uglyhobbitfeet/pen/dybQGEw" target="_blank">https://codepen.io/uglyhobbitfeet/pen/dybQGEw</a>

**Comment by westmorelandnyc** [comment]
@UglyHobbitFeet I'm experiencing the same thing on v1.5.16. It seems to have to do with the way  `computedContentHeight()` is being calculated. For example, I'm passing in a `height="120px"` prop on the component, so that triggers the first line here, without any code to find the actual element's `outerHeight()` or anything:
```javascript
// /vuetify/lib/components/VToolbar/VToolbar.js
// Line 80
        computedContentHeight: function computedContentHeight() {
            if (this.height) return parseInt(this.height);
            if (this.dense) return this.heights.dense;
            if (this.prominent || this.$vuetify.breakpoint.mdAndUp) return this.heights.desktop;
            if (this.$vuetify.breakpoint.smAndDown && this.$vuetify.breakpoint.width > this.$vuetify.breakpoint.height) return this.heights.mobileLandscape;
            return this.heights.mobile;
        }
```

**Comment by madebycaliper** [comment]
@UglyHobbitFeet  I'm experiencing the same thing on v1.5.16. It seems to have to do with the way  `computedContentHeight()` is being calculated. For example, I'm passing in a `height="120px"` prop on the component, so that triggers the first line here, without any code to find the actual element's `outerHeight()` or anything:
```javascript
// /vuetify/lib/components/VToolbar/VToolbar.js
// Line 80
        computedContentHeight: function computedContentHeight() {
            if (this.height) return parseInt(this.height);
            if (this.dense) return this.heights.dense;
            if (this.prominent || this.$vuetify.breakpoint.mdAndUp) return this.heights.desktop;
            if (this.$vuetify.breakpoint.smAndDown && this.$vuetify.breakpoint.width > this.$vuetify.breakpoint.height) return this.heights.mobileLandscape;
            return this.heights.mobile;
        }
```

**Comment by johnleider** [comment]
You have to assign a height of **auto** if you want it to adjust: https://codepen.io/johnjleider/pen/gObKYWW

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
