### ISSUE TITLE
<v-dialog> overlay stays when navigating away

### ISSUE THREAD

**Issue by maartendraijer** [vuetifyjs/vuetify#911]
Similar to #570, this stopped working again since v0.13.

To reproduce on JS Fiddle, http://jsfiddle.net/y0yfgv6y/:

Click 'Open dialog'
Click 'CLOSE'
Now you end up on the Home route with an overlay from the dialog's route.

**Comment by nekosaur** [comment]
It seems like the dialog creates two overlays and then only removes ome of them.

**Comment by johnleider** [comment]
This is actually not a bug just a quirk. When dialog boots up, it checks to see if it is active, if it is, it creates an overlay. The problem here though, is the active state is being set on mounted, which is coinciding with the mounted load, causing 2 overlays.

-1 http://jsfiddle.net/7r9wrap4/ The way I recommend doing it until this fix releases
-2 I'm going to add a check for the overlay to not be able to spawn twice
