### ISSUE TITLE
[Bug Report] VSpeedDial strane animation if buttons have event listener

### ISSUE THREAD

**Issue by NothingWeAre** [vuetifyjs/vuetify#9171]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90, Mozilla Firefox, Google Chrome
**OS:** Windows 10, Windows, Linux, Android

### Steps to reproduce
Create `VSpeedDial`, add `VBtn` with event listener (`@click, @hover`, etc.)

if there are no event listeners animations work as expected

### Expected Behavior
smooth animations on opening and closing

### Actual Behavior
choppy animation on opening

### Reproduction Link
<a href="https://codesandbox.io/embed/vuetify-playground-h1mk9" target="_blank">https://codesandbox.io/embed/vuetify-playground-h1mk9</a>

**Comment by BjornLuG** [comment]
I've been digging for the past few hours with no solution. Here's what I got so far:

1. This started to happen on v2.0.19. v2.0.18 was working fine.
2. Not only event listeners, any attributes that are not the component's props also caused the issue, e.g. `aria-label`.
3. The buttons are in a transition group, and the issue arises because the buttons are directly set to class `fade-transition-enter-to` instead of the usual `fade-transition-enter` > `fade-transition-enter-active` > `fade-transition-enter-to` progress.

The problem must be in one of the files in the v2.0.19 release, but I can't find any. There's no direct reference to the VSpeedDial component. Something must be causing this "side effect".

**Comment by NothingWeAre** [comment]
after some investigation I have narrowed this to:
https://github.com/vuetifyjs/vuetify/blob/v2.1.0/packages/vuetify/src/mixins/binds-attrs/index.ts

**Comment by BjornLuG** [comment]
Indeed that file was the culprit, I tried some stuff and finally found a few workarounds. It seems like a bug in Vue as well. Will later sent a PR later and an issue on Vue explaining what I got.
