### ISSUE TITLE
[Bug Report] [Vuetify] v-ripple can only be used on block-level elements

### ISSUE THREAD

**Issue by nPaul** [vuetifyjs/vuetify#9205]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 7

### Steps to reproduce
got error [Vuetify] v-ripple can only be used on block-level elements
if using router-linkt in components v-btn v-items
example
<v-item :to="{name: 'NameOfRoute' }>

i thing maybe bug in window.getComputedStyle, becouse it set style element to "display: inline"

to fix i  try
<v-item :to="{name: 'NameOfRoute' } style="display: flex">
and it work FINE without errors

please fix it!

### Expected Behavior
qwe

### Actual Behavior
qwe

### Reproduction Link
<a href="https://codepen.io/hackeresq/pen/MWgZJeq" target="_blank">https://codepen.io/hackeresq/pen/MWgZJeq</a>

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by johnleider** [comment]
This isn't a bug. Do not use ripple on inline-elements. You can use a helper class to designate a block/flex etc if needed.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by escapedcat** [comment]
Linking a similar issue here: https://github.com/vuetifyjs/vuetify/issues/9055
