### ISSUE TITLE
[Bug Report] [v-text-field] `dense` prop doesn't have any effect when `filled` prop is used

### ISSUE THREAD

**Issue by mrksoftware** [vuetifyjs/vuetify#9256]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
- Add `filled` prop to `v-text-field` with `dense` = true

### Expected Behavior
`filled` prop shall occupy same vertical space as for outlined case

### Actual Behavior
`dense` prop doesn't have effect when `filled` is used. With `outlined` it works

### Reproduction Link
<a href="https://codepen.io/mrksoftware/pen/abbbgNe" target="_blank">https://codepen.io/mrksoftware/pen/abbbgNe</a>

**Comment by melbahja** [comment]
use `single-line` prop with dense
https://codepen.io/dev0x0/pen/LYYELgZ

**Comment by mrksoftware** [comment]
Hi @melbahja thank you for your response!
True, but we loose the label and the label shall remain as I can see from #9105

**Comment by mrksoftware** [comment]
Also, if you use `outlined `+ `filled `+ `single-line` in the same component you will end up with this situation: https://codepen.io/mrksoftware/pen/eYYmKVy

As you can see, the last one lose the label (because of the single line) and the second one is too big (doesn't respect `dense`)

**Comment by melbahja** [comment]
I think vuetify team following MD standards
filled without dense is 56dp height:
![image](https://user-images.githubusercontent.com/8259014/66390207-16fb3580-e9c2-11e9-96ec-5820ce74a21e.png)

dense with a label is 52dp height
![image](https://user-images.githubusercontent.com/8259014/66390163-fc28c100-e9c1-11e9-8f7e-516681b4eb8a.png)

that exactly the height of fields right now, I don't maybe someone from the team answer you, and I will be happy to open a new PR if there a bug

**Comment by cafedo** [comment]
I think that we are mixing two different issues:

1. When **outlined**, we obtain an unexpected "big" height behaviour when we set on v-text-field `outlined`, `filled` and `dense` (as it has been highlighted in the updated codepen of @mrksoftware : https://codepen.io/mrksoftware/pen/abbbgNe). This I think that is a bug, because, as you can see, in the v-combobox it works well.  

2. When **not outlined**, when we set on both v-text and v-combobox `filled` and `dense`, the height of both controls is "big". Also in this case my personal opinion is that the height should be the same of outlined version; but it is a different topic from point 1.

I think that at least point 1 should be fixed: what do you think @melbahja and @MajesticPotatoe ?

**Comment by MajesticPotatoe** [comment]
@cafedo point 1 def looks like a bug. Seems like the filled height is overriding the outlined height because in that example, even the label is positioned as if it was outlined.

As for point 2, yeah its a different topic than point 1, because given the spec with label its 52px (which is really only 4px smaller than normal). though without its 40, and that can be achieved using `single-line` prop

**Comment by melbahja** [comment]
Ok guys about point 1 I will open a new PR tomorrow to fix it
