### ISSUE TITLE
[Bug Report] Badge spacing on list broken

### ISSUE THREAD

**Issue by jameshhood** [vuetifyjs/vuetify#9290]
### Environment
**Vuetify Version:** 2.1.1
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
I personally used a list inside a nav-drawer

Create list
Define list item with v-badge inside v-list-item-content

### Expected Behavior
Have a list item with a badge to have the same look and feel as other list items

### Actual Behavior
Badge is displayed way off to the right of the list item content area

### Reproduction Link
<a href="https://codepen.io/hoodj/pen/GRRJZZe?&editable=true&editors=101" target="_blank">https://codepen.io/hoodj/pen/GRRJZZe?&editable=true&editors=101</a>

### Other comments
I noticed that this is pretty much related directly to the use of v-list-item-content and v-badge. If you switch v-list-item-content to item-title and the badge works but the text is off-centered

**Comment by johnleider** [comment]
Workaround for now: https://codepen.io/johnjleider/pen/eYYxOxw

This will be a challenging thing to support out of the box. Not so much in regards to the one css change, but how lists are constructed to support MD spec. The way I get around it in the example is by using a regular element within the content flex container to eat the **flex: 1 0 100%** applied by the content, and then process as normal with a badge wrapping the title. 

I'll have to look into why we added **overflow: hidden** to the container since the children are what handle the vertical line clamping.

**Comment by nekosaur** [comment]
Version 2.2 has `inline` prop that solves this pretty well <https://codepen.io/nekosaur/pen/Bapopym?editors=1010>
