### ISSUE TITLE
[Bug Report] FAB is not properly positioned in bottom sheets

### ISSUE THREAD

**Issue by 1isten** [vuetifyjs/vuetify#9324]
### Environment
**Vuetify Version:** 2.1.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
Check out the codepen reproduction link, toggle the bottom sheet to see FAB's position change.

### Expected Behavior
FAB should stick to the edge of the bottom sheet? 

### Actual Behavior
FAB is moved outside the bottom sheet.

### Reproduction Link
<a href="https://codepen.io/1isten/pen/YzzyOgr?editors=1010" target="_blank">https://codepen.io/1isten/pen/YzzyOgr?editors=1010</a>

### Other comments
If this is not an issue but the nature of vuetify's FAB, can I change this to a feature request for FAB that works with bottom sheet?

**Comment by johnleider** [comment]
This is because `v-sheet` had it's **position** property removed because of the other components that extend it. I would like to have position helper classes in the future, but for now, this is expected functionality.

https://github.com/vuetifyjs/vuetify/commit/fbcb00895d61a54979a28ef7995b344a4a39e43b#diff-1b3fcb85b76e57fb7d6699163f19a885

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
