### ISSUE TITLE
[Bug Report] text-capitalize doesn't work when text is already in uppercase

### ISSUE THREAD

**Issue by btalebpour-mfi** [vuetifyjs/vuetify#9333]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Just try the following in a dialog:
```html
<v-card-title class="headline text-capitalize">ADD GROUPS TO IDENTITIES</v-card-title>
```
If I change text to lowercase, it works fine.

### Expected Behavior
To make text capitalized regardless of its original case. text-lowercase and text-uppercase behaving properly

### Actual Behavior
Doesn't change the text case if it is uppercase

### Reproduction Link
<a href="https://codepen.io/btalebpour/pen/abbdNNB" target="_blank">https://codepen.io/btalebpour/pen/abbdNNB</a>

### Other comments
text-lowercase, text-uppercase, and text-capitalize should change the text case accordingly regardless of the text's original case

**Comment by MrJmpl3** [comment]
All work perfect!

Capitalize transforms every first letter of a word to uppercase, but it does not transform the other letters to lowercase. Not even the :first-letter pseudo-class will cut it (because it applies to the first letter of each element, not each word), and I can't see a way of combining lowercase and capitalize to get the desired outcome.

So as far as I can see, this is indeed impossible to do with CSS.

Source:
https://stackoverflow.com/questions/3471157/css-text-transform-capitalize-on-all-caps

**Comment by MajesticPotatoe** [comment]
These classes are working as intended. All they do is apply text-transform, in which case `text-transform: capitalize` only capitalizes the first character of each word. (If you lowercase the first letters in you capitalize `p` it will capitalize)

**Comment by Previesam** [comment]
You can string interpolate the text `{{ 'samuelsndusud'.toLowerCase() }}` then apply the text-capitalize class
