### ISSUE TITLE
[Bug Report] <v-list-item-group> includes items nested in menus

### ISSUE THREAD

**Issue by inad9300** [vuetifyjs/vuetify#9406]
### Environment
**Vuetify Version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Mac OS 10.15.0

### Steps to reproduce
1. Click on the first item's ellipsis.
2. Click on the bomb.
3. Observe alert's content.
4. Repeat steps 1 through 3 and see the changing results.
5. Do the same for the second and third items.

### Expected Behavior
The index synced with the v-model property should never be above the length of the items over which we are iterating. Furthermore, the selection (highlight) of the items in the list should be kept after clicking any item on the menu.

### Actual Behavior
The index goes above the expected range in an unpredictable and nonsensical manner. Additionally, when clicking on an element inside the menu, the item of the list which was previously highlighted stops being so.

### Reproduction Link
<a href="https://codepen.io/inad9300/pen/YzzGbOp?&editable=true&editors=101" target="_blank">https://codepen.io/inad9300/pen/YzzGbOp?&editable=true&editors=101</a>

### Other comments
The documentation should clarify what type of value v-model accepts (i.e. the index of the list, presumably) and under what circumstances will it change.

**Comment by KaelWD** [comment]
It's selecting list items in the menus. 

> goes above the expected range in an unpredictable and nonsensical manner

Not so, display it with `{{ model }}` and you'll see it's correct, you're just alerting the *previous* value. 

We could prevent this by making v-list a boundary to v-list-item-group.

**Comment by DjOli** [comment]
I am experiencing this same problem. 

```
<v-list>
  <v-list-item-group v-model="foo">
    <v-list-item>
      <v-menu>
        <v-list>
          <v-list-item></v-list-item>
        </v-list>
      </v-menu>
    </v-list-item>
  </v-list-item-group>
</v-list
```

Essentially I have a list which maintains selection, therefore i've wrapped it in an item group. Each item then has a menu, which subsequently has its own list and list items. The list items in the menu are triggering updates on the model for the list item group (and naturally adjusting the model value to a value outside the bounds of the items in the item group).

I'm currently working around this by wrapping my internal list in another item group. The drawback to this is that it then adds selection mechanics to the child list (which I don't want). I am unable to bypass the selection mechanic (I attempted setting max to 0 and v-model to null), so instead I have set the list to flat and applied an active class so that the selected item doesn't look selected.

It would be great if the bounds of a v-list-item-group did not extend into further v-list components.

**Comment by hugomejia** [comment]
Indeed, I'm another victim of this vicious bug hehehe LoL, took me some time to realize it was actually a Vuetify issue. Fortunately the solution is quite simple and there are plenty of different ways to solve it.  Hope this will be solved soon!

**Comment by KaelWD** [comment]
Workaround:
```js
// StopListGroup.js

export default {
  provide: {
    isInGroup: false,
    listItemGroup: undefined
  },

  render () {
    return this.$scopedSlots.default()
  }
}
```

```vue
<v-list>
  <v-list-item-group v-model="foo">
    <v-list-item>
      <stop-list-group>
        <v-menu>
          <v-list>
            <v-list-item></v-list-item>
          </v-list>
        </v-menu>
      </stop-list-group>
    </v-list-item>
  </v-list-item-group>
</v-list>
```

**Comment by xolott** [comment]
Same workaround as @KaelWD but in typescript

```ts
import { Vue, Component, Provide } from "vue-property-decorator";
import { VNode } from "vue/types/umd";

@Component({
  name: "stop-list-group",
})
export default class StopListGroup extends Vue {
  @Provide() isInGroup = false;
  @Provide() listItemGroup = undefined;

  render(): VNode[] | undefined {
    return this.$slots.default;
  }
}
```
