### ISSUE TITLE
[Bug Report] <v-input> ID and other attributes are automaticaly removed

### ISSUE THREAD

**Issue by vanillamasonry** [vuetifyjs/vuetify#9528]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Windows 10

### Steps to reproduce
<v-input id="test" ></v-input>

### Expected Behavior
id "test" MUST BE AVAILABLE in DOM after processing

### Actual Behavior
id and other attributes are deleted

### Reproduction Link
<a href="https://codepen.io/Paul_1001/pen/ZEEazbZ" target="_blank">https://codepen.io/Paul_1001/pen/ZEEazbZ</a>

### Other comments
far too many bugs by comparison with other frameworks

**Comment by vanillamasonry** [comment]
<v-banner> Is  another component that removes ID and other attributes
style is no tremoved
Reproduction Link
https://codepen.io/Paul_1001/pen/poodRme

**Comment by vanillamasonry** [comment]
"v-banner"

**Comment by johnleider** [comment]
The `v-banner` issue was resolved in ddb2b9f980d497f2fa75fc8676bd15f07b46c89d .

`v-input` is done that way by [design](https://github.com/vuetifyjs/vuetify/blob/7a9080a0dd856be67d74c53476ae7363e4df65be/packages/vuetify/src/components/VInput/VInput.ts#L39). We do not inherit attributes since they are passed down to inner input elements.

I'm going to update the documentation to reflect this special aspect of the `v-input` component.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
