### ISSUE TITLE
[Bug Report] menuProps closeOnClick not working properly in autocomplete or select

### ISSUE THREAD

**Issue by richardadrian** [vuetifyjs/vuetify#9533]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Mac OS 10.15.0

### Steps to reproduce
Changing closeOnClick to true breaks the autocomplete component.  And the default of 'false' should prevent it from closing on outside click but does not.

This is from your Advanced Slot currency example.  I tried using the menu props closeOnClick: false but the menu still closes when I click outside of the component.

### Expected Behavior
Leave the menu open if the component loses focus due to outside click.

### Actual Behavior
Menu closes.

### Reproduction Link
<a href="https://codepen.io/rjadrian/pen/eYYeQvd" target="_blank">https://codepen.io/rjadrian/pen/eYYeQvd</a>

**Comment by richardadrian** [comment]
Is this because v-select closeConditional function is not using this.closeOnClick (or $_menuProps in this case) like the same function in v-menu ?

**Comment by pyr31** [comment]
Hi, this bug affects me today, is there a workaround? Thx.

**Comment by giray123** [comment]
Is there an update on this?

**Comment by schirrel** [comment]
Hi, any update on this?

**Comment by schirrel** [comment]
I've update today to 2.5.9, new release, and it was fixed

**Comment by SaiyedRushan** [comment]
Hello, any update on this? Apparently, the scroll strategy doesn't work as intended as well I think. @KaelWD theres no one assigned for this bug, its been open since 2019. Can someone please fix this?

**Comment by Ge6ben** [comment]
I get same issue , I solve it by bind props to my list:
```
	        <v-autocomplete
		:item-title="itemTitle"
		:items="currentMenuItems"
		clearable
		:item-value="itemValue"	>
		
		<template #item="{ index, props }">
			<v-list-item  v-bind="props >
				{{ currentMenuItems[index][itemTitle] }}
			</v-list-item>
		</template>

	
	         </v-autocomplete>

**Comment by AngelPhp122** [comment]
Hello.
I had exactly the same problem with the menu-props (closeOnClick) of v-autocomplete, apparently it does not work exactly as you would expect according to what the documentation describes since the autocomplete menu always closes if you click outside. The solution I found was to use the following menu-props in this way, it is worth mentioning that it also required the events emitted by the input and a watch of the autocomplete v-model to be able to dynamically update that menu property.

The validations that I use are simple :)

https://codepen.io/AngelPhp122/pen/azowgMa
