### ISSUE TITLE
[Bug Report] Dark theme colors not applying when dark:false + dark prop

### ISSUE THREAD

**Issue by mrodal** [vuetifyjs/vuetify#9581]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
Set up custom dark theme
Leave dark:false on theme config
Use dark prop on something like a toolbar

### Expected Behavior
The toolbar should use the custom dark colors

### Actual Behavior
The toolbar uses light colors

### Reproduction Link
<a href="https://codepen.io/mrodal/pen/OJJvyer" target="_blank">https://codepen.io/mrodal/pen/OJJvyer</a>

### Other comments
Original (closed) issue https://github.com/vuetifyjs/vuetify/issues/7084
and https://github.com/vuetifyjs/vuetify/issues/9573

Please don't close the issues without allowing some response, because we are forced to open another issue. I think that with the label system you can filter the ones waiting for feedback from the author from the ones you never addressed...

**Comment by KaelWD** [comment]
Yeah this is just the way the current theme system works unfortunately, we only inject styles for the current global light/dark not both. There's another overhaul in the works eventually but this can't really be implemented properly without at least partially dropping IE support thanks to CSS cascade. 

> Please don't close the issues without allowing some response...

There's almost 1000 open, most of the time if you're wrong about something that's it and there's no need for a response. This is separate to #9573 because you weren't using multiple theme colours in that and were setting the global theme incorrectly. 
This is a genuine issue but there's no immediate plan to resolve it so there's no point leaving it open.
