### ISSUE TITLE
[Documentation] API Explorer page should help me to navigate to component page.

### ISSUE THREAD

**Issue by aneesshameed** [vuetifyjs/vuetify#9602]
### Problem to solve
I can easily find the component and its props from the API explorer page. But if I can navigate from there to the component page then I will be able to see the implementation examples which will be very helpful.

### Proposed solution
Add open-in-new window icon near to the close icon in API explorer search box, or when I click on the selected component in API explorer search box then take me to the selected component page. Thanks

**Comment by MajesticPotatoe** [comment]
Probably wont be an open-in-new-window sorta thing, will probably be a link to route to keep things smooth. I agree though, having a way to navigate to the component would be useful.

Main problem that will come up is not API explorer items are 1:1 with a dedicated page, and a lot of components are grouped into a single page if they are sub components. Main reason there's issues with lang descriptions right now because current API explorer is built off routing.

Will def include this though when API explorer gets redone in the near future. Thanks!

**Comment by aneesshameed** [comment]
I understood the complexity, Basically, this was the same trouble that I was facing. I search for a component in the API explorer. I will happily find it, then when I try to find the same in the navigation drawer, oops it's not there. Now I understand that its because the component doesn't have the dedicated page.

Anyway if we can sort out this, it will be a huge help. Thanks.

**Comment by MajesticPotatoe** [comment]
API Explorer page no longer exists, and all api pages have quick links to their components.
