### ISSUE TITLE
[Bug Report] Navigation Drawer mini variant does not have accessible labels

### ISSUE THREAD

**Issue by mattgreenfield** [vuetifyjs/vuetify#9741]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a navigation drawer with the `mini-variant` prop set to true.
Use a screen reader, the labels are `display: none` to do not announce.
You can also use the accessibility viewer in firefox which shows the links as having no name.

If you open the menu, `display: none` is removed and everything is fine.

Reproducible on the docs page: 
https://vuetifyjs.com/en/components/navigation-drawers#navigation-drawers

<img width="1257" alt="Screenshot 2019-11-20 at 10 13 39" src="https://user-images.githubusercontent.com/7290654/69230933-23a5a880-0b80-11ea-9eb2-eb18ed92751e.png">
<img width="1254" alt="Screenshot 2019-11-20 at 10 14 02" src="https://user-images.githubusercontent.com/7290654/69230934-243e3f00-0b80-11ea-9458-7009cc6fff80.png">

### Expected Behavior
The icons should have an accessible label

### Actual Behavior
They don't have a accessible label

### Reproduction Link
<a href="https://codepen.io/devmount/pen/pwWKYR?editors=1010#0" target="_blank">https://codepen.io/devmount/pen/pwWKYR?editors=1010#0</a>

### Other comments
The fix is probably to a `aria-label` or `aria-describedby` that matches the text seen when the drawer is expanded.

**Comment by phiter** [comment]
This happens because the current implementation hides every element but the first inside `v-list-item` using `display: none;`.

The solution is to hide them visually instead of like that, so that the Screen Reader can properly read the contents.

Using `aria-label` would not work because it doesn't work on divs (unless they have some specific roles), which is what is used by default. Also we would need to get the text value of that node to make it work.

This is an example of a working solution:

https://codepen.io/phiter/pen/BayOoOP

Video: https://www.youtube.com/watch?v=WTqKscfKvgM
