### ISSUE TITLE
[Bug Report] DataTable seach using custom filter function inside TableHeader doesn't work properly

### ISSUE THREAD

**Issue by MasterKolka** [vuetifyjs/vuetify#9887]
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Try to search something using search text field

### Expected Behavior
It works properly

### Actual Behavior
It doesn't search properly

### Reproduction Link
<a href="https://codesandbox.io/s/condescending-butterfly-2099q?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/condescending-butterfly-2099q?fontsize=14&hidenavigation=1&theme=dark</a>

### Other comments
If all headers has custom search function or if noone has - it works. But not in that case.

**Comment by KaelWD** [comment]
It's filtering first by headers without custom filters then those with, instead of combining the results:
https://github.com/vuetifyjs/vuetify/blob/bb12b961d392ac2cf12d84936faef1e62e55e233/packages/vuetify/src/components/VDataTable/VDataTable.ts#L44-L50

You may also be interested in #7066

**Comment by KaelWD** [comment]
The description of #7271 sounds like this was intentional @nekosaur?

> change column filtering logic to filter after regular filtering

**Comment by nekosaur** [comment]
Hmm. Yes, there was definitely an intention behind it, though of course now I can't remember exactly what.

**Comment by AuspeXeu** [comment]
Any update on this. The behavior makes not really sense. Imagine the following scenario. I have 10 primitive props for my items and one object prop. If I want the column which displays the object prop filter by a prop of that object, this requires me to implement the filtering logic for all columns myself. The `some` case is the only one that makes sense if only one header has a custom filter function, doesn't it?

**Comment by froks** [comment]
Even if all header functions have a custom sort function, it doesn't work, because  `headersWithoutCustomFilters` will be empty, and therefore `filtered` will be empty. Also  `headersWithCustomFilters` uses `every` instead of `some`.

At the moment it doesn't seem possible to search/filter based on a custom template (combined) value instead of the default, without deferring to other tricks (like adding a calculated property in your data-objects).

**Comment by klmdb** [comment]
```javascript
 if (headersWithCustomFilters.length) { 
   filtered = filtered.filter(item => headersWithCustomFilters.every(filterFn(item, search, defaultFilter))) 
 } 
```

I don't understand how this could be intended. Shouldn't `some` be used, instead of `every`?

Proposed fix for https://github.com/vuetifyjs/vuetify/blob/bb12b961d392ac2cf12d84936faef1e62e55e233/packages/vuetify/src/components/VDataTable/VDataTable.ts#L44-L50
:
```javascript
 filtered = items.filter(item => {
 	if(headersWithoutCustomFilters.length){
 		if(!search || headersWithoutCustomFilters.some(filterFn(item, search, customFilter))){
 			return true
 		}
 	}
 	if(headersWithCustomFilters.length){
	 	if(headersWithCustomFilters.some(filterFn(item, search, customFilter))){
			return true
	 	}
 	}
 	return false
 })
```

**Comment by froks** [comment]
That'd fail if you had only fields with custom filters, but no search string - `!search ||` needs to be added to the `headersWithCustomFilters`-if.

**Comment by edwardsph** [comment]
Any plans to fix this soon?

I think I understand how this came about (@nekosaur) - it makes sense if certain columns need to filter on related values on the page such as the setting a minimum value for a column. Then you want the table search to look for rows that contain a value (anywhere) whilst the column filter restricts the dataset based on that value. In these cases the search value of the filter function is not used. The logic of the current code matches this 2 stage usage i.e filter rows based on the search value (looking at headersWithoutCustomFilters), then further filter these rows based on custom filters inheadersWithCustomFilters.

The problem occurs when you try and use the same mechanism to enhance the standard table search to account for columns with complex data. This looks like it is possible because of the search parameter being passed to the filter funtion but the logic of the current code is then wrong. In this case we need the proposed fix above (@klmdb) i.e. a single stage that filter rows using the default filter for columns without a custom filter and using custom filters where required.

I've seen suggestions that you can get arround this problem using the table level custom-filter but that gets very difficult if you have more than one column with complex data.

To avoid breaking existing code, I suggest that filter continues to use the current code but that a new search property is added to headers e.g.
```
search?: (value: any, search: string, item: any) => boolean
```
Then the code becomes something like this:
```js
// first stage table search
if (search) { 
  filtered = filtered.filter(item => {
    // apply either the default search or the search defined in the column header
  })
} 

// second stage filtering - doesn't use the table search value
if (headersWithCustomFilters.length) { 
  filtered = filtered.filter(item => {
    // apply the custom filter for the column to keep or reject the row
  })
}
```
I haven't looked at the full source so I may be missing things but hopefully gives a sense of the logic I propose.

**Comment by nengine** [comment]
Hello, would it be possible to search across multiple columns?  For example, if type 'Females USA' then it would it would return all rows from column Gender and Country matching Females and USA.
