### ISSUE TITLE
[Documentation] Missing class overview

### ISSUE THREAD

**Issue by jarkt** [vuetifyjs/vuetify#9904]
### Environment

**Browsers:** Firefox 70.0, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer, Opera, Other
**OS:** Windows 10, Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
So many classes are not documented. For example there are classes like "overflow-x-hidden". Google helps to find out, that there exists. But they are not part of the documentation.
It's only an example. I noticed it with many classes.
Is there a reason? Is it only an internal class? Should I not use it?

### Expected Behavior
Documentated

### Actual Behavior
Not documentated

### Reproduction Link
<a href="https://vuetifyjs.com/" target="_blank">https://vuetifyjs.com/</a>

**Comment by MajesticPotatoe** [comment]
`overflow-x-hidden` i believe is a v1.5 helper class (it was removed from the documentation in 2.x, though not sure if it was intentional or not). AFAIK all valid classes are documented unless you have some more that are not, in which i we can look into to see if they are indeed missing, were removed, or moved somewhere else.

Here is the 1.5 documentation of [`overflow`](https://v15.vuetifyjs.com/en/framework/display#overflow)

**Comment by johnleider** [comment]
We will update the documentation once we establish the remaining helper classes we wish to add.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
