### ISSUE TITLE
[Bug Report] Combobox Text Selection

### ISSUE THREAD

**Issue by MatthiasRossbach** [vuetifyjs/vuetify#9920]
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.14.4

### Steps to reproduce
Select a Text in a Combobox

### Expected Behavior
Should behave like a normal input field, but only behaves the same if field has already focus

### Actual Behavior
No Initial Focus behavior: Drag & Drop everytimes start in the beginning (no reverse selection). If selection drag ends out of bounds, text gets deselected

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. Please open a new issue with the missing information.

Thank you for your contribution and interest in improving Vuetify. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
