### ISSUE TITLE
[Feature Request] Make adding multiple files to v-file-input more user friendly

### ISSUE THREAD

**Issue by WikiWookie** [vuetifyjs/vuetify#9985]
### Problem to solve
Currently when adding multiple files you need to shift click them in order to add them on the file pick pop up.  Some/many users may not be familiar with this and may have trouble adding multiple files.

### Proposed solution
Add a plus button to open up the file picker screen.  Then add each  file to a list where the user can see what files they have added where they can also delete files.

**Comment by websitevirtuoso** [comment]
+

**Comment by peppeg85** [comment]
it's totally user un-friendly, before there was the plugin vue upload button that worked very well, but now it's not supported because the "native" functionality, that is not so good like the plugin

**Comment by MajesticPotatoe** [comment]
`v-file-input` is meant to extend/mimic native input, and is different than something like `v-upload` (not available yet). Should move this feedback to the running `v-upload` issue #8812 so that we can consider it when creating the component.

@peppeg85 AFAIK we never had an official plugin for this, and there's various user-land implementations out there that are more robust (that we hope `v-upload` will strive to be like)
