### ISSUE TITLE
[Documentation] Use of Breakpoints (and the use of sass variables in general) in scss

### ISSUE THREAD

**Issue by sofuxro** [vuetifyjs/vuetify#9994]
### Problem to solve
There is a lack to none of documentation regarding breakpoints use in scss.

Is this the correct way to do it in vuetify (for now at least) ?

    @import '~vuetify/src/styles/settings/_variables';

    @media #{map-get($display-breakpoints, 'md-and-down')} {
        .custom-class {
            display: block;
        }
    }

### Proposed solution
A documentation and utility function addition like in bootstrap

https://getbootstrap.com/docs/4.3/layout/overview/#responsive-breakpoints

    @include media-breakpoint-down(md) {
        .custom-class {
            display: block;
        }
    }

**Comment by MajesticPotatoe** [comment]
Could you provide a little more info on what you are looking for? Are you trying to simply define your breakpoints? Or is it more just how to use sass vars locally in a component?

Sass variable use is documented here:
https://vuetifyjs.com/en/customization/sass-variables

However in prep for 2.2 (and in the 2.2 beta) we have added in sass var api
https://dev.vuetifyjs.com/en/customization/sass-variables#variable-api

**Comment by sofuxro** [comment]
In my case to use sass vars locally in a component.
In  https://dev.vuetifyjs.com/en/customization/sass-variables#variable-api under $display-breakpoints should be added an example of usage

    // Usage:
    @media #{map-get($display-breakpoints, 'md-and-down')} {
        .custom-class {
            display: block;
        }
    }

And as a second point their should be exposed (and more created) functions for ease of use as bootstrap has it.
In the 2 example shown above the first (vanila one) is more clunky than the second one (from bootstrap)

As media query are commonly used I think (maybe the community can back me up or contradict me) there should be more attention given to this.

**Comment by MajesticPotatoe** [comment]
I would agree an example on local usage should be added, though, I would not clutter it in the variable-api as this isn't something specific to any particular variable and is a more broad concept. A dedicated section on how to use sass vars in a local setting would be more suitable and usable throughout. breakpoints can be used as good example as it uses map-get which is a little deeper than using a basic variable (we don't actually have that many maps compared to simple vars).

As for functions for ease of use, we do have some, they are in source, they are not documented/explained as of yet, but are on list of things to add along side variable descriptions as I am still debating best way to handle it in a maintainable way.

**Comment by djmattyg007** [comment]
I'm honestly not sure how it's supposed to work in custom components. I've done this:

```
<style lang="scss" scoped>
@media #{map-get($display-breakpoints, 'md-and-up')} {
    .my-classname {
        color: red;
    }
}
</style>
```

And I'm always told that `$display-breakpoints` is not defined. I haven't managed to find any documentation on how I'm supposed to use any of the variables defined by vuetify in my custom components, and nothing I've tried has managed to make it work. If the documentation is there, it's too difficult to find or not clear enough.

I'm using the a la carte installation through vue-cli 3. Everything else abut vuetify seems to work just fine.

Also, the docs aren't clear on the topic of overriding things like the grid breakpoints. This page:

https://vuetifyjs.com/en/customization/sass-variables

```
When you run yarn serve, the vuetify-cli-plugin will automatically hoist the global Vuetify variables to all of your sass/scss files. When making changes to individual component variables, you will still need to manually include its variables file.
```

But it doesn't state what happens when I'm not using `yarn serve`, and it isn't clear exactly which variables are "global" Vuetify variables. To be specific, I've created a file named `src/scss/variables.scss` and put this in it:

```
$grid-breakpoints: (
    'xl': 1800px - 16px
);
```

Am I supposed to re-import a file after this declaration? If so, which one? It's not the styles for an individual component.

**Comment by sofuxro** [comment]
@djmattyg007 sorry for the incomplete example.
you need to import the variables (from node_modules vuetify):

    @import '~vuetify/src/styles/settings/_variables';

**Comment by djmattyg007** [comment]
To clarify, what I think you're saying is:

I need to put this line:

    @import '~vuetify/src/styles/settings/_variables';

At the end of this file:

    src/scss/variables.scss

Is that correct?

Or is this related to how to use `$display-breakpoints` in my custom components? Because if I import `@import '~vuetify/src/styles/settings/_variables';` in my custom component, that isn't going to account for my overrides in `src/scss/variables.scss`.

Also, when I attempted to import this file in one of my custom components (while trying to get the `$display-breakpoints` variable to work), I was told that the file couldn't be found:

    @import "~vuetify/src/styles/styles/sass";

**Comment by johnleider** [comment]
The correct way to do this would be:

```vue
<style lang="sass">
  @import '~vuetify/src/styles/styles.sass'

  @media #{map-get($display-breakpoints, 'md-and-down')}
    .custom-class
      display: none
</style>
```

You can use scss if you want, it's the same. I'll provide some clear direction in the docs about this.

**Comment by djmattyg007** [comment]
I don't think you answered the first part of my previous reply:

> To clarify, what I think you're saying is:
> 
> I need to put this line:
> 
> ```
> @import '~vuetify/src/styles/settings/_variables';
> ```
> 
> At the end of this file:
> 
> ```
> src/scss/variables.scss
> ```
> 
> Is that correct?

**Comment by tvld** [comment]
Same issue as... ?
https://github.com/vuetifyjs/vuetify/issues/9394
